docs/wiki/home.md
=> docs: 去掉故障自愈链接

requirements.txt
- bug fix
- 升级requests依赖包，解决可能的风险
close #15
=> imporve： #15 升级requests依赖包，解决可能的风险

.flake8, .travis.yml, requirements.txt
- 优化项
- 加入 CI 配置
- 升级urllib3依赖包，解决可能的风险
=> minor: #15 升级urllib3依赖包，解决可能的风险

requirements.txt
=> 同步依赖版本包修复到V3.3.X

readme.md, readme_en.md
- 新功能
- readme 添加单元测试和测试覆盖率 badge
close #25
=> Improve travis

config/default.py
- bug fix
- 修复打包后pipeline.blueflow找不到的问题 #30
=> bugfix: 修复打包后pipeline.blueflow找不到的问题 #30

docs/install/dev_deploy.md, docs/install/dev_web.md
- bug fix
- 修复docs中本地部署文档中收集前端静态资源部分未生效 
close #42
=> bugfix: 修复docs中本地部署文档中收集前端静态资源部分未生效 #42

pipeline/engine/utils.py, pipeline/tests/engine/utils/test_utils_func.py
- bug fix
- 修复节点执行时间超过一天后耗时计算不正确的问题
close #52
=> bugfix: 修复节点执行时间超过一天后耗时计算不正确的问题

gcloud/apigw/views.py, gcloud/taskflow3/api.py, gcloud/tasktmpl3/api.py, gcloud/tests/apigw/test_apigw.py, gcloud/tests/mock.py, gcloud/tests/taskflow3/test_api.py
- 新功能
- 使用流程模板新建任务时，返回未引用的全局变量
=> feature: 使用流程模板新建任务时，返回未引用的全局变量 #36

blueapps/account/components/bk_token/models.py, blueapps/patch/settings_open_saas.py, blueapps/patch/settings_paas_services.py, blueapps/template/context_processors.py, django_signal_valve/admin.py, gcloud/contrib/appmaker/admin.py, gcloud/contrib/appmaker/models.py, gcloud/core/command.py, gcloud/tasktmpl3/sites/open/import_data.py, gcloud/tasktmpl3/sites/open/import_data_2_to_3.py, gcloud/tasktmpl3/sites/utils.py, pipeline/component_framework/admin.py, pipeline/component_framework/base.py, pipeline/component_framework/models.py, pipeline/engine/admin.py, pipeline/tests/engine/models/function/test_function_switch.py, pipeline_plugins/components/utils/__init__.py
- 优化项
- 修复部分python文件头部coding: utf-8格式不统一
close #57
=> improve: 修复部分python文件头部coding: utf-8格式不统一 #57

gcloud/apigw/decorators.py, gcloud/apigw/views.py
- 优化项
- 优化gcloud.apigw模块是否加载bkoauth的逻辑
=> improve: 优化gcloud.apigw模块是否加载bkoauth的逻辑 #64

pipeline/engine/core/runtime.py, pipeline/engine/models/core.py, pipeline/tests/engine/core/test_runtime.py, pipeline/tests/mock.py
- bug fix
- 修复流程状态获取接口 API 返回的节点名与实际节点名不符的问题
close #77
=> bugfix: 修复流程状态获取接口 API 返回的节点名与实际节点名不符的问题

pipeline/blueflow/src/components/common/PipelineCanvas/ConfigBar.vue, pipeline/blueflow/src/components/common/PipelineCanvas/index.vue, pipeline/blueflow/src/components/common/RenderForm/FormGroup.vue, pipeline/blueflow/src/components/common/RenderForm/FormItem.vue, pipeline/blueflow/src/components/common/RenderForm/RenderForm.vue, pipeline/blueflow/src/components/common/RenderForm/formMixins.js, pipeline/blueflow/src/pages/task/TaskExecute/ModifyParams.vue, pipeline/blueflow/src/pages/task/TaskParamEdit.vue, pipeline/blueflow/src/pages/template/TemplateEdit/NodeConfig.vue, pipeline/blueflow/src/pages/template/TemplateEdit/TemplateSetting/TabLocalDraft.vue, pipeline/blueflow/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue, pipeline/blueflow/src/pages/template/TemplateEdit/index.vue
- 新功能
- 无
- 优化项
-本地缓存表格实现方式改为 table 元素
- 输入参数 tooltip z-index 层级调整为 TagSelect loading 层级
- 任务执行参数 loading 状态取消，需要等待所有参数加载完毕
- bug fix
- 无
close #54
=> 本地缓存表格重构、任务执行修改参数loading时机、标准插件参数勾选tooltip层级优化 #54

scripts/develop/dev_settings.py
- 优化项
- 本地开发local_settings模板文件优化 
close #59
=> improve: 本地开发local_settings模板文件优化 #59

pipeline/blueflow/src/components/common/RenderForm/IpSelector/StaticIp.vue, pipeline/blueflow/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue, pipeline/blueflow/src/components/common/RenderForm/tags/TagMember_selector.vue
- 新功能
- 无
- 优化项
- ip选择器组件搜索框、静态ip操作项下拉框的样式优化
- 云区域名称的字段替换
- bug fix
- 无
close #63
=> imporvement: ip选择器样式优化、云区域名称替换 #63

pipeline/blueflow/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, pipeline/blueflow/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- 新功能
- 无
- 优化项
- 全局变量编辑或者新建时，配置项没有加载完成，禁用掉保存按钮
- bug fix
- 无
close #69
=> improvement：全局变量配置项未加载完成不允许保存 #69

config/urls_custom.py, pipeline_plugins/variables/query.py, pipeline_plugins/variables/sites/open/constants.py, pipeline_plugins/variables/urls.py
=> feature: 提供获取自定义全局变量的接口 #68

pipeline/blueflow/src/api/index.js, pipeline/blueflow/src/pages/appmaker/index.vue, pipeline/blueflow/src/store/modules/appmaker.js
- 新功能
- 轻应用页面增加高级搜索功能
- 优化项
- 无
- bug fix
- 无
close #107
=> feature: 轻应用页面增加高级搜索功能 #107

pipeline/blueflow/src/pages/home/index.vue, pipeline/blueflow/src/pages/template/TemplateList/index.vue, pipeline/blueflow/src/store/modules/templateList.js
- 新功能
- 无
- 优化项
- 无
- bug fix
- 公共流程模版列表和普通流程模版列表数据源做区分
close #115
=> bugfix: 公共流程模版列表和普通流程模版列表数据源做区分 #115

pipeline/blueflow/src/pages/task/TaskExecute/NodeTree.vue, pipeline/blueflow/src/pages/task/TaskExecute/TaskOperation.vue, pipeline/blueflow/src/pages/task/TaskExecute/ViewParams.vue
- 新功能
- 无
- 优化项
- 任务执行页面查看参数，节点树的排序需要按照广度优先排序
- bug fix
- 无
close #117
=> improvement: 任务执行节点树查看按照广度优先排序 #117

pipeline/blueflow/src/api/index.js, pipeline/blueflow/src/pages/statistics/Appmaker/index.vue, pipeline/blueflow/src/pages/statistics/Atom/index.vue, pipeline/blueflow/src/pages/statistics/Instance/index.vue, pipeline/blueflow/src/pages/statistics/Template/index.vue, pipeline/blueflow/src/store/index.js
- 新功能
- 无
- 优化项
- 数据统计页面拉取所有业务
- bug fix
- 无
close #119
=> improvement: 数据统计页面拉取所有业务 #119

pipeline/blueflow/src/components/common/PipelineCanvas/ConfigBar.vue, pipeline/blueflow/src/components/common/PipelineCanvas/index.vue, pipeline/blueflow/src/pages/audit/index.vue, pipeline/blueflow/src/pages/functor/index.vue, pipeline/blueflow/src/pages/template/TemplateEdit/index.vue
- 新功能
- 流程模版编辑增加新建任务按钮
- 职能化中心列表、审计中心列表增加高级搜索功能
- 优化项
- 无
- bug fix
- 无
close #123 #125
=> feature: 流程模版编辑增加新建任务按钮；职能化中心列表、审计中心列表增加高级搜索功能 #123 #125

pipeline_plugins/components/collections/sites/open/job.py
- 新功能
- JOB 执行作业插件不填 IP 参数为空时使用 JOB 侧配置的默认值
close #87
=> feature: JOB 执行作业插件不填 IP 参数为空时使用 JOB 侧配置的默认值

pipeline_plugins/components/collections/sites/open/bk.py
- bug fix
- 修复BK-发送通知插件中邮件通知内容不换行的问题 
close #132
=> bugfix: 修复BK-发送通知插件中邮件通知内容不换行的问题 #132

pipeline/blueflow/src/components/common/Individualization/IpLogContent.vue
- bug fix
- JOB-执行作业查看IP日志详情未展示所有状态的IP日志
close #89
=> bugfix: 修复JOB-执行作业查看IP日志详情未展示所有状态的IP日志的问题

pipeline/blueflow/src/pages/task/TaskExecute/NodeTree.vue
- 新功能
- 无
- 优化项
- 无
- bug fix
- 任务执行页面查看任务参数节点树样式错位问题修复
close #135
=> bugfix:任务执行页面查看任务参数节点树样式错位问题修复

frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
- bug fix
- 节点重试取消按钮点击无效问题修复
close #168
=> bugfix：节点重试取消按钮点击无效问题修复 #168

frontend/desktop/src/components/common/RenderForm/FormGroup.vue, frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- bug fix
- 修复Tag组件调用get_child获取combine组件错误的问题
close #175
=> bugfix:修复Tag组件调用get_child获取combine组件错误的问题

frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
=> refactory: 流程模版导出弹窗重构

pipeline_plugins/components/collections/sites/open/cc.py
- bug fix
- 修复 CMDB-故障机替换插件错误信息不明确的问题
close #186
=> bugfix: CMDB-故障机替换插件错误信息不明确 bug 修复

gcloud/core/api_adapter/sites/open/app_maker.py
- bug fix
- 修复企业版上传轻应用 LOGO 链接拼接错误的问题
close #188
=> bugfix: 修复企业版上传轻应用 LOGO 链接拼接错误的问题

gcloud/core/utils/sites/open/utils.py
- bug fix
- 修复用户在默认业务已归档时访问业务首页返回 500 的问题
close #190
=> bugfix: 修复用户在只有一个已归档业务时访问业务首页返回 500 的问题

pipeline/core/data/converter.py, pipeline/tests/core/data/test_converter.py, pipeline/tests/core/data/test_library.py, pipeline_plugins/cmdb_ip_picker/query.py, pipeline_plugins/cmdb_ip_picker/utils.py, pipeline_web/parser/format.py
- bug fix
- 新版IP选择器根据IP筛选为空 
close #193
=> V3.3.x bugfix ip selector by host

frontend/desktop/src/pages/home/SelectTemplateDialog.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue, frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue
- bug fix
- 模版导入弹窗导入按钮的文案逻辑判断错误修复
close #198
=> bugfix：模版导入弹窗导入按钮的文案逻辑判断错误修复

frontend/desktop/src/pages/template/TemplateList/index.vue
- bug fix
- 管理员入口公共流程页面新建、导入、导出按钮不显示问题修复
close #199
=> bugfix：管理员入口公共流程页面新建、导入、导出按钮不显示问题修复

gcloud/core/models.py, gcloud/core/utils/sites/open/utils.py, gcloud/webservice3/resources.py, pipeline_plugins/components/collections/sites/open/cc.py
- bug fix
- 不允许用户在已停运业务下进行操作
close #196
=> Bugfix user only have arc biz 500

frontend/desktop/src/pages/functor/index.vue, frontend/desktop/src/pages/template/TemplateList/index.vue
- bug fix
- 修复职能化中心新建任务按钮丢失的问题
close #205
=> bugfix:修复职能化中心新建任务按钮丢失的问题

gcloud/core/utils/sites/open/utils.py
- bug fix
- 修复无法正常获取到某个业务下具有运维角色的用户信息的问题
close #209
=> bugfix: 修复无法正确获取业务下拥有运维角色用户的问题

gcloud/commons/template/resources.py
- bug fix
- 修复获取公共流程列表接口中返回的数据缺少 has_subprocess 字段的问题
close #212
=> bugfix: 修复获取公共流程列表接口中返回的数据缺少 has_subprocess 字段的问题

gcloud/commons/template/models.py, gcloud/tasktmpl3/models.py
- 新功能
- 禁止业务流程和公共流程交叉导入时保留ID
- bug fix
- 修复从业务流程导出的模板导入到公共流程后，修改业务流程会影响公共流程数据的问题 
close #206
=> feature: 禁止业务流程和公共流程交叉导入时保留ID

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 修复节点参数编辑时select、datetime等tag点击收起面板的问题
link #182
=> bugfix: 修复节点参数编辑时popup类tag点击收起面板的问题

frontend/desktop/src/pages/functor/index.vue
- 优化项
- 职能化中心列表所属业务置于第一列
- 职能化中心列表ID列取任务id的值
close #216
=> improvement: 职能化中心列表所属业务置于第一列，ID改为任务id值

frontend/desktop/src/pages/functor/index.vue, frontend/desktop/src/pages/template/TemplateList/index.vue
- bug fix
- 职能化中心创建任务选择模版失败修复
link #205
=> bugfix: 职能化中心创建任务选择模版失败修复

frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- bug fix
- 业务流程创建周期任务点下一步不跳转问题修复
close #235
=> bugfix: 业务流程创建周期任务点下一步不跳转问题修复

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabLocalDraft.vue
- 优化项
- 本地缓存为空时样式优化
close #241
=> improvement: 本地缓存为空时样式优化

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- 优化项
- 输出参数勾选到全局变量，点开编辑时不需要加载配置项
close #238
=> improvement:输出参数勾选到全局变量，点开编辑时不需要加载配置项

frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- bug fix
- 下拉框Tag设置多选后default属性不生效的问题修复
close #221
=> bugfix: 下拉框Tag设置多选后default属性不生效的问题修复

frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- bug fix
- 任务节点参数编辑样式select框禁用态padding调整
close #201
=> bugfix: 任务节点参数编辑样式select框禁用态padding调整 #201

frontend/desktop/src/components/layout/Navigator.vue
- 优化项
- 页面头部导航左右间距统一为25px
close #246
=> improvement: 页面头部导航左右间距统一

docs/install/dev_deploy.md
- 优化项
- 本地开发环境搭建文档添加部署蓝鲸智云社区版内容 
close #181
=> docs: 本地开发环境搭建文档添加部署蓝鲸智云社区版内容 #181

gcloud/taskflow3/models.py, gcloud/taskflow3/resources.py
- 优化项
- 不允许用户删除已经开始执行且未进入归档状态的流程
close #260
=> improvement: 不允许用户删除已经开始执行且未进入归档状态的流程

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/task/TaskExecute/ViewParams.vue
- bug fix
- 修复任务执行时，修改参数保存后，查看参数节点参数信息不展示问题
close #192
=> bugfix: 修复任务执行时，修改参数保存后，查看参数节点参数信息不展示问题 #192

frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- 优化项
- 导出流程弹窗loading时，业务选择下拉框禁用
close #240
=> improvement: 导出流程loading样式优化 #240

frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- 优化项
- 去掉 TagSelect 组件冗余代码
- bug fix
- TagSelect 组件搜索结果为空时，下拉框列表被清空问题修复
close #256
=> bugfix:TagSelect搜索结果为空时，下拉框列表被清空问题修复；去掉冗余代码

.travis.yml, config/dev.py
=> minor: fix travis ci db codec issue

gcloud/core/models.py
- 新功能
- 获取标准运维内部不存在的环境变量时支持从当前系统中的环境变量获取
close #279
=> feature: 获取标准运维内部不存在的环境变量时支持从当前系统中的环境变量获取

frontend/desktop/src/api/index.js, frontend/desktop/src/api/urls.js
- 优化项
- template/get_business_basic_info/接口迁移
close #49
=> improvement: template/get_business_basic_info/接口迁移

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabLocalDraft.vue
- bug fix
- 去掉流程模版本地缓存为空时hover底色
- 新建缓存控制台报校验相关错误修复
close #282
=> bugfix: 去掉流程模版本地缓存为空时hover底色；新建缓存控制台报校验相关错误修复

frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
- bug fix
- 任务创建参数填写、职能化认领页面表格内textarea宽度自适应
close #286
=> bugfix: 任务创建参数填写、职能化认领页面表格内textarea宽度自适应

pipeline/models.py, pipeline/service/pipeline_engine_adapter/adapter_api.py, pipeline/service/task_service.py, pipeline/signals/handlers.py
- 优化项
- 替换 pipeline.model 中对引擎底层 API 的调用
close #272
=> improvement: 替换 pipeline.model 中对引擎底层 API 的调用

docs/apidoc/en/import_common_template.md, docs/apidoc/sops.yaml, docs/apidoc/zh_hans/import_common_template.md, gcloud/apigw/urls.py, gcloud/apigw/views.py, gcloud/tests/apigw/test_apigw.py, gcloud/tests/mock_settings.py
- 新功能
- 添加公共流程导入 API
close #311
=> feature: 添加公共流程导入 API

gcloud/commons/template/resources.py, gcloud/tasktmpl3/resources.py
- bug fix
- 修复无编辑权限的用户能够更新模板数据的问题
close #315
=> bugfix: 修复无编辑权限的用户能够更新模板数据的问题

frontend/desktop/src/pages/appmaker/AppCard.vue
- bug fix
- 轻应用组件引入样式文件路径大小写问题修复
=> bugfix:轻应用组件引入样式文件路径大小写问题修复

pipeline/component_framework/test.py
=> minor: add pipeline component test framework

config/__init__.py, docs/install/dev_deploy.md
- 优化项
- 优化本地后台开发配置，支持修改settings，不需要设置环境变量 
close #331
=> improve: 优化本地后台开发配置，支持修改settings，不需要设置环境变量 #331

pipeline_plugins/components/collections/sites/open/bk.py
- sprint fix
- 修复BK-发送通知插件执行时报settings配置错误问题 
close #324
=> sprintfix: 修复BK-发送通知插件执行时报settings配置错误问题 #324

.flake8, .gitignore
- 优化项
- flake和git排除本地运行单元测试coverage生成的结果文件 
close #313
=> minor: flake和git排除本地运行单元测试coverage生成的结果文件 #313

frontend/desktop/builds/webpack.dev.config.js, gcloud/tasktmpl3/api.py, gcloud/tasktmpl3/urls.py
- 优化项
- 去掉template/get_business_basic_info/{biz_cc_id}/接口 
close #49
=> improve: 去掉template/get_business_basic_info/{biz_cc_id}/接口 #49

pipeline/core/flow/activity.py
- 优化项
- 调度间隔生成器命名修改
close #262
=> minors: 调度间隔生成器命名修改

pipeline/models.py, pipeline/tests/mock.py, pipeline/tests/mock_settings.py, pipeline/tests/models/test_instance.py
- bug fix
- 修复启动流程时由于事务隔离导致新创建的流程实例对 worker 不可见的问题
close #322
=> bugfix: 修复启动流程时由于事务隔离导致新创建的流程实例对 worker 不可见的问题

frontend/desktop/src/api/index.js
- 新功能
-  标准插件配置项加载兼容内嵌到form字段
close #342
=> feature: 标准插件配置项加载兼容内嵌到form字段

frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- bug fix
- 执行作业输出参数会显示其他节点已勾选的输出参数项修复
close #344
=> 执行作业输出参数会显示其他节点已勾选的输出参数项修复

frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- bug fix
- 标准插件点击事件元素隐藏会导致父容器面板消失的问题修复
close #346
=> 标准插件点击事件元素隐藏会导致父容器面板消失的问题修复

frontend/desktop/src/pages/functor/index.vue
- bug fix
- 职能化认领列表页新建任务弹窗，清空业务后模版未清空问题修复
close #348
=> bugfix:职能化认领列表页新建任务弹窗，清空业务后模版未清空问题修复

frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- 优化项
- 模版导出弹窗，切换模版类型时关联名称搜索条件
close #350
=> improvement: 模版导出弹窗，切换模版类型时关联名称搜索条件

frontend/desktop/src/assets/css/bkflow.scss, frontend/desktop/src/pages/home/TaskFeeds.vue, frontend/desktop/src/pages/task/TaskList/index.vue
- 优化项
- 任务记录列表也节点暂停状态增加 icon 显示
- 首页任务状态 icon 统一
- 任务节点执行时暂停状态 icon 样式优化
close #355
=> improvement: 节点暂停icon、首页任务状态icon统一、任务执行暂停icon样式优化

frontend/desktop/src/pages/audit/index.vue, frontend/desktop/src/pages/functor/index.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateList/index.vue
- bug fix
- 列表带分页的页面，高级搜索时去掉列表数据偏移量
close #357
=> bugfix:列表带分页的页面，高级搜索时去掉列表数据偏移量

frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
- 优化项
- ip 选择器 loading 效果优化
close #360
=> improvement:ip选择器loading效果优化

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- bug fix
- 任务节点树查看时，汇聚节点之后的节点不显示问题修复
close #362
=> bugfix:任务节点树查看时，汇聚节点之后的节点不显示问题修复

frontend/desktop/builds/webpack.dev.config.js, frontend/desktop/src/assets/html/template.html
- 优化项
- 优化本地开发前端代理配置，默认代理到本地8000端口
=> import: 优化本地开发前端代理配置，默认代理到本地8000端口 #329

gcloud/core/context_processors.py
- bug fix
- 修复管理员入口刷新后默认业务为空的问题 
close #271
=> bugfix: 修复管理员入口刷新后默认业务为空的问题 #271

frontend/desktop/src/pages/appmaker/AppCard.vue, frontend/desktop/src/pages/appmaker/index.vue, frontend/desktop/src/scss/mixins/multiLineEllipsis.scss
- 修复项
1.修复轻应用查看简介无法正确换行
2.:修复轻应用标题过长时省略号偏移
3.修复轻应用高级搜索里的按钮文字未居中
4.修复轻应用搜索按钮与输入框未对齐
5.修复轻应用时间选择器在小屏幕下显示不完整
6.更换轻应用权限查看页面的部分文案
7.修复轻应用搜索loading时刷新整个页面
- bug fix
- 无
link #340
=> improve:轻应用bug修复

frontend/desktop/src/pages/appmaker/AppCard.vue, frontend/desktop/src/pages/task/TaskList/index.vue
- 优化项
轻应用执行记录跳转到任务记录时，把执行记录的创建方式改为轻应用。
link #367
=> improvement:轻应用执行记录跳转后把创建方式设置为轻应用

frontend/desktop/src/pages/appmaker/index.vue
- 优化项
- 轻应用页面高级搜索条件改为更新人和更新时间 
close #380
=> improve: 轻应用页面高级搜索条件改为更新人和更新时间 #380

gcloud/conf/sites/community/ver_settings.py, gcloud/contrib/appmaker/api.py, gcloud/contrib/appmaker/models.py, gcloud/taskflow3/models.py, pipeline_plugins/components/utils/sites/open/utils.py, pipeline_plugins/tests/test_utils/sites/open/test_utils.py, requirements.txt
- bug fix
- 修复JOB插件回调链接和轻应用访问链接无BK_PAAS_URL前缀的错误 
close #390
=> bugifx: 修复JOB插件回调链接和轻应用访问链接无BK_PAAS_URL前缀的错误 #390

app.yml, gcloud/external_plugins/admin.py, gcloud/external_plugins/migrations/0003_auto_20190524_1529.py, gcloud/external_plugins/models/__init__.py, gcloud/external_plugins/models/cache.py, gcloud/external_plugins/models/origin.py
- 新功能
- 远程包源和缓存配置可以django admin查看和管理 
close #399
=> feature: 远程包源和缓存配置可以django admin查看和管理 #399

pipeline/contrib/external_plugins/apps.py
- bug fix
- 屏蔽远程包源模块通过supervisor部署应用报错的问题
=> sprintfix: 修复远程包源模块通过supervisor部署应用报错的问题 #403

gcloud/core/models.py, gcloud/webservice3/resources.py
- 优化项
- 业务生命周期属性life_cycle，需要兼容多版本和历史旧数据 
close #405
=> improve: 业务生命周期属性life_cycle，需要兼容多版本和历史旧数据 #405

docs/install/source_code_deploy.md
- bug fix
- 本地部署文档优化，修改PaaS文档链接
close #391
=> docs: 本地部署文档优化 #391

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/task/TaskExecute/index.vue, frontend/desktop/src/pages/task/TaskStep.vue, frontend/desktop/src/scss/common.scss
- 优化项
1.修改节点名称的显示位置
2.查看节点详情样式重构
- bug fix
无
link #305
=> refactory:任务执行查看节点详情重构

frontend/desktop/src/pages/config/index.vue
- 优化项
根据UI还原执行者配置界面，保持和其他界面风格统一
link #308
=> minors:执行者配置页面title统一

frontend/desktop/src/pages/appmaker/AppCard.vue
- 优化项
-轻应用在不同环境打开和点击区域调整
- bug fix
- 无
link #384
=>  improvement:轻应用在不同环境打开和点击区域调整

pipeline/core/data/context.py
- bug fix
- 修复context模块的包导入问题
close #395
=> 规范化 pipeline 中 context 模块的导入语句

docs/apidoc/readme.md
- 优化项
- 在 apidocs readme 中添加跳转到新接口的链接
=> minor: 在 apidocs readme 中添加跳转到新接口的链接

gcloud/external_plugins/models/cache.py, gcloud/external_plugins/resources.py, gcloud/external_plugins/schemas.py
- bug fix
- 修复修改远程包源和缓存源配置时接口500问题
=> sprintfix: 修复修改远程包源和缓存源配置时接口500问题 #275

pipeline/contrib/external_plugins/apps.py
- bug fix
- 修复在不通过 django manage 命令启动应用时获取当前命令参数可能会失败的问题
close #403
=> bugfix: 修复在不通过 django manage 命令启动应用时获取当前命令参数可能会失败的问题

frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- bug fix
- 业务流程、公共流程未选择流程模板时可以点击确定导出空数据，建议为空时点确定报错，提示“请选择 
流程”（和任务记录页面中新建任务中未选择流程的提示一致）
link #307
=> bugfix:修复业务流程、公共流程未选择流程模板时可以点击确定导出空数据

frontend/mobile/build/webpack.prod.conf.babel.js
=> minor: 移动端打包去掉资源hash后缀

frontend/desktop/src/pages/admin/statistics/Instance/index.vue, frontend/desktop/src/pages/admin/statistics/verticalBarChart/index.vue
- 优化项
- 在管理员入口的数据统计里，把原来的横向柱状图重构为纵向柱状图，调整部分样式。
- bug fix
- 无
link #217
=> improvement:数据统计页面支持竖向柱状图

docs/install/dev_web.md, frontend/desktop/builds/webpack.dev.config.js
- 优化项
- 前端本地开发代理到线上地址配置项和开发文档更新
=> improve: 前端本地开发代理到线上地址配置项和开发文档更新

gcloud/external_plugins/admin.py, pipeline/contrib/external_plugins/admin.py, pipeline/contrib/external_plugins/models/fields.py, pipeline/contrib/external_plugins/models/forms.py
- bug fix
- 修复JSONField字段在admin编辑报500错误的问题 
close #437
=> sprintfix: 修复JSONField字段在admin编辑报500错误的问题 #437

gcloud/external_plugins/models/origin.py
- bug fix
- 修复远程包源更新数据不生效的问题 
close #442
=> sprintfix: 修复远程包源更新数据不生效的问题 #442

frontend/mobile/src/api/urls.js, frontend/mobile/src/components/VantForm/VantCell.vue, frontend/mobile/src/components/VantForm/VantInput.vue, frontend/mobile/src/components/VantForm/index.vue, frontend/mobile/src/components/navbar/Navbar.vue, frontend/mobile/src/main.js, frontend/mobile/src/router/index.js, frontend/mobile/src/store/modules/business.js, frontend/mobile/src/store/modules/component.js, frontend/mobile/src/store/modules/task.js, frontend/mobile/src/store/modules/taskList.js, frontend/mobile/src/store/modules/template.js, frontend/mobile/src/views/task/create.vue, weixin/resources.py, weixin/templates/weixin/index.html, weixin/urls.py, weixin/views.py
- 新功能
- 创建任务表单支持自定义变量渲染
- 优化项
- URL统一添加SITE_URL,并且抽取至一个文件中定义
=> feature: 前后端联调优化项 #432

frontend/mobile/src/main.js, frontend/mobile/src/store/modules/component.js
- bug fix
- 修复移动端获取标准插件和变量的表单链接错误的问题 
close #454
=> bugfix: 修复移动端获取标准插件和变量的表单链接错误的问题 #454

weixin/core/admin.py
=> improve: 微信用户在Admin中展示

weixin/core/middlewares.py
=> sprintfix: 修复微信端登录获取用户失败的问题

gcloud/webservice3/resources.py
=> sprintfix: 修复移动端获取业务失败的问题

frontend/mobile/build/webpack.base.conf.babel.js, frontend/mobile/build/webpack.dev.conf.babel.js, frontend/mobile/build/webpack.prod.conf.babel.js, frontend/mobile/package.json, frontend/mobile/postcss.config.js, frontend/mobile/src/App.vue, frontend/mobile/src/components/MobileCanvas/MobileNodeTemplate.vue, frontend/mobile/src/components/MobileStatusIcon/index.vue, frontend/mobile/src/components/NoData/index.vue, frontend/mobile/src/components/VantForm/VantTextarea.vue, frontend/mobile/src/components/navbar/Navbar.vue, frontend/mobile/src/views/home/index.vue, frontend/mobile/src/views/task/canvas.vue, frontend/mobile/src/views/task/create.vue, frontend/mobile/src/views/task/detail.vue, frontend/mobile/src/views/task/list.vue, frontend/mobile/src/views/task/nodes.vue, frontend/mobile/src/views/task/parameter.vue, frontend/mobile/src/views/task/reset.vue, frontend/mobile/src/views/task/timing.vue, frontend/mobile/src/views/template/index.vue, frontend/mobile/static/style/app.scss, frontend/mobile/static/style/commonico.scss, frontend/mobile/static/style/page.scss, frontend/mobile/static/style/var.scss
- 优化项
- 构建输出文件夹支持多版本文件共存
- bug fix
- 移动端字体文件路径引用错误修复
close #455
=> sprintfix:移动端字体文件路径引用错误修复，构建输出文件夹支持多版本文件共存

frontend/desktop/src/api/index.js, frontend/desktop/src/constants/manage.js, frontend/desktop/src/pages/admin/manage/SourceEdit/CacheEdit.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/CacheForm.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageEdit.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/index.vue, frontend/desktop/src/pages/admin/manage/SourceManage/index.vue, frontend/desktop/src/pages/admin/manage/SourceSync/index.vue, frontend/desktop/src/pages/admin/manage/index.vue
- 优化项
- 远程包源支持删除主包源和本地缓存
- 包源同步列表添加操作人列
- bug fix
- 样式问题修改
- 本地缓存不可编辑态丢失问题修复
=> sprintfix: 远程包源删除主包源和本地缓存、样式问题修改

frontend/desktop/src/main.js, frontend/desktop/src/pages/admin/manage/SourceEdit/CacheForm.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue, frontend/desktop/src/pages/admin/manage/SourceSync/index.vue, frontend/desktop/src/pages/admin/manage/index.vue
- 优化项
- “包源管理”改为“远程插件包源管理”，“包源同步”改为“远程插件同步”，“远程包同步”改为“同步到本地缓存”
- “包源管理”改为“远程插件包源管理”，“包源同步”改为“远程插件同步”，“远程包同步”改为“同步到本地缓存”
- 包源名称、缓存名称、子模块名称校验：不能为空，最大不超过50字符，名字校验不合法提示优化：名称由英文字母、数字、下划线组成，且不能以数字开头
- 详细信息和模块配置所有字段时必填项
close #475
=> sprintfix: 包源管理优化项

frontend/mobile/src/App.vue, frontend/mobile/src/main.js, frontend/mobile/static/style/commonico.scss
- bug fix
- 移动端外部scss文件未被sass-loader编译修复
close #476
=> bugfix: 移动端外部scss文件未被sass-loader编译修复

frontend/desktop/.eslintrc.js, frontend/desktop/src/api/index.js
- 优化项
- 标准插件内嵌配置项字符串解析
close #479
=> sprintfix: 标准插件内嵌配置项字符串解析

app.yml, readme.md, readme_en.md
=> minor: 修改版本信息

gcloud/core/migrations/0010_create_project_for_exist_biz.py
- bug fix
- 修复创建项目 migration 中的中文编码问题
=> bugfix: 修复创建项目 migration 中的中文编码问题

docs/apidoc/en/import_common_template.md, docs/apidoc/zh_hans/import_common_template.md, gcloud/commons/template/models.py
=> minor: 修改模板导入api协议

frontend/desktop/src/pages/admin/manage/SourceManage/index.vue, gcloud/external_plugins/resources.py
- 优化项
- 远程包源及包管理模块错误提示和文案优化 
close #486
=> improve: 远程包源及包管理模块错误提示和文案优化 #486

frontend/desktop/src/api/index.js
- bug fix
- 标准插件加载内嵌配置项控制台报错问题修复
=> sprintfix: 标准插件加载内嵌配置项控制台报错问题修复

gcloud/contrib/appmaker/migrations/0007_add_project_relation.py, gcloud/core/migrations/0011_create_project_for_non_active_biz.py, gcloud/periodictask/migrations/0003_add_project_relation.py, gcloud/taskflow3/migrations/0007_add_project_relation.py, gcloud/tasktmpl3/migrations/0012_add_project_relation.py
- bug fix
- 修复为现有业务创建项目时没有考虑到未激活业务的问题
=> bugfix: 修复为现有业务创建项目时没有考虑到为激活业务的问题

frontend/desktop/src/assets/html/template.html, frontend/desktop/src/components/common/RenderForm/FormItem.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue, frontend/desktop/src/components/common/RenderForm/RenderForm.vue, frontend/desktop/src/components/common/RenderForm/formMixins.js, frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- 新功能
- RenderForm组件 formOption 字段新增 validateSet 配置项支持自定义校验类型：['required', 'custom', 'regex']
- ip选择器支持配置是否允许值为空
close #439
=> RenderForm组件支持自定义校验类型、ip选择器支持配置是否允许值为空

frontend/mobile/build/webpack.base.conf.babel.js, frontend/mobile/build/webpack.dev.conf.babel.js, frontend/mobile/build/webpack.prod.conf.babel.js
=> spintfix: 移动端生产环境打包样式问题修复

frontend/mobile/src/components/navbar/Navbar.vue
=> sprintfix: 移动端导航样式问题修复

frontend/mobile/src/store/modules/component.js
- bug fix
- 修复移动端请求插件和变量的路径错误问题 
close #508
=> sprintfix: 修复移动端请求插件和变量的路径错误问题 #508

frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
=> feature: TagSelect支持选项分组、禁用配置

gcloud/core/api_adapter/sites/open/user_info.py
- bug fix
- 修复获取用户信息接口失败时导致请求返回500的问题 
close #511
=> bugfix: 修复获取用户信息接口失败时导致请求返回500的问题 #511

weixin/core/accounts.py, weixin/core/middlewares.py
- bug fix
- 修复移动端post请求csrftoken丢失问题 
close #466
=> sprintfix: 修复移动端post请求csrftoken丢失问题 #466

gcloud/core/api_adapter/sites/open/user_info.py, gcloud/core/api_adapter/sites/open/user_role.py, gcloud/core/utils/sites/open/utils.py, gcloud/taskflow3/api.py, pipeline_plugins/cmdb_ip_picker/query.py, pipeline_plugins/components/query/sites/open/query.py, pipeline_plugins/tests/cmdb_ip_picker/test_query.py
- bug fix
- 修复移动端获取client失败导致请求APIGW报错的问题 
close #516
=> srintfix: 修复移动端获取client失败导致请求APIGW报错的问题 #516

gcloud/webservice3/resources.py
=> improvement: 项目资源接口允许对名称及状态进行过滤

gcloud/core/migrations/0011_create_project_for_non_active_biz.py
- 优化项
- 项目同步已有业务时，为非激活的业务将其对应项目设置为停用
=> minor: 项目同步已有业务时，为非激活的业务将其对应项目设置为停用

frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- bug fix
- TagSelect分组选项渲染逻辑判断修复
=> bugfix：TagSelect分组选项渲染逻辑判断修复

frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue, frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue
=> improvement: 去掉TagSelect和TagTree缓存

gcloud/core/api.py, gcloud/core/urls.py
- 新功能
- 添加设置用户默认项目接口
close #524
=> feature: 添加设置用户默认项目接口

gcloud/core/context_processors.py, gcloud/core/templates/core/base_vue.html
=> minor: 修改首页返回的部分变量命名

auth_backend/backends/base.py, auth_backend/backends/bkiam.py, auth_backend/examples.py, auth_backend/exceptions.py, auth_backend/resources/base.py, auth_backend/resources/django.py, bkiam/client.py
- 优化项
- auth_backend 增强，添加无实例资源类型，添加鉴权接口
- 权限中心 client 调整，增加错误日志
- DdjangoModelResource 允许用户控制是否自动注册, 添加 AuthBackend 接口
=> Feature auth backend improve

pipeline_plugins/components/collections/sites/open/cc.py, pipeline_plugins/components/static/components/atoms/sites/open/cc/cmdb_transfer_fault_host.js, pipeline_plugins/components/static/components/atoms/sites/open/cc/cmdb_transfer_host_resource.js, pipeline_plugins/tests/components/utils/sites/open/test_cmdb_transfer_fault_host.py, pipeline_plugins/tests/components/utils/sites/open/test_cmdb_transfer_host_resource.py, static/components/atoms/sites/open/cc/cmdb_transfer_fault_host.js, static/components/atoms/sites/open/cc/cmdb_transfer_host_resource.js
- 新功能
- 增加转移主机至业务故障机插件
- 增加转移主机至资源池插件
- 优化项
- 无
- bug fix
- 无
=> feature：添加转移主机至故障机和资源池插件 issue Tencent#253 Tencent#254

gcloud/webservice3/resources.py
- bug fix
-  修复项目 project 接口时间字段无时区信息的问题
=> sprintfix: 修复项目 project 接口时间字段无时区信息的问题 #535

gcloud/tasktmpl3/resources.py
=> improve: 执行方案API代码优化 #535

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 修复在编辑或创建流程时，配置子流程参数界面，子流程下拉框第一次展开未定位到已选择的子流程。
link #494
=> bugfix:修复子流程下拉框第一次展开未定位到已选择的子流程

frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue, frontend/desktop/src/pages/audit/index.vue, frontend/desktop/src/pages/functor/index.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateList/index.vue
- 优化项
- 列表行高未45px，调整为42px
link #448
=>  minor:列表行高还原

frontend/desktop/src/pages/task/ParameterInfo.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/task/TaskStep.vue
- 优化项
- 任务执行里的查看‘眼睛’大小还原
- 任务执行界面的标题居中
- 创建任务参数背景颜色还原
- bug fix
- 无
link #452
=> minors:修复创建任务流程的样式问题

gcloud/core/api.py
=> sprintfix: 修复切换用户默认业务报500的问题 #535

gcloud/core/api.py, gcloud/tasktmpl3/resources.py
=> merge V3.4.x to V3.4.X_bk_iam

gcloud/apigw/views.py, gcloud/core/admin.py, gcloud/core/migrations/0010_create_project_for_exist_biz.py, gcloud/core/migrations/0011_create_project_for_non_active_biz.py, gcloud/core/migrations/0012_auto_20190612_2113.py, gcloud/core/models.py, gcloud/tasktmpl3/models.py, gcloud/tests/apigw/test_apigw.py, gcloud/tests/core/models/test_project.py, gcloud/tests/mock.py, gcloud/webservice3/resources.py
- 优化项
- 项目关联业务ID字段cmdb_biz_id改为bk_biz_id，admin优化
=> improve: 项目关联业务ID字段cmdb_biz_id改为bk_biz_id，admin优化 #535

gcloud/apigw/views.py, gcloud/core/admin.py, gcloud/core/api.py, gcloud/core/migrations/0010_create_project_for_exist_biz.py, gcloud/core/migrations/0011_create_project_for_non_active_biz.py, gcloud/core/migrations/0012_auto_20190612_2113.py, gcloud/core/models.py, gcloud/tasktmpl3/models.py, gcloud/tests/apigw/test_apigw.py, gcloud/tests/core/models/test_project.py, gcloud/tests/mock.py, gcloud/webservice3/resources.py
- 优化项
- 项目关联业务ID字段cmdb_biz_id改为bk_biz_id，admin优化
=> 项目关联业务ID字段cmdb_biz_id改为bk_biz_id，admin优化

auth_backend/examples.py, auth_backend/plugins/constants.py, auth_backend/plugins/decorators.py, auth_backend/plugins/tastypie/resources.py, auth_backend/resources/base.py, auth_backend/resources/django.py, auth_backend/resources/inspect.py, bkiam/client.py, blueapps/utils/cache.py, config/default.py, gcloud/apigw/views.py, gcloud/commons/template/resources.py, gcloud/contrib/appmaker/resources.py, gcloud/contrib/function/resources.py, gcloud/core/utils/__init__.py, gcloud/core/utils/common.py, gcloud/core/utils/sites/open/utils.py, gcloud/exceptions.py, gcloud/periodictask/resources.py, gcloud/taskflow3/models.py, gcloud/taskflow3/resources.py, gcloud/tasktmpl3/api.py, gcloud/tasktmpl3/resources.py, gcloud/tests/apigw/test_apigw.py, gcloud/webservice3/paginator.py, gcloud/webservice3/resources.py, gcloud/webservice3/serializers.py
=> 添加单个资源的简单操作鉴权装饰器

auth_backend/plugins/decorators.py, auth_backend/plugins/delegation.py, auth_backend/plugins/http.py, auth_backend/plugins/tastypie/authorization.py, auth_backend/resources/django.py, gcloud/core/migrations/0010_create_project_for_exist_biz.py, gcloud/core/migrations/0011_create_project_for_non_active_biz.py, gcloud/tasktmpl3/resources.py
- 优化项
- 为无权限时返回的响应添加内容类型
- bug fix
- 修复无权限时响应 dump JSON 序列化出错的问题
=> V3.4.x parent resource auth

frontend/desktop/src/components/common/RenderForm/FormItem.vue, frontend/desktop/src/components/common/RenderForm/RenderForm.vue, frontend/desktop/src/pages/task/ParameterInfo.vue, frontend/desktop/src/pages/task/TaskParamEdit.vue
- 优化项
- 去除未引用变量的必填提示
link #552
=> improvement:去除未引用变量的必填提示

auth_backend/plugins/decorators.py, auth_backend/plugins/http.py, auth_backend/plugins/tastypie/authorization.py, auth_backend/plugins/utils.py
=> feature: 无权限时统一数据格式和HTTP状态码 #528

frontend/desktop/src/api/index.js, frontend/desktop/src/api/urls.js, frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/components/layout/ProjectSelector.vue, frontend/desktop/src/pages/admin/statistics/Appmaker/index.vue, frontend/desktop/src/pages/admin/statistics/Atom/index.vue, frontend/desktop/src/pages/admin/statistics/Instance/index.vue, frontend/desktop/src/pages/admin/statistics/Template/index.vue, frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue, frontend/desktop/src/pages/audit/index.vue, frontend/desktop/src/pages/functor/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TemplateSetting.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue, frontend/desktop/src/pages/template/TemplateList/index.vue, frontend/desktop/src/routers/index.js, frontend/desktop/src/store/index.js, frontend/desktop/src/store/modules/project.js, frontend/desktop/src/store/modules/template.js, frontend/desktop/src/utils/draft.js
- 优化项
-  首页默认路径跳转、路径改为project
- ccId变量替换，business字段、变量替换
=> improvement: 首页默认路径跳转、路径改为project；sprintfinx: ccId变量替换，business字段、变量替换

auth_backend/plugins/utils.py
- 优化项
- 组装权限不通过的response支持instance为空
=> improve: 组装权限不通过的response支持instance为空 #528

auth_backend/plugins/decorators.py, auth_backend/plugins/http.py, auth_backend/plugins/tastypie/authorization.py, config/default.py, gcloud/core/api.py, gcloud/core/urls.py, gcloud/core/utils/__init__.py, gcloud/core/utils/common/__init__.py, gcloud/core/utils/common/apis.py, gcloud/core/utils/common/dates.py, gcloud/core/utils/common/strings.py
=> feature: 新增查询申请权限API接口 #528

auth_backend/plugins/tastypie/resources.py, gcloud/core/api.py, gcloud/core/urls.py
=> feature: 添加查询某人是否有单个资源权限的API #528

gcloud/webservice3/resources.py
=> sprintfix: 修复项目按照id过滤失败问题 #528

gcloud/commons/template/permissions.py, gcloud/commons/template/resources.py, gcloud/periodictask/resources.py, gcloud/taskflow3/resources.py, gcloud/tasktmpl3/resources.py, gcloud/webservice3/resources.py
- 优化项
- 公共流程resource添加导出和克隆操作
- 修复周期任务按项目过滤错误
- 项目按ID倒序
=> V3.4.x bugfix tastypie 401

gcloud/webservice3/resources.py
- 新功能
- 项目可以按照ID、名称、描述、创建人过滤
- 优化项
- 项目名称、时区、创建人禁止修改
=> V3.4.x bk iam fix

auth_backend/plugins/middlewares.py, config/default.py, gcloud/core/middlewares.py, gcloud/tasktmpl3/api.py
=> bugfix: 导入流程鉴权逻辑问题修复

gcloud/commons/template/resources.py, gcloud/taskflow3/resources.py, gcloud/tasktmpl3/resources.py, gcloud/webservice3/resources.py
- bug fix
- 修复非运维人员编辑流程模板报错提示弹窗是登录的问题 
close #581
=> bugfix: 修复非运维人员编辑流程模板报错提示弹窗是登录的问题 #581

auth_backend/plugins/tastypie/resources.py, auth_backend/plugins/utils.py, auth_backend/resources/base.py, gcloud/commons/template/resources.py, gcloud/contrib/appmaker/resources.py, gcloud/contrib/function/resources.py, gcloud/periodictask/resources.py, gcloud/taskflow3/resources.py, gcloud/tasktmpl3/resources.py, gcloud/webservice3/resources.py
- 优化项
- resource信息和operations信息放到API的meta中
=> feature: resource信息和operations信息放到API的meta中 #528

gcloud/commons/message/__init__.py, gcloud/contrib/audit/views.py, gcloud/core/utils/sites/open/utils.py, gcloud/webservice3/resources.py
=> bugfix: 修复新建项目字段无效问题 #528

gcloud/core/api.py
- bug fix
- query_resource_verify_perms改为POST方法
=> bugfix: query_resource_verify_perms改为POST方法 #598

gcloud/core/utils/sites/open/utils.py, gcloud/taskflow3/api.py, pipeline_plugins/components/utils/common.py
=> minor: 优化部分错误提示

frontend/desktop/src/App.vue, frontend/desktop/src/api/index.js, frontend/desktop/src/components/layout/ProjectSelector.vue, frontend/desktop/src/config/setting.js, frontend/desktop/src/pages/appmaker/AppEditDialog.vue, frontend/desktop/src/pages/home/QuickCreateTask.vue, frontend/desktop/src/pages/home/SelectTemplateDialog.vue, frontend/desktop/src/pages/home/TaskFeeds.vue, frontend/desktop/src/pages/home/index.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/project/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/pages/template/TemplateList/index.vue, frontend/desktop/src/routers/index.js
- 新功能
- 资源类接口权限字典字段修改
- 接口参数'business'替换为'project'
- 项目详情添加到全局上下文 $.content.project
=> 资源类接口权限字典字段修改;接口参数'business'替换为'project';项目详情添加到全局上下文 $.content.project

frontend/desktop/src/api/index.js, frontend/desktop/src/components/layout/permissionApply.vue
- 新功能
- 获取用户权限、跳转权限中心url接口参数调整
- bug fix
- project_id拼写错误修复
=> 获取用户权限、跳转权限中心url接口参数调整; project_id拼写错误修复

auth_backend/plugins/tastypie/resources.py, gcloud/webservice3/resources.py
=> feature: tatypie API详情展示操作和资源信息 #598

frontend/desktop/src/App.vue, frontend/desktop/src/api/index.js, frontend/desktop/src/api/interceptors.js, frontend/desktop/src/components/common/modal/PermissionModal.vue, frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/pages/appmaker/AppCard.vue, frontend/desktop/src/pages/appmaker/AppEditDialog.vue, frontend/desktop/src/pages/appmaker/index.vue, frontend/desktop/src/pages/home/QuickCreateTask.vue, frontend/desktop/src/pages/home/SelectTemplateDialog.vue, frontend/desktop/src/pages/home/TaskFeeds.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/project/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue, frontend/desktop/src/pages/template/TemplateList/index.vue, frontend/desktop/src/store/modules/project.js
=> feature: 资源权限获取跳转链接

auth_backend/plugins/tastypie/resources.py, auth_backend/plugins/utils.py, gcloud/core/project.py
- 优化项
- 用户默认项目为空优先返回有查看全选的权限业务
=> feature: 用户默认项目为空优先返回有查看全选的权限业务 #598

auth_backend/plugins/utils.py, blueapps/utils/cache.py, gcloud/core/project.py
=> bugfix: 修复查询权限接口使用缓存出错问题 #598

gcloud/core/context_processors.py, gcloud/core/templates/core/base_vue.html
- bug fix
- 修复默认业务为None前端识别出错问题
=> bugfix: 修复默认业务为None前端识别出错问题 #598

frontend/desktop/src/pages/task/TaskExecute/index.vue
- bug fix
- 修复查看职能化流程后，默认任务类型出现职能化流程。
link #571
=> bugfix:修复默认任务类型出现职能化流程

pipeline/models.py
- bug fix
- 修复流程创建后获取不到执行者的问题
close #618
=> bugfix: 修复流程创建后获取不到执行者的问题

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
=> sprintFix: 修复节点排序问题

frontend/mobile/package.json, frontend/mobile/src/components/VantForm/VantSelect.vue, frontend/mobile/src/components/VantForm/index.vue
- 新功能
- 适配了radio和checkbox的表单类型
radio试用了vant的picker，checkbox使用了自定义的multiple select组件
=> 移动端适配radio和checkbox类型表单

auth_backend/plugins/decorators.py, auth_backend/resources/base.py, bkiam/client.py, gcloud/commons/template/permissions.py, gcloud/contrib/appmaker/permissions.py, gcloud/contrib/audit/__init__.py, gcloud/contrib/function/apps.py, gcloud/contrib/function/permissions.py, gcloud/core/api_adapter/sites/open/user_role.py, gcloud/core/permissions.py, gcloud/periodictask/permissions.py, gcloud/taskflow3/permissions.py, gcloud/tasktmpl3/permissions.py
=> feature: 添加职能化、审计中心对接权限体系功能 #528

gcloud/tasktmpl3/permissions.py
=> improve: 流程模板添加新建、删除执行方案操作权限 #598

frontend/desktop/src/App.vue, frontend/desktop/src/api/index.js, frontend/desktop/src/api/interceptors.js, frontend/desktop/src/components/common/PipelineCanvas/ConfigBar.vue, frontend/desktop/src/components/common/PipelineCanvas/index.vue, frontend/desktop/src/components/common/modal/PermissionModal.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/directives/cursor.js, frontend/desktop/src/mixins/permission.js, frontend/desktop/src/pages/appmaker/AppCard.vue, frontend/desktop/src/pages/appmaker/AppEditDialog.vue, frontend/desktop/src/pages/home/QuickCreateTask.vue, frontend/desktop/src/pages/home/SelectTemplateDialog.vue, frontend/desktop/src/pages/home/TaskFeeds.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/project/index.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue, frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/task/TaskExecute/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue, frontend/desktop/src/pages/template/TemplateList/index.vue, frontend/desktop/src/routers/index.js, frontend/desktop/src/store/modules/project.js
- 新功能
- 首页收藏模板点击时跳转到模板编辑的权限判断
- 创建任务、职能化认领、任务操作按钮增加权限判断
- 模板编辑保存、保存创建任务按钮权限校验
- 权限弹窗公共逻辑提取
- 无项目id时显示申请权限页面
- 权限申请页面按钮增加权限判断
=> feature: 二级页面操作按钮增加权限判断，权限弹窗公共逻辑提取，无项目id显示权限申请页面

gcloud/core/permissions.py, gcloud/taskflow3/permissions.py, gcloud/tasktmpl3/resources.py
- 新功能
- 执行方案新建、删除权限添加对流程模板编辑权限的依赖
- 优化项
- 权限资源名称优化
=> V3.4.x bk iam bugfix

frontend/desktop/src/App.vue, frontend/desktop/src/api/index.js, frontend/desktop/src/components/common/PipelineCanvas/ConfigBar.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/pages/audit/index.vue, frontend/desktop/src/pages/home/QuickCreateTask.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue, frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue, frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/task/TaskExecute/index.vue, frontend/desktop/src/routers/index.js, frontend/desktop/src/store/modules/project.js, frontend/desktop/src/store/modules/template.js
- 新功能
- 职能化、审计中心用户只能访问对应权限页面
- 审计中心查看链接权限判断
- 创建任务节点方案创建、删除权限判断
- 执行任务页面编辑任务参数按钮权限校验
- 优化项
- 获取项目列表接口is_disable参数默认为false
=> feature:审计中心、创建任务节点方案创建删除、执行任务修改参数权限判断； 职能化、审计中心用户权限控制

frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
=> bugfix: 修复云区域显示问题

frontend/desktop/src/pages/admin/manage/SourceEdit/CacheEdit.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageEdit.vue
=> improvement:编辑远程包源去掉标题

frontend/desktop/src/App.vue, frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/pages/appmaker/AppCard.vue, frontend/desktop/src/pages/appmaker/AppEditDialog.vue, frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue, frontend/desktop/src/pages/appmaker/index.vue, frontend/desktop/src/pages/home/SelectTemplateDialog.vue, frontend/desktop/src/pages/home/TaskFeeds.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue, frontend/desktop/src/routers/index.js, frontend/desktop/src/store/index.js, frontend/desktop/src/store/modules/appmaker.js
=> feature：轻应用创建任务相关权限判断; 权限判断相关逻辑代码用公共方法替换

frontend/desktop/src/pages/home/QuickCreateTask.vue
- 新功能
- 首页快速创建任务点击收藏的模板应该校验创建任务权限
=> sprintfix: 首页快速创建任务点击收藏的模板应该校验创建任务权限

pipeline/core/data/base.py, pipeline/core/flow/activity.py, pipeline_plugins/__init__.py, pipeline_plugins/apps.py
- bug fix
- 修复老版本流程在升级后无法继续操作的问题
close #633
=> bugfix: 修复老版本流程在升级后无法继续操作的问题

gcloud/apigw/views.py, gcloud/taskflow3/api.py, gcloud/taskflow3/models.py, gcloud/taskflow3/utils.py, gcloud/tasktmpl3/models.py, gcloud/tasktmpl3/utils.py, gcloud/tests/apigw/test_apigw.py, pipeline/contrib/web/views_v1.py, pipeline_plugins/components/collections/sites/open/cc.py, pipeline_plugins/components/query/sites/open/query.py, pipeline_plugins/components/utils/common.py, pipeline_plugins/variables/collections/sites/open/cc.py, pipeline_plugins/variables/static/variables/sites/open/var_ip_picker.js, static/variables/sites/open/var_ip_picker.js
=> feature: 全局变量支持从CMDB同步的项目筛选IP #598

frontend/desktop/src/pages/template/TemplateEdit/index.vue
- bug fix
- 修复新建模板流程点击保存后，「保存」、「新建任务」按钮变为没有权限状态的问题
=> bugfix: 修复新建模板流程点击保存后，「保存」、「新建任务」按钮变为没有权限状态的问题

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
=> bugfix: 修复流程统计列表展示一行[resubmit]

pipeline_plugins/components/collections/sites/open/job.py
- bug fix
- 修复 JOB-快速执行脚本 获取业务 ID 错误的问题
=> bugfix: 修复 JOB-快速执行脚本 获取业务 ID 错误的问题

frontend/desktop/src/components/layout/permissionApply.vue
- bug fix
- 轻应用无权限访问项目时隐藏「新建项目」按钮
=> bugfix:轻应用无权限访问项目时隐藏「新建项目」按钮

config/default.py, gcloud/core/middlewares.py, gcloud/core/tasks.py
- bug fix
- 修复在中间件中进行业务同步可能会重复创建项目的问题，改为使用 celery 周期任务进行同步
=> V3.4.x bk iam bugfix biz sync parallel issue

pipeline_plugins/components/collections/sites/open/job.py
- bug fix
- 修复 JOB 快速执行脚本输出错误时可能出现编码错误的问题
=> bugfix: 修复 JOB 快速执行脚本输出错误时可能出现编码错误的问题

auth_backend/constants.py, auth_backend/plugins/tastypie/authorization.py, auth_backend/plugins/tastypie/resources.py
- bug fix
- 修复用户在权限中心中拥有任意资源权限时在标准运维中不生效的问题
=> bugfix: 修复用户在权限中心中拥有任意资源权限时在标准运维中不生效的问题

gcloud/taskflow3/api.py
=> bugfix: 修复获取子流程状态时报错的问题

gcloud/tasktmpl3/resources.py
=> bugfix: 修复无法创建执行方案的问题

frontend/desktop/src/api/index.js, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
=> imprvement: 子流程状态查询接口参数调整

gcloud/periodictask/api.py
- bug fix
- 修复周期任务无法修改周期表达式的问题
=> bugfix: 修复周期任务无法修改周期表达式的问题

frontend/desktop/src/components/common/PipelineCanvas/MenuBar.vue
=> bugfix: 模板编辑无权限子流程禁止添加

frontend/desktop/src/components/layout/Navigator.vue
- 优化项
- 头部导航管理员入口的展示由后台管理查看权限控制
=> improvement:头部导航管理员入口的展示由后台管理查看权限控制

gcloud/tasktmpl3/api.py
=> bugfix: 修复子流程表单无法渲染的问题

frontend/desktop/src/pages/appmaker/AppCard.vue
=> bugfix:轻应用页卡点击执行历史没有跳转修复

frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
=> bugfix: 节点选择画布高度未撑满样式问题修复

frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue, frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
- bug fix
- 职能化认领参数填写页面按钮样式问题修复
- 任务修改参数按钮状态样式问题修复
=> bugfix：职能化认领参数填写页面按钮、任务修改参数按钮状态样式问题修复

frontend/desktop/src/pages/appmaker/AppEditDialog.vue
- bug fix
- 轻应用新建和编辑弹窗确定按钮权限区分
=> bugfix:轻应用新建和编辑弹窗确定按钮权限区分

frontend/desktop/src/api/index.js, frontend/desktop/src/api/urls.js, frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
- bug fix
- 职能化中心认领任务时project_id使用的项目默认id问题修复
=> bugfix: 职能化中心认领任务时project_id使用的项目默认id问题修复

gcloud/taskflow3/resources.py
=> bugfix: 修复公共流程无法新建任务的问题

frontend/desktop/src/App.vue, frontend/desktop/src/routers/index.js, frontend/desktop/src/store/index.js
- bug fix
- 职能化中心认领的任务无法执行任务修复
=> bugfix:职能化中心认领的任务无法执行任务修复

frontend/desktop/src/api/index.js
- bug fix
- 修复创建公共流程project_id为空
=> bugfix: 修复创建公共流程project_id为空

frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- 优化项
- 优化顶部导航栏点击默认选择第一子级
- 改变新增参数 border 颜色
=> feature: 优化顶部导航栏点击默认选择第一子级，改变新增参数 border 颜色【reSubmit】

frontend/desktop/src/components/common/PipelineCanvas/MenuBar.vue
- 优化项
- 新建流程左侧节点类型条里面的开始与结束字号调整
link #559
=>  minor:节点类型条的字号调整

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/task/TaskStep.vue
- bug fix
- 修复创建任务返回cc_id丢失
- 创建任务返回到对应的列表
=> bugfix: 修复创建任务返回cc_id丢失; 创建任务返回到对应的列表

frontend/desktop/src/App.vue
- bug fix
- 增加项目id为空判断，跳转无权限页面申请
=> bugfix:增加项目id为空判断，跳转无权限页面申请

frontend/desktop/builds/webpack.dev.config.js, frontend/desktop/src/assets/html/template.html
=> feature:本地开发配置文件

pipeline/utils/boolrule/boolrule.py
- bug fix
- 修复分支判断表达式解析不严格的
close #674
=> bugfix: 修复分支判断表达式解析不严格的问题

frontend/desktop/src/App.vue, frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/pages/admin/statistics/index.vue, frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue, frontend/desktop/src/pages/appmaker/index.vue, frontend/desktop/src/pages/audit/index.vue, frontend/desktop/src/pages/config/index.vue, frontend/desktop/src/pages/functor/index.vue, frontend/desktop/src/pages/home/index.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskExecute/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/pages/template/TemplateList/index.vue
- 优化项
- 导航栏布局调整
- 首页loading加载区域调整
- bug fix
- 点击首页和任务记录页导航栏消失
=> bugfix: 首页和任务记录页导航栏消失，首页loading加载区域调整，布局调整

frontend/desktop/src/components/layout/Navigator.vue
=> improve: 优化职能化,审计页面 logo 显示错位

frontend/desktop/src/pages/home/index.vue, frontend/desktop/src/pages/task/ParameterInfo.vue, frontend/desktop/src/pages/task/TaskCreate/index.vue, frontend/desktop/src/pages/task/TaskExecute/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/task/TaskStep.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue
- bug fix
- 首页执行详情报错
- 模板编辑画布高度
- 参数填写样式问题
=> bugfix: 前端PR合并引起样式问题修复

frontend/desktop/src/pages/functor/index.vue
- bug fix
- 职能化新建任务切换业务未清空选择流程
=> bugfix: 职能化新建任务切换业务未清空选择流程

frontend/desktop/src/App.vue, frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/config/setting.js, frontend/desktop/src/main.js, frontend/desktop/src/pages/admin/common/template.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/pages/template/TemplateList/index.vue, frontend/desktop/src/routers/index.js
- 新功能
- 全局上下文增加biz_binding和bk_biz_id
- 优化项
- 公共流程新建流程权限和项目新建普通流程按钮的权限区分
=> feature: 全局上下文增加biz_binding和bk_biz_id；公共流程新建流程权限和项目新建普通流程按钮的权限区分

frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue, frontend/desktop/src/pages/task/ParameterInfo.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- bug fix
- 修复IP 选择器修改参数不生效（值没有正确保存）
=> bugfix: 修复IP 选择器修改参数不生效（值没有正确保存）

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TemplateSetting.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/utils/draft.js
- 优化项
- 优化缓存列表为按时间排序
- bug fix
- 修复切换缓存节点图标不更新
=> bugfix: 修复切换缓存图标不更新, 优化缓存列表为按时间排序

config/sites/community/ver_settings.py, pipeline_plugins/apps.py
=> improvement: 插件模块兼容性区分版本

pipeline_plugins/components/static/components/atoms/sites/open/job/job_cron_task.js, pipeline_plugins/components/static/components/atoms/sites/open/job/job_fast_execute_sql.js, static/components/atoms/sites/open/job/job_cron_task.js, static/components/atoms/sites/open/job/job_fast_execute_sql.js
- 优化项
- 新开发的标准插件添加版权头部 
close #697
=> improve:新开发的标准插件添加版权头部 #697

frontend/desktop/src/components/common/PipelineCanvas/ConfigBar.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskStep.vue, frontend/desktop/src/pages/template/TemplateList/index.vue
- 优化项
- 轻应用新建任务去掉返回按钮
- bug fix
- 修复返回按钮问题（任务记录，轻应用，流程模板）
=>  bugfix: 修复返回按钮问题（任务记录，轻应用，流程模板页面），轻应用新建任务去掉返回按钮

frontend/desktop/src/assets/js/node-cron-valid/pattern-validation.js, frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue, frontend/desktop/src/pages/periodic/PeriodicList/ModifyPeriodicDialog.vue
- 优化项
- 周期选择组件间距
- 周期选择组件去掉placeholder
- bug fix
- 周期任务无参数编辑不发请求
- 周期选择组件数字加字母无法验证
=> bugfix: 周期任务无参数编辑不发请求,周期选择组件数字加字母无法验证,优化周期选择组件样式

frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskCreate/index.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
- 优化项
- 新建周期任务标题修改。
- 去掉周期任务执行步骤【任务执行】
- 调整参数信息高度过大
=> improve: 优化N627提出的一些样式问题

frontend/desktop/src/pages/admin/statistics/Appmaker/index.vue, frontend/desktop/src/pages/task/TaskStep.vue
=> improve: 轻应用新建去掉返回按钮

frontend/desktop/src/pages/task/TaskStep.vue
=> improve: 优化轻应用返回到任务记录

readme_en.md
- 优化项
- 优化readme英文文档格式问题 
close #711
=> docs: 优化readme英文文档格式问题 #711

gcloud/core/api_adapter/sites/open/user_role.py, gcloud/tasktmpl3/api.py
- bug fix
- 修复拉取用户信息出错时日志格式化不正确的问题
- 修复导入公共流程时覆盖流程所需权限不正确的问题
=> V3.4.x bk iam bugfix 0710

frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue, frontend/desktop/src/main.js, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- 优化项
- 优化周期规则循环间隔时间验证
- 新建模版时控制台报错
close #720 
close #721
=> improve: 优化周期规则循环间隔时间验证，新建模版时控制台报错

docs/apidoc/en/import_common_template.md, docs/apidoc/zh_hans/import_common_template.md
=> minor: 导入公共流程模板 api 文档参数示例修改

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- 优化项
- 职能化/审计中心时,隐藏[查看流程]按钮
close: #725
=> improve: 职能化/审计中心时,隐藏[查看流程]按钮

frontend/desktop/src/pages/task/NodePreview.vue
- 优化项
- 优化任务预览模式出现一大块空白
close: #723
=> improve: 优化任务预览模式出现一大块空白

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- 优化项
- 节点操作悬浮框样式异常
close: #728
=> improve: 节点操作悬浮框样式异常

config/default.py, frontend/desktop/src/api/index.js, gcloud/commons/template/resources.py, gcloud/tasktmpl3/resources.py, gcloud/webservice3/urls.py
- 新功能
- 公共流程执行方案需要业务隔离，添加公共流程执行方案API 
close #733
=> feature: 公共流程执行方案需要业务隔离，添加公共流程执行方案API #733

frontend/desktop/src/pages/task/TaskList/index.vue
=> improve: 任务记录，用户名过长时，显示有遮挡

gcloud/commons/template/resources.py
- bug fix
- 修复删除公共流程方案错误的问题 
close #733
=> sprintfix: 修复删除公共流程方案错误的问题 #733

frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
=> bugfix: 公共流程删除执行方案不生效

frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- bug fix
- 修复执行方案预览模式下不能切换 
close: #739
=> bugfix: 修复执行方案预览模式下不能切换

gcloud/commons/template/resources.py
=> minor: flake8问题修复

frontend/desktop/src/components/common/PipelineCanvas/index.vue, frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- bug fix
- 修复节点选择预览模式下排除节点在参数填写时会清空的问题
=> bugfix: 修复节点选择预览模式下排除节点在参数填写时会清空的问题

frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- bug fix
- 节点选择预览模式切换方案排除节点在参数填写未更新
=> bugfix:节点选择预览模式切换方案排除节点在参数填写未更新

frontend/desktop/src/scss/iconfont.scss
=> improve: 优化文件覆盖引起的图标错乱

pipeline_plugins/components/utils/sites/open/utils.py
- bug fix
- 修复IP选择器对多内网IP的服务器解析处理问题
close #755
=> bugfix: 修复IP选择器对多内网IP的服务器解析处理问题 #755

config/perms.py
- 优化项
- 产品，开发，测试，职能化人员权限模板移除任务相关权限，改为按需申请
=> minor: 产品，开发，测试，职能化人员权限模板移除任务相关权限，改为按需申请

auth_backend/backends/bkiam.py, auth_backend/plugins/shortcuts.py, gcloud/commons/template/api.py, gcloud/commons/template/models.py, gcloud/tasktmpl3/models.py
- bug fix
- 修复公共流程导入导出相关接口未鉴权的问题 
- 修复导入新流程时没有向权限中心注册的问题
=> bugfix: 1.修复公共流程导入导出相关接口未鉴权的问题 2.修复导入新流程时没有向权限中心注册的问题

gcloud/core/utils/sites/open/utils.py, gcloud/exceptions.py, pipeline_plugins/components/query/sites/open/query.py
=> improvement: 插件请求第三方系统错误时返回 499

frontend/desktop/src/pages/admin/manage/SourceEdit/CacheForm.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageEdit.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue, frontend/desktop/src/pages/admin/manage/SourceSync/index.vue, frontend/desktop/src/pages/admin/manage/index.vue
- bug fix
- 远程包源名称校验规则不存在导致校验报错修复
-  样式调整
=> bugfix: 远程包源名称校验规则不存在导致校验报错修复

pipeline_plugins/cmdb_ip_picker/query.py
- 优化项
- IP选择器查询业务拓扑层级时无权限时后台返回499 
- bug fix
- 修复IP选择器接口报500错误的问题 
close #770
=> V3.4.x bk iam bugfix api

frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
=> improve: IP选择器 border 样式统一

frontend/desktop/src/pages/periodic/PeriodicList/ModifyPeriodicDialog.vue
- bug fix
- 修复有参数时修改周期任务确认按钮一直处于loading状态
=> bugfix: 修复有参数时修改周期任务确认按钮一直处于loading状态

frontend/desktop/src/api/index.js, frontend/desktop/src/pages/functor/index.vue
- bug fix
- 修复职能化中心新建任务加载项目模板列表参数错误
=> bugfix:修复职能化中心新建任务加载项目模板列表参数错误

gcloud/core/command.py, gcloud/core/urls.py
- 新功能
- 管理员可以查看所有settings变量，便于排查环境问题 
close #783
=> feature: 管理员可以查看所有settings变量，便于排查环境问题 #783

config/default.py
- 优化项
- 添加 UUID 首字母数字敏感设定
close #789
=> minor: 添加 UUID 首字母数字敏感设定

gcloud/webservice3/resources.py
- bug fix
- 修复标准插件列表API未返回标记插件前端是否内置的字段的问题 
close #791
=> bugfix: 修复标准插件列表API未返回标记插件前端是否内置的字段的问题 #791

pipeline/contrib/external_plugins/utils/importer/git.py, pipeline/contrib/external_plugins/utils/importer/s3.py
- 优化项
- HTTP的GIT/S3导入远程插件失败提示优化 
link #486
=> minor: HTTP的GIT/S3导入远程插件失败提示优化 #486

frontend/desktop/src/components/common/PipelineCanvas/ConfigBar.vue, frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/task/TaskStep.vue, frontend/desktop/src/pages/template/TemplateList/index.vue
- 优化项
- 优化返回链接错误和高亮问题
- bug fix
- 克隆流程的操作按钮修复
close: #564
=> improve: 优化返回链接错误和高亮问题；克隆流程的操作按钮修复

frontend/desktop/src/pages/home/index.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
=> improve: 优化首屏和参数填写页闪屏问题

frontend/desktop/src/pages/task/ParameterInfo.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
- 优化项
- 优化参数填写页面 footer 位置保持在最下方
=> improve: 优化参数填写页面 footer 位置保持在最下方

frontend/desktop/src/components/common/PipelineCanvas/index.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/ConditionItem.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/IpSearchInput.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/SelectCondition.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue, frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue, frontend/desktop/src/pages/task/TaskExecute/index.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- 优化项
- 画布编辑添加节点个数底色增加透明度
- 导出流程卡片圆角，删除已选流程icon底色
- ip 选择器禁用态样式优化
- 任务执行步骤底色统一
=> improvement: 样式优化项

pipeline/docs/quick_start.md
=> minor: bamboo 文档添加索引

frontend/desktop/src/pages/task/ParameterInfo.vue
- bug fix
- 修复未未引用变量隐藏时，参数列表显示不为空 
close: #810
=> bugfix: 修复未未引用变量隐藏时，参数列表显示不为空

gcloud/taskflow3/models.py
- 优化项
- 优化 taskflow 部分操作抛出异常时打印的错误日志
close #807
=> improvement: 优化 taskflow 部分操作抛出异常时打印的错误日志

auth_backend/resources/django.py
- 优化项
- DjangoModelResource 实例注册、更新、删除失败时添加错误日志
=> improvement: DjangoModelResource 实例注册、更新、删除失败时添加错误日志

frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/routers/index.js
- bug fix
- 用户无初始化项目权限时，导航区域点击会跳转404修复
=> bugfix:用户无初始化项目权限时，导航区域点击会跳转404修复

frontend/desktop/src/pages/project/index.vue
=> feature: 项目管理新增查看操作

frontend/desktop/src/pages/project/index.vue
- 优化项
- 新建项目导航栏项目列表同步刷新
close: #801
=> improve: 新建项目导航栏项目列表未同步刷新 

frontend/desktop/src/App.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/routers/index.js
- 优化项
- 无权限申请页面点击去申请无项目时跳转到项目管理页面，反之跳转到权限中心申请查看权限
=> improvement: 无权限申请页面点击去申请无项目时跳转到项目管理页面，反之跳转到权限中心申请查看权限

frontend/desktop/src/pages/admin/manage/SourceEdit/CacheForm.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageEdit.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue, frontend/desktop/src/pages/admin/manage/SourceManage/index.vue
- 优化项
- 表格编辑表单增加hover时的边框颜色变更
- 包源模块配置增加必填校验
- bug fix
- 包源模块配置删除逻辑错误修复
- 添加主包源文案错误
=> 远程包源管理相关优化和bugfix

pipeline_plugins/components/static/components/atoms/bk/http.js
- bug fix
- 「发送请求」标准插件URL正则匹配规则引起回溯问题修复
=> bugfix:「发送请求」标准插件URL正则匹配规则引起回溯问题修复

frontend/desktop/src/pages/home/index.vue
=> bugfix: 修复首页报错问题

docs/apidoc/en/create_task.md, docs/apidoc/en/get_task_detail.md, docs/apidoc/en/get_task_node_detail.md
- 优化项
- 删除英文 API 文档中的中文
close #828
=> minor: 删除英文 API 文档中的中文

static/components/atoms/bk/http.js
- bug fix
- 「http请求」标准插件URL正则匹配修改同步到static文件夹
=> minor: 「http请求」标准插件URL正则匹配修改同步到static文件夹

frontend/desktop/src/pages/admin/statistics/verticalBarChart/index.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/scss/datastatistics/datastatistics.scss
- 优化项
- 数据统计在小屏幕下的样式问题
- 执行任务页面 tooltip 样式问题
- 任务统计时间维度图样式调整
=> improve: 样式调整

frontend/desktop/src/pages/admin/statistics/verticalBarChart/index.vue
=> minor: 任务统计国际化

pipeline_plugins/components/static/components/atoms/bk/http.js, static/components/atoms/bk/http.js
- bug fix
- 「http请求」标准插件url匹配规则修改
=> bugfix: 「http请求」标准插件url匹配规则修改

weixin/core/accounts.py
=> minor: 添加日志

frontend/desktop/src/components/common/modal/ErrorCode405.vue, frontend/desktop/src/components/common/modal/ErrorCode406.vue, frontend/desktop/src/mixins/permission.js
- 优化项
- 添加 scope_type_name
- bk_cc 改为 bk_cmdb
=> improve: 添加 scope_type_name, bk_cc 改为 bk_cmdb

pipeline/conf/default_settings.py, pipeline/core/flow/event.py, pipeline/engine/exceptions.py, pipeline/engine/signals/__init__.py, pipeline/engine/signals/dispatch.py, pipeline/engine/signals/handlers.py, pipeline/tests/utils/boolrule/tests.py, pipeline/utils/boolrule/boolrule.py
- 新功能
- 增加pipeline流程结束事件信号
close #786 
- bug修复
- 网关的条件中配置多层级校验无效问题
close #785
=> 增加pipeline流程end事件的回调和网关校验无效问题修复

frontend/desktop/src/components/common/modal/PermissionModal.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- 优化项
- 没有权限访问资源的格式优化
- 导出流程无权限卡片优化样式
- 申请权限弹窗里面需要申请的资源内容缺失
=> improve: 申请的资源内容缺失，资源的格式优化，无权限卡片优化样式

pipeline/core/flow/event.py, pipeline/signals/handlers.py
- 优化项
- 将 PipelineInstance SetFinish 动作提到上层
close #845
=> improvement: 将 PipelineInstance SetFinish 动作提到上层

docs/develop/dev_plugins.md
=> minor: 更新标准插件开发文档

frontend/desktop/src/pages/template/TemplateEdit/index.vue
- bug fix
- 修复第一次【保存并新建任务】获取不到模板信息
=> bugfix: 修复第一次【保存并新建任务】获取不到模板信息

frontend/mobile/src/main.js
=> bugfix:移动端清理无关引用

docs/apidoc/en/get_common_template_info.md, docs/apidoc/en/get_common_template_list.md, docs/apidoc/en/get_template_info.md, docs/apidoc/sops.yaml, docs/apidoc/zh_hans/get_common_template_info.md, docs/apidoc/zh_hans/get_common_template_list.md, gcloud/apigw/urls.py, gcloud/apigw/views.py
- 新功能
- 添加公共流程相关 API
close #854
=> feature: 添加公共流程相关 API

frontend/desktop/src/components/common/base/AdvanceSearch.vue
=> minor: 高级搜索组件重命名文件提交

auth_backend/plugins/delegation.py, auth_backend/plugins/tastypie/authorization.py, gcloud/contrib/function/resources.py, gcloud/taskflow3/resources.py
- 新功能
- 职能化任务API接入权限中心鉴权 
link #815
=> feature: 职能化任务API接入权限中心鉴权 #815

docs/install/mobile_deploy.md, gcloud/core/middlewares.py, readme.md, readme_en.md, weixin/core/accounts.py
- 优化项
- 移动端文档图片大小调整
- bug fix
- 定位移动端访问user类型错误报错500问题 
link #863
=> Mobile bugfix user error

weixin/core/middlewares.py
- bug fix
- 修复移动端访问设置request.user属性错误导致500的问题 
close #863
=> bugfix：修复移动端访问设置request.user属性错误导致500的问题 #863

pipeline/core/flow/event.py
- 优化项
- 删除 EmptyEndEvent 中的无用逻辑
=> improvement: 删除 EmptyEndEvent 中的无用逻辑

frontend/desktop/src/mixins/permission.js
=> improvre: 申请权限 url 获取接口参数补充

gcloud/core/utils/common/apis.py
- bug fix
- 调整向权限申请 URL 获取请求格式
=> bugfix: 调整向权限申请 URL 获取请求格式

frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue, frontend/desktop/src/components/common/PipelineCanvas/index.vue, frontend/desktop/src/components/common/base/DialogLoadingBtn.vue, frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/pages/appmaker/AppEditDialog.vue, frontend/desktop/src/pages/appmaker/index.vue, frontend/desktop/src/pages/config/index.vue, frontend/desktop/src/pages/periodic/PeriodicList/ModifyPeriodicDialog.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/ParameterInfo.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEditDialog.vue, frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue, frontend/desktop/src/pages/template/TemplateList/index.vue
- 优化项
- 模板导出弹窗按钮宽度调整
- 变量编辑弹窗padding恢复
- 上传文件和导入列表的间距调整
- 周期任务列表、任务记录列表创建任务弹窗搜索框样式优化
- 全局变量和本地缓存tooltip icon颜色保持一致
- 头部导航用户头像的tooltip对齐
- 业务配置任务执行者tooltip宽度调整
- 任务创建弹窗模板卡片圆角统一为2px
- 模板列表高级搜索时间空间增加placeholder
- 变量编辑select底色统一为白色
- 编辑周期任务弹窗周期信息组件水平居中
- 轻应用列表高级搜索清空按钮对时间生效
- bug fix
- 画布编辑复位icon错误修复，节点框选icon激活态样式恢复
- 参数填写未引用tooltip样式错乱修复
- 周期任务列表更多操作下拉框在safari不显示的问题修复
- 任务列表查询按钮间距调整
- 模板列表高级搜索清空按钮对子流程更新不起作用
- 轻应用编辑弹窗padding恢复
- 周期任务列表页启动状态icon颜色错误修复
=> magicbox组件升级引入问题修复

frontend/desktop/package.json, frontend/desktop/src/pages/appmaker/AppEditDialog.vue, frontend/desktop/src/pages/appmaker/index.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskExecute/GatewaySelectDialog.vue, frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/task/TaskExecute/revokeDialog.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue, frontend/desktop/src/pages/template/TemplateList/index.vue, frontend/desktop/src/scss/common.scss
- 优化项
- 模板导出弹窗支持输入框搜索支持清除
- 节点配置失败处理组件替换
- bug fix
- 轻应用页面报错、编辑问题修复
- 职能化认领预览弹窗不显示问题修复
- 任务执行撤销弹窗、分支跳过弹窗不显示问题修复
- 模板列表、周期任务列表操作项显示不全修复
link #883
=> magicbox 版本升级引入问题修复

app.yml
=> minor: 将应用市场翻译移动到 app.yml 中

frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- 新功能
- Tag select增加set_loading方法
close #892
=> feature: Tag select增加set_loading方法

frontend/mobile/src/views/task/canvas.vue
- bug fix
- 正在执行的节点，只有暂停节点才能有继续按钮，定时节点有修改定时，其他都没有操作项
- 失败节点重试,直接重试没有二次确认
- 修正当没有任何操作按钮的时候显示问题
=> bugfix:修复节点操作和显示逻辑不正确的问题 #897

frontend/desktop/src/components/common/PipelineCanvas/ConfigBar.vue, frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue, frontend/desktop/src/pages/task/TaskCreate/index.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/task/TaskStep.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/pages/template/TemplateList/index.vue
- 优化项
- 新建流程、任务执行返回优化
close: #812
=> improve:  新建流程、任务执行返回优化

frontend/desktop/src/components/common/PipelineCanvas/MenuBar.vue, frontend/desktop/src/components/common/PipelineCanvas/index.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
=> feature: 原子节点和子流程节点支持直接拖拽出来

frontend/desktop/src/store/modules/template.js
=> bugfix: 修复切换子流程控制台报错

frontend/desktop/src/components/common/RenderForm/FormGroup.vue, frontend/desktop/src/components/common/RenderForm/FormItem.vue, frontend/desktop/src/components/common/RenderForm/RenderForm.vue, frontend/desktop/src/components/common/RenderForm/tags/TagCheckbox.vue, frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue, frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue, frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEditDialog.vue, frontend/desktop/src/scss/reset.scss
- 优化项
- 标准插件表单勾选到全局变量checkbox组件替换为magicbox组件
- Tag 类组件默认接受value数据类型扩展
- 默认去掉所有元素outline
- bug fix
- ip选择器变量勾选报错修复
link #883
=> magicbox组件替换bugfix和优化

frontend/desktop/src/directives/cursor.js, frontend/desktop/src/pages/functor/index.vue
- 新功能
- 职能化中心新建任务弹窗确定按钮增加权限判断
- 职能化中心任务列表增加权限判断
close #815
=> feature:职能化中心新建任务弹窗确定按钮增加权限判断

frontend/desktop/src/components/common/RenderForm/FormItem.vue
- 优化项
- TagRadio和TagSelect支持Boolean类型的value值
=> improvement: TagRadio和TagSelect支持Boolean类型的value值

frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/pages/appmaker/AppCard.vue
- 优化项
- 权限中心版本无权限页面内容高度调整为百分比
- 轻应用卡片无权限操作按钮增加锁头动画
=> improvement: 权限中心版本无权限页面内容高度调整为百分比，轻应用卡片无权限操作按钮增加锁头动画

frontend/desktop/src/components/common/modal/PermissionModal.vue, frontend/desktop/src/components/layout/permissionApply.vue
- 优化项
- iframe中申请权限打开app跳转到权限中心
close #890
=> feature: iframe中申请权限打开app跳转到权限中心

frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue
- 优化项
- 全局变量 tips 里面输入输出类型文字后增加对应图标
- 全局变量列表 hover 输入输出 icon 时增加 tooltip
- ip 选择器增加最外层边框
=> improvement: 全局变量相关样式优化，ip选择器增加最外层边框

config/perms.py
=> minor: 修改权限模板的名称

auth_backend/conf.py, auth_backend/resources/base.py, auth_backend/tests/mock_path.py, auth_backend/tests/resources/base/test_resource.py
- 优化项
- 返回的数据结构中添加 scope_type_name 字段
=> minor: Resource 返回的数据结构中添加 scope_type_name 字段

auth_backend/resources/base.py, auth_backend/resources/django.py, auth_backend/tests/resources/base/test_resource.py
=> bugfix: 修复实例清洗逻辑错误的问题

frontend/desktop/src/components/common/modal/PermissionModal.vue
=> improve: 新建项目不传资源实例

weixin/templates/weixin/index.html
- 优化项
- 正式出包前去掉前端调试工具VConsole 
close #917
=> minor: 正式出包前去掉前端调试工具VConsole #917

config/sites/community/ver_settings.py
- bug fix
- 修复从 3.2.X 升级到 3.3.X 时流程无法继续的问题
close #920
=> bugfix: 修复从 3.2.X 升级到 3.3.X 时流程无法继续的问题

auth_backend/plugins/utils.py, auth_backend/tests/plugins/test_utils.py, pipeline_plugins/components/query/sites/open/query.py
- bug fix
- 修复 499 响应返回 permission 接口不正确的问题
=> bugfix: 修复 499 响应返回 permission 接口不正确的问题

frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue, frontend/desktop/src/components/common/PipelineCanvas/ConfigBar.vue, frontend/desktop/src/pages/appmaker/index.vue, frontend/desktop/src/pages/config/index.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue, frontend/desktop/src/pages/template/TemplateList/index.vue, frontend/desktop/src/scss/datastatistics/datastatistics.scss
- 优化项
- 周期表达式样式错位
- 周期任务没有输入验证
- 业务配置样式问题
- 流程模板和公共流程搜索多一个图标
- 轻应用清空未触发搜索
- 轻应用右侧未对齐
- 流程编辑中节点失败处理提示高度不对
- 全局变量是否显示禁止清空
- 变量KEY换行而不是隐藏
- 数据统计页面底色问题
- 运行次数表头宽度调整
- 失败处理换行了
- 执行方案预览列表，hover 样式统一，参考缓存列表
- 任务记录创建任务弹窗选择流程分类缺少默认值，且不能清空
- 画布编辑「保存并新建任务」按钮颜色统一
- 全局变量 tips 优化
- bug fix
- 周期任务列表新建周期任务弹窗选择业务类型切换后数据丢失
=> improve: magicbox 升级回归测试问题修复-2

frontend/desktop/src/components/common/RenderForm/IpSelector/ConditionItem.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/IpSearchInput.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue, frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue, frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/task/TaskList/TaskCloneDialog.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabLocalDraft.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEditDialog.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- 优化项
- 树组件label间距优化，全局变量操作按钮样式调整，本地缓存input组件替换
- 全局变量、本地缓存tooltip内容间距调整
- 全局变量、本地缓存列表删除icon颜色统一
- 基础信息选择框字号统一
- 任务克隆弹窗input替换为bk-input
- 全局变量、本地缓存tooltip出现和隐藏去掉延时
- bug fix
- 模板导出弹窗已选择模板删除icon显示不全修复
- 任务记录删除失败后弹窗不显示问题修复
- TagTextarea行距太高调整
- 任务执行参数查看编辑按钮点击激活区域问题修复
=> magicbox升级回归测试问题修复

docs/apidoc/en/get_common_template_info.md, docs/apidoc/en/get_common_template_list.md, docs/apidoc/sops.yaml, docs/apidoc/zh_hans/get_common_template_info.md, docs/apidoc/zh_hans/get_common_template_list.md, gcloud/apigw/decorators.py, gcloud/apigw/urls.py, gcloud/apigw/views.py
- 新功能
- 添加公共流程模板列表，公共流程模板详情 API
=> feature: 添加公共流程模板列表，公共流程模板详情 API

docs/install/mobile_deploy.md
=> docs: 移动端部署环境变量配置图优化

auth_backend/backends/utils.py
=> improvement: 获取不到鉴权后端时抛出异常

gcloud/core/utils/sites/open/utils.py, pipeline_plugins/variables/static/variables/select.js, static/variables/select.js
- 优化项
- 提升事务执行速度，降低可能出现的deadlock概率
=> Bugfix db deadlock

gcloud/webservice3/resources.py
- bug fix
- 修复后台没有对项目描述字段长度进行限制的问题
=> bugfix: 修复后台没有对项目描述字段长度进行限制的问题

gcloud/tasktmpl3/resources.py
- bug fix
- 修复模板执行方案获取接口过滤条件不生效的问题
=> bugfix: 修复模板执行方案获取接口过滤条件不生效的问题

gcloud/taskflow3/api.py, pipeline_plugins/components/query/sites/open/query.py
- 优化项
- 获取 job 执行日志处理 job 返回无权限的情况
=> improvement: 获取 job 执行日志处理 job 返回无权限的情况

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- bug fix
- 任务执行节点树点击根节点请求参数错误修复
=> bugfix: 任务执行节点树点击根节点请求参数错误修复

frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- bug fix
- 轻应用创建任务参数填写任务申请权限是resource_id取轻应用id
=> bugfix: 轻应用创建任务参数填写任务申请权限是resource_id取轻应用id

frontend/desktop/src/pages/audit/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue
=> improvement: 无查看权限任务执行状态显示

frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
- bug fix
- 轻应用任务记录列表跳转到任务详情项目id字段取用错误修复
=> bugfix: 轻应用任务记录列表跳转到任务详情项目id字段取用错误修复

auth_backend/plugins/tastypie/authorization.py, auth_backend/plugins/tastypie/inspect.py, auth_backend/plugins/tastypie/resources.py, gcloud/contrib/function/resources.py
- 优化项
- tastypie 资源探测器添加实例 id 探测功能
=> improvement: tastypie 资源探测器添加实例 id 探测功能

frontend/desktop/src/components/common/modal/PermissionModal.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/mixins/permission.js
- bug fix
- 无权限人员首次进入应用报错问题修复
- 创建项目权限申请url不需要传资源参数
=> bugfix: 无权限人员首次进入应用报错问题修复；创建项目权限申请url不需要传资源参数

gcloud/core/models.py, gcloud/core/project.py, gcloud/core/tasks.py, gcloud/core/utils/sites/open/utils.py, gcloud/tests/core/models/test_project.py, gcloud/tests/mock.py
=> improvement: 同步 CMDB 中已归档的业务并停用

frontend/desktop/src/directives/cursor.js
- bug fix
- 无权限按钮上的锁头在获取权限后状态未发生变更修复
=> bugfix: 无权限按钮上的锁头在获取权限后状态未发生变更修复

frontend/desktop/src/pages/admin/manage/SourceManage/PackageTable.vue
=> feature: 远程插件，已导入插件接入数据

gcloud/apigw/constants.py, gcloud/apigw/decorators.py, gcloud/apigw/utils.py, gcloud/apigw/views.py, gcloud/tests/apigw/test_apigw.py
- 优化项
- API 兼容存量调用，默认通过 bk_biz_id 来检索项目
=> feature: API 兼容存量调用，默认通过 bk_biz_id 来检索项目

pipeline/builder/builder.py, pipeline/builder/flow/activity.py, pipeline/core/constants.py, pipeline/engine/core/handlers/service_activity.py, pipeline/engine/core/schedule.py, pipeline/engine/signals/__init__.py, pipeline/parser/pipeline_parser.py, pipeline/service/pipeline_engine_adapter/adapter_api.py, pipeline/service/task_service.py, pipeline/tests/engine/core/handlers/test_service_act_handler.py, pipeline/tests/engine/core/test_schedule.py
- 优化项
- 引擎节点失败处理配置优化
close #954
=> improvement: 引擎节点失败处理配置优化

frontend/desktop/src/constants/manage.js, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue
- 优化项
- 远程包输入框提示样式需要优化
- GIT类型的远程包源信息填写加提示
=> improve: 远程包输入框提示样式需要优化

frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue, frontend/desktop/src/pages/appmaker/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/scss/mixins/advancedSearch.scss
- 新功能
- 轻应用任务记录添加高级搜索
- 说明
- 必须在 V3.3.X 合入 magicbox_update 后，才能并入此更改！
colse: #743
=> feature: 轻应用任务记录添加高级搜索

frontend/desktop/src/pages/admin/manage/SourceEdit/CacheEdit.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/CacheForm.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageEdit.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue, frontend/desktop/src/pages/admin/manage/SourceManage/index.vue, frontend/desktop/src/pages/admin/manage/SourceSync/index.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue
- 优化项
- 远程包 magicbox 组件更新
- 全局变量图标 tips 组件替换
=> improve: 远程包 magicbox 组件更新

frontend/mobile/src/components/VantForm/VantSelect.vue, frontend/mobile/src/components/VantForm/index.vue
=> bugfix:修复元变量单选显示错误的问题

frontend/desktop/src/pages/task/TaskParamEdit.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- bug fix
- 全局变量自定义校验规则未生效问题修复
close #958
=> bugfix: 全局变量自定义校验规则未生效问题修复

frontend/desktop/src/assets/js/node-cron-valid/convert-expression/index.js, frontend/desktop/src/assets/js/node-cron-valid/convert-expression/month-names-conversion.js, frontend/desktop/src/assets/js/node-cron-valid/convert-expression/range-conversion.js, frontend/desktop/src/assets/js/node-cron-valid/convert-expression/step-values-conversion.js, frontend/desktop/src/assets/js/node-cron-valid/convert-expression/week-day-names-conversion.js, frontend/desktop/src/assets/js/node-cron-valid/pattern-validation.js
- 优化项
- 周期表达式验证性能优化
close: #903
=> improve:  周期表达式验证优化

frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue, frontend/desktop/src/pages/admin/manage/SourceManage/PackageTable.vue
- 优化项
- 远程包样式优化
- bug fix
- 修复远程包详细新字段显示错误
=> improve: 远程包样式优化，修复显示字段错误

frontend/desktop/src/constants/manage.js, frontend/desktop/src/pages/admin/manage/SourceEdit/EditHeader.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageEdit.vue, frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue
- 优化项
- 远程包类型切换数据空白
- 步骤条样式修改
- 模块表格宽度调整
- 模块配置默认渲染一行
- 删除模块配置（只有一条时不显示删除按钮）
close: #972
=> improve: 远程包相关逻辑和样式优化

gcloud/core/models.py, gcloud/webservice3/resources.py
- bug fix
- 修改业务可用性的判断规则
close #865
=> bugfix: 修改业务可用性的判断规则

weixin/core/accounts.py, weixin/core/middlewares.py, weixin/core/migrations/0004_weixinusersession.py, weixin/core/models.py, weixin/core/utils.py
- 优化项
- 移动端登录状态session实现优化 
close #981
=> improve: 移动端登录状态session实现优化 #981

weixin/core/middlewares.py, weixin/core/migrations/0005_auto_20190827_1024.py, weixin/core/models.py
- bug fix
- 修复微信cookies设置错误问题 
close #981
=> bugfix: 微信cookies设置错误问题 #981

weixin/core/models.py
- bug fix
- 修复session过期时间对比错误问题 
link #981
=> bugfix: 修复session过期时间对比错误问题 #981

frontend/desktop/src/pages/task/TaskExecute/GatewaySelectDialog.vue
- 优化项
- 任务执行失败分支条件选择弹窗，默认选中第一个分支
close #969
=> improvement: 任务执行失败分支条件选择弹窗，默认选中第一个分支

weixin/core/middlewares.py
- bug fix
- 修复直接返回401导致登录失败时500问题 
link #981
=> bugfix: 修复直接返回401导致登录失败时500问题 #981

frontend/desktop/src/config/setting.js
- 优化项
- $.context上下文增加biz_cc_id兼容旧数据
=> improvement: $.context上下文增加biz_cc_id兼容旧数据

gcloud/core/migrations/0011_create_project_for_non_active_biz.py
- bug fix
- 修复进行归档业务迁移到项目时创建者不正确的问题
=> bugfix: 修复进行归档业务迁移到项目时创建者不正确的问题

frontend/desktop/src/components/common/PipelineCanvas/ConfigBar.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
- 优化项
- IP 选择器样式优化
- 新建模版返回按钮宽度和导出统一
=> improve: IP 选择器样式优化

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- 优化项
- 全局变量输入框类型默认值正则规则与显示/隐藏状态下校验逻辑优化
#958
=> improvement: 全局变量输入框类型默认值正则规则与显示/隐藏状态下校验逻辑优化

pipeline/contrib/external_plugins/models/base.py
- bug fix
- 修复S3远程包源serviece_address不合法时接口报500的问题 
close #1011
=> bugfix: 修复S3远程包源serviece_address不合法时接口报500的问题 #1011

frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- 优化项
- 周期任务执行时隐藏立即执行按钮
close: #1005
=> improve: 周期任务执行时隐藏立即执行按钮

frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
- bug fix
- 修复任务执行时 IP 选择器编辑未保存
=> bugfix: 修复任务执行时 IP 选择器编辑未保存

pipeline_plugins/components/collections/sites/open/job.py
- bug fix
- 修复 JOB 部分插件没有处理 data.inputs 中不存在 biz_cc_id 的问题
=> bugfix: 修复 JOB 部分插件没有处理 data.inputs 中不存在 biz_cc_id 的问题

locale/en/LC_MESSAGES/djangojs.po
=> docs: 优化翻译

frontend/desktop/src/components/common/RenderForm/FormGroup.vue, frontend/desktop/src/components/common/RenderForm/FormItem.vue, frontend/desktop/src/components/common/RenderForm/RenderForm.vue, frontend/desktop/src/components/common/RenderForm/tags/TagButton.vue
- 新功能
- 增加 TagButton
- 支持标准插件表单单行布局
=> feature: 标准插件增加TagButton和单行布局支持

auth_backend/backends/base.py, auth_backend/backends/bkiam.py, auth_backend/backends/utils.py, auth_backend/contrib/consistency/tests/test_legacy.py, auth_backend/resources/base.py, auth_backend/tests/backends/test_bkiam.py, auth_backend/tests/backends/test_utils.py, auth_backend/tests/mock_path.py, gcloud/contrib/auth/__init__.py, gcloud/contrib/auth/backend.py, gcloud/tests/contrib/__init__.py, gcloud/tests/contrib/test_backend.py, gcloud/tests/mock_settings.py
=> feature: 添加无权限后端

frontend/desktop/src/components/common/RenderForm/tags/TagButton.vue
=> minor: TagButton.vue加上版权说明

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 节点可选按钮状态未改变
close: #1036
=> bugfix: 节点可选按钮状态未改变

frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
- bug fix
- 新建任务搜索任何值都是无数据
close: #1029
=> bugfix: 新建任务搜索任何值都是无数据

frontend/desktop/src/components/common/PipelineCanvas/ConfigBar.vue, frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskCreate/index.vue, frontend/desktop/src/pages/task/TaskExecute/index.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/task/TaskStep.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/pages/template/TemplateList/index.vue, frontend/desktop/src/routers/index.js
- 优化项
- 模板编辑、任务创建、任务执行、特殊人员、返回链接相关逻辑优化
- 管理员入口添加新建、编辑、克隆路由
=> improve: 返回按钮（链接）相关优化

frontend/mobile/src/components/MobileCanvas/index.vue
=> bugfix:移动端画布分支条件添加样式

frontend/desktop/src/config/setting.js
- 新功能
- $.content上新增getConstants方法获取当前流程模板的全局变量值
close #1045
=> feature: $.content上新增getConstants方法获取当前流程模板的全局变量值

frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
- 新功能
- 上传组件增加手动上传按钮，支持传入自定义上传函数
close #1035
=> feature: 上传组件增加手动上传按钮，支持传入自定义上传函数

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/store/modules/atomForm.js
=> feature: 标准插件配置面板添加版本切换

frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- 优化项
- 新建周期任务隐藏执行计划
close: #1013
=> improve: 新建周期任务时隐藏执行计划

docs/apidoc/en/create_periodic_task.md, docs/apidoc/en/create_task.md, docs/apidoc/en/fast_create_task.md, docs/apidoc/en/get_common_template_info.md, docs/apidoc/en/get_common_template_list.md, docs/apidoc/en/get_periodic_task_info.md, docs/apidoc/en/get_task_detail.md, docs/apidoc/en/get_task_status.md, docs/apidoc/en/get_template_info.md, docs/apidoc/en/get_template_list.md, docs/apidoc/en/modify_constants_for_periodic_task.md, docs/apidoc/readme.md, docs/apidoc/sops.yaml, docs/apidoc/zh_hans/create_periodic_task.md, docs/apidoc/zh_hans/create_task.md, docs/apidoc/zh_hans/fast_create_task.md, docs/apidoc/zh_hans/get_common_template_info.md, docs/apidoc/zh_hans/get_periodic_task_info.md, docs/apidoc/zh_hans/get_task_detail.md, docs/apidoc/zh_hans/get_task_status.md, docs/apidoc/zh_hans/get_template_info.md, docs/apidoc/zh_hans/modify_constants_for_periodic_task.md
- 优化项
- 新增快速新建任务API文档，部分API文档优化 
link #1057
=> docs：新增快速新建任务API文档，部分API文档优化 #1057

frontend/mobile/src/components/MobileCanvas/index.vue
=> bugfix:修复移动端画布分支条件css的问题

pipeline_plugins/components/collections/sites/open/cc.py, pipeline_plugins/components/collections/sites/open/job.py, pipeline_plugins/tests/components/collections/sites/open/job_test/test_job_cron_task.py, pipeline_plugins/tests/components/collections/sites/open/job_test/test_job_execute_task.py
=> feature: V3.3 新增插件适配权限中心

gcloud/external_plugins/resources.py
=> feature: 包源管理接入权限中心

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 子流程节点combine类参数勾选source_tag赋值不正确问题修复
close #1069
=> bugfix: 子流程节点combine类参数勾选source_tag赋值不正确问题修复

frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
=> minor: 去掉eslint校验不合法的call调用

frontend/mobile/src/store/modules/task.js
=> bugfix: 任务节点继续接口参数传递错误修复

gcloud/core/api_adapter/sites/open/user_info.py
- bug fix
- 修复 3.3.X 合入 3.4.X 时引入的用户信息获取的问题
close #1099
=> 修复 3.3.X 合入 3.4.X 时引入的用户信息获取的问题

gcloud/taskflow3/context.py, gcloud/taskflow3/utils.py
- bug fix
- 修复运维人员执行任务随机使用业务任一运维身份的问题 
close #1101
=> bugfix: 修复运维人员执行任务随机使用业务任一运维身份的问题 #1101

frontend/mobile/src/views/task/create.vue
- bug fix
- 修复新建任务预览流程后执行方案未生效的问题
=> bugfix:修复新建任务预览流程后执行方案未生效的问题

frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue, frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue, frontend/desktop/src/pages/task/TaskExecute/ModifyTime.vue, frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue, frontend/desktop/src/pages/task/TaskExecute/ViewParams.vue, frontend/desktop/src/pages/task/TaskParamEdit.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/ReuseVarDialog.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/scss/common.scss, frontend/desktop/src/store/modules/atomList.js, frontend/desktop/src/store/modules/template.js, frontend/desktop/src/utils/atomFilter.js, frontend/desktop/src/utils/tools.js
- 优化项
- 侧边栏插件列表中不需要展示插件多版本
- 全局变量 key 唯一，相关逻辑改
- 全局变量添加版本信息
- 还原 tagcode 相关处理逻辑
- bug fix
- 修复切换版本信息未清空，修改全局变量复用逻辑
-修复切换版本表单勾选状态未更新
close: #1089
=> bugfix: 插件版本全局变量相关bug修复

frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
=> minor: 修复前端webpack失败问题

frontend/desktop/src/components/common/PipelineCanvas/ConfigBar.vue, frontend/desktop/src/pages/task/TaskExecute/index.vue, frontend/desktop/src/pages/task/TaskStep.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue
+ 优化项
- 返回链接优化
- 任务执行都返回到任务记录列表
- 职能化认领返回到任务记录列表（因为职能化认领页面只能是任务记录页面进入）
- 模版新建按钮进入到任务创建页-返回到模版编辑页面
=> improve: 返回链接优化

frontend/desktop/src/utils/validatePipeline.js
- 优化项
- 画布节点出入度规则修改
- 去掉汇聚节点和并行、分支节点个数匹配逻辑
=> improvement: 画布节点出入度规则修改，去掉汇聚节点和并行、分支节点个数匹配逻辑

frontend/desktop/src/components/common/modal/PermissionModal.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- 优化项
-  周期任务、任务记录列表页创建任务弹窗模板增加权限判断
=> feature: 创建任务弹窗模板增加权限判断

frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue
- 优化项
- 周期任务表达式样式和文案修复
close: #1115
=> improve: 周期任务表达式样式和文案修复

gcloud/contrib/appmaker/models.py
- 优化项
- 轻应用未上传LOGO时，logo_url 设置为空 
close #1116
=> improve: 轻应用未上传LOGO时，logo_url 设置为空 #1116

frontend/desktop/src/pages/appmaker/AppCard.vue, frontend/desktop/src/pages/appmaker/AppEditDialog.vue
- 优化项
- 轻应用列表 logo 为空显示默认图片
link #1116
=> improve: 轻应用列表 logo 为空显示默认图片

gcloud/tasktmpl3/api.py
- 优化项
- template/api/draw_pipeline/ 改为 application/json 协议
link #1085
=> improve: template/api/draw_pipeline/ 改为 application/json 协议 #1085

gcloud/taskflow3/api.py
- 优化项
- 任务状态获取接口权限豁免
close #1134
=> improvement: 任务状态获取接口权限豁免

requirements.txt
- bug fix
- 修复requirements.txt 未加入 PyJWT 依赖包的问题 
link #1106
=> sprintfix: 修复requirements.txt 未加入 PyJWT 依赖包的问题 #1106

frontend/desktop/src/config/setting.js
- 新功能
- $.context上添加是否可选业务方法、获取属性方法
=> feature: $.context上添加是否可选业务方法、获取属性方法

frontend/desktop/src/App.vue, frontend/desktop/src/config/setting.js
- 优化项
- $.context在非项目页面，project相关字段置为undefinde
- $.context 去掉 bk_biz_id，增加getBkBizId方法
=> feature: $.context在非项目页面，project相关字段置为undefinde；去掉 bk_biz_id，增加getBkBizId方法

gcloud/taskflow3/context.py, gcloud/taskflow3/urls.py
- 优化项
- 获取流程内置全局变量API返回数据格式优化 
link #888
=> improve: 获取流程内置全局变量API返回数据格式优化 #888

frontend/desktop/src/api/urls.js, frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue, frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/components/layout/ProjectSelector.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/pages/admin/statistics/Appmaker/index.vue, frontend/desktop/src/pages/admin/statistics/Atom/index.vue, frontend/desktop/src/pages/admin/statistics/Instance/index.vue, frontend/desktop/src/pages/admin/statistics/Template/index.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue, frontend/desktop/src/store/modules/project.js, frontend/desktop/src/utils/nodeFilter.js
- 优化项
- 项目无权限跳转权限中心或项目管理页逻辑优化
- 执行方案接口路径修改
- bug fix
- 网关name字段缺失问题修复
- 导出流程弹窗为获取模板分类数据报错
- 节点、连线id前缀规则修改
=> V3.4.x前端功能性问题修复

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- 优化项
- 节点信息配置切换已缓存标准插件时重新渲染renderForm
=> improment: 节点信息配置切换已缓存标准插件时重新渲染renderForm

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabLocalDraft.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEditDialog.vue
- 优化项
- 选择节点、子流程字号调整
- 节点是否跳过开关大小调整
- 模板配置字号调整
- 变量编辑弹窗padding调整到30px
close #1104
=> 模板编辑页面各部分字号样式调整

frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue
- bug fix
- 流程导入时接口报错后，再次上传文件无效
- 优化项
- 提交失败时错误提示，并保留当前数据
close: #1121
=> bugfix: 流程导入时接口报错后，再次上传文件无效

frontend/desktop/src/components/common/TemplateCanvas/index.vue, frontend/desktop/src/components/common/base/BaseTitle.vue, frontend/desktop/src/pages/admin/components/NaviHeader.vue, frontend/desktop/src/pages/admin/manage/SourceManage/index.vue, frontend/desktop/src/pages/admin/manage/SourceSync/index.vue, frontend/desktop/src/pages/admin/statistics/index.vue, frontend/desktop/src/pages/project/index.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
- 优化项
- 画布连线和label层级设定值修改
- 项目列表无权限操作按钮底色不正确问题修复
- 管理员入口后台管理与其他页面title样式保持统一
- bug fix
- 流程模板编辑页面流程名称样式修改
- 新建周期任务弹窗出现错位修复
=> V3.4.X分支合并后样式问题修复

frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- bug fix
- 模板导出弹窗报错修复同步到V3.3.X
close #1155
=> bugfix: 模板导出弹窗报错修复同步到V3.3.X

pipeline/models.py
- bug fix
- 修复周期任务启动后会检测 celery worker 是否存在的问题
=> bugfix: 修复周期任务启动后会检测 celery worker 是否存在的问题

frontend/desktop/src/routers/index.js
- 优化项
- 首页 url  项目 id 后用 / 符号闭合
=> improvement: 首页 url 项目 id 后用 / 符号闭合

pipeline_plugins/variables/static/variables/input.js, static/variables/input.js
- bug fix
- 修复输入框类型变量都要必填的问题（V3.3.X）
close #1157
=> bugfix：修复输入框类型变量都要必填的问题 #1157

pipeline_plugins/cmdb_ip_picker/query.py, pipeline_plugins/cmdb_ip_picker/utils.py, pipeline_plugins/components/utils/__init__.py, pipeline_plugins/components/utils/common.py, pipeline_plugins/components/utils/sites/open/utils.py, pipeline_plugins/tests/utils.py
- 优化项
- 支持多内网IP的主机筛选和展示
- bug fix
- 业务主机为空时不查询agent状态接口，避免接口报错
close #1132
=> Improve and bugfix ip selector

frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/pages/project/index.vue
- 优化项
- 优化项目下拉禁用逻辑
- 项目列表点击项目查看，跳转到该项目首页
- 项目列表有权限显示进入，无权限显示查看
=> improve: 优化项目下拉禁用逻辑

pipeline_plugins/components/static/components/atoms/bk/notify.js, pipeline_plugins/components/static/components/atoms/cc/cc_batch_delete_set.js, pipeline_plugins/components/static/components/atoms/cc/cc_create_set.js, pipeline_plugins/components/static/components/atoms/cc/cc_empty_set_hosts.js, pipeline_plugins/components/static/components/atoms/cc/cc_replace_fault_machine.js, pipeline_plugins/components/static/components/atoms/cc/cc_transfer_host_module.js, pipeline_plugins/components/static/components/atoms/cc/cc_transfer_to_idle.js, pipeline_plugins/components/static/components/atoms/cc/cc_update_host.js, pipeline_plugins/components/static/components/atoms/cc/cc_update_module.js, pipeline_plugins/components/static/components/atoms/cc/cc_update_set.js, pipeline_plugins/components/static/components/atoms/cc/cc_update_set_service_status.js, pipeline_plugins/components/static/components/atoms/job/job_cron_task.js, pipeline_plugins/components/static/components/atoms/job/job_execute_task.js, pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js, pipeline_plugins/components/static/components/atoms/sites/open/job/job_fast_push_file.js, static/components/atoms/bk/notify.js, static/components/atoms/cc/cc_batch_delete_set.js, static/components/atoms/cc/cc_create_set.js, static/components/atoms/cc/cc_empty_set_hosts.js, static/components/atoms/cc/cc_replace_fault_machine.js, static/components/atoms/cc/cc_transfer_host_module.js, static/components/atoms/cc/cc_transfer_to_idle.js, static/components/atoms/cc/cc_update_host.js, static/components/atoms/cc/cc_update_module.js, static/components/atoms/cc/cc_update_set.js, static/components/atoms/cc/cc_update_set_service_status.js, static/components/atoms/job/job_cron_task.js, static/components/atoms/job/job_execute_task.js, static/components/atoms/job/job_fast_execute_script.js, static/components/atoms/sites/open/job/job_fast_push_file.js
- bug fix
- 修复业务下，插件的业务参数勾选后反选，值未还原的问题
close #1175
=> bugfix: 修复业务选项勾选后取消勾选值消失的问题

pipeline/core/constants.py
- bug fix
- 修复 PipelineElement 中缺少 version 属性的问题
=> bugfix: 修复 PipelineElement 中缺少 version 属性的问题

frontend/desktop/package.json, frontend/desktop/src/components/common/RenderForm/FormItem.vue, frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- 新功能
- DataTable Tag新增上传下载按钮，并且用户可以自定义按钮的文本、以及执行函数
- 优化项
- 优化FormItem的显示问题，针对于按钮tag没有label的问题，去除彼时的class
close #1147
=> feature: update datatable tag and little change formitem tag #1147

frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/pages/appmaker/AppEditDialog.vue, frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue, frontend/desktop/src/pages/audit/index.vue, frontend/desktop/src/pages/functor/index.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/routers/index.js
- bug fix
- 新建用户首页404问题修复
- 权限申请页面跳转url需要随资源动态更新
- 流程模板保存、自动编排之前节点校验功能恢复
- 职能化中心页面代码合并后未去业务修复
- 审计中心页面代码合并后未去业务修复
- 周期任务列表页、审计中心列表列宽度调整
- 轻应用编辑弹窗确定按钮未选中模板时去掉锁的状态
- 节点配置项出错再点开未提示错误项修复
=> V3.4.6.X前端验收回归问题修复

frontend/desktop/src/pages/audit/index.vue, frontend/desktop/src/pages/periodic/PeriodicList/index.vue
- bug fix
- 周期任务列表、审计中心列表列宽度调整同步到V3.3.X
=> 周期任务列表、审计中心列表列宽度调整同步到V3.3.X

frontend/desktop/src/components/common/TemplateCanvas/index.vue
=> feature: 连线单独配置midpoint

frontend/desktop/src/components/layout/Navigator.vue, frontend/desktop/src/pages/project/index.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- 优化项
- 导出流程、新建任务等页面中”申请权限“按钮宽度自适应
- 项目列表展示停用项目宽度增加
- 任务列表-创建方式宽度优化
- 小屏幕宽度下顶部导航业务选择框错位
=> improve: V3.4.X 国际化样式优化

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- 优化项
- 优化插件打开验证逻辑
- 新建变量都加上 validation 字段
=> improve: 优化插件验证; 新建变量都加上 validation 字段

frontend/desktop/src/pages/admin/statistics/Appmaker/index.vue, frontend/desktop/src/pages/admin/statistics/Atom/index.vue, frontend/desktop/src/pages/admin/statistics/Instance/index.vue, frontend/desktop/src/pages/admin/statistics/Template/index.vue
=> bugfix:数据统计去业务遗留问题修复

frontend/desktop/src/pages/project/index.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- 优化项
- 导出流程和新建任务无权限卡片样式优化
- 项目新建和编辑弹框表单宽度统一
=> improve: 项目新建和编辑弹框表单宽度统一

frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
=> improve: 国际化任务卡片申请权限文字溢出

frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue
=> improvement:模板导入弹窗按钮文案优化

frontend/desktop/src/api/index.js, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue, frontend/desktop/src/pages/task/NodePreview.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue, frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue, frontend/desktop/src/pages/task/TaskCreate/index.vue, frontend/desktop/src/store/modules/task.js
- 优化项
- 执行方案组件拆分
- bug fix
- 轻应用选择执行方案新建任务时不展示执行方案面板，未选择执行方案时展示不可编辑的执行方案面板
=> bugfix: 轻应用新建任务不展示执行方案，执行方案组件拆分

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
=> bugfix: 子流程执行状态丢失

frontend/desktop/src/pages/appmaker/AppEditDialog.vue
=> bugfix:轻应用编辑确认按钮点击报错

frontend/desktop/src/components/common/RenderForm/FormItem.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/ConditionItem.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/IpSearchInput.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/SelectCondition.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue, frontend/desktop/src/components/common/RenderForm/RenderForm.vue, frontend/desktop/src/components/common/RenderForm/tags/TagButton.vue, frontend/desktop/src/components/common/RenderForm/tags/TagCheckbox.vue, frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue, frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue, frontend/desktop/src/components/common/RenderForm/tags/TagInt.vue, frontend/desktop/src/components/common/RenderForm/tags/TagPassword.vue, frontend/desktop/src/components/common/RenderForm/tags/TagRadio.vue, frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue, frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue, frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
=> improvement: 标准插件表单字号调整为12px

frontend/desktop/package.json, frontend/desktop/src/App.vue, frontend/desktop/src/utils/errorHandler.js
=> improvement:错误提示最多显示一行样式问题优化

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
=> bugfix: 轻应用查看流程跳转错误

gcloud/commons/message/__init__.py, gcloud/commons/message/common.py
- bug fix
- 修复从 CMDB 同步的项目流程执行通知无法发送的问题
=> bugifx: 修复从 CMDB 同步的项目流程执行通知无法发送的问题

frontend/desktop/src/api/index.js, frontend/desktop/src/api/urls.js, frontend/desktop/src/components/common/Individualization/IpLogContent.vue, frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
=> bugfix:job查看日志业务id传递错误修复

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableItem.vue
=> improve: 全局变量列表名称添加 title

frontend/desktop/package.json
- bug fix
- magicbox 组件版本升级select api不兼容问题修复
=> bugfix: magicbox 组件版本升级select api不兼容问题修复

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableItem.vue
=> improve: 系统变量样式排序调整

pipeline/core/flow/activity/__init__.py, pipeline/core/flow/activity/base.py
- bug fix
- 修复 3.4.8 之前的流程无法操作的问题
=> bugfix: 修复 3.4.8 之前的流程无法操作的问题

frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- bug fix
- _tag_init 调用 _set_value 方法时会清空标准插件初始值的问题修复
=> bugfix: _tag_init 调用 _set_value 方法时会清空标准插件初始值的问题修复

frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- bug fix
- 修复公共流程接口错误
close: #1227
=> bugfix: 修复公共流程接口错误

gcloud/commons/template/permissions.py, gcloud/tasktmpl3/permissions.py
- bug fix
- 公共流程执行方案权限依赖查看和编辑权限 
link #1229
=> bugfix: 公共流程执行方案权限依赖查看和编辑权限 #1229

frontend/desktop/src/utils/nodeFilter.js
=> bugfix: 节点、连线id正则匹配规则修改

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue
- bug fix
- 全局变量处于编辑状态时，点击保存流程，报错
=> bugfix: 全局变量处于编辑状态时，点击保存流程，报错

auth_backend/plugins/utils.py, blueapps/utils/cache.py
- bug fix
- 修复权限接口数据的缓存偶现瞬间失效返回None导致前端接口500的问题 
close #1239
=> Bugfix cache expired cause 500

pipeline_plugins/components/collections/sites/open/job.py
- bug fix
- 修复JOB-执行作业官方插件全局参数值包含中文时执行报错的问题 
close #1243
=> bugfix: 修复JOB-执行作业官方插件全局参数值包含中文时执行报错的问题 #1243

pipeline_plugins/components/collections/sites/open/cc.py, pipeline_plugins/components/collections/sites/open/job.py
- bug fix
- 修复JOB-执行作业官方插件全局参数值包含中文时执行报错的问题
- 修复 CMDB-故障机替换插件主机不存在时错误信息未国际化问题
close #1243
close #1245
=> V3.4.x sync bufix of v3.3.x

gcloud/conf/sites/community/ver_settings.py, gcloud/core/api.py, gcloud/core/api_adapter/__init__.py, gcloud/core/api_adapter/sites/open/user_info.py, gcloud/core/urls.py
- 新功能
- 提供人员选择器接口 /core/api/get_user_list/ 
link #1232
=> feature: 提供人员选择器接口 /core/api/get_user_list/ #1232

pipeline_plugins/components/collections/sites/open/nodeman.py
- 新功能
- 无
- 优化项
- 无
- bug fix
- 修改pr提到的问题。
=> Bugfix: 官方插件-Agent安装合入 V3.4.X 问题修复 

gcloud/contrib/analysis/analyse_items/app_maker.py, gcloud/contrib/analysis/analyse_items/task_flow_instance.py, gcloud/contrib/analysis/analyse_items/task_template.py, gcloud/contrib/analysis/decorators.py, gcloud/contrib/analysis/views.py, gcloud/contrib/appmaker/api.py, gcloud/contrib/appmaker/models.py, gcloud/core/constant.py, gcloud/core/utils/common/strings.py, gcloud/taskflow3/models.py, gcloud/tasktmpl3/api.py, gcloud/tasktmpl3/models.py, pipeline/contrib/statistics/signals/handlers.py, pipeline/tests/models/test_template.py
- 优化项
- 修复数据统计后台API问题 
link #1019
=> sprintfix: 修复数据统计后台API问题 #1019

frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
=> improvement: ip选择器字号统一调整

static/components/atoms/sites/open/nodeman/nodeman_create_task.js
- bug fix
- 修复节点管理-安装插件表单 404 的问题
=> bugfix: 修复节点管理-安装插件表单 404 的问题

frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue
- bug fix
- 远程包源编辑模块配置非modules字段后，导致modules字段数据类型变更的问题修复
=> bugfix: 远程包源编辑模块配置非modules字段后，导致modules字段数据类型变更的问题修复

frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue
- bug fix
- 远程包源编辑模块配置非modules字段后，导致modules字段数据类型变更的问题修复
=> [V3.3.X]bugfix: 远程包源编辑模块配置非modules字段后，导致modules字段数据类型变更的问题修复

frontend/desktop/src/components/common/TemplateCanvas/index.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue
- bug fix
- 画布新增节点、删除节点、删除连线、自动编排操作，新建任务按钮状态需要变更
=> bugfix: 画布新增节点、删除节点、删除连线、自动编排操作，新建任务按钮状态需要变更

frontend/desktop/src/components/common/TemplateCanvas/index.vue
- 优化项
- 从任务节点、子流程菜单拖拽节点时，生成节点的有效区域优化
=> improvement: 从任务节点、子流程菜单拖拽节点时，生成节点的有效区域优化

gcloud/taskflow3/models.py
=> improve: API返回字段规范化 #1019

frontend/desktop/src/store/modules/template.js
- bug fix
- 拖拽的开始、结束、网关节点的name字段缺失问题修复
=> bugfix: 拖拽的开始、结束、网关节点的name字段缺失问题修复

frontend/desktop/src/pages/appmaker/AppEditDialog.vue, frontend/desktop/src/pages/appmaker/index.vue
- bug fix
- 创建轻应用提交成功后，弹窗填写内容未清空问题修复
=> bugfix: 创建轻应用提交成功后，弹窗填写内容未清空问题修复

frontend/mobile/src/api/urls.js, weixin/resources.py
- 优化项
- 移动端资源名称需要和PC端区分开，避免解析异常 
close #1284
=> improve:移动端资源名称需要和PC端区分开，避免解析异常 #1284

docs/develop/tag_usage_dev.md, frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
=> improvement:文件上传tag新增上传相关的钩子函数配置项

frontend/mobile/src/api/urls.js, gcloud/apigw/views.py, gcloud/tests/apigw/test_apigw.py, weixin/resources.py
- 优化项
- 移动端资源名称需要和PC端区分开，避免解析异常 
- bug fix
- bugfix: 修复通过APIGW使用公共流程新建的任务，页面打开报错404的问题 
link #1284
link #1287
=> Bugfix sync v3.4.x

auth_backend/migrations/0001_initial.py, auth_backend/migrations/0002_201909061515.py, auth_backend/migrations/__init__.py, auth_backend/resource_snapshots/0001_bk_sops_201906261756.json, auth_backend/resource_snapshots/0002_bk_sops_201909061515.json
- bug fix
- 恢复auth_backend中的migrations文件
=> bugfix: 恢复auth_backend中的migrations文件 #1190

gcloud/tasktmpl3/api.py, pipeline_web/drawing.py, pipeline_web/tests/test_drawing.py
=> improve: 自动排版适应新画布比例 #1292

pipeline_plugins/components/query/sites/open/query.py
- bug fix
- 修复 JOB-执行作业 插件索引数组类型变量格式错误及IP获取不到的问题
close #1303
=> bugfix: 修复 JOB-执行作业 插件索引数组类型变量格式错误及IP获取不到的问题

frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- bug fix
- ip选择器静态筛选分页不正确
- 任务执行修改参数点击ip选择器筛选条件分类面板会收起
close #1309
=> bugfix: ip选择器问题修复

pipeline_plugins/cmdb_ip_picker/utils.py, pipeline_plugins/tests/cmdb_ip_picker/test_utils.py
- bug fix
- 修复 IP 选择器按拓扑和 IP 筛选、排除后的结果不准确的问题 
close #1319
=> bugfix: 修复 IP 选择器按拓扑和 IP 筛选、排除后的结果不准确的问题 #1319

frontend/desktop/src/pages/admin/statistics/Appmaker.vue, frontend/desktop/src/pages/admin/statistics/Atom.vue, frontend/desktop/src/pages/admin/statistics/HorizontalBarChart.vue, frontend/desktop/src/pages/admin/statistics/Instance.vue, frontend/desktop/src/pages/admin/statistics/Template.vue
- 优化项
- 数据统计横向柱状图数据默认从大到小排列
- 表格列宽度调整
- 数据为0时柱状默认高度为1px
- bug fix
- 表格排序条件会出现null的情况修复
=> improvement: 数据统计优化

pipeline_plugins/components/static/components/atoms/job/job_push_local_files.js, static/components/atoms/job/job_push_local_files.js
- bug fix
- 修复分发本地文件插件文件字段可以为空的问题
=> bugfix: 修复分发本地文件插件文件字段可以为空的问题

gcloud/commons/template/admin.py, gcloud/commons/template/api.py, gcloud/commons/template/models.py, gcloud/tasktmpl3/api.py, gcloud/tasktmpl3/models.py, pipeline_web/wrapper.py
- bug fix
- 导入流程时若流程为新建状态则创建者应该为导入人
=> bugfix: 导入流程时若流程为新建状态则创建者应该为导入人

frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue, frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- bug fix
- ip选择器静态筛选分页不正确
- 任务执行修改参数点击ip选择器筛选条件分类面板会收起
close #1309
=> bugfix: ip选择器问题修复同步到V3.3.X

frontend/desktop/src/pages/template/TemplateEdit/index.vue
- bug fix
- 删除正在编辑参数的节点时，节点编辑面板无法收起的问题修复
=> bugfix:删除正在编辑参数的节点时，节点编辑面板无法收起的问题修复

frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- bug fix
- ip选择器简单版change事件value为空问题修复
close #1322
=> bugfix: ip选择器简单版change事件value为空问题修复

pipeline_plugins/variables/collections/sites/open/cc.py
- 优化项
- IP 选择器(简单版)提示即将下线 
link #1322
=> improve: IP 选择器(简单版)提示即将下线 #1322

frontend/desktop/src/components/common/TemplateCanvas/index.vue
- bug fix
- 自动排版后删除开始、结束节点，无法再添加到画布
close #1310
=> bugfix: 自动排版后删除开始、结束节点，无法再添加到画布

blueapps/account/migrations/0002_real_initial.py, gcloud/taskflow3/models.py, gcloud/taskflow3/resources.py, pipeline/engine/api.py, pipeline/engine/signals/__init__.py, pipeline/migrations/0022_pipelineinstance_is_revoked.py, pipeline/migrations/0023_set_is_revoked.py, pipeline/models.py, pipeline/signals/handlers.py, pipeline/tests/models/test_instance.py
- 新功能
- pipeline instance 模型添加 is_revoked 属性 
close #1268
=> feature: pipeline instance 模型添加 is_revoked 属性 #1268

frontend/desktop/src/components/layout/permissionApply.vue
- bug fix
- 新用户没有默认项目时访问应用，点击去申请按钮没有正确跳转
close #1327
=> 新用户没有默认项目时访问应用，点击去申请按钮没有正确跳转

frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- bug fix
- ip选择器简单版change事件value为空问题修复同步到 V3.3.X
close #1322
=> bugfix: (V3.3.X)ip选择器简单版change事件value为空问题修复

frontend/mobile/package.json
- bug fix
- postcss-svgo 依赖的 svgo 版本问题锁定
=> bugfix: postcss-svgo依赖的svgo版本问题锁定

gcloud/apigw/views.py, gcloud/commons/message/__init__.py, gcloud/commons/message/sites/open/send_msg.py, gcloud/conf/__init__.py, gcloud/contrib/analysis/permissions.py, gcloud/contrib/audit/permissions.py, gcloud/contrib/function/permissions.py, gcloud/core/api.py, gcloud/core/api_adapter/sites/open/user_role.py, gcloud/core/api_adapter/utils.py, gcloud/core/utils/sites/open/utils.py, gcloud/taskflow3/api.py, gcloud/taskflow3/models.py, gcloud/tasktmpl3/models.py, gcloud/tests/apigw/test_apigw.py, gcloud/utils/forms.py, packages/bkoauth/jwt_client.py, packages/blueking/component/base.py, packages/blueking/component/client.py, packages/blueking/component/utils.py, pipeline/contrib/external_plugins/models/forms.py, pipeline/contrib/statistics/signals/handlers.py, pipeline/core/data/base.py, pipeline/core/flow/gateway.py, pipeline/tests/core/data/test_base.py, pipeline_plugins/cmdb_ip_picker/query.py, pipeline_plugins/components/utils/common.py, pipeline_plugins/components/utils/sites/open/utils.py
- bug fix
- 修复 python3 环境 byte 类型 json.dumps 报错问题 
link #1190
=> bugfix: 修复 python3 环境 byte 类型 json.dumps 报错问题 #1190

frontend/desktop/src/pages/admin/statistics/Atom.vue, gcloud/taskflow3/models.py, pipeline/contrib/statistics/signals/handlers.py
- bug fix
- 修复运营数据-标准插件执行统计数据不准确的问题 
close #244
=> bugfix: 修复运营数据-标准插件执行统计数据不准确的问题 #244

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
=> bugfix: 任务节点为空点击报错修复

gcloud/apigw/views.py, gcloud/commons/message/__init__.py, gcloud/commons/message/sites/open/send_msg.py, gcloud/conf/__init__.py, gcloud/core/api.py, gcloud/core/api_adapter/utils.py, gcloud/core/utils/sites/open/utils.py, gcloud/taskflow3/api.py, gcloud/taskflow3/models.py, gcloud/tasktmpl3/models.py, gcloud/tests/apigw/test_apigw.py, gcloud/utils/forms.py, packages/bkoauth/jwt_client.py, packages/blueking/component/base.py, packages/blueking/component/client.py, packages/blueking/component/utils.py, pipeline/contrib/external_plugins/models/forms.py, pipeline/contrib/statistics/signals/handlers.py, pipeline/core/data/base.py, pipeline/core/flow/gateway.py, pipeline/tests/core/data/test_base.py, pipeline_plugins/cmdb_ip_picker/query.py, pipeline_plugins/components/utils/common.py, pipeline_plugins/components/utils/sites/open/utils.py
- bug fix
- 修复分支条件失败时保存错误信息异常，未展示具体错误的问题 
close #1344
=> bugfix: 修复分支条件失败时保存错误信息异常，未展示具体错误的问题 #1344

frontend/desktop/src/components/common/TemplateCanvas/HelpInfo/index.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue, frontend/desktop/src/components/common/TemplateCanvas/index.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/store/modules/template.js
- 新功能
- 选择节点的查看参数时，画布上的节点也显示被选中的状态
- 优化项
- 节点参数面板树菜单点击后，画布跟随节点更新
- bug fix
- 执行任务页时点击节点无法打开执行信息面板
- 待[improve: 画布高优先级问题修复](https://github.com/Tencent/bk-sops/pull/1312)合并后再处理
=> feature: 执行任务页面画布优化

docs/develop/tag_usage_dev.md
=> improve: 更新人员选择器 tag 文档使用说明

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue
=> feature: 全局变量增加隐藏系统内置变量功能

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
=> bugfix: 进入未执行的子流程中报错

frontend/desktop/src/pages/home/TaskFeeds.vue, frontend/desktop/src/pages/task/TaskList/index.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue
- 优化项
- 任务记录暂停图标未居中
- 首页项目动态 icon 颜色不对
- bug fix
- 编辑变量不能取消
=> bugfix: 编辑变量不能取消；优化执行任务icon样式

frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue, frontend/desktop/src/components/common/TemplateCanvas/index.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue
=> bugfix: 分支网关错误后无法点开

pipeline_plugins/components/static/components/atoms/cc/cc_batch_delete_set.js, pipeline_plugins/components/static/components/atoms/cc/cc_create_set.js, pipeline_plugins/components/static/components/atoms/cc/cc_empty_set_hosts.js, pipeline_plugins/components/static/components/atoms/cc/cc_transfer_host_module.js, pipeline_plugins/components/static/components/atoms/cc/cc_update_host.js, pipeline_plugins/components/static/components/atoms/cc/cc_update_module.js, pipeline_plugins/components/static/components/atoms/cc/cc_update_set.js, pipeline_plugins/components/static/components/atoms/cc/cc_update_set_service_status.js, pipeline_plugins/components/static/components/atoms/job/job_cron_task.js, pipeline_plugins/components/static/components/atoms/job/job_execute_task.js, pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js, static/components/atoms/cc/cc_batch_delete_set.js, static/components/atoms/cc/cc_create_set.js, static/components/atoms/cc/cc_empty_set_hosts.js, static/components/atoms/cc/cc_transfer_host_module.js, static/components/atoms/cc/cc_update_host.js, static/components/atoms/cc/cc_update_module.js, static/components/atoms/cc/cc_update_set.js, static/components/atoms/cc/cc_update_set_service_status.js, static/components/atoms/job/job_cron_task.js, static/components/atoms/job/job_execute_task.js, static/components/atoms/job/job_fast_execute_script.js
- bug fix
- 修复 2.4 旧数据部分插件表单渲染时值被清空的问题
close #1351
=> bugfix: 修复 2.4 旧数据部分插件表单渲染时值被清空的问题

gcloud/apigw/decorators.py, gcloud/apigw/views.py, gcloud/commons/message/__init__.py, gcloud/commons/message/sites/open/send_msg.py, gcloud/conf/__init__.py, gcloud/contrib/analysis/utils.py, gcloud/core/api_adapter/utils.py, gcloud/core/middlewares.py, gcloud/core/utils/sites/open/utils.py, gcloud/core/views.py, gcloud/taskflow3/api.py, gcloud/taskflow3/models.py, gcloud/tasktmpl3/models.py, gcloud/tasktmpl3/sites/open/import_data_2_to_3.py, gcloud/tests/analysis/tests.py, gcloud/tests/apigw/test_apigw.py, gcloud/utils/forms.py, packages/blueking/component/base.py, packages/blueking/component/client.py, packages/blueking/component/utils.py, pipeline/contrib/external_plugins/models/forms.py, pipeline/contrib/statistics/signals/handlers.py, pipeline/core/data/base.py, pipeline/core/flow/gateway.py, pipeline/tests/core/data/test_base.py, pipeline_plugins/cmdb_ip_picker/query.py, pipeline_plugins/components/utils/common.py, pipeline_plugins/components/utils/sites/open/utils.py
- bug fix
-  修复分支条件失败时保存错误信息异常，未展示具体错误的问题(V3.3.X) 
close #1344
=> bugfix: 修复分支条件失败时保存错误信息异常，未展示具体错误的问题(V3.3.X) #1344

frontend/desktop/src/api/index.js, frontend/desktop/src/pages/template/TemplateList/index.vue
=> improve: 前端导出流程改为 POST 请求

frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/pages/project/index.vue
- 优化项
- 隐藏新建项目入口
- 优化无项目权限提示文案
=> improvement: 隐藏新建项目入口，优化无项目权限提示文案

frontend/desktop/src/api/index.js, frontend/desktop/src/pages/template/TemplateList/index.vue
- 优化项
- V3.3.X 前端导出流程改为 POST 请求
=> improve: V3.3.X 前端导出流程改为 POST 请求

frontend/desktop/src/api/index.js, frontend/desktop/src/api/urls.js, frontend/desktop/src/assets/html/template.html, frontend/desktop/src/components/common/Individualization/MemberSelect.vue, frontend/desktop/src/components/common/RenderForm/FormItem.vue, frontend/desktop/src/components/common/RenderForm/tags/TagMemberSelector.vue, frontend/desktop/src/components/common/RenderForm/tags/TagMember_selector.vue, frontend/desktop/src/store/modules/member.js
=> feature: 添加 人员选择器tag

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 节点配置子流程加载详情时，禁用子流程更新和子流程切换
close #1360
=> bugfix: 节点配置子流程加载详情时，禁用子流程更新和子流程切换

frontend/desktop/src/pages/admin/statistics/Atom.vue, frontend/desktop/src/pages/admin/statistics/HorizontalBarChart.vue
- 新功能
- 数据统计横向柱状图增加排序方式选项
- 数据统计横向柱状图增加查看全部功能
=> feature: 数据统计横向柱状图增加排序方式和查看全部功能

frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue, frontend/desktop/src/pages/audit/index.vue, frontend/desktop/src/pages/home/TaskFeeds.vue, frontend/desktop/src/pages/task/TaskList/index.vue
- 优化项
- 任务记录，撤销的任务状态直接返回，不需要再次查询状态
=> improve: 任务记录，撤销的任务状态直接返回，不需要再次查询状态

gcloud/commons/template/api.py, gcloud/commons/template/utils.py, gcloud/contrib/appmaker/models.py, gcloud/tasktmpl3/api.py, pipeline/management/commands/create_atoms_app.py
- bug fix
- 修复 hash 和 base64 函数处理字符串编码异常问题 
link #1190
=> sprintfix: 修复 hash 和 base64 函数处理字符串编码异常问题 #1190

gcloud/taskflow3/api.py, gcloud/taskflow3/models.py, gcloud/tasktmpl3/resources.py, pipeline/engine/api.py, pipeline/engine/models/core.py, pipeline/parser/utils.py, pipeline_web/parser/parser.py, pipeline_web/parser/schemas.py
- 新功能
- 流程解析 Parser 支持循环结构，网关和结束节点的出入度新规则校验
- 节点详情 API 支持按循环序号查询结果 
link #1365
=> feature: 流程解析 Parser 支持循环结构，网关和结束节点的出入度新规则校验；节点详情 API 支持按循环序号查询结果 #1365

frontend/desktop/src/components/common/TemplateCanvas/HelpInfo/index.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue, frontend/desktop/src/components/common/TemplateCanvas/index.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/store/modules/template.js
- 新功能
- 画布选择的节点支持上下左右键移动
- 优化项
- 分支失败跳过时，选项文字改成 分支名称
- 节点配色调整
- 失败/成功网关状态未渲染
- 节点上的 ckeckbox 样式调整
=> improve: 画布节点优化

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- 新功能
- 节点执行详情处需要展示插件当前版本
- bug fix
- 标准插件描述丢失
=> feature: 执行详情添加当前版本; 修复标准插件描述丢失

gcloud/commons/template/api.py, gcloud/tasktmpl3/api.py
- 优化项
- 导出流程/公共流程模板请求需改为 POST 方法请求
close #1297
=> improvement: 导出流程/公共流程 API 改为 POST 方法

frontend/desktop/src/components/common/TemplateCanvas/index.vue
=> sprintfix: 修复分支合并导致前端的问题

frontend/desktop/src/pages/periodic/PeriodicList/index.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue, frontend/desktop/src/pages/task/TaskList/index.vue
- 新功能
- 公共流程支持创建周期任务
- bug fix
- 新建周期任务隐藏执行计划
=> feature: 公共流程支持创建周期任务，前端改动

frontend/desktop/builds/webpack.dev.config.js, frontend/desktop/src/components/common/TemplateCanvas/HelpInfo/index.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue, frontend/desktop/src/components/common/TemplateCanvas/index.vue, frontend/desktop/src/components/common/TemplateCanvas/options.js, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableItem.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue
- 优化项
- 节点锚点层级优化
- 点击连线优化
- 选中后移动改为 ctrl + 方向键
- V3.4.X合入refactor 冲突解决
- 网管节点取消配置按钮
- mock 代码补充
- bug fix
- 全局变量不能保存
=> improve: 节点连线优化,refactor 冲突解决和问题修复

pipeline_plugins/variables/query.py, pipeline_plugins/variables/static/variables/select.js, pipeline_plugins/variables/urls.py, static/variables/select.js
- 优化项
- 下拉框远程数据源改为后台请求，防止产生跨域问题 
close #1180
=> improve: 下拉框远程数据源改为后台请求，防止产生跨域问题 #1180

auth_backend/__init__.py, auth_backend/plugins/tastypie/resources.py, auth_backend/plugins/utils.py, gcloud/core/project.py
- bug fix
- 修复克隆任务后进入详情页面可能会没有权限操作的问题
close #1369
=> bugfix: 修复克隆任务后进入详情页面可能会没有权限操作的问题

frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
- bug fix
- TagUpload组件错误信息不显示
=> bugfix: TagUpload组件错误信息不显示

packages/blueking/component/apis/cc.py, pipeline_plugins/components/collections/sites/open/cc.py
- 优化项
- [CMDB-故障机替换]插件主机属性更新接口替换
=> improvement: [CMDB-故障机替换]插件主机属性更新接口替换

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 画布任务节点incoming、outgoing字段会出现缺失的问题修复
close #1398
=> bugfix: 画布任务节点incoming、outgoing字段会出现缺失的问题修复

gcloud/taskflow3/models.py
- bug fix
- 修复插件执行失败率统计返回了 0.00 的问题，改为 0
close #1401
=> Improve data analysis components failed percent

frontend/desktop/src/components/common/TemplateCanvas/HelpInfo/index.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue, frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue, frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue, frontend/desktop/src/components/common/TemplateCanvas/index.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue
- 优化项
- 快捷键面板代码优化
- 端点参考线长度优化（避免靠近节点时闪烁）
- 快捷面板距离优化
- 操作节点时（点击，拖动）关闭分支面板
- 开始结束节点替换成 svg,侧边工具栏 icon 大小调整成 28px
- bug fix
- 修复单击选中的节点，复制时位置不对
=> improve: 画布相关样式优化

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- bug fix
- 公共流程新建的任务，在任务执行页面跳转到公共流程模板列表链接错误
=> bugfix: 公共流程新建的任务，在任务执行页面跳转到公共流程模板列表链接错误

frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- bug fix
- 任务创建页面调用自动排版接口参数错误修复
=> bugfix: 任务创建页面调用自动排版接口参数错误修复

frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
=> improvement: 创建任务弹窗只在弹窗显示时请求接口

frontend/desktop/src/pages/project/index.vue
=> improvement: 停用项目隐藏「进入」「编辑」按钮

pipeline_plugins/components/collections/sites/open/nodeman.py, pipeline_plugins/tests/components/collections/sites/open/job_test/test_job_fast_execute_script.py, pipeline_plugins/tests/components/collections/sites/open/nodeman_test/test_nodeman_create_task.py
- bug fix
- 1. 修复节点管理安装插件无法停止的bug和单元测试问题
- 2. 修复快速执行脚本插件单元测试问题
close #1397
=> bugfix: 修复节点管理插件和快速执行脚本插件问题 

frontend/desktop/src/constants/pipelineTreeSchema.js, frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableItem.vue, frontend/desktop/src/store/modules/template.js
- bug fix
- 流程模板全局变量勾选到输出的切换开关显示问题
- outputs校验规则更新
=> bugfix: 流程模板全局变量勾选到输出的切换开关显示问题；outputs校验规则更新

gcloud/taskflow3/models.py
- bug fix
- 修复查询子流程插件参数时获取插件版本报错问题
=> sprintfix: 修复查询子流程插件参数报错问题

gcloud/taskflow3/signals/handlers.py, gcloud/taskflow3/tasks.py
- bug fix
- 修复发送消息时读取业务信息缓存操作产生死锁影响任务执行的问题
=> bugfix: 修复发送消息时读取业务信息缓存操作产生死锁影响任务执行的问题

pipeline_plugins/variables/collections/bk_manage_user_selector.py, pipeline_plugins/variables/static/variables/bk_manage_user_selector.js, static/variables/bk_manage_user_selector.js
- 新功能
- 新增人员选择器类型全局变量，方便快速填写人员信息参数 
close #1232
=> feature: 新增人员选择器类型全局变量，方便快速填写人员信息参数 #1232

frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue, frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/store/modules/template.js
- 优化项
- pipeline_tree数据can_retry、isSkipped字段替换，兼容旧数据; 分支条件tag字段去掉
close #1049
=> improvement: pipeline_tree数据can_retry、isSkipped字段替换，兼容旧数据；分支条件tag字段去掉

frontend/desktop/src/components/common/TemplateCanvas/index.vue
- bug fix
- 修复有横向滚动条时，节点生成参考线位置偏移
=> bugfix: 修复有横向滚动条时，节点生成参考线位置偏移(V3.5.X)

frontend/desktop/src/components/common/TemplateCanvas/index.vue
- bug fix
- 修复有横向滚动条时，节点生成参考线位置偏移
=> bugfix: 修复有横向滚动条时，节点生成参考线位置偏移

gcloud/taskflow3/models.py, gcloud/taskflow3/resources.py, gcloud/tasktmpl3/resources.py, pipeline/validators/base.py, pipeline/validators/gateway.py, pipeline/validators/utils.py, pipeline_web/parser/format.py
- bug fix
- 修复允许环状结构时网关数据校验报错的问题
=> sprintfix: 修复允许环状结构时网关数据校验报错的问题

frontend/desktop/src/pages/template/TemplateList/index.vue, frontend/desktop/src/routers/index.js
- 优化项
- 路由优化，修复新建和克隆跳转到编辑的隐患
- bug fix
- 修复 admin 下公共流程新建跳转到 template 新建
=> bugfix: 前端模版路由配置修复

gcloud/taskflow3/models.py
- bug fix
- 修复查询节点执行详情接口 500 问题 
link #1365
=> sprintfix: 修复查询节点执行详情接口 500 问题 #1365

gcloud/commons/template/models.py, gcloud/tasktmpl3/models.py
- bug fix
- 修复项目流程导出文件能够在公共流程内覆盖的问题
close #1436
=> bugfix: 修复项目流程导出文件能够在公共流程内覆盖的问题

frontend/desktop/src/pages/template/TemplateEdit/index.vue
=> bugfix: 公共流程模板缓存异常修复

gcloud/taskflow3/models.py, pipeline/core/flow/activity/service_activity.py
- bug fix
- 修复查询节点详情和数据接口错误问题 
link #1365
=> bugfix: 修复查询节点详情和数据接口错误问题 #1365

frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue, pipeline_plugins/components/static/components/atoms/job/job_push_local_files.js
- bug fix
- 修复分发本地文件插件上传文件未保存的问题
=> bugfix: 修复分发本地文件插件上传文件未保存的问题

pipeline_plugins/tests/components/collections/sites/open/cc_test/test_cmdb_transfer_fault_host.py, pipeline_plugins/tests/components/collections/sites/open/cc_test/test_cmdb_transfer_host_resource.py, pipeline_plugins/tests/components/collections/sites/open/job_test/test_job_cron_task.py, pipeline_plugins/tests/components/collections/sites/open/job_test/test_job_execute_task.py
=> bugfix: 插件单元测试问题修复

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/routers/index.js
- bug fix
- 公共流程编辑子流程节点，点击子流程跳转链接错误修复
=> bugfix: 公共流程编辑子流程节点，点击子流程跳转链接错误修复

frontend/desktop/src/components/common/modal/PermissionModal.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/mixins/permission.js
=> improvement:无权限弹窗无关联资源实例时，展示资源类型

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 子流程更新参数值保留逻辑修复
- 添加子流程后配置项未清空修复
=> bugfix:子流程更新参数值保留逻辑修复；添加子流程后配置项未清空修复

gcloud/periodictask/signals/handlers.py
- bug fix
- 修复版本升级到V3.4.13后之前的周期任务无法执行的问题 
close #1460
=> bugfix: 修复版本升级到V3.4.13后之前的周期任务无法执行的问题 #1460

frontend/desktop/builds/webpack.base.js, frontend/desktop/builds/webpack.prod.config.js
=> improvement：前端打包静态资源添加版本号V3.3.X

frontend/desktop/builds/webpack.base.js, frontend/desktop/builds/webpack.prod.config.js
=> improvement：前端打包静态资源添加版本号

frontend/desktop/builds/webpack.base.js, frontend/desktop/builds/webpack.prod.config.js
=> improvement：前端打包静态资源添加版本号V3.5.X

gcloud/core/templates/core/base_vue.html
=> improvement: 入口 JS 添加当前版本号

gcloud/core/templates/core/base_vue.html
=> improvement: 入口 CSS 添加当前版本号

gcloud/core/templates/core/base_vue.html
- 优化项
- v3.3.x entrance js version add
=> Improvement v3.3.x entrance js version add

frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue, frontend/desktop/src/components/common/modal/PermissionModal.vue, frontend/desktop/src/components/layout/permissionApply.vue, frontend/desktop/src/mixins/permission.js, frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue, frontend/desktop/src/pages/template/TemplateEdit/index.vue, frontend/desktop/src/routers/index.js, pipeline_plugins/components/static/components/atoms/job/job_push_local_files.js
- bug fix
- 同步V3.4.X修复的问题到V3.5.X
=> 同步V3.4.X修复的问题到V3.5.X

frontend/desktop/src/pages/admin/statistics/Atom.vue, frontend/desktop/src/pages/admin/statistics/Instance.vue
- bug fix
- 数据统计任务、标准插件表格倒序排列参数不正确修复
=> bugfix:数据统计任务、标准插件表格倒序排列参数不正确修复

frontend/desktop/package.json, frontend/desktop/src/constants/pipelineTreeSchema.js, frontend/desktop/src/pages/task/ParameterInfo.vue, frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue, frontend/desktop/src/store/modules/template.js, frontend/desktop/src/utils/validatePipeline.js
- 优化项
- pipeline_tree数据校验错误提示信息优化
- activities、start_event、end_event、gateways与flows互相校验
- 节点预览接口报错后错误信息优化
=> pipeline_tree数据校验错误提示信息优化，新增流程数据字段间相互校验

frontend/desktop/src/pages/periodic/PeriodicList/ModifyPeriodicDialog.vue
=> bugfix: 编辑周期任务表达式值未回显（V3.4.X）

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
=> bugfix: 修复切换变量配置面板关闭(V3.4.X)

frontend/desktop/src/pages/admin/statistics/HorizontalBarChart.vue
=> improvement: 数据统计柱状图非0数据设置最小宽度2px

frontend/desktop/builds/webpack.base.js, frontend/desktop/src/components/common/CodeEditor.vue
- bug fix
- monaco-editor worker 文件去掉版本号
=> sprintfix: monaco-editor worker 文件去掉版本号

frontend/desktop/builds/webpack.base.js, frontend/desktop/src/components/common/CodeEditor.vue
- bug fix
- monaco-editor worker 文件去掉
=> sprintfix: monaco-editor worker 文件去掉

frontend/desktop/src/pages/admin/statistics/Appmaker.vue, frontend/desktop/src/pages/admin/statistics/Atom.vue, frontend/desktop/src/pages/admin/statistics/HorizontalBarChart.vue, frontend/desktop/src/pages/admin/statistics/Instance.vue, frontend/desktop/src/pages/admin/statistics/Template.vue
=> 数据统计V3.4.X同步到V3.5.X
