TencentBlueKing/bk-sops

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- frontend/desktop/src/utils/validatePipeline.js
> sprintfix: 任务执行循环次数选项固定

- frontend/desktop/src/pages/periodic/PeriodicList/ModifyPeriodicDialog.vue
> bugfix: 编辑周期任务值未回显（V3.5.X）

- pipeline_plugins/components/collections/sites/open/job.py
- pipeline_plugins/components/utils/common.py
- bug fix
- 修复JOB-执行作业 插件全局参数引用整数类型变量解析失败的问题 
close #1500
> bugfix: 修复JOB-执行作业 插件全局参数引用整数类型变量解析失败的问题（V3.4.X）

- pipeline_plugins/components/collections/sites/open/job.py
- pipeline_plugins/components/utils/common.py
- bug fix
- 修复JOB-执行作业 插件全局参数引用整数类型变量解析失败的问题 
close #1500
> bugfix: 修复JOB-执行作业 插件全局参数引用整数类型变量解析失败的问题（V3.5.X）

- gcloud/taskflow3/models.py
- gcloud/tasktmpl3/models.py
- bug fix
- 修复运营数据-任务统计中排序后导致页数丢失的问题 
close #1483
> bugfix: 修复运营数据-任务统计中排序后导致页数丢失的问题（V3.4.X）

- gcloud/taskflow3/models.py
- gcloud/tasktmpl3/models.py
- bug fix
- 修复运营数据-任务统计中排序后导致页数丢失的问题
close #1485
> bugfix: 修复运营数据-任务统计中排序后导致页数丢失的问题（V3.5.X）

- frontend/desktop/src/pages/admin/statistics/Appmaker.vue
- frontend/desktop/src/pages/admin/statistics/Atom.vue
- frontend/desktop/src/pages/admin/statistics/Instance.vue
- frontend/desktop/src/pages/admin/statistics/Template.vue
> improvement: 数据统计表格列宽度优化

- pipeline_plugins/components/collections/sites/open/cc.py
- bug fix
- 修复 CMDB-创建集群 插件集群容量参数未使用整数的问题
> bugfix: 修复 CMDB-创建集群 插件集群容量参数未使用整数的问题

- gcloud/utils/handlers.py
- pipeline_plugins/components/collections/sites/open/job.py
- pipeline_plugins/components/utils/common.py
- pipeline_plugins/tests/components/collections/sites/open/job_test/test_job_fast_execute_script.py
> minor: 单元测试问题修复

- pipeline_plugins/components/collections/sites/open/cc.py
- bug fix
- 修复 CMDB-创建集群 插件集群容量参数未使用整数的问题
> 修复 CMDB-创建集群 插件集群容量参数未使用整数的问题（V3.5.X）

- bkiam/client.py
- blueapps/conf/default_settings.py
- bug fix
- 修复 client 发起请求时抛出异常未处理的问题
- 删除 CSRF 中间件的注释
> 修复 client 发起请求时抛出异常未处理的问题

- bkiam/client.py
- bug fix
- 修复 client 发起请求时抛出异常未处理的问题
> bugfix: 修复 client 发起请求时抛出异常未处理的问题

- frontend/desktop/src/store/modules/template.js
> improvemnet: 结束节点新增时outgoing置为空字符串

- frontend/desktop/builds/webpack.base.js
- frontend/desktop/builds/webpack.prod.config.js
- 优化项
- 文件版本改为query参数的方式，打包脚本不变
> improvement:文件版本改为query参数的方式

- config/default.py
- gcloud/core/middlewares.py
> minor: 删除根据无用业务鉴权中间件

- frontend/desktop/src/api/index.js
> sprintFix: 加载插件代码请求参数格式修改

- frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
- 新功能
- xxx
- 优化项
- xxx
- bug fix
- 修复无参数标准插件重试时看不到确认按钮的问题 #1455
> bugfix: 修复无参数标准插件重试时看不到确认按钮的问题 #1455.

- frontend/desktop/builds/webpack.base.js
- frontend/desktop/builds/webpack.prod.config.js
> improvement:文件版本改为query参数的方式(3.3.x)

- frontend/desktop/builds/webpack.base.js
- frontend/desktop/builds/webpack.prod.config.js
> improvement:文件版本改为query参数的方式(3.5.X)

- gcloud/core/templates/core/base_vue.html
- 优化项
- 静态文件版本通过 query string 来进行传递
> minor: 静态文件版本通过 query string 来进行传递

- frontend/mobile/build/config.js
- frontend/mobile/build/webpack.base.conf.babel.js
- frontend/mobile/build/webpack.prod.conf.babel.js
- 优化项
- 移动端前端打包文件名称添加版本号query参数
> improvement: 移动端前端打包文件名称添加版本号query参数

- gcloud/contrib/collection/resources.py
- 新功能
- 无
- 优化项
- 无
- bug fix
- 修复批量增加收藏接口
close #1498
> bugfix: 批量增加收藏接口报错修复

- frontend/desktop/src/utils/validatePipeline.js
> bugfix:流程节点校验规则回滚

- blueapps/account/handlers/response.py
- blueapps/account/sites/open/conf.py
- config/default.py
> feature: 后台支持前端进行弹窗续期登陆（3.4.X）

- blueapps/account/handlers/response.py
- blueapps/account/sites/open/conf.py
- config/default.py
> feature: 后台支持前端进行弹窗续期登陆

- frontend/desktop/src/pages/template/TemplateEdit/index.vue
> improvement:自动编排后画布复位

- frontend/desktop/src/utils/validatePipeline.js
> improvement: 画布节点字段错误信息增加节点名称

- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- 优化项
- 勾选变量默认排在列表最后 colse: #1533
> improve: 勾选变量默认排在列表最后（V3.4.X）

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- 优化项
- 勾选变量默认排在列表最后 colse: #1533
- bug fix
- 复用变量报错，删除旧代码
> improve: 勾选变量默认排在列表最后（V3.5.X_admin）

- pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
- static/components/atoms/job/job_execute_task.js
- 新功能
- 任务模板增加刷新按钮
- 优化项
- 点击刷新任务模板保存源数据
- bug fix
- 无
close #1530
> feature: job 快速执行任务插件增加任务模板刷新按钮，并保存源数据

- pipeline_plugins/components/utils/common.py
- pipeline_plugins/components/utils/sites/open/utils.py
- 优化项
- IP正则匹配表达式优化
- bug fix
- 获取IP信息的字符编码修复
> improve: 获取IP信息的字符编码修复，IP正则匹配表达式优化

- blueapps/account/components/bk_token/backends.py
- config/default.py
- gcloud/core/migrations/0013_admin_init.py
- 优化项
- 管理员身份判定改造; 添加初始化管理员身份配置
> minor: 管理员身份判定改造; 添加初始化管理员身份配置（V3.4.X）

- gcloud/taskflow3/api.py
- gcloud/taskflow3/models.py
> improvement: 丰富内部节点回调接口跟踪日志（V3.3.X）

- gcloud/taskflow3/api.py
- gcloud/taskflow3/models.py
> improvement: 丰富内部节点回调接口跟踪日志（V3.4.X）

- gcloud/taskflow3/api.py
- gcloud/taskflow3/models.py
> improvement: 丰富内部节点回调接口跟踪日志（V3.5.X）

- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/PipelineTreeEditDialog.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TemplateSetting.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
> feature: 模板编辑页面支持画布数据查看和编辑

- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
> bugfix: 任务节点树遍历支持流程打回

- frontend/desktop/package.json
- frontend/desktop/src/constants/pipelineTreeSchema.js
- frontend/desktop/src/pages/atomdev/atomConfigSchema.js
- frontend/desktop/src/pages/atomdev/configPanel/ConfigPanel.vue
- frontend/desktop/src/pages/task/ParameterInfo.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- frontend/desktop/src/store/modules/template.js
- frontend/desktop/src/utils/validatePipeline.js
同步V3.4.X前端改动到feature_V3.5.X_admin
> 同步V3.4.X前端改动到feature_V3.5.X_admin

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
> bugfix: 修复切换变量配置面板关闭 (同步到V3.5.X_admin)

- frontend/desktop/src/components/common/TemplateCanvas/index.vue
- frontend/desktop/src/utils/validatePipeline.js
> imporvement: 分支网关支持回连

- gcloud/apigw/decorators.py
- gcloud/apigw/views.py
- gcloud/commons/template/models.py
- gcloud/commons/template/utils.py
- gcloud/err_code.py
- gcloud/taskflow3/models.py
- gcloud/tasktmpl3/models.py
> minor: API 返回数据添加 code 字段

- gcloud/taskflow3/models.py
- bug fix
- 修复当流程中包含子流程时获取节点详情可能出错的问题
> bugfix: 修复当流程中包含子流程时获取节点详情可能出错的问题（V3.5.X）

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskInfo.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/PipelineTreeEditDialog.vue
- frontend/desktop/src/utils/validatePipeline.js
- bug fix
- 管理端代码块样式统一
- 管理端模板数据编辑弹窗保存
- 非管理端试图查看任务节点详情显示插件版本
> bugfix:管理端回归问题修复

- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- bug fix
- 任务节点跳过操作isSkipped、skippable新旧数据兼容修复
> bugfix:任务节点跳过操作isSkipped、skippable新旧数据兼容修复

- gcloud/taskflow3/models.py
- bug fix
- 修复当流程中包含子流程时获取节点详情可能出错的问题
> bugfix: 修复当流程中包含子流程时获取节点详情可能出错的问题（V3.3.X）

- gcloud/taskflow3/models.py
- bug fix
- 修复当流程中包含子流程时获取节点详情可能出错的问题
> bugfix: 修复当流程中包含子流程时获取节点详情可能出错的问题（V3.4.X)

- pipeline/templates/create_atoms_app/plugins.tmpl
- 新功能
- xxx
- 优化项
- xxx
- bug fix
- Fixed #1395
> minor: 更新插件模板里import settings.

- blueapps/conf/default_settings.py
- bug fix
- 修复使用命令行  报错问题 
close #1579
> bugfix: 修复使用命令行  报错问题 #1579

- gcloud/contrib/admin/views/templates.py
- bug fix
- 修复恢复模板时没有注册回权限中心的问题
> bugfix: 修复恢复模板时没有注册回权限中心的问题

- gcloud/periodictask/resources.py
- pipeline/parser/pipeline_parser.py
- bug fix
- 修复包含子流程的公共流程无法创建周期任务的问题
- 修复子流程中有环时无法执行任务的问题
> V3.5.x bugfix common process with subproc can not create periodic task

- pipeline_web/wrapper.py
- bug fix
- 修复导入包含子流程的模板时编码错误的问题
> bugfix: 修复导入包含子流程的模板时编码错误的问题

- frontend/desktop/src/components/common/RenderForm/tags/TagButton.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCheckbox.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagRadio.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
- frontend/desktop/src/pages/admin/manage/AdminSearch/index.vue
- frontend/desktop/src/pages/atomdev/PageTitle.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskInfo.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/PipelineTreeEditDialog.vue
> improvement:前端新增文件、文本国际化翻译配置

- gcloud/apigw/decorators.py
- gcloud/apigw/whitelist.py
- gcloud/tests/apigw/test_whitelist.py
> feature: api app 白名单支持从环境变量中读取（V3.5.X）

- gcloud/apigw/decorators.py
- gcloud/apigw/whitelist.py
- gcloud/tests/apigw/test_whitelist.py
> feature: api app 白名单支持从环境变量中读取（V3.4.X）

- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 执行作业输出参数勾选后，切换作业模板删除对应全局变量修复
> bugfix: 执行作业输出参数勾选后，切换作业模板删除对应全局变量修复

- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- frontend/desktop/src/components/common/TemplateCanvas/index.vue
- frontend/desktop/src/components/common/TemplateCanvas/options.js
- frontend/desktop/src/pages/admin/manage/AdminSearch/index.vue
- frontend/desktop/src/pages/task/PeriodicList/BootRecordDialog.vue
- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TemplateSetting.vue
- frontend/desktop/src/store/modules/template.js
- frontend/desktop/src/utils/validatePipeline.js
- 优化项
- 周期任务启动记录无执行异常显示'--'
- 文案修改:业务改为项目
- bug fix
- 任务节点信息循环次数选择
- 任务节点执行详情增加插件版本
- 流程模板编辑全局变量勾选更新小红点显示不正确问题修复
- 分支网关支持回连
- 节点树按照广度优先规则排序
- 节点删除勾选的变量未删除修复
- 子流程输出参数不显示修复
- 执行作业输出参数随作业模板更新修复
> V3.5.X前端体验问题修复

- frontend/desktop/src/components/common/TemplateCanvas/HelpInfo/index.vue
- frontend/desktop/src/pages/functor/index.vue
- frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
- 新功能
- 画布支持滚轮缩放
- 优化项
- “业务” 改成 “项目”
> feature: 画布支持滚轮缩放

- frontend/desktop/.babelrc
- frontend/desktop/package.json
- frontend/desktop/src/assets/js/node-cron-valid/convert-expression/asterisk-to-range-conversion.js
- frontend/desktop/src/assets/js/node-cron-valid/convert-expression/index.js
- frontend/desktop/src/assets/js/node-cron-valid/convert-expression/month-names-conversion.js
- frontend/desktop/src/assets/js/node-cron-valid/convert-expression/range-conversion.js
- frontend/desktop/src/assets/js/node-cron-valid/convert-expression/step-values-conversion.js
- frontend/desktop/src/assets/js/node-cron-valid/convert-expression/week-day-names-conversion.js
- frontend/desktop/src/assets/js/node-cron-valid/node-cron-vaild.js
- frontend/desktop/src/assets/js/node-cron-valid/pattern-validation.js
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- bug fix
- webpack生产环境打包文件分片异常修复
> bugfix: webpack生产环境打包文件分片异常修复

- frontend/desktop/src/api/index.js
- frontend/desktop/src/api/interceptors.js
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
> feature: 任务执行页面新增接口请求取消机制

- gcloud/commons/template/models.py
- gcloud/tasktmpl3/resources.py
- 优化项
- improve: 流程模板被轻应用直接引用时禁止删除 
close #1607
> improve: 流程模板被轻应用直接引用时禁止删除 #1607

- pipeline_web/drawing_new/constants.py
- pipeline_web/drawing_new/position.py
- pipeline_web/tests/drawing_new/test_drawing.py
- 优化项
- 流程画布自动排版增大子流程间距，节点的坐标改为整数 
close #1605
> improve: 流程画布自动排版增大子流程间距，节点的坐标改为整数 #1605

- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- bug fix
- 执行作业输出参数勾选后，编辑表格勾选取消问题修复
> bugfix: 执行作业输出参数勾选后，编辑表格勾选取消问题修复(3.5.X)

- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- bug fix
- 执行作业输出参数勾选后，编辑表格勾选取消问题修复
> bugfix: 执行作业输出参数勾选后，编辑表格勾选取消问题修复

- gcloud/contrib/admin/views/taskflow.py
- bug fix
- 修复管理端查看节点详情无法查看网关和事件详情的问题
> bugfix: 修复管理端查看节点详情无法查看网关和事件详情的问题

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
> bugfix: 网关节点失败后详情接口请求参数修改

- frontend/desktop/src/api/urls.js
> bugfix: 常用业务接口地址修复(V3.5.X)

- pipeline_web/parser/schemas.py
- pipeline_web/parser/validator.py
- bug fix
- 修复系统内置全局变量勾选为输出时保存流程接口报错的问题 
close #1625
> bugfix: 修复系统内置全局变量勾选为输出时保存流程接口报错的问题 #1625

- frontend/desktop/src/api/index.js
- frontend/desktop/src/api/urls.js
- frontend/desktop/src/pages/atomdev/PageTitle.vue
- frontend/desktop/src/pages/atomdev/atomSetting/AtomSetting.vue
- frontend/desktop/src/pages/atomdev/configPanel/ConfigPanel.vue
- frontend/desktop/src/pages/atomdev/index.vue
- 优化项
- 页面标题增加 beta 标识
- 表单配置侧滑栏增加确认、取消按钮
- 插件事件配置选择由 tag_code 改名 name
- bug fix
- api 接口调用拉取后台代码修复
> improvement：标准插件开发页面优化

- frontend/desktop/src/pages/template/TemplateEdit/index.vue
> feature:模板编辑页面刷新或关闭增加二次确认提示

- frontend/desktop/src/pages/template/TemplateEdit/index.vue
> feature:模板编辑页面刷新或关闭增加二次确认提示(V3.4.X)

- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- 优化项
- 标准插件表单icon居中
- 任务执行操作按钮居中
> improvement: 表单icon样式优化(V3.4.X)

- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- 优化项
- 标准插件表单icon居中
- 任务执行操作按钮居中
> improvement: 表单icon样式优化

- frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
> improvement:恢复模板操作前端不做权限校验

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- frontend/desktop/src/pages/task/TaskExecute/ModifyTime.vue
- frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- frontend/desktop/src/pages/task/TaskExecute/ViewParams.vue
- frontend/desktop/src/pages/task/TaskParamEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- bug fix
- 勾选变量报错(子流程输出参数未显示)
- 执行版本显示 undefined
- 插件值 form 中非必填项为空时，值为 undefined，导致无法保存
> bugfix: 插件版本相关问题修复

- pipeline_plugins/cmdb_ip_picker/query.py
- pipeline_plugins/cmdb_ip_picker/utils.py
- pipeline_plugins/components/utils/sites/open/utils.py
- bug fix
- 修复CDMB中主机云区域为空时，IP选择器接口报500的问题 
close #1627
> bugfix: 修复CDMB中主机云区域为空时，IP选择器接口报500的问题 #1627

- frontend/desktop/builds/webpack.base.js
- frontend/desktop/src/pages/atomdev/configPanel/FormConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/PipelineTreeEditDialog.vue
- 优化项
- 模板编辑pipeline_tree语法错误提示优化
> improvement:模板编辑pipeline_tree语法错误提示优化

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCascader.vue
- frontend/desktop/src/main.js
- frontend/desktop/src/utils/atomFilter.js
> feature:新增cascader Tag(V3.5.X)

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCascader.vue
- frontend/desktop/src/main.js
- frontend/desktop/src/utils/atomFilter.js
> feature:新增cascader Tag(V3.4.X)

- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- bug fix
- 任务执行子流程切换后主流程状态未更新修复
> bugfix: 任务执行子流程切换后主流程状态未更新修复

- pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
- static/components/atoms/job/job_execute_task.js
- bug fix
- 修复 JOB 刷新变量后未回填的问题
> bugfix: 修复 JOB 刷新变量后未回填的问题

- frontend/desktop/src/api/interceptors.js
- bug fix
- 应用在paas平台上打开，弹窗登录不显示修复
> bugfix:应用在paas平台上打开，弹窗登录不显示修复（V3.4.X）

- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
- frontend/desktop/src/components/common/advanceSearchForm/index.vue
- frontend/desktop/src/pages/home/MyDynamic.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableItem.vue
- 优化项
- 首页我的动态添加跳转
- 鼠标移出节点矩形范围时，不显示删除按钮
- safari高级搜索显示错位
- bug fix
- 删除全局变量报错 & index = -1
> bugfix: N33 验收遗留问题收尾（V3.5.X）

- frontend/desktop/src/api/interceptors.js
- bug fix
- 应用在paas平台上打开，弹窗登录不显示修复
> bugfix:应用在paas平台上打开，弹窗登录不显示修复

- gcloud/contrib/collection/resources.py
- bug fix
- 修复用户收藏项权限查询时缓存 key 不正确的问题
> bugfix: 修复用户收藏项权限查询时缓存 key 不正确的问题

- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
> improvement: 模板编辑勾选的变量不限制key长度

- frontend/desktop/src/utils/tools.js
> improve: 节点耗时为0时，前端展示了 `--`

- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
> improvement: 模板编辑勾选的变量不限制key长度(V3.5.X)

- frontend/desktop/src/config/setting.js
> feature:插件上下文增加获取项目id方法(V3.4.X)

- frontend/desktop/src/config/setting.js
> feature:插件上下文增加获取项目id方法(V3.5.X)

- frontend/desktop/src/components/common/TemplateCanvas/HelpInfo/index.vue
- frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableItem.vue
- frontend/desktop/src/pages/template/TemplateList/index.vue
- 新功能
- 左侧工具栏“标准插件节点”点击后展开，再次点击收起
- 优化项
- 公共流程右侧操作栏体验问题
- 修复退出模版编辑控制台报错
- 关闭查看参数面板未清除节点选中状态
- 执行方案报错提示错误时，内容挤出页面
- bug fix
- 删除变量报错 & index = 1
> improve: V3.5.X 修复同步到 V3.4.X (V3.4.X)

- frontend/desktop/src/components/common/TemplateCanvas/index.vue
> improvement:节点框选复制后粘贴位置优化

- pipeline_plugins/cmdb_ip_picker/query.py
- pipeline_plugins/cmdb_ip_picker/utils.py
- pipeline_plugins/components/utils/sites/open/utils.py
- bug fix
- 修复CDMB中主机云区域为空时，IP选择器接口报500的问题
> V3.4.x bugfix ip selector cloud empty 500

- frontend/desktop/src/assets/js/node-cron-valid/convert-expression/index.js
- frontend/desktop/src/components/common/base/BaseCard.vue
- frontend/desktop/src/pages/home/MyCollection.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- 优化项
- 导出流程卡片优化，替换成通用组件
- 首页控制台报错
- 【样式】优化创建任务任务名称间距
- bug fix
- 修复周期表达式手动输入验证问题
> improve: 首页、导出流程优化；周期表达式 bug 修复

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- bug fix
- 任务节点失败后执行记录表头文案未显示问题修复
> bugfix: 任务节点失败后执行记录表头文案未显示问题修复

- frontend/desktop/package.json
- frontend/desktop/src/pages/functor/FunctionList.vue
- frontend/desktop/src/pages/home/CommonlyUsed.vue
- frontend/desktop/src/pages/home/MyCollection.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- 优化项
- magicbox 升级到 2.1.8, 
- select 组件升级引入问题修复
- 首页 title 间距调整
> improve: magicbox 升级到 2.1.8; improve: 首页 title 间距调整

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/Individualization/MemberSelect.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCascader.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCheckbox.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagDatetime.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagInt.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagMemberSelector.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagPassword.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagRadio.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
- 优化项
- 部分Tag组件支持disabled配置(text、button、tree、datatable未添加)
> improvement: 部分Tag组件支持disabled配置(V3.4.X)

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/Individualization/MemberSelect.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCascader.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCheckbox.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagDatetime.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagInt.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagMemberSelector.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagPassword.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagRadio.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
- 优化项
- 部分Tag组件支持disabled配置(text、button、tree、datatable未添加)
> improvement: 部分Tag组件支持disabled配置(V3.5.X)

- frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
- frontend/desktop/src/pages/admin/statistics/Appmaker.vue
- frontend/desktop/src/pages/admin/statistics/Atom.vue
- frontend/desktop/src/pages/admin/statistics/Instance.vue
- frontend/desktop/src/pages/admin/statistics/Template.vue
- frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
- frontend/desktop/src/pages/audit/AuditList.vue
- frontend/desktop/src/pages/functor/FunctionList.vue
- frontend/desktop/src/pages/project/index.vue
- frontend/desktop/src/pages/task/PeriodicList/index.vue
- frontend/desktop/src/pages/task/TaskList/index.vue
- frontend/desktop/src/pages/template/TemplateList/index.vue
- frontend/desktop/src/pages/template/common/CommonTemplateList.vue
- 新功能
- 所有 table 列表添加 limit 切换功能
> feature: 所有 table 列表添加 limit 切换功能

- auth_backend/plugins/utils.py
- gcloud/webservice3/resources.py
- 优化项
- 首页常用业务逻辑改进：用户第一次访问，初始化2个常用项目
> feature: 用户第一次访问，初始化有权限的项目

- frontend/desktop/src/api/index.js
- frontend/desktop/src/pages/project/index.vue
> bugfix: 项目列表点击进入，未切换项目上下文

- bkiam/client.py
- bkiam/conf.py
- config/default.py
- gcloud/core/context_processors.py
- gcloud/core/templates/core/base_vue.html
- 新功能
- base_view 渲染时添加底层原子平台的链接信息
> base_view 渲染时添加底层原子平台的链接信息（V3.4.X）

- auth_backend/README.md
- auth_backend/docs/settings/basic_settings.md
- bkiam/client.py
- bkiam/conf.py
- config/default.py
- gcloud/core/context_processors.py
- gcloud/core/templates/core/base_vue.html
- 新功能
- base_view 渲染时添加底层原子平台的链接信息
> feature: base_view 渲染时添加底层原子平台的链接信息（V3.5.X）

- pipeline_plugins/components/static/components/atoms/job/job_push_local_files.js
- static/components/atoms/job/job_push_local_files.js
- bug fix
- 修复公共流程编辑上下文中上传本地文件逻辑不正确的问题
> bugfix: 修复公共流程编辑上下文中上传本地文件逻辑不正确的问题

- gcloud/webservice3/resources.py
- 新功能
- 插件详情接口添加 output_form 字段 #1678
> feature: 插件详情接口添加 output_form 字段

- frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
> bugfix: TagInput默认被禁用修复

- requirements.txt
- support-files/supervisord.conf
- support-files/uwsgi.ini
- 新功能
- 添加 supervisor, uwsgi 自定义配置模板
> feature: 添加 supervisor, uwsgi 自定义配置模板

- frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
- frontend/desktop/src/utils/atomFilter.js
> improvment: ip选择器增加是否带云区域配置选项（V3.3.X）

- frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
- frontend/desktop/src/utils/atomFilter.js
> improvment: ip选择器增加是否带云区域配置选项（V3.5.X）

- pipeline_plugins/variables/collections/sites/open/cc.py
- pipeline_plugins/variables/static/variables/sites/open/var_cmdb_ip_selector.js
- static/variables/sites/open/var_cmdb_ip_selector.js
> feature: IP 选择器支持配置值是否带云区域 ID

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/Individualization/IpLogContent.vue
- frontend/desktop/src/components/common/Individualization/LogDisplay.vue
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagLogDisplay.vue
- frontend/desktop/src/config/setting.js
- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- frontend/desktop/src/store/modules/atomForm.js
- frontend/desktop/src/utils/atomFilter.js
- frontend/desktop/src/utils/formSchema.js
- 新功能
- 添加输出表单渲染规则
- 新加日志显示 tag
> feature: 前端添加输出表单渲染规则

- frontend/desktop/src/mixins/permission.js
> bugfix:项目操作无权限时，申请资源为空修复（V3.5.X）

- frontend/desktop/src/mixins/permission.js
> bugfix:项目操作无权限时，申请资源为空修复（V3.4.X）

- frontend/desktop/src/pages/admin/manage/AdminSearch/index.vue
> improvement: 管理员搜索输入框增加自动跳转结果页的逻辑

- pipeline_plugins/components/collections/sites/open/cc.py
- bug fix
- 修复CMDB-创建集群中集群信息参数表格单项数据为空会被上一行覆盖的问题 
close #1712
> bugfix: 修复CMDB-创建集群中集群信息参数表格单项数据为空会被上一行覆盖的问题（V3.5.X）

- pipeline_plugins/components/collections/sites/open/cc.py
- 优化项
- 优化CMDB-创建集群中调用CMDB接口逻辑，减少接口调用
- bug fix
- 修复CMDB-创建集群中集群信息参数表格单项数据为空会被上一行覆盖的问题 
link #1712
> bugfix: 修复CMDB-创建集群中集群信息参数表格单项数据为空会被上一行覆盖的问题 （V3.3.X）

- pipeline_plugins/components/collections/sites/open/cc.py
- bug fix
- 修复CMDB-创建集群中集群信息参数表格单项数据为空会被上一行覆盖的问题 
link #1712
> bugfix: 修复CMDB-创建集群中集群信息参数表格单项数据为空会被上一行覆盖的问题（V3.4.X）

- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- bug fix
- 修复节点引导 tips，浏览器返回时未消失
> bugfix: 修复节点引导 tips，浏览器返回时未消失

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 修复 magicbox 升级引入问题，配置面板插件切换 select 值未显示
> bugfix: 修复 magicbox 升级引入问题，配置面板插件切换 select 值未显示

- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
- frontend/desktop/src/pages/template/TemplateList/index.vue
- 优化项
- 执行中状态图标错位
- 项目流程高级搜索样式和其他页面统一
> improve: 节点状态、项目流程高级搜索样式优化（V3.4.X）

- frontend/desktop/src/components/common/base/BaseTitle.vue
- frontend/desktop/src/pages/home/MyDynamic.vue
- frontend/desktop/src/routers/index.js
- 优化项
- 首页我的动态间距优化
- 修复 baseTitle 路由引起报错
> improve: 修复 baseTitle 路由引起报错，我的动态样式间距优化

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- frontend/desktop/src/store/modules/template.js
- bug fix
- 兼容脏数据 can_retry、isSkipped 字段不存在问题
> bugfix: 兼容脏数据 can_retry、isSkipped 字段不存在问题(V3.5.X)

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- frontend/desktop/src/store/modules/template.js
- bug fix
- 兼容脏数据 can_retry、isSkipped 字段不存在问题
> bugfix: 兼容脏数据 can_retry、isSkipped 字段不存在问题(V3.4.X)

- pipeline_plugins/components/collections/sites/open/cc.py
- 新功能
- xxx
- 优化项
- xxx
- bug fix
- 修复 CMDB-更新集群属性 插件集群容量参数未使用整数的问题
> bugfix: 修复 CMDB-更新集群属性 插件集群容量参数未使用整数的问题

- frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue
> bugfix：tagTree勾选后控制台报错兼容(V3.5.X)

- docs/develop/tag_usage_dev.md
- frontend/desktop/package.json
- frontend/desktop/src/assets/js/table-to-excel.js
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- 优化项
- 表格数据导出函数依赖包改为本地文件引用
- 按钮点击事件回调上下文绑定到tag组件
- 多个按钮样式对齐
> improvement: tagDatatable组件自定义按钮功能改造(V3.5.X)

- frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue
> bugfix：tagTree勾选后控制台报错兼容(V3.4.X)

- docs/develop/tag_usage_dev.md
- frontend/desktop/package.json
- frontend/desktop/src/assets/js/table-to-excel.js
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- 优化项
- 表格数据导出函数依赖包改为本地文件引用
- 按钮点击事件回调上下文绑定到tag组件
- 多个按钮样式对齐
> improvement: tagDatatable组件自定义按钮功能改造(V3.4.X)

- pipeline_plugins/components/query/sites/open/query.py
- pipeline_plugins/components/static/components/atoms/job/job_execute_task_output.js
- static/components/atoms/job/job_execute_task_output.js
> improvement: 优化 JOB-执行作业 输出表单

- frontend/desktop/src/pages/template/TemplateEdit/index.vue
> bugfix: 保存模版路由未跳转

- gcloud/taskflow3/api.py
> improvement: 节点回调接口增加重试机制(V3.5.X)

- gcloud/taskflow3/api.py
> improvement: 节点回调接口增加重试机制(V3.3.X)

- config/perms.py
> minor: 修改职能化人员的权限模板

- gcloud/commons/template/models.py
- gcloud/tasktmpl3/api.py
- gcloud/tasktmpl3/models.py
- gcloud/tasktmpl3/urls.py
- 新功能
- 添加获取项目下子流程过期的模板 API
close #1733
> feature: 添加获取项目下子流程过期的模板 API

- pipeline_plugins/components/collections/http/v1_0.py
- pipeline_plugins/components/static/components/atoms/bk/v1.0/http.js
- static/components/atoms/bk/v1.0/http.js
> HTTP-请求插件优化，增加鲁棒性

- pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
- static/components/atoms/job/job_execute_task.js
- 优化项
- datatable 优化后，Job-执行作业全局参数表格改为不展示删除按钮 
link #1728
> improve: datatable 优化后，Job-执行作业全局参数表格改为不展示删除按钮 #1728

- pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
- static/components/atoms/job/job_execute_task.js
- 优化项
- datatable 优化后，Job-执行作业全局参数表格改为不展示删除按钮 
link #1728
> improve: datatable 优化后，Job-执行作业全局参数表格改为不展示删除按钮（V3.4.X）

- requirements.txt
- 优化项
- improvement: 控制 gitdb2 的版本号, 防止最新版 import 出错
> improvement: 控制 gitdb2 的版本号, 防止最新版 import 出错

- frontend/desktop/src/components/common/RenderForm/FormGroup.vue
- 优化项
- combine类组件增加get_parent方法
> improvement:combine类组件增加get_parent方法

- frontend/desktop/src/components/common/RenderForm/FormGroup.vue
- 优化项
- combine类组件增加get_parent方法
> improvement:combine类组件增加get_parent方法(V3.4.X)

- bkiam/client.py
- bkiam/conf.py
- pipeline_plugins/components/collections/sites/open/bcs.py
- pipeline_plugins/components/query/__init__.py
- pipeline_plugins/components/query/sites/open/bcs.py
- pipeline_plugins/components/static/components/atoms/bcs/bcs_mesos_command.js
- pipeline_plugins/components/static/components/atoms/bcs/bcs_mesos_create.js
- pipeline_plugins/components/static/components/atoms/bcs/bcs_mesos_operate.js
- pipeline_plugins/components/static/components/atoms/bcs/bcs_mesos_rollingupdate.js
- pipeline_plugins/components/utils/bcs_client.py
- static/components/atoms/bcs/bcs_mesos_command.js
- static/components/atoms/bcs/bcs_mesos_create.js
- static/components/atoms/bcs/bcs_mesos_operate.js
- static/components/atoms/bcs/bcs_mesos_rollingupdate.js
> 新增 BCS-Mesos 操作插件

- gcloud/core/utils/common/dates.py
- bug fix
- 修复按月获取任务执行统计数据时后台500的问题
> bugfix:修复按月获取任务执行统计数据时后台500的问题

- frontend/desktop/src/pages/template/TemplateList/index.vue
- frontend/desktop/src/pages/template/common/CommonTemplateList.vue
- bug fix
- 公共流程列表点击执行历史跳转到任务记录列表
> bugfix:公共流程列表点击执行历史跳转到任务记录列表

- frontend/desktop/src/pages/functor/FunctionList.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- frontend/desktop/src/pages/task/TaskCreate/index.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
> bugfix: 职能化权限问题导致创建任务异常

- frontend/desktop/src/pages/admin/statistics/HorizontalBarChart.vue
> improvement:数据统计横向柱状图兼容字符串格式数据(3.4.X)

- frontend/desktop/src/pages/admin/statistics/HorizontalBarChart.vue
> improvement:数据统计横向柱状图兼容字符串格式数据

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEdit.vue
> bugfix: 插件版本默认值问题修复

- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/routers/index.js
> bugfix: 轻应用首页按钮未屏蔽

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 插件版本切换后配置项没清空导致保存模板时报错
> bugfix: 插件版本切换后配置项没清空导致保存模板时报错

- frontend/desktop/src/components/layout/Navigator.vue
> improvement:帮助链接跳转到文档中心

- frontend/desktop/src/components/common/modal/ProjectSelectorModal.vue
- frontend/desktop/src/components/layout/ProjectSelector.vue
> improve: 选择项目弹窗样式优化

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- 新功能
- tagDatatable 支持分页和添加点击事件
> feature: tagDatatable 支持分页和添加点击事件

- frontend/desktop/src/api/index.js
- frontend/desktop/src/components/common/Individualization/LogDisplay.vue
- frontend/desktop/src/components/common/RenderForm/formMixins.js
- frontend/desktop/src/components/layout/ProjectSelector.vue
- frontend/desktop/src/pages/project/index.vue
- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- frontend/desktop/src/store/modules/atomForm.js
- 优化项
- 输出参数和输出表单共存
- 插件配置的取值统一在 atomForm.js 中完成
- bug fix
- 修复输出表单再次打开不显示
- 显示日志组件数据重复
- 表格 editable 未生效
> bugfix: 输出表单相关优化以及 bug 修复

- frontend/desktop/src/components/common/TemplateCanvas/index.vue
> improve:  画布节点连接参考线优化，换成 svg 实现（V3.4.X）

- frontend/desktop/src/components/common/TemplateCanvas/index.vue
> improve: 画布节点连接参考线优化，换成 svg 实现

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 节点参数编辑数字0会转换为空字符修复
> bugfix:节点参数编辑数字0会转换为空字符修复

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
- bug fix
- 节点参数编辑数字0会转换为空字符修复
> bugfix:节点参数编辑数字0会转换为空字符修复(V3.4.X)

- gcloud/webservice3/resources.py
> improvement: 用户常用项目列表中过滤掉已停用的项目

- pipeline_plugins/components/query/sites/open/query.py
- bug fix
- 修复插件中业务列表能够获取到已经归档的业务的问题
close #1780
> bugfix: 修复插件中业务列表能够获取到已经归档的业务的问题

- gcloud/commons/template/models.py
- gcloud/periodictask/models.py
- gcloud/periodictask/signals/handlers.py
- gcloud/shortcuts/message/__init__.py
- gcloud/shortcuts/message/common.py
- gcloud/taskflow3/models.py
- gcloud/tasktmpl3/models.py
- 优化项
- 公共流程执行通知功能修复; 代码结构优化
close #1774
> improvement: 公共流程执行通知功能修复; 代码结构优化

- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
> improvement:任务执行失败重试、跳过按钮样式优化

- pipeline_plugins/base/query/cmdb.py
- pipeline_plugins/base/urls.py
- pipeline_plugins/base/utils/adapter.py
- 新功能
- 新加/pipeline/cc_search_topo_tree/{biz_cc_id}/ API，查询集群下模块详情
link #1724
> feature: 新加/pipeline/cc_search_topo_tree/{biz_cc_id}/ API，查询集群下模块详情 

- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
- bug fix
-【开始节点】处使用快捷添加节点 outgoing 丢失
> bugfix: 【开始节点】处使用快捷添加节点 outgoing 丢失

- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
- bug fix
-【开始节点】处使用快捷添加节点 outgoing 丢失
> bugfix:【开始节点】处使用快捷添加节点 outgoing 丢失（V3.4.X）

- frontend/desktop/src/components/common/modal/ProjectSelectorModal.vue
- frontend/desktop/src/pages/home/CommonlyUsed.vue
- frontend/desktop/src/pages/template/common/CommonTemplateList.vue
- bug fix
- 公共流程历史记录为跳转
- 优化项
- 常用项目点击修改默认项目
> bugfix: 公共流程历史记录没有业务时隐藏，常用项目点击修改默认项目

- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/pages/admin/statistics/index.vue
- 优化项
- 导航栏选中态错误修复
- 优化运营数据时间范围未居中
> improve: 导航选中态优化，运营数据时间范围未居中优化

- frontend/desktop/src/pages/home/MyDynamic.vue
> improve: 我的动态创建方式下拉和动态列表保持一致

- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- bug fix
- job执行作业刷新按钮未垂直居中修复
> bugfix:job执行作业刷新按钮未垂直居中修复

- pipeline_plugins/components/collections/sites/open/bcs.py
- 优化项
- bcs-create scheudle 方法状态获取鲁棒性增强
> bcs-create scheudle 方法状态获取鲁棒性增强

- pipeline/component_framework/apps.py
- pipeline_plugins/apps.py
> improvement: 插件初始化过程支持忽略某些命令

- frontend/desktop/src/pages/home/AddCollectionDialog.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/template/TemplateEdit/ReuseVarDialog.vue
- bug fix
- 职能化权限导致，创建任务异常，修复 flow_type
- searchSelect 组件点击 x 不能同步更新待选面板数据
> bugfix: 职能化创建任务异常；添加收藏输入框点击 x 不能同步更新待选面板数据

- gcloud/apigw/views.py
> feature:  新增api网关接口 dispatch_pipeline_plugin_query

- Procfile
- config/default.py
- gcloud/commons/template/permissions.py
- gcloud/contrib/analysis/permissions.py
- gcloud/contrib/appmaker/permissions.py
- gcloud/contrib/audit/permissions.py
- gcloud/contrib/function/permissions.py
- gcloud/core/api_adapter/sites/open/user_info.py
- gcloud/core/permissions.py
- gcloud/core/utils/common/apis.py
- gcloud/periodictask/permissions.py
- gcloud/taskflow3/permissions.py
- gcloud/tasktmpl3/permissions.py
- pipeline/contrib/periodic_task/djcelery/tzcrontab.py
> V3.5.x c optimization

- frontend/desktop/src/components/common/advanceSearchForm/AdvanceSearch.vue
- frontend/desktop/src/components/common/advanceSearchForm/index.vue
- frontend/desktop/src/pages/functor/FunctionList.vue
- 新功能
- 职能化添加任务状态展示
- 职能化列表添加自动刷新选项
> feature: 职能化添加任务状态、自动刷新选项

- frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
- frontend/desktop/src/store/modules/template.js
- 优化项
- 节点引用逻辑修改
- 全局变量控制台报错
- bug fix
- 无法保存流程模版
> bugfix: 无法保存流程模版，模版编辑页面报错

- gcloud/apigw/whitelist.py
> minor: 判断环境变量报错日志优化(V3.4.X)

- gcloud/apigw/whitelist.py
> minor: 判断环境变量报错日志优化(V3.5.X)

- frontend/desktop/src/api/index.js
- frontend/desktop/src/pages/appmaker/AppEditDialog.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
- frontend/desktop/src/store/modules/task.js
- bug fix
- 修复节点选择执行方案列表接口参数不正确问题
> bugfix: 修复节点选择执行方案列表接口参数不正确问题

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/api/index.js
- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
- frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagSetAllocation.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue
- frontend/desktop/src/store/index.js
- 新功能
- ip选择器、资源选择器支持传入接口 url 配置
- 优化项
- 资源选择器样式优化
- bug fix
- 集群节点可选逻辑修改
- 切换集群后，模块数据未清空修复
- 筛选主机请求参数增加 topo
> improvement: ip选择器、资源选择器优化

- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- bug fix
- 自动排版目前会导致节点重叠，暂时关闭，等待修复后开启
> bugfix: 自动排版目前会导致节点重叠，暂时关闭，等待修复后开启

- frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue
- frontend/desktop/src/pages/admin/manage/SourceManage/PackageTable.vue
> improvement:远程包源模块配置导入模块替换为换行符分割

- gcloud/core/admin.py
- gcloud/core/models.py
- 优化项
- ProjectCounter 添加 admin 管理配置
> minor: ProjectCounter 添加 admin 管理配置

- pipeline_plugins/components/collections/sites/open/nodeman.py
- pipeline_plugins/tests/components/collections/sites/open/nodeman_test/test_nodeman_create_task.py
- bug fix
- 修复节点管理执行 RSA 加密时报错的问题
> bugfix: 修复节点管理执行 RSA 加密时报错的问题

- app.yml
- config/default.py
- docs/release.md
- readme.md
- readme_en.md
> minor: 版本号升级到 V3.5.402

- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
> bugfix:job执行作业输出参数判断条件修改

- pipeline_plugins/components/utils/sites/open/utils.py
> feature: 内部节点回调链接 HOST 支持配置

- pipeline_plugins/components/collections/sites/open/job.py
- pipeline_plugins/components/query/sites/open/query.py
- pipeline_plugins/tests/components/collections/sites/open/job_test/test_job_execute_task.py
- 优化项
- 使用 category 而不是 type 来判断 job 全局变量类型
> improvement: 使用 category 而不是 type 来判断 job 全局变量类型

- gcloud/core/views.py
- bug fix
- 修复 404 handler 用户认证出错的问题
> 修复 404 handler 用户认证出错的问题

- gcloud/taskflow3/models.py
- bug fix
- 修复查看非 legacy 版本插件参数时报错的问题
> bugfix: 修复查看非 legacy 版本插件参数时报错的问题

- files/factory.py
- files/managers/base.py
- files/managers/upload_module.py
- gcloud/core/context_processors.py
- gcloud/core/templates/core/base_vue.html
- pipeline_plugins/components/query/sites/open/query.py
- pipeline_plugins/components/static/components/atoms/job/job_push_local_files.js
- static/components/atoms/job/job_push_local_files.js
添加 upload_module FileManager 测试代码
> minor: 添加 upload_module FileManager 测试代码

- gcloud/apigw/apps.py
- gcloud/apigw/views/create_periodic_task.py
- gcloud/apigw/views/create_task.py
- gcloud/apigw/views/fast_create_task.py
- gcloud/apigw/views/get_task_detail.py
- gcloud/apigw/views/get_task_node_detail.py
- gcloud/apigw/views/get_task_status.py
- gcloud/apigw/views/import_common_template.py
- gcloud/apigw/views/node_callback.py
- gcloud/apigw/views/plugin_proxy.py
- gcloud/apigw/views/query_task_count.py
- gcloud/apigw/whitelist.py
- gcloud/tests/apigw/views/test_create_task.py
- gcloud/tests/mock_settings.py
- 新功能
- create_task 接口支持传入 pipeline_tree
> feature: create_task 接口支持传入 pipeline_tree

- gcloud/taskflow3/context.py
- bug fix
- 修复 TaskContext 没有 biz_supplier_account 的问题
> bugfix: 修复 TaskContext 没有 biz_supplier_account 的问题

- pipeline_plugins/components/utils/common.py
> bugfix: 修复获取开发商 ID 不正确的问题

- pipeline_plugins/components/query/sites/open/query.py
minor: file_upload add csrf_exempt
> minor: file_upload add csrf_exempt

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
> bugfix: 子流程表单勾选状态判断错误修复

- frontend/desktop/src/components/layout/Navigator.vue
> improve: 导航栏不能右键跳转优化

- frontend/desktop/src/pages/home/CommonlyUsed.vue
> bugfix: 首页常用项目无数据跳转链接修复

- gcloud/apigw/urls.py
- gcloud/apigw/views/get_tasks_status.py
- gcloud/tests/apigw/views/test_get_tasks_status.py
- gcloud/tests/mock.py
- gcloud/tests/mock_settings.py
> feature: 增加批量获取任务状态 API

- gcloud/commons/template/migrations/0006_auto_20200325_1458.py
- gcloud/contrib/function/migrations/0003_auto_20200325_1458.py
- gcloud/core/migrations/0015_auto_20200325_1458.py
- gcloud/external_plugins/migrations/0005_auto_20200325_1458.py
- gcloud/periodictask/migrations/0007_auto_20200325_1458.py
- gcloud/taskflow3/migrations/0012_auto_20200325_1458.py
- gcloud/tasktmpl3/migrations/0016_auto_20200325_1458.py
- pipeline/component_framework/migrations/0006_auto_20200325_1458.py
- pipeline/contrib/periodic_task/migrations/0003_auto_20200325_1458.py
- pipeline/engine/migrations/0021_auto_20200325_1458.py
- pipeline/migrations/0024_auto_20200325_1458.py
> minor: 升级py3后DB字符编码变更

- frontend/desktop/builds/webpack.base.js
- frontend/desktop/package.json
- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
> improvement: 前端加入文件名称大小写检查插件

- pipeline_web/drawing_new/position.py
- bug fix
- 修复自动排版导致前端location中属性丢失问题 
link #1870
> bugfix: 修复自动排版导致前端location中属性丢失问题 #1870

- pipeline_web/drawing.py
- bug fix
- 修复自动排版导致前端location中属性丢失问题 
close #1870
> bugfix: 修复自动排版导致前端location中属性丢失问题 （V3.4.X）

- gcloud/apigw/views/utils.py
- gcloud/tests/apigw/views/test_get_common_template_info.py
- gcloud/tests/apigw/views/test_get_template_info.py
- 优化项
- 获取模板详情 API 中的 pipeline_tree 增加 location 与 line 字段
> minor: 获取模板详情 API 中的 pipeline_tree 增加 location 与 line 字段

- gcloud/taskflow3/signals/handlers.py
- bug fix
- 修复任务失败通知发送错误的问题
close #1876
> bugfix: 修复任务失败通知发送错误的问题

- gcloud/contrib/appmaker/models.py
- bug fix
- 修复上传轻应用 logo 时后台报错的问题
close #1873
> bugfix: 修复上传轻应用 logo 时后台报错的问题

- frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
- 优化项
- tagUpload文件非编辑模式展示上传文件名称
> improvement: tagUpload文件非编辑模式展示上传文件名称

- pipeline_plugins/variables/collections/common.py
> improvement: 下拉框变量多选模式值支持更多类型

- pipeline_plugins/components/collections/sites/open/job.py
- 优化项
- JOB-快速执行脚本脚本参数字段支持更多类型
> improvement: JOB-快速执行脚本脚本参数字段支持更多类型

- gcloud/core/api_adapter/sites/open/user_info.py
- packages/blueking/component/apis/usermanage.py
> minor: 人员列表接口切换

- config/sites/community/ver_settings.py
- gcloud/core/views.py
- 优化项
- page_not_found 用户验证逻辑优化，适配多版本
> improvement: page_not_found 用户验证逻辑优化，适配多版本

- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/routers/index.js
- bug fix
- 导航project_id丢失问题修复
> bugfix: 导航project_id丢失问题修复

- frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
- bug fix
- 普通流程克隆编辑页取项目下新建流程权限
- 公共流程新建、克隆编辑页权限单独查询公共流程新建流程权限
> bugfix: 普通流程克隆编辑页取项目下新建流程权限，公共流程新建、克隆编辑页权限单独查询公共流程新建流程权限

- frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
- bug fix
- 文件上传tag在修改其他表单项时会取消正在下载的文件修复
> bugfix: 文件上传tag在修改其他表单项时会取消正在下载的文件修复

- gcloud/apigw/urls.py
- gcloud/apigw/views/import_project_template.py
> feature: 添加导入项目流程 API

- pipeline_plugins/components/query/sites/open/query.py
- pipeline_web/drawing_new/constants.py
- 优化项
- 自动排版根据节点大小对齐
- bug fix
- 修复资源筛选API 500 问题
> Bugfix new feature backends

- frontend/desktop/src/api/index.js
- frontend/desktop/src/constants/nodes.js
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- frontend/desktop/src/store/modules/template.js
> improvement: 自动编排接口参数修改

- pipeline_plugins/components/static/components/atoms/cc/v1.0/cc_create_set.js
- static/components/atoms/cc/v1.0/cc_create_set.js
- 优化项
- CMDB-创建集群V1.0表格输入框优化为文本框
> imporve: CMDB-创建集群V1.0表格输入框优化为文本框

- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
- frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
- frontend/desktop/src/components/layout/ProjectSelector.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
- 新功能
- 节点选择配置面板，选择插件/子流程输入框支持选择分组
- bug fix
- 资源筛选变量不同集群模块主机不能相同
- 资源筛选表格样式问题修复
- 优化项
- 变量引用说明文案更新
- 项目选择组件显示单行
> WIP: 新功能体验优化和问题修复v2

- gcloud/tasktmpl3/api.py
- 优化项
- 跨业务导入模板时，会将模板中的业务选择器设置为当前业务
> improvement: 跨业务导入模板时，会将模板中的业务选择器设置为当前业务

- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
> bugfix:全局变量修改key不生效修复

- frontend/desktop/src/components/common/RenderForm/FormGroup.vue
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/pages/task/TaskParamEdit.vue
- 优化项
- 创建任务参数填写页面全局变量名称和全局变量表单的label区分显示
> improvement: 创建任务参数填写页面全局变量名称和全局变量表单的label区分显示

- blueapps/account/components/bk_token/middlewares.py
- blueapps/account/handlers/response.py
- blueapps/patch/settings_open_saas.py
- gcloud/core/views.py
> improve: 优化登录跳转

- frontend/desktop/src/config/login.js
> improvement：小窗登录支持iframe跨域

- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/pages/task/TaskList/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/SubflowUpdateTips.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- frontend/desktop/src/routers/index.js
- 优化项
- 导航宽度不够(临时方案)
- 任务列表状态列、操作项列，宽度增加
- 子流程更新动画优化
> imporvement:导航宽度不够优化(临时方案)，任务列表表格操作项宽度增加，子流程更新动画优化

- frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue
- frontend/desktop/src/components/common/advanceSearchForm/AdvanceSearch.vue
- frontend/desktop/src/components/common/advanceSearchForm/index.vue
- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/components/layout/ProjectSelector.vue
- frontend/desktop/src/pages/task/TaskList/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableCitedList.vue
- frontend/desktop/src/pages/template/TemplateList/index.vue
- frontend/desktop/src/pages/template/common/CommonTemplateList.vue
- 优化项
- 未命名节点输入参数引用全局变量时，全局变量列表显示问题优化
- 列表页高级搜索样式优化，多余样式规则去除
- 周期表达式选择器国际化样式优化
- 导航右侧显示、禁用逻辑优化
> improvement: V3.5.X国际化和测试问题修复

- config/default.py
- 优化项
- 兼容 BK_IAM_INNER_HOST 变量不存在的情况
> improvement: 兼容 BK_IAM_INNER_HOST 变量不存在的情况

- frontend/desktop/src/pages/home/CommonlyUsed.vue
- frontend/desktop/src/pages/home/MyCollection.vue
> improve: 首页刷新控制台报错

- frontend/desktop/src/components/common/advanceSearchForm/index.vue
- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
- 优化项
- 高级搜索表单操作按钮和表单对齐
- 模板编辑名称垂直居中兼容safari
- bug fix
- 轻应用任务执行页面激活创建任务导航项
- 轻应用打开页面logo不支持单击和右键跳转到首页
> improvement: V3.5.X测试问题处理

- frontend/desktop/src/components/layout/Navigator.vue
- bug fix
- 轻应用任务执行页面激活任务记录导航项
> bugfix: 轻应用任务执行页面激活任务记录导航项

- gcloud/webservice3/resources.py
- bug fix
- 修复当权限中心中项目资源有脏数据，会导致获取常用项目接口500的问题 
- 修复首次从权限中心拉取有权限的业务，接口返回的数据不准确的问题
close #1927
close #1938
> bugfix: 修复首次从权限中心拉业务的BUG

- pipeline_plugins/base/utils/inject.py
- pipeline_plugins/components/utils/common.py
- bug fix
- 修复获取项目/业务的开发商ID错误的问题 
close #1932
> bugfix: 修复获取项目/业务的开发商ID错误的问题 #1932

- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
- frontend/desktop/src/components/common/base/BaseCard.vue
- frontend/desktop/src/components/common/base/BaseTitle.vue
- frontend/desktop/src/pages/home/AddCollectionDialog.vue
- frontend/desktop/src/pages/home/CommonlyUsed.vue
- frontend/desktop/src/pages/home/MyCollection.vue
- frontend/desktop/src/pages/task/TaskList/index.vue
- frontend/desktop/src/pages/template/ListPageTipsTitle.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/SystemVariableEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabPipelineTreeEdit.vue
- frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- 优化项
- 标题栏不统一，不同页面分割线位置和文字位置不一致
- 重试和跳过还原度问题
- 首页卡片缺少2px圆角
- 添加收藏和导出流程弹窗细节问题
- 新建任务按钮宽度120
- 双开侧边栏时，参考设计稿增加条分割线
- 快捷工具栏与节点之间的间距参考设计稿调整
- 选择插件控件样式问题
- 节点配置面板文字颜色不一致
- 新建全局变量背景色还原度问题
- 编辑变量输入框和文本域disable状态下描边颜色没有统一
- 提示“i” icon没有纵向居中对齐
- 流程模版数据保存按钮改为左对齐
- 节点文字左右padding太小了，改为10px；
> improve: 设计走查问题优化

- frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue
> improvement:远程包源加载模块名称不能重复

- config/default.py
- bug fix
- 修复 open_paas 版本低于 2.10.7 时申请权限跳转链接错误问题 
close #1934
> bugfix: 修复 open_paas 版本低于 2.10.7 时申请权限跳转链接错误问题 (V3.4.X)

- bkiam/client.py
- config/default.py
- frontend/desktop/src/pages/home/CommonlyUsed.vue
- gcloud/core/context_processors.py
- gcloud/core/templates/core/base_vue.html
- gcloud/core/utils/common/apis.py
- bug fix
- 修复 open_paas 版本低于 2.10.7 时申请权限跳转链接错误问题，环境变量改为 BKAPP_IAM_SAAS_HOST (V3.5.X) #1936
> bugfix: 修复 open_paas 版本低于 2.10.7 时申请权限跳转链接错误问题 (V3.5.X) #1936

- app.yml
- config/default.py
- docs/release.md
- readme.md
- readme_en.md
> docs: 版本号升级到 V3.4.21

- gcloud/core/api.py
- gcloud/core/footer/__init__.py
- gcloud/core/footer/sites/__init__.py
- gcloud/core/footer/sites/open/__init__.py
- gcloud/core/footer/sites/open/footer.py
- gcloud/core/urls.py
> feature: 页面 footer 支持从后台进行获取

- frontend/desktop/src/App.vue
- frontend/desktop/src/api/index.js
- frontend/desktop/src/api/urls.js
- frontend/desktop/src/components/layout/CopyrightFooter.vue
- frontend/desktop/src/store/index.js
> feature:页面footer模板采用后台自定义生成方式

- gcloud/core/api.py
- gcloud/core/footer/sites/open/footer.py
> improvement: footer 年份根据当前时间获取

- gcloud/apigw/constants.py
- gcloud/apigw/decorators.py
- 新功能
-  API免用户认证白名单默认值添加bk_datainstaller和bk_dataadmin 
close #1939
> feature: API免用户认证白名单默认值添加bk_datainstaller和bk_dataadmin #1939

- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- 优化项
- 流程模板被删除后，访问对应模板详情、节点选择、参数填写页面时，跳转到404页面
> improvement: 流程模板被删除后，访问对应模板详情、节点选择、参数填写页面时，跳转到404页面

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
- 优化项
- 子流程节点不显示节点标签表单
- 节点标签分类下只能选择一种
> improvement：子流程节点不显示标签表单；节点标签分类下只能选一种

- gcloud/apigw/views/get_task_status.py
- 优化项
- get_task_status API 在子流程节点不存在或未执行时不抛出异常
> improvement: get_task_status API 在子流程节点不存在或未执行时不抛出异常

- blueapps/account/admin.py
- gcloud/contrib/collection/admin.py
- gcloud/core/admin.py
- templates/admin/base_site.html
- weixin/core/accounts.py
- weixin/core/decorators.py
- weixin/core/middlewares.py
- bug fix
- 修复后台admin页面修改数据保存时可能报403问题 
close #1963
> bugfix: 修复后台admin页面修改数据保存时可能报403问题 #1963

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/formMixins.js
- frontend/desktop/src/components/common/RenderForm/tags/TagButton.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
- static/components/atoms/job/job_execute_task.js
- 优化项
- 子流程选择面板分组按照接口返回顺序
- tagbutton组件替换为bk-button;job执行作业刷新按钮间距
- JOB执行作业插件刷新按钮配置项修改
- bug fix
- 流程模板保存后添加子流程节点时不能选择自己
- 子流程节点参数错误收起后，点开节点未提示错误信息修复
> bugfix: 测试问题处理

- config/default.py
- config/dev.py
> docs: 代码注释优化 #1413

- gcloud/webservice3/resources.py
- bug fix
- 修复当项目数超过1000时，部分项目不显示的问题 
close #1965
> bugfix: 修复当项目数超过1000时，部分项目不显示的问题 #1965

- pipeline_plugins/components/collections/sites/open/cc_plugins/v1_0.py
- pipeline_plugins/components/collections/sites/open/job.py
- bug fix
- 修复CMDB-创建集群（v1.0）等插件执行完后查看节点详情表格参数为空的问题 
close #1971
> bugfix: 修复CMDB-创建集群（v1.0）等插件执行完后查看节点详情表格参数为空的问题 #1971

- packages/bkoauth/utils.py
- pipeline/utils/collections.py
- bug fix
- 修复get_task_detail 接口报错 500 的问题 
close #1984
> bugfix: 修复get_task_detail 接口报错 500 的问题 #1984

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
- bug fix
- 复用变量弹窗异常关闭修复
close #1979
> bugfix: 复用变量弹窗异常关闭修复

- frontend/desktop/src/components/common/TemplateCanvas/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- bug fix
- 分支网关条件值会被双引号提前截断修复
close #1978
> bugfix: 分支网关条件值会被双引号提前截断修复

- frontend/desktop/src/store/modules/project.js
- bug fix
- 项目默认id为空字符串时，会被转为0修复
> bugfix:项目默认id为空字符串时，会被转为0修复

- frontend/desktop/src/components/layout/Navigator.vue
- bug fix
- 职能化和操作审计页面权限申请url接口参数修改
> bugfix:职能化和操作审计页面权限申请url接口参数修改

- auth_backend/README.md
- config/default.py
- 优化项
- 和权限有关的环境变量settings优化 
close #1982
> improve: 和权限有关的环境变量settings优化 #1982

- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
- frontend/desktop/src/pages/template/ListPageTipsTitle.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
- frontend/desktop/src/pages/template/common/CommonTemplateList.vue
- bug fix
- 资源筛选变量已选集群模板名称不显示问题
- 变量复用选择key不正确问题处理
- 公共流程模板导出参数格式修改
> bugfix: 测试问题修复

- frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeItem.vue
- frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
- frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- frontend/desktop/src/store/modules/atomForm.js
- frontend/desktop/src/store/modules/atomList.js
> improvement: 流程模板编辑页面子流程列表增加权限判断

- frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- 优化项
- 分支网关分支条件侧滑交互优化，和节点编辑保持一致
> improvement: 分支网关分支条件侧滑交互优化，和节点编辑保持一致

- frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
- frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
> feature: IP 选择器支持排序

- frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
- frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
> improvement: 国际化样式优化

- pipeline_plugins/components/static/components/atoms/bk/timer.js
- static/components/atoms/bk/timer.js
- 优化项
- 蓝鲸服务(BK)-定时 插件优化，定时时间在流程编辑时作为显示的变量可以为空 
close #1990
> 蓝鲸服务(BK)-定时 插件优化，定时时间在流程编辑时可以为空 #1990

- pipeline_plugins/components/static/components/atoms/job/job_cron_task.js
- static/components/atoms/job/job_cron_task.js
> minor: 修改 JOB-新建定时作业 定时规则占位符

- gcloud/core/models.py
- 优化项
- 业务信息从CMDB同步到标准运维项目时，如果time_zone字段有变化也同步 
close #1995
> improve: 业务信息从CMDB同步到标准运维项目时，如果time_zone字段有变化也同步 #1995

- packages/bkoauth/decorators.py
- 优化项
- API JWT 可以通过环境变量 BKAPP_API_JWT_EXEMPT 豁免
> imporve: API JWT 可以通过环境变量 BKAPP_API_JWT_EXEMPT 豁免

- docs/develop/dev_plugins.md
> minor: 修复标准插件开发文档里的一些错误.

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
- bug fix
- 节点配置面板关闭面板时节点名称未保存修复
close #1997
> bugfix: 节点配置面板关闭面板时节点名称未保存修复

- gcloud/shortcuts/cmdb.py
> minor: 获取消息通知人代码优化

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- bug fix
- 节点执行详情Job执行作业输出参数展示问题
> bugfix: 节点执行详情Job执行作业输出参数展示问题

- config/default.py
- requirements.txt
> feature: 支持配置跨域请求豁免白名单

- gcloud/tasktmpl3/models.py
- bug fix
-  修复获取过期子流程id列表时未过滤已删除流程的问题
close #2007
> bugfix: 修复获取过期子流程id列表时未过滤已删除流程的问题

- frontend/desktop/src/utils/tools.js
> improve: 任务执行耗时显示的不合理修复

- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagSetAllocation.vue
- bug fix
- 自定义变量切换后资源筛选变量报错问题修复
> bugfix: 自定义变量切换后资源筛选变量报错问题修复

- auth_backend/contrib/consistency/legacy.py
- auth_backend/plugins/decorators.py
- gcloud/apigw/views/get_task_detail.py
- gcloud/apigw/views/get_task_node_detail.py
- gcloud/apigw/views/node_callback.py
- gcloud/core/api_adapter/sites/open/user_role.py
- gcloud/periodictask/resources.py
- bug fix
- 修改format格式不规范导致KeyError、CI不通过的问题
> V3.5.x fix format error

- frontend/desktop/src/pages/template/TemplateList/index.vue
- bug fix
- 项目流程列表高级搜索子流程更新参数错误修复
> bugfix:项目流程列表高级搜索子流程更新参数错误修复

- frontend/desktop/src/components/common/base/BaseTitle.vue
> bugfix:数据统计时间选择控件位置偏上修复

- frontend/desktop/src/components/layout/ProjectSelector.vue
- 优化项
- 无默认项目时，切换项目默认跳转到流程列表
> 出现场景，无默认项目点击项目列表，显示无项目权限，再切换项目时，页面未刷新，还是无项目权限页面
> improve: 无默认项目时，切换项目默认跳转到流程列表

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/desktop/src/store/modules/template.js
- bug fix
- 标准插件版本切换已勾选参数未清空修复
> bugfix: 标准插件版本切换已勾选参数未清空修复

- frontend/desktop/src/components/common/TemplateCanvas/index.vue
- frontend/desktop/src/pages/template/TemplateList/index.vue
- frontend/desktop/src/utils/tools.js
- bug fix
- 分支网关条件title属性会被提前关闭问题修复
- 子流程筛选条件默认参数问题修复
close #2037
> bugfix：分支网关条件title属性会被提前关闭，子流程筛选条件默认参数问题修复

- frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
- frontend/desktop/src/components/common/advanceSearchForm/AdvanceSearch.vue
- frontend/desktop/src/components/common/advanceSearchForm/index.vue
- frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
- frontend/desktop/src/pages/admin/manage/AdminSearch/index.vue
- frontend/desktop/src/pages/project/index.vue
- frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
- frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
> bugfix:  前后有空格时搜索结果为空修复

- frontend/desktop/src/pages/template/common/CommonTemplateList.vue
- bug fix
- 公共流程高级搜索子流程筛选条件参数错误
> bugfix:公共流程高级搜索子流程筛选条件参数错误

- pipeline_plugins/components/collections/sites/open/cc.py
> minor: 中文去掉u前缀，国际化标记

- pipeline_web/parser/schemas.py
- 优化项
- 移除后端保存流程时对变量 key 长度的校验
> minor: 移除后端保存流程时对变量 key 长度的校验

- frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
- frontend/desktop/src/pages/audit/AuditList.vue
- frontend/desktop/src/pages/functor/FunctionList.vue
- frontend/desktop/src/pages/task/PeriodicList/index.vue
- frontend/desktop/src/pages/task/TaskList/index.vue
- frontend/desktop/src/pages/template/TemplateList/index.vue
- frontend/desktop/src/pages/template/common/CommonTemplateList.vue
- bug fix
- 高级搜索，点击搜索的时候当前页码未初始化修复
close #2049
> bugfix: 高级搜索，点击搜索的时候当前页码未初始化修复

- frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
- bug fix
- 职能化、审计、任务执行页面返回按钮按钮路径错误
close #2060
> bugfix: 职能化、审计、任务执行页面返回按钮按钮路径错误

- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- bug fix
- 双击分支网关报错修复
close #2061
> bugfix:双击分支网关报错修复

- pipeline_web/drawing_new/position.py
- bug fix
- 修复自动排版宽度超出画布换行时计算坐标异常的问题 
close #2064
> bugfix: 修复自动排版宽度超出画布换行时计算坐标异常的问题 #2064

- pipeline_plugins/components/http.py
- 新功能
- xxx
- 优化项
- xxx
- bug fix
- xxx
> minor: http_do增加请求头处理

- gcloud/commons/template/models.py
- bug fix
- 修复老版本流程数据导入时业务流程能够覆盖公共流程的问题
close #2070
> bugfix: 修复老版本流程数据导入时业务流程能够覆盖公共流程的问题

- frontend/desktop/src/pages/home/AddCollectionDialog.vue
> improve: V3.5.10 国际化问题汇总

- pipeline_plugins/components/static/components/atoms/job/job_push_local_files.js
- static/components/atoms/job/job_push_local_files.js
> optimization: JOB-分发本地文件必填字段校验优化

- gcloud/core/admin.py
- gcloud/core/api.py
- gcloud/core/context_processors.py
- gcloud/core/footer/sites/open/footer.py
> feature: 页面 footer 与副标题支持自定义

- frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
> improve: tagTextarea 高度不定问题优化

- frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
- frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
- frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
- 优化项
- ip选择器表格列固定宽度
- 插件分组增加搜索配置
> improve: ip选择器表格列固定宽度；插件分组增加搜索配置

- frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
- frontend/desktop/src/store/modules/template.js
- 优化项
- 开始节点后添加的节点未在一条直线上
- 开始节点下的快捷面板距离过高
> improve: 画布开始节点样式优化

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
> feature: tagUpload组件上传文件时支持传附加参数

- frontend/desktop/src/components/common/base/BaseTitle.vue
> bugfix:运营数据时间选择组件层级问题修复

- files/tests/managers/test_nfs.py
- 新功能
- xxx
- 优化项
- xxx
- bug fix
- xxx
> minor: nfs单元测试适配windows/linux

- gcloud/core/api_adapter/__init__.py
- gcloud/core/api_adapter/sites/open/business_location.py
- gcloud/core/project.py
- 优化项
- CMDB业务同步支持按照location过滤
> improve: CMDB业务同步支持按照location过滤

- gcloud/shortcuts/cmdb.py
- bug fix
- 修复 BKAPP_DEFAULT_SUPPLIER_ACCOUNT 在发送通知获取人员时不生效的问题
close #2101
> bugfix: 修复 BKAPP_DEFAULT_SUPPLIER_ACCOUNT 在发送通知获取人员时不生效的问题

- pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
- static/components/atoms/job/job_execute_task.js
- bug fix
- JOB-执行作业 插件前端表单调整
close #2095
> bugfix: JOB-执行作业 插件前端表单调整

- frontend/desktop/src/components/common/TemplateCanvas/HelpInfo/index.vue
> improvement: 画布缩放提示文案修改

- frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
> bugfix: ip选择器变量不发送请求修复

- frontend/desktop/src/components/common/CodeEditor.vue
- frontend/desktop/src/pages/atomdev/configPanel/FormConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabPipelineTreeEdit.vue
> improve: 分支表达式输入框使用代码编辑器替换

- gcloud/contrib/appmaker/models.py
- gcloud/iam_auth/authorization_helpers/flow.py
- gcloud/iam_auth/shortcuts.py
- gcloud/taskflow3/resources.py
- iam/shortcuts.py
> V3.6.x iam v3

- frontend/desktop/src/App.vue
- frontend/desktop/src/components/common/modal/PermissionModal.vue
- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/components/layout/permissionApply.vue
- frontend/desktop/src/pages/functor/FunctionList.vue
- frontend/desktop/src/pages/home/SelectCreateTaskDialog.vue
- frontend/desktop/src/pages/project/index.vue
- frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
- frontend/desktop/src/pages/template/common/CommonTemplateList.vue
- frontend/desktop/src/store/index.js
- 优化项
- 查询权限接口路径拼接完整
- is_allow接口按照返回格式调整取值逻辑
- 职能化、轻应用无权限处理
> minor:新版权限中心接入改造

- frontend/desktop/src/components/common/RenderForm/tags/TagCascader.vue
- 优化项
-  tagcascader组件lazyload方法this指向组件
> improvement: tagcascader组件lazyload方法this指向组件

- gcloud/contrib/appmaker/models.py
- gcloud/iam_auth/conf.py
- support-files/iam/initial.json
> V3.6.X UPDATE

- frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- 优化项
- 节点选择预览接口exclude_node_list字段传列表类型
> improvement: 节点选择预览接口exclude_node_list字段传列表类型

- gcloud/contrib/appmaker/resources.py
- gcloud/iam_auth/resource_api/task.py
- gcloud/iam_auth/resource_helpers/base.py
- gcloud/iam_auth/resource_helpers/flow.py
- gcloud/iam_auth/resource_helpers/mini_app.py
- gcloud/iam_auth/resource_helpers/periodic_task.py
- gcloud/iam_auth/resource_helpers/task.py
- gcloud/periodictask/resources.py
- gcloud/taskflow3/resources.py
- gcloud/tasktmpl3/resources.py
- bug fix
- 修复部分iam资源实例构建时属性不全的问题
> bugfix: 修复部分iam资源实例构建时属性不全的问题

- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- 优化项
- 创建任务参数填写预览接口exclude_node_list字段传列表类型
> improvement: 创建任务参数填写预览接口exclude_node_list字段传列表类型

- gcloud/core/project.py
- gcloud/core/resources.py
- gcloud/iam_auth/__init__.py
- gcloud/iam_auth/filter.py
- gcloud/iam_auth/resource_helpers/flow.py
- gcloud/iam_auth/resource_helpers/mini_app.py
- gcloud/iam_auth/resource_helpers/periodic_task.py
- gcloud/iam_auth/resource_helpers/task.py
- gcloud/iam_auth/shortcuts.py
- gcloud/iam_auth/view_interceptors/taskflow.py
- gcloud/taskflow3/resources.py
- bug fix
- 修复 resource_help 返回的资源 id 不是字符串的问题
> bugfix: 修复 resource_help 返回的资源 id 不是字符串的问题

- frontend/desktop/src/pages/appmaker/AppCard.vue
> bugfix: 收藏轻应用跳转链接错误

- pipeline_web/wrapper.py
- bug fix
- 流程导入导出时带上节点标签等属性 
close #1889
> sprintfix: 流程导入导出时带上节点标签等属性 #1889

- gcloud/commons/template/api.py
- gcloud/core/middlewares.py
- gcloud/err_code.py
- gcloud/iam_auth/view_interceptors/taskflow.py
- gcloud/periodictask/api.py
- gcloud/taskflow3/api.py
- gcloud/taskflow3/resources.py
- gcloud/tasktmpl3/api.py
- gcloud/utils/decorators.py
- bug fix
- 修复 taskflow api 部分权限拦截器报错的问题
- 修复部分接口返回 code 格式不正确的问题
> bugfix: 1.修复 taskflow api 部分权限拦截器报错的问题 2.修复部分接口返回 code 格式不正确的问题

- config/default.py
- gcloud/apigw/views/create_periodic_task.py
- gcloud/apigw/views/create_task.py
- gcloud/apigw/views/fast_create_task.py
- gcloud/apigw/views/get_task_node_data.py
- gcloud/apigw/views/get_task_node_detail.py
- gcloud/apigw/views/get_task_status.py
- gcloud/apigw/views/get_user_project_detail.py
- gcloud/apigw/views/get_user_project_list.py
- gcloud/apigw/views/import_common_template.py
- gcloud/apigw/views/import_project_template.py
- gcloud/apigw/views/modify_constants_for_periodic_task.py
- gcloud/apigw/views/modify_cron_for_periodic_task.py
- gcloud/apigw/views/operate_node.py
- gcloud/apigw/views/plugin_proxy.py
- gcloud/apigw/views/preview_task_tree.py
- gcloud/apigw/views/query_task_count.py
- gcloud/contrib/admin/command.py
- gcloud/contrib/admin/urls.py
- gcloud/core/urls.py
- gcloud/err_code.py
- gcloud/taskflow3/models.py
- gcloud/tests/apigw/views/test_create_task.py
- gcloud/tests/apigw/views/test_get_user_project_detail.py
- gcloud/tests/apigw/views/test_get_user_project_list.py
- gcloud/tests/apigw/views/test_preview_task_tree.py
- pipeline/conf/default_settings.py
- 新功能
- SaaS管理员可以主动将pipeline缓存数据从backend(redis)迁移到candidate_backend(msyql))
close #2108
> SaaS管理员可以主动将pipeline缓存数据从backend(redis)迁移到candidate_backend

- frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue
- 优化项
- 模板导入校验接口返回错误后可继续选择其他上传方案
> improvement: 模板导入校验接口返回错误后可继续选择其他上传方案

- pipeline_plugins/components/static/components/atoms/cc/create_module/legacy.js
- static/components/atoms/cc/create_module/legacy.js
- bug fix
- 修复 cc_id undefined 问题
> bugfix: cc_id undefined

- frontend/desktop/src/pages/appmaker/AppEditDialog.vue
- frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
- frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- frontend/desktop/src/pages/template/TemplateList/index.vue
- frontend/desktop/src/store/modules/templateList.js
> improvement:加载流程列表接口参数由调用方法传入

- frontend/desktop/src/components/common/TemplateCanvas/ToolPanel/index.vue
- 优化项
- 画布工具栏 tooltip 时间修改为 300ms
> improve: 画布工具栏 tooltip 时间修改为 300ms

- gcloud/taskflow3/resources.py
- 新功能
- taskflow list 接口返回相关的 template_name
> taskflow list 接口返回相关的 template_name

- frontend/desktop/src/App.vue
- frontend/desktop/src/api/interceptors.js
- frontend/desktop/src/components/common/modal/ErrorCode405.vue
- frontend/desktop/src/components/common/modal/ErrorCode406.vue
- frontend/desktop/src/components/common/modal/PermissionModal.vue
- frontend/desktop/src/components/layout/permissionApply.vue
- frontend/desktop/src/config/login.js
- frontend/desktop/src/config/setting.js
- frontend/desktop/src/pages/appmaker/AppCard.vue
- frontend/desktop/src/pages/home/CommonlyUsed.vue
- frontend/desktop/src/utils/isCrossOriginIFrame.js
- frontend/desktop/src/utils/openOtherApp.js
- 优化项
- 页面被嵌入iframe处理跳转app和小窗登录逻辑优化
> improvment:页面被嵌入iframe处理跳转app和小窗登录逻辑优化

- pipeline_plugins/components/collections/sites/open/job.py
> minor: JOB 插件获取作业全局变量时增加日志

- gcloud/contrib/collection/models.py
- gcloud/contrib/collection/resources.py
- gcloud/core/project.py
- gcloud/core/resources.py
- gcloud/iam_auth/utils.py
- gcloud/taskflow3/resources.py
- 新功能
- 收藏列表接口添加用户关于收藏实例的操作权限信息
> feature: 收藏列表接口添加用户关于收藏实例的操作权限信息

- pipeline_plugins/components/collections/sites/open/nodeman/__init__.py
- bug fix
- 修复节点管理插件升级时没有兼容旧插件路径的问题
> bugfix: 修复节点管理插件升级时没有兼容旧插件路径的问题

- .pre-commit-config.yaml
- gcloud/commons/template/models.py
- gcloud/commons/template/resources.py
- gcloud/contrib/appmaker/models.py
- gcloud/contrib/function/models.py
- gcloud/contrib/function/resources.py
- gcloud/core/resources.py
- gcloud/iam_auth/resource_helpers/base.py
- gcloud/iam_auth/resource_helpers/flow.py
- gcloud/iam_auth/resource_helpers/mini_app.py
- gcloud/iam_auth/resource_helpers/periodic_task.py
- gcloud/iam_auth/resource_helpers/task.py
- gcloud/iam_auth/utils.py
- gcloud/iam_auth/view_interceptors/apigw/create_periodic_task.py
- gcloud/iam_auth/view_interceptors/apigw/create_task.py
- gcloud/iam_auth/view_interceptors/apigw/fast_create_task.py
- gcloud/iam_auth/view_interceptors/apigw/flow_view.py
- gcloud/iam_auth/view_interceptors/apigw/get_common_template_info.py
- gcloud/iam_auth/view_interceptors/apigw/get_template_info.py
- gcloud/iam_auth/view_interceptors/apigw/periodic_task_edit.py
- gcloud/iam_auth/view_interceptors/apigw/project_view.py
- gcloud/iam_auth/view_interceptors/apigw/task_operate.py
- gcloud/iam_auth/view_interceptors/apigw/task_view.py
- gcloud/periodictask/models.py
- gcloud/periodictask/resources.py
- gcloud/taskflow3/models.py
- gcloud/taskflow3/resources.py
- gcloud/tasktmpl3/resources.py
- pyproject.toml
> 权限中心 V3 联调问题修复

- gcloud/iam_auth/authorization_helpers/common_flow.py
- gcloud/iam_auth/authorization_helpers/flow.py
- gcloud/iam_auth/authorization_helpers/function_task.py
- gcloud/iam_auth/authorization_helpers/mini_app.py
- gcloud/iam_auth/authorization_helpers/periodic_task.py
- gcloud/iam_auth/authorization_helpers/task.py
- bug fix
- authorization helper 返回的 iam 资源实例增加相关属性
> bugfix: authorization helper 返回的 iam 资源实例增加相关属性

- gcloud/contrib/appmaker/models.py
- gcloud/iam_auth/view_interceptors/apigw/create_periodic_task.py
- gcloud/iam_auth/view_interceptors/apigw/create_task.py
- gcloud/iam_auth/view_interceptors/apigw/flow_view.py
- gcloud/iam_auth/view_interceptors/apigw/get_periodic_task_info.py
- gcloud/iam_auth/view_interceptors/apigw/get_template_info.py
- gcloud/iam_auth/view_interceptors/apigw/periodic_task_edit.py
- gcloud/iam_auth/view_interceptors/apigw/task_operate.py
- gcloud/iam_auth/view_interceptors/apigw/task_view.py
- gcloud/periodictask/resources.py
- gcloud/taskflow3/resources.py
- gcloud/tasktmpl3/resources.py
- bug fix
- 修复调用 shortcuts 鉴权时资源实例没有 path 属性的问题
> bugfix: 修复调用 shortcuts 鉴权时资源实例没有 path 属性的问题

- frontend/desktop/src/App.vue
- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
- frontend/desktop/src/pages/admin/manage/AdminSearch/index.vue
- frontend/desktop/src/pages/admin/manage/SourceEdit/CacheEdit.vue
- frontend/desktop/src/pages/admin/manage/SourceEdit/index.vue
- frontend/desktop/src/pages/admin/manage/SourceManage/index.vue
- frontend/desktop/src/pages/admin/manage/SourceSync/index.vue
- frontend/desktop/src/pages/admin/manage/index.vue
- frontend/desktop/src/pages/admin/statistics/index.vue
- frontend/desktop/src/pages/audit/AuditList.vue
- frontend/desktop/src/pages/audit/index.vue
- frontend/desktop/src/pages/functor/FunctionList.vue
- frontend/desktop/src/pages/functor/index.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/task/TaskCreate/index.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- frontend/desktop/src/pages/task/TaskExecute/index.vue
- frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
- frontend/desktop/src/pages/task/TaskList/index.vue
- frontend/desktop/src/store/index.js
- frontend/desktop/src/store/modules/task.js
- 优化项
- 管理员入口页面权限控制
- 职能化、审计权限判断优化
- 职能化认领接口去掉qs.stringify
> improvement:管理员入口页面权限控制，职能化、审计权限判断优化，职能化认领接口去掉qs.stringify

- config/default.py
- iam/api/http.py
- iam/contrib/iam_migration/migrator.py
- iam/contrib/iam_migration/utils/do_migrate.py
- iam/iam.py
> minor: iam sdk upgrade

- gcloud/iam_auth/view_interceptors/apigw/create_periodic_task.py
- gcloud/iam_auth/view_interceptors/apigw/create_task.py
- gcloud/iam_auth/view_interceptors/apigw/fast_create_task.py
- gcloud/iam_auth/view_interceptors/apigw/flow_view.py
- gcloud/iam_auth/view_interceptors/apigw/get_common_template_info.py
- gcloud/iam_auth/view_interceptors/apigw/get_periodic_task_info.py
- gcloud/iam_auth/view_interceptors/apigw/periodic_task_edit.py
- gcloud/iam_auth/view_interceptors/apigw/project_view.py
- gcloud/iam_auth/view_interceptors/apigw/task_operate.py
- gcloud/iam_auth/view_interceptors/apigw/task_view.py
> bugfix: apigw 鉴权拦截器问题修复

- pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py
- pipeline_plugins/components/query/sites/open/query.py
- pipeline_plugins/components/static/components/atoms/sites/open/nodeman/create_task/v2_0.js
- pipeline_plugins/tests/components/collections/sites/open/nodeman_test/create_task_test/test_nodeman_v2_create_task.py
- static/components/atoms/sites/open/nodeman/create_task/v2_0.js
- 新功能
- xxx
- 优化项
- xxx
- bug fix
- xxx
> minor:节点管理2.0插件优化

- frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- bug fix
- 公共流程导出取common_flow_view权限
> bugfix:公共流程导出取common_flow_view权限

- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- 新功能
- datatable支持配置操作列是否显示编辑按钮
> feature: datatable支持配置操作列是否显示编辑按钮

- pipeline_plugins/components/collections/sites/open/cc/create_module/legacy.py
- pipeline_plugins/components/query/sites/open/query.py
- pipeline_plugins/components/static/components/atoms/cc/create_module/legacy.js
- pipeline_plugins/tests/components/collections/sites/open/cc_test/create_module/test_legacy.py
- static/components/atoms/cc/create_module/legacy.js
- 新功能
- 新增api接口 获取指定biz_cc_id模板类型拓扑
- 优化项
- 表单校验，后台空模块信息校验
- bug fix
- 任务执行前后执行表单信息不对应，添加表单为空校验
closed #2161
> bugfix: CMDB创建模块缺陷修复

- gcloud/apigw/views/import_common_template.py
- gcloud/commons/template/models.py
- gcloud/core/middlewares.py
- gcloud/periodictask/models.py
- gcloud/taskflow3/models.py
- gcloud/taskflow3/resources.py
- gcloud/tasktmpl3/models.py
- gcloud/tests/apigw/views/test_import_common_template.py
> bugfix: apigw api 测试问题修复

- gcloud/commons/template/models.py
- bug fix
- 修复删除流程时检测关联轻应用未过滤已删除轻应用的问题
> bugfix: 修复删除流程时检测关联轻应用未过滤已删除轻应用的问题

- gcloud/commons/template/models.py
- gcloud/contrib/collection/resources.py
- gcloud/iam_auth/res_factory.py
- gcloud/iam_auth/view_interceptors/common_template.py
- gcloud/taskflow3/validators.py
- support-files/iam/initial.json
- bug fix
- 修复公共流程导入导出权限拦截器的问题
> bugfix: 修复公共流程导入导出权限拦截器的问题

- pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py
> bugfix: 节点管理参数值名称更新

- config/default.py
- config/prod.py
- config/stag.py
- bug fix
- 修复获取 APP_HOST 时机不正确的问题
> bugfix: 修复获取 APP_HOST 时机不正确的问题

- frontend/desktop/src/components/common/RenderForm/tags/TagCascader.vue
- bug fix
-tagCascaser组件lazyLoad方法大小写拼写问题修复
> bugfix：tagCascaser组件lazyLoad方法大小写拼写问题修复

- gcloud/contrib/function/resources.py
- gcloud/iam_auth/res_factory.py
- gcloud/iam_auth/resource_helpers/function_task.py
- bug fix
- 修复 function_task_helper 返回实例时没有 type 属性的问题
> bugfix: 修复 function_task_helper 返回实例时没有 type 属性的问题

- pipeline_plugins/components/collections/sites/open/cc/update_module/v1_0.py
> minor: 国际化，报错信息修改

- gcloud/iam_auth/res_factory.py
- gcloud/iam_auth/resource_api/flow.py
- gcloud/iam_auth/resource_api/mini_app.py
- gcloud/iam_auth/resource_api/periodic_task.py
- gcloud/iam_auth/resource_api/task.py
- iam/contrib/converter/queryset.py
- 优化项
- iam path protocol modify
> iam path protocol modify

- pipeline/core/data/expression.py
- pipeline/core/data/sandbox.py
- pipeline/tests/core/data/test_expression.py
- pipeline/tests/core/data/test_sandbox.py
- 新功能
- 变量引擎渲染内置函数时返回原字符串 
close #2157
> 变量引擎渲染内置函数时返回原字符串 #2157

- config/default.py
- docs/develop/dev_plugins.md
- docs/features/plugin_usage.md
- pipeline/utils/register.py
- readme.md
- readme_en.md
- 新功能
- 标准插件支持自动加载模块子路径下的所有插件 
close #2178
> feature: 标准插件支持自动加载模块子路径下的所有插件 #2178

- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- bug fix
- 旧版本任务节点点击树查看参数未兼容legacy修复
> bugfix:旧版本任务节点点击树查看参数未兼容legacy修复

- pipeline_web/wrapper.py
> bugfix: 修复子流程参数无法传入的问题

- .pre-commit-config.yaml
- pyproject.toml
- 优化项
- add pre-commit relate config
> minor: add pre-commit relate config

- pipeline_plugins/variables/query/__init__.py
- pipeline_plugins/variables/query/sites/__init__.py
- pipeline_plugins/variables/query/sites/open/__init__.py
- pipeline_plugins/variables/query/sites/open/query.py
- pipeline_plugins/variables/query/sites/open/select.py
- 优化项
- pipeline_plugins/variables 路由结构优化
> refactor: pipeline_plugins/variables 路由结构优化

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
- frontend/desktop/src/store/index.js
> improvement:流程模板通知方式改为由接口动态获取

- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
- 优化项
- 全局变量编辑标准插件表单能监听最外层表单事件
> imporvement：全局变量编辑标准插件表单能监听最外层表单事件

- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
- bug fix
- 修复combine类型插件value字段缺失，表单值不能回填的问题
> bugfix:修复combine类型插件value字段缺失，表单值不能回填的问题

- app.yml
- config/default.py
- docs/release.md
- readme.md
- readme_en.md
> minor: 版本号升级到 3.5.1302

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- 优化项
- 流程编辑子流程节点查看子流程
- 选择插件/子流程默认展开已选分组或第一组
> improvement:流程编辑子流程节点查看子流程；选择插件/子流程默认展开已选分组或第一组

- requirements.txt
> minor: MarkupSafe升级到1.1.1

- gcloud/iam_auth/res_factory.py
- gcloud/iam_auth/resource_api/flow.py
- gcloud/iam_auth/resource_api/mini_app.py
- gcloud/iam_auth/resource_api/periodic_task.py
- gcloud/iam_auth/resource_api/task.py
- iam/contrib/converter/queryset.py
- iam/contrib/converter/sql.py
- iam/eval/constants.py
- iam/eval/expression.py
> minor: iam_path 协议调整

- gcloud/contrib/admin/urls.py
- gcloud/contrib/admin/views/__init__.py
- gcloud/contrib/admin/views/command.py
- gcloud/contrib/admin/views/templates.py
- pipeline/celery/settings.py
- pipeline/core/flow/activity/service_activity.py
- bug fix
- 修复 pipeline 升级 2.4.1 时引入的问题
> bugfix: 修复 pipeline 升级时引入的问题

- gcloud/contrib/admin/views/templates.py
> minor: 模板通知方式刷新接口优化

- gcloud/contrib/admin/views/templates.py
- bug fix
- 修复 refresh_template_notify_type 的问题
> bugfix: 修复 refresh_template_notify_type 的问题

- docs/features/redis_usage.md
- readme.md
> minor: 添加 redis 各部署模式配置说明

- gcloud/core/templates/core/base_vue.html
> minor: 修改页面 title

- pipeline_plugins/components/collections/common.py
- pipeline_plugins/components/collections/http/v1_0.py
- pipeline_plugins/tests/components/collections/http_test/test_v1_0.py
- 优化项
- 修改 http-插件 最大超时时间为 30s
> minor: 修改 http-插件 最大超时时间为 30s

- gcloud/core/utils/sites/open/utils.py
- bug fix
- 修复部分场景没有使用环境变量中设置的开发商账号的问题
> bugfix: 修复部分场景没有使用环境变量中设置的开发商账号的问题

- pipeline/apps.py
- 优化项
- 增加 python 解释器允许的最大递归数上线
> optimization: 增加 python 解释器允许的最大递归数上限

- pipeline_plugins/tests/plugin_path/__init__.py
- pipeline_plugins/tests/plugin_path/test_import_path.py
> minor: 添加插件导入路径测试用例

- dev_log/dev/v_xugzhou_202007061531.yaml
- frontend/desktop/src/components/layout/ProjectSelector.vue
- 优化项
- "项目选择下拉 name 修改为 [id] + name"
- "返回的项目如果 from_cmdb 的值为 true，展示的时候名字前的 id 取 project.bk_biz_id"
- "返回的项目如果 from_cmdb 的值为 false，展示的时候名字前的 id 取 project.id"
> improve：项目选择下拉 name 修改为 [id] + name（V3.5.X）

- pipeline_plugins/tests/plugin_path/test_import_path.py
- 优化项
- 插件导入路径测试读取 open_ver 适配不同版本
> minor: test_import_path fix

- packages/blueking/component/apis/nodeman.py
- pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py
- pipeline_plugins/components/query/sites/open/query.py
> minor: 节点管理 API NAME 规范化

- pipeline_plugins/tests/plugin_path/__init__.py
- pipeline_plugins/tests/plugin_path/test_import_path.py
> minor: 添加插件导入路径测试用例（V3.6.X）

- auth_backend/plugins/tastypie/resources.py
- 优化项
- 优化 BkSaaSLabeledDataResourceMixin 的实现
> optimization: 优化 BkSaaSLabeledDataResourceMixin 的实现

- auth_backend/plugins/tastypie/authorization.py
- auth_backend/plugins/tastypie/inspect.py
- auth_backend/plugins/tastypie/resources.py
- gcloud/contrib/function/resources.py
- 优化项
- 优化单个资源实例鉴权的性能
- bug fix
- 修复优化后拉取职能化列表时 500 的问题
> Optimization v3.5.x list auth actions

- gcloud/contrib/function/resources.py
- bug fix
- 修复职能化任务 detail 读取错误的问题
> bugfix: 修复职能化任务 detail 读取错误的问题

- requirements.txt
> minor: 升级 Django 版本

- config/default.py
- gcloud/webservice3/resources.py
- pipeline/core/constants.py
- pipeline_web/plugin_management/__init__.py
- pipeline_web/plugin_management/admin.py
- pipeline_web/plugin_management/apps.py
- pipeline_web/plugin_management/migrations/0001_initial.py
- pipeline_web/plugin_management/migrations/__init__.py
- pipeline_web/plugin_management/models.py
- pipeline_web/plugin_management/tests/__init__.py
- pipeline_web/plugin_management/tests/models/__init__.py
- pipeline_web/plugin_management/tests/models/test_deprecated_plugins.py
- pipeline_web/plugin_management/tests/utils/__init__.py
- pipeline_web/plugin_management/tests/utils/test_find_deprecated_plugins_in_spread_tree.py
- pipeline_web/plugin_management/tests/utils/test_find_deprecated_plugins_in_unfold_tree.py
- pipeline_web/plugin_management/utils.py
> feature: 添加插件生命周期管理功能

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
- bug fix
- 兼容流程模板全局变量不存在version字段时勾选参数复用的情况
> bugfix:兼容流程模板全局变量不存在version字段时勾选参数复用的情况(V3.6.X)

- gcloud/contrib/function/resources.py
- bug fix
- 修复职能化任务无权限时详情查看报错的问题
> bugfix: 修复职能化任务无权限时详情查看报错的问题

- gcloud/iam_auth/view_interceptors/template.py
- bug fix
- 修复 form 接口 500 的问题
> bugfix: 修复 form 接口 500 的问题

- config/default.py
- pipeline_plugins/components/utils/sites/open/utils.py
> optimization: JOB 任务链接生成适配 V2 V3

- config/default.py
- pipeline_plugins/components/utils/sites/open/utils.py
* optimization: JOB 任务链接生成适配 V2 V3
> optimization: JOB 任务链接生成适配 V2 V3 (#2315)

- config/default.py
- pipeline_plugins/components/utils/sites/open/utils.py
- support-files/iam/02_add_action_group.json
> JOB 任务链接生成适配 V2 V3

- gcloud/core/context_processors.py
- gcloud/core/templates/core/base_vue.html
- 优化项
- window 中添加 BK_IAM_APP_CODE
> minor: window 中添加 BK_IAM_APP_CODE

- dev_log/dev/v_xugzhou_202007140856.yaml
- frontend/desktop/src/pages/project/index.vue
> improvement:项目列表添加 CMDB ID 展示

- frontend/desktop/src/pages/template/TemplateEdit/index.vue
> minor: 去掉调试语句

- dev_log/dev/v_xugzhou_202007140856.yaml
- frontend/desktop/src/pages/project/index.vue
> improvement:项目列表添加 CMDB ID 展示(V3.6.X_develop)

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- 优化项
- 任务执行异常信息嵌入pre标签时支持字符超出文档宽度换行
> improvment:任务执行异常信息嵌入pre标签时支持字符超出文档宽度换行(V3.6.X)

- frontend/desktop/src/components/common/RenderForm/IpSelector/ConditionItem.vue
- frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue
- frontend/desktop/src/components/common/RenderForm/IpSelector/IpSearchInput.vue
- frontend/desktop/src/components/common/RenderForm/IpSelector/SelectCondition.vue
- frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
- frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
- frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
- frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
- frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabLocalDraft.vue
- 新功能
- 静态ip增加手动输入添加方式
- 动态拓扑增加已选节点展示交互
- 优化项
- 筛选条件和排除条件交互整合
> feature: ip选择器优化(V3.6.X)

- auth_backend/backends/dummy.py
- auth_backend/tests/backends/test_dummy.py
- bug fix
- 修复 dummy auth backend 使用报错的问题
> bugfix: 修复 dummy auth backend 使用报错的问题

- dev_log/dev/homholueng_202007171044.yaml
- gcloud/iam_auth/resource_api/common_flow.py
- gcloud/iam_auth/resource_api/flow.py
- gcloud/iam_auth/resource_api/mini_app.py
- gcloud/iam_auth/resource_api/periodic_task.py
- gcloud/iam_auth/resource_api/project.py
- gcloud/iam_auth/resource_api/task.py
- iam/contrib/django/dispatcher/dispatchers.py
- iam/resource/provider.py
- bug fix
- 修复 IAM 调用 fetch_instance_info 接口失败的问题
> bugfix: 修复 IAM 调用 fetch_instance_info 接口失败的问题

- pipeline_plugins/components/collections/controller.py
- bug fix
- bk-timer修改bk_timing和force_check获取方式
> bugfix:bk-timer修改bk_timing和force_check获取方式(V3.5.X)

- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- frontend/desktop/src/utils/atomFilter.js
- bug fix
- tagCodeEditor编辑值未保存修复
> bugfix: tagCodeEditor编辑值未保存修复

- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
- frontend/desktop/src/utils/atomFilter.js
- bug fix
- tagCodeEditor编辑值未保存修复
> bugfix: tagCodeEditor编辑值未保存修复(V3.6.X)

- .gitignore
- scripts/extract_version_log.py
> minor: 添加版本日志提取脚本

- dev_log/dev/normal-wls_202007171058.yaml
- pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
- static/components/atoms/job/job_fast_execute_script.js
- 优化项
-【JOB-快速执行脚本】插件脚本输入框替换为代码编辑器
> improve:【JOB-快速执行脚本】插件脚本输入框替换为代码编辑器(3.6.X_dev)

- dev_log/dev/normal-wls_202007171058.yaml
- pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
- static/components/atoms/job/job_fast_execute_script.js
- 优化项
- job快速执行脚本插件脚本内容使用code_editor tag
> improve: job快速执行脚本插件脚本内容使用code_editor tag（V3.5.X_dev）

- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- bug fix
-renderform并发更新表单参数值丢失问题修复
> bugfix:renderform并发更新表单参数值丢失问题修复(V3.6.X)

- gcloud/core/api_adapter/__init__.py
- gcloud/core/project.py
- 优化项
- 移除根据 cmdb 业务 location 停用项目逻辑
> minor: 移除根据 cmdb 业务 location 停用项目逻辑（V3.6.X_dev）

- pipeline_plugins/base/utils/adapter.py
- pipeline_plugins/cmdb_ip_picker/query.py
- pipeline_plugins/cmdb_ip_picker/utils.py
- pipeline_plugins/components/utils/sites/open/utils.py
- pipeline_plugins/variables/collections/sites/open/cc.py
- 优化项
- 关键路径中 cmdb 主机属性获取采用保守方式
> optimization: 关键路径中 cmdb 主机属性获取采用保守方式

- frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
- frontend/desktop/src/pages/template/TemplateList/index.vue
- frontend/desktop/src/pages/template/common/CommonTemplateList.vue
- frontend/desktop/src/routers/index.js
> improvement: 流程模板编辑点击返回能记住列表页对应页码(V3.6.X)

- dev_log/dev/normal-wls_202007211710.yaml
- gcloud/taskflow3/models.py
- 新功能
- 未执行节点支持node/detail接口状态查询
> feature:未执行节点支持node/detail接口状态查询

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
> repair: 修复node/detail接口前端报错问题

- gcloud/core/api.py
- 优化项
- get_basic_info api 标准化
> minor: get_basic_info api 标准化

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
> minor:子流程节点参数详情接口字段格式修改

- gcloud/contrib/admin/views/command.py
- gcloud/core/tasks.py
- 优化项
- 优化 redis 数据迁移方式，切换为异步任务迁移
> optimization: 优化 redis 数据迁移方式，切换为异步任务迁移

- dev_log/dev/v_xugzhou_202007271630.yaml
- frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
- frontend/desktop/src/pages/task/TaskExecute/ModifyTime.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- 优化项
- 任务全局变量修改保存按钮添加 loading 状态
> improve: 任务全局变量修改保存按钮添加 loading 状态

- dev_log/dev/v_xugzhou_202007271630.yaml
- frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
- frontend/desktop/src/pages/task/TaskExecute/ModifyTime.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- 优化项
- 任务全局变量修改保存按钮添加 loading 状态
> develop: 任务全局变量修改保存按钮添加 loading 状态

- pipeline_plugins/components/collections/sites/open/cc/create_set_by_template/__init__.py
- pipeline_plugins/components/collections/sites/open/cc/create_set_by_template/v1_0.py
- static/components/atoms/cc/create_set_by_template/v1_0.js
- bug fix
- 修复根据模板创建集群插件表单不存在的问题
> bugfix: 修复根据模板创建集群插件表单不存在的问题

- pipeline_plugins/components/collections/sites/open/cc/create_set_by_template/__init__.py
- pipeline_plugins/components/collections/sites/open/cc/create_set_by_template/v1_0.py
- static/components/atoms/cc/create_set_by_template/v1_0.js
- bug fix
- 修复根据模板创建集群插件表单不存在的问题
> Bugfix v3.6.x create set by template form

- dev_log/dev/homholueng_202008031045.yaml
- docs/features/redis_usage.md
- gcloud/core/apps.py
- pipeline/apps.py
- pipeline/tests/test_apps.py
- readme.md
- 优化项
- redis sentinel 模式支持配置 redis sentinel 独立密码
> optimization: redis sentinel 模式支持配置 redis sentinel 独立密码

- dev_log/dev/v_xugzhou_202007271702.yaml
- frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
- 优化项
- job快速执行脚本组件script前端语言与job平台提供语言兼容
> improve: 添加改变脚本类型语言的方法

- pipeline_plugins/components/collections/sites/open/cc/batch_delete_set/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/create_set/v2_0.py
- pipeline_plugins/components/collections/sites/open/cc/create_set_by_template/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/empty_set_hosts/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/update_module/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/update_set/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/update_set_service_status/v1_0.py
> improvement: cc系列插件填参方式统一使用枚举类（V3.5.X）

- pipeline_plugins/components/collections/sites/open/cc/batch_delete_set/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/create_set/v2_0.py
- pipeline_plugins/components/collections/sites/open/cc/create_set_by_template/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/empty_set_hosts/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/update_module/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/update_set/v1_0.py
- pipeline_plugins/components/collections/sites/open/cc/update_set_service_status/v1_0.py
> improvement: cc系列插件填参方式统一使用枚举类（sync V3.6.X_develop）

- dev_log/dev/normal-wls_202007211710.yaml
- gcloud/taskflow3/models.py
- 新功能
- 未执行节点支持node/detail接口状态查询
> feature: 未执行节点支持node/detail接口状态查询 (sync 3.6.x dev)

- dev_log/dev/fannluo_202007311524.yaml
- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- 新功能
- tagSelect增加支持输入框创建选项配置
> feature: tagSelect增加支持输入框创建选项配置

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- 新功能
- tagSelect增加支持输入框创建选项配置
> feature: tagSelect增加支持输入框创建选项配置(V3.6.X)

- dev_log/dev/homholueng_202008061236.yaml
- gcloud/iam_auth/resource_api/common_flow.py
- gcloud/iam_auth/resource_api/flow.py
- gcloud/iam_auth/resource_api/mini_app.py
- gcloud/iam_auth/resource_api/task.py
- bug fix
- 修复 list_instance api 会返回已删除数据的实例的问题
> bugfix: 修复 list_instance api 会返回已删除数据的实例的问题

- gcloud/tasktmpl3/models.py
> minor: 导入流程时支持从导入数据中读取模板覆盖设定（V3.5.X_dev）

- gcloud/tasktmpl3/models.py
> 导入流程时支持从导入数据中读取模板覆盖设定（V3.6.X_dev）

- frontend/desktop/src/components/layout/Navigator.vue
- bug fix
- 项目流程列表选择页码后点击导航页面需要清空
> bugfix:项目流程列表选择页码后点击导航页面需要清空(V3.5.X)

- config/sites/enterprise/__init__.py
- config/sites/enterprise/ver_settings.py
- gcloud/conf/sites/enterprise/__init__.py
- gcloud/conf/sites/enterprise/ver_settings.py
> minor: add enterprise version files

- config/sites/enterprise/__init__.py
- config/sites/enterprise/ver_settings.py
- gcloud/conf/sites/enterprise/__init__.py
- gcloud/conf/sites/enterprise/ver_settings.py
> V3.6.x ee sync

- config/sites/enterprise/__init__.py
- config/sites/enterprise/ver_settings.py
- gcloud/conf/sites/enterprise/__init__.py
- gcloud/conf/sites/enterprise/ver_settings.py
> V3.5.x ee sync

- gcloud/iam_auth/conf.py
- 新功能
- iam meta 接口 resource 字段增加 parent_id
> feature: iam meta 接口 resource 字段增加 parent_id

- dev_log/dev/fannluo_202008111924.yaml
- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagDatetime.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagTime.vue
- frontend/desktop/src/utils/atomFilter.js
- 新功能
- 日期选择器支持配置显示类型
- 新增 tagTime 组件
>  feature:日期选择器支持配置显示类型，新增 tagTime 组件

- frontend/desktop/builds/mock/config/index.js
- frontend/desktop/src/App.vue
- frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
- frontend/desktop/src/components/common/modal/PermissionModal.vue
- frontend/desktop/src/components/layout/permissionApply.vue
- frontend/desktop/src/mixins/permission.js
- frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
- frontend/desktop/src/pages/appmaker/AppCard.vue
- frontend/desktop/src/pages/appmaker/AppEditDialog.vue
- frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
- frontend/desktop/src/pages/audit/AuditList.vue
- frontend/desktop/src/pages/functor/FunctionList.vue
- frontend/desktop/src/pages/home/AddCollectionDialog.vue
- frontend/desktop/src/pages/home/MyCollection.vue
- frontend/desktop/src/pages/home/MyDynamic.vue
- frontend/desktop/src/pages/task/PeriodicList/index.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
- frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
- frontend/desktop/src/pages/task/TaskList/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
- frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
- frontend/desktop/src/pages/template/TemplateList/index.vue
- frontend/desktop/src/pages/template/common/CommonTemplateList.vue
> improvement:申请权限中心跳转链接请求参数字段格式修改（V3.6.X）

- gcloud/contrib/admin/views/taskflow.py
- 优化项
- 优化 admin taskflow detail 返回的 TaskContext 的格式
> optimization: 优化 admin taskflow detail 返回的 TaskContext 的格式

- gcloud/contrib/admin/views/taskflow.py
- 优化项
- 优化 admin taskflow detail 返回的 TaskContext 的格式
> optimization: 优化 admin taskflow detail 返回的 TaskContext 的格式（V3.5.X_dev）

- frontend/desktop/src/components/common/TemplateCanvas/index.vue
> improvement:画布查看状态不显示任务节点端点(V3.6.X)

- dev_log/dev/fannluo_202008101036.yaml
- frontend/desktop/src/pages/task/ParameterInfo.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- 优化项
- 任务节点有输出参数时节点不可选，preview_task_tree接口报错时不可创建任务
> improvement:任务节点有输出参数时节点不可选，preview_task_tree接口报错时不可创建任务（V3.5.X）

- frontend/desktop/src/components/common/TemplateCanvas/index.vue
> feature:画布导出图片功能(V3.6.X)

- frontend/desktop/src/pages/task/ParameterInfo.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- 优化项
- 任务节点有输出参数时节点不可选，preview_task_tree接口报错时不可创建任务
> improvement:任务节点有输出参数时节点不可选，preview_task_tree接口报错时不可创建任务（V3.6.X）

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- frontend/desktop/src/pages/task/TaskExecute/ModifyTime.vue
- frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
- frontend/desktop/src/pages/task/TaskParamEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- frontend/desktop/src/store/modules/atomForm.js
> improvement:业务下的插件配置项请求带上业务参数(V3.5.X)

- frontend/desktop/src/store/modules/template.js
- bug fix
- 任务节点删除后勾选为输出的变量未清空问题修复
> bugfix:任务节点删除后勾选为输出的变量未清空问题修复(V3.6.X)

- frontend/desktop/src/components/common/TemplateCanvas/index.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
> merge 3.5.X frontend to develop

- frontend/desktop/package.json
> minor: 前端增加依赖包dom-to-image

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagDatetime.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagTime.vue
- frontend/desktop/src/utils/atomFilter.js
- 新功能
- 日期选择器支持配置显示类型
- 新增 tagTime 组件
> feature:日期选择器支持配置显示类型，新增 tagTime 组件(V3.6.X)

- dev_log/dev/fannluo_202008132114.yaml
- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- 优化项
- tagselect增加是否显示清除表单值icon
> improvement: tagselect增加是否显示清除表单值icon(V3.5.X)

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- 优化项
- tagselect增加是否显示清除表单值icon
> improvement: tagselect增加是否显示清除表单值icon(V3.6.X)

- dev_log/dev/normal-wls_202008112107.yaml
- pipeline_plugins/variables/query/sites/open/select.py
- 优化项
- 开发者对于下拉框远程数据源可配置自定义转换函数
> improvement:开发者对于下拉框远程数据源可配置自定义转换函数（3.5.x_dev）

- dev_log/dev/normal-wls_202008112107.yaml
- pipeline_plugins/variables/query/sites/open/select.py
- 优化项
- 开发者对于下拉框远程数据源可配置自定义转换函数
> improvement:开发者对于下拉框远程数据源可配置自定义转换函数（3.6.x_dev）

- frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
- frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
- frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
- frontend/desktop/src/pages/task/TaskParamEdit.vue
- bug fix
- 流程模板引用隐藏的元变量创建任务时报错修复
- 未执行meta_transform修复
> bugfix:流程模板引用隐藏的元变量创建任务时报错和未执行meta_transform修复(V3.6.X)

- frontend/desktop/src/components/layout/Navigator.vue
- bug fix
- 项目流程列表选择页码后点击导航页面需要清空
> bugfix:项目流程列表选择页码后点击导航页面需要清空(V3.6.X)

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- frontend/desktop/src/pages/task/TaskExecute/ModifyTime.vue
- frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
- frontend/desktop/src/pages/task/TaskParamEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
- frontend/desktop/src/store/modules/atomForm.js
> improvement:业务下的插件配置项请求带上业务参数(V3.6.X)

- config/default.py
- dev_log/dev/homholueng_202008171542.yaml
- pipeline/conf/default_settings.py
- pipeline/core/data/sandbox.py
- pipeline/tests/core/data/test_expression.py
- pipeline/tests/core/data/test_sandbox.py
- 新功能
- mako 模板渲染上下文支持配置屏蔽关键字及导入模块
> feature: mako 模板渲染上下文支持配置屏蔽关键字及导入模块（V3.5.X_dev）

- config/default.py
- dev_log/dev/homholueng_202008171542.yaml
- pipeline/conf/default_settings.py
- pipeline/core/data/sandbox.py
- pipeline/tests/core/data/test_expression.py
- pipeline/tests/core/data/test_sandbox.py
- 新功能
- mako 模板渲染上下文支持配置屏蔽关键字及导入模块
> feature: mako 模板渲染上下文支持配置屏蔽关键字及导入模块（V3.6.X_dev）

- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
- bug fix
-  修改版本日志图标大小
-  节点日志换行
-  修改点击查看详情报错和默认选中第一个
> bugfix:  V3.6.X_dev 自检问题修复（V3.6.X_develop)

- frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
- frontend/desktop/src/pages/task/TaskExecute/ModifyTime.vue
- frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
- frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
- frontend/desktop/src/scss/iconfont.scss
- 优化项
- "修改节点树父节点不添加选中态 任务节点添加选中态"
-"点击未执行节点打开任务详情面板"
-"修改参数面板添加关闭按钮 修改按钮位置"
-"修改插件开发字体图标"
> improve：任务执行页面节点树查看参数问题V3.6.X_develop

- frontend/desktop/package.json
> minor:magicbox组件升级(V3.6.X)

- config/default.py
> optimization: 添加引擎内部数据自动过期设置

- gcloud/webservice3/resources.py
- gcloud/webservice3/urls.py
> optimization: 添加用户有查看权限的项目获取接口

- gcloud/webservice3/resources.py
- 优化项
- user project 列表接口增加权限 meta 数据
> minor: user project 列表接口增加权限 meta 数据

- pipeline/models.py
- bug fix
- 修复Snapshot md5sum修改bug
> bugfix: 修复Snapshot md5sum修改bug(3.6.x_dev)

- pipeline_plugins/variables/collections/common.py
> minor: 优化字符串分隔

- static/variables/date.js
- static/variables/time.js
- 优化项
- 将 日期 和 时间 两个变量的静态文件收集到 static/variables/ 下面.
> minor: 将 日期 和 时间 两个变量的静态文件收集到 static/variables/ 下面.

- support-files/supervisord.conf
- bug fix
- 修复划分队列后 supervisord 配置没更新的问题
> bugfix: 修复划分队列后 supervisord 配置没更新的问题

- frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
> improve: 修改任务按钮图标大小 (V3.6.X_dev)

- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- bug fix
- 修改forEach需求  .length问题
> improve: 修改forEach需求  .length问题

- config/default.py
- gcloud/contrib/admin/migration_api/__init__.py
- gcloud/contrib/admin/migration_api/app_maker.py
- gcloud/contrib/admin/migration_api/decorators.py
- 新功能
- add migrate api auth decorator
> feature: add migrate api auth decorator（V3.5.X_dev）

- config/default.py
- gcloud/contrib/admin/migration_api/__init__.py
- gcloud/contrib/admin/migration_api/app_maker.py
- gcloud/contrib/admin/migration_api/decorators.py
- 新功能
- add migrate api auth decorator
> feature: add migrate api auth decorator（V3.6.X_dev）

- dev_log/dev/fannluo_20200825.yaml
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- frontend/desktop/src/pages/appmaker/AppEditDialog.vue
- 优化项
- 表格内tagtextarea查看模式文本水平居中
- bug fix
- 轻应用编辑弹窗tooltip层级问题修复
> minor：测试问题处理(3.6.X)

- pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_module_selector.py
- pipeline_plugins/variables/collections/sites/open/cmdb/var_set_module_selector.py
- pipeline_plugins/variables/collections/sites/open/docs/cmdb/var_set_module_selector.md
- pipeline_plugins/variables/static/variables/cmdb/var_set_module_selector.js
- static/variables/cmdb/var_set_module_selector.js
- 新功能
-支持同一个集群下，选择多模块;
- 优化项
- 修复表单交互的缺陷问题.
> feature: 支持 同一个集群下，选择多模块；sprintfix: 修复表单交互的缺陷问题.

- dev_log/dev/v_xugzhou_202008261141.yaml
- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- 优化项
- 修改forEach需求  .length问题
> improve: 修改forEach需求  .length问题 ( v3.6.x )

- pipeline/models.py
- bug fix
- 修复Snapshot md5sum修改bug
> bugfix: 修复Snapshot md5sum修改bug（dev3.5.x）

- pipeline/engine/api.py
- bug fix
- 修复 mq 连接超时错误日志打印抛出异常的问题
> bugfix: mq connection_error handler log bug fix（V3.5.X_dev）

- config/default.py
- pipeline_plugins/components/utils/sites/open/utils.py
> minor: JOB 任务链接生成策略固定为 V3 版本

- dev_log/dev/normal-wls_202008181024.yaml
- docs/apidoc/en/get_task_status.md
- docs/apidoc/zh_hans/get_task_status.md
- gcloud/apigw/views/get_task_status.py
- pipeline/engine/api.py
- pipeline/tests/engine/test_api.py
- pipeline/tests/mock.py
- pipeline/tests/mock_settings.py
- 新功能
- API接口增强，get_task_status支持获取失败节点的异常数据
> feature: API接口增强，get_task_status支持获取失败节点的异常数据（3.6.x_dev）

- dev_log/dev/normal-wls_202008181024.yaml
- docs/apidoc/en/get_task_status.md
- docs/apidoc/zh_hans/get_task_status.md
- gcloud/apigw/views/get_task_status.py
- pipeline/engine/api.py
- pipeline/tests/engine/test_api.py
- pipeline/tests/mock.py
- pipeline/tests/mock_settings.py
- 新功能
- API接口增强，get_task_status支持获取失败节点的异常数据
> feature: API接口增强，get_task_status支持获取失败节点的异常数据（3.5.x_dev）

- frontend/desktop/package.json
> minor:magicbox组件升级(V3.5.X)

- dev_log/dev/fannluo_202008261715.yaml
- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagRadio.vue
> feature:tagDatatable支持表格分页展示(3.5.X_dev)

- dev_log/dev/fannluo_202008261715.yaml
- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagRadio.vue
> feature:tagDatatable支持表格分页展示(V3.6.X)

- pipeline_plugins/variables/static/variables/date.js
- static/variables/date.js
> bugfix: 修改 日期 变量 type 问题.

- frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
- frontend/desktop/src/pages/template/TemplateEdit/index.vue
> bugfix:分支条件编辑时光标跳转问题修复(V3.6.X_dev)

- gcloud/contrib/admin/migration_api/__init__.py
- gcloud/contrib/admin/migration_api/app_maker.py
- gcloud/contrib/admin/urls.py
> feature: 添加轻应用导入接口（V3.5.X_dev）

- gcloud/contrib/admin/migration_api/__init__.py
- gcloud/contrib/admin/migration_api/app_maker.py
- gcloud/contrib/admin/urls.py
> feature: 添加轻应用导入接口（V3.6.X_dev）

- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCascader.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagDatetime.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagTime.vue
- bug fix
- tag组件与magicbox内部zIndex层级管理问题修复
> bugfix: tag组件与magicbox内部zIndex层级管理问题修复(V3.5.X_dev)

- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
> imporvement:节点配置侧滑组件操作按钮固定在底部(V3.6.X_dev)

- dev_log/dev/fannluo_202008281612.yaml
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagCascader.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagDatetime.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagTime.vue
- bug fix
- tag组件与magicbox内部zIndex层级管理问题修复
> bugfix: tag组件与magicbox内部zIndex层级管理问题修复(V3.6.X)

- frontend/desktop/src/components/common/Individualization/MemberSelect.vue
> improvement:人员选择器查询接口host由变量传入(V3.6.X_dev)

- dev_log/dev/fannluo_202008272147.yaml
- frontend/desktop/src/components/common/Individualization/MemberSelect.vue
> improvement:人员选择器查询接口host由变量传入(V3.5.X)

- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
- frontend/desktop/src/components/common/RenderForm/tags/TagRadio.vue
> feature:tagDatatable支持表格数据分页展示(V3.5.X)

- frontend/desktop/src/pages/template/TemplateEdit/index.vue
> improve: 修改功能块和提示重叠问题 (V3.6.X_dev)

- config/default.py
- gcloud/core/context_processors.py
- gcloud/core/templates/core/base_vue.html
> feature：提供人员选择器查询接口host变量值 (3.5.X)

- frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
- frontend/desktop/src/store/modules/atomForm.js
- 优化项
- 公共流程模板编辑页面，请求类型变量列表不需要带 project_id
> improve: 公共流程模板编辑页面，请求类型变量列表不需要带 project_id (V3.6.X_dev)

- pipeline/engine/models/fields.py
- pipeline/engine/models/nr_pickle.py
- bug fix
- IOField 支持序列化节点数更多的流程
> bugfix: IOField 支持序列化节点数更多的流程（V3.5.X_dev）

- pipeline/engine/models/fields.py
- pipeline/engine/models/nr_pickle.py
- bug fix
-  IOField 支持序列化节点数更多的流程
> bugfix: IOField 支持序列化节点数更多的流程（V3.6.X_dev）

- frontend/desktop/src/App.vue
> improvement:项目详情加载时页面loading优化

- frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
> minor:去掉插件生命周期调试数据(V3.5.X_release)

- config/dev.py
- config/prod.py
- config/stag.py
- pipeline/core/data/expression.py
- pipeline/engine/core/context.py
- pipeline/engine/core/runtime.py
- pipeline/engine/core/schedule.py
- pipeline/log/handlers.py
- requirements.txt
- 优化项
- component 输出流的日志支持记录到引擎日志中
> optimization: component 输出流的日志支持记录到引擎日志中

- blueapps/account/components/bk_token/backends.py
> minor: 用户管理员权限不再由平台控制

- config/prod.py
> minor:添加数据库正式环境配置(3.5.X)

- config/prod.py
> minor:添加数据库正式环境配置(3.6.X)

- config/default.py
- gcloud/core/context_processors.py
- gcloud/core/templates/core/base_vue.html
> feature：提供人员选择器查询接口host变量值（3.6.x_dev）

- dev_log/dev/v_xugzhou_202009021136.yaml
- frontend/desktop/src/pages/home/AddCollectionDialog.vue
- bug fix
- 添加收藏弹框，修改bk-search-selector组件下拉框层递问题
> bugfix: 添加收藏弹框，修改bk-search-selector组件下拉框层递问题（V3.5.X_dev)

- dev_log/dev/v_xugzhou_202009021144.yaml
- frontend/desktop/src/pages/home/AddCollectionDialog.vue
- bug fix
- 添加收藏弹框，修改bk-search-selector组件下拉框层递问题
> bugfix: 添加收藏弹框，修改bk-search-selector组件下拉框层递问题(V3.6.X_dev)

- dev_log/dev/fannluo_202009042229.yaml
- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/FormGroup.vue
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/formMixins.js
- frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
- frontend/desktop/src/components/common/TemplateCanvas/index.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
- 优化项
- tag 组件支持获取当表单项勾选为全局变量时的实际 value 值
> improvement:tag 组件支持获取当表单项勾选为全局变量时的实际 value 值(V3.6.X)

- dev_log/dev/fannluo_202009042229.yaml
- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/FormGroup.vue
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/RenderForm.vue
- frontend/desktop/src/components/common/RenderForm/formMixins.js
- frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
- frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
- 优化项
- tag 组件支持获取当表单项勾选为全局变量时的实际 value 值
> improvement:tag 组件支持获取当表单项勾选为全局变量时的实际 value 值(V3.5.X_release)

- config/prod.py
> minor: 取消数据库正式环境配置(3.6.X)

- config/prod.py
> minor: 取消数据库正式环境配置(3.5.X)

- frontend/desktop/src/components/common/RenderForm/FormGroup.vue
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/formMixins.js
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
> minor：表格单元格事件交互默认值根据type类型取值(V3.6.X)

- frontend/desktop/src/components/common/RenderForm/FormGroup.vue
- frontend/desktop/src/components/common/RenderForm/FormItem.vue
- frontend/desktop/src/components/common/RenderForm/formMixins.js
- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
> minor：表格单元格事件交互默认值根据type类型取值(V3.5.X_dev)

- frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
> sprintfix: 解决el-table列固定时渲染两个相同表格触发事件不统一的问题(V3.5.X)

- gcloud/core/apis/__init__.py
- gcloud/core/apis/drf/__init__.py
- gcloud/core/apis/drf/serilaziers/__init__.py
- gcloud/core/apis/drf/serilaziers/project_config.py
- gcloud/core/apis/drf/viewsets/__init__.py
- gcloud/core/apis/drf/viewsets/project_config.py
- gcloud/resources/urls.py
- 新功能
- 增加 project_config rest api
> feature: 增加 project_config rest api

- config/default.py
- dev_log/dev/normal-wls_202009092249.yaml
- gcloud/core/apis/drf/exceptions.py
- gcloud/core/apis/drf/serilaziers/resource_config.py
- gcloud/core/apis/drf/validators.py
- gcloud/core/apis/drf/viewsets/__init__.py
- gcloud/core/apis/drf/viewsets/project_config.py
- gcloud/core/apis/drf/viewsets/resource_config.py
- gcloud/core/apis/drf/viewsets/utils.py
- gcloud/resources/urls.py
- pipeline_plugins/cmdb_ip_picker/query.py
- pipeline_plugins/components/query/sites/open/cc.py
- 优化项
- 添加ApiMixin，对drf接口响应进行格式标准化
> improve: 添加ApiMixin，对drf接口响应进行格式标准化

- gcloud/core/apis/drf/serilaziers/staff_group.py
- gcloud/core/apis/drf/viewsets/staff_group.py
- gcloud/resources/urls.py
> minor:新增人员分组配置接口(3.6.x_iterate)

- gcloud/core/apis/drf/serilaziers/resource_config.py
- gcloud/core/apis/drf/viewsets/resource_config.py
> improve: 增加资源筛选方案更新接口(V3.6.x_iterate)

- config/default.py
- dev_log/dev/homholueng_202009101953.yaml
- gcloud/iam_auth/conf.py
- gcloud/iam_auth/resource_api/__init__.py
- gcloud/iam_auth/shortcuts.py
- bug fix
- 修复 iam_auth.conf SYSTEM_ID 没有从 settings 获取的问题
> bugfix: 修复 iam_auth.conf SYSTEM_ID 没有从 settings 获取的问题

- gcloud/core/apis/drf/viewsets/resource_config.py
> minor: 增加request.data类型判断

- frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
- frontend/desktop/src/store/index.js
- frontend/desktop/src/store/modules/project.js
> improvement:集群筛选变量适配v1版功能

- dev_log/dev/fannluo_202009141155.yaml
- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
> improvement:输入框tag增加密码模式显示模式(V3.6.X)

- dev_log/dev/fannluo_202009141155.yaml
- docs/develop/tag_usage_dev.md
- frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
> improvement:输入框tag增加密码模式显示模式(V3.5.X)

- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
- frontend/desktop/src/store/index.js
- frontend/desktop/src/store/modules/manage.js
- frontend/desktop/src/store/modules/project.js
> sprintfix: 资源筛选变量接口请求报错处理

- pipeline_web/parser/format.py
- bug fix
- 修复子流程传参逻辑优化引入的 Lazy 类型变量传递失败的问题
> bugfix: 修复子流程传参逻辑优化引入的 Lazy 类型变量传递失败的问题

- gcloud/iam_auth/shortcuts.py
- 新功能
- 支持本地配置用于访问权限中心的 app_code 及 app_secret
> feature: 支持本地配置用于访问权限中心的 app_code 及 app_secret

- dev_log/dev/v_xugzhou_202009161556.yaml
- frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
- bug fix
- 修复节日详情页日志一直loading问题
> fixbug: 修复节日详情页日志一直loading问题

- config/default.py
> improve: 添加celery心跳设置

- gcloud/iam_auth/view_interceptors/taskflow.py
- gcloud/taskflow3/apis/__init__.py
- gcloud/taskflow3/apis/views/__init__.py
- gcloud/taskflow3/apis/views/v4/__init__.py
- gcloud/taskflow3/apis/views/v4/node_action.py
- gcloud/taskflow3/apis/views/v4/urls.py
- gcloud/taskflow3/models.py
- gcloud/taskflow3/urls.py
- gcloud/taskflow3/validators.py
- 新功能
- taskflow/api/v4/node_action 接口支持进行强制失败操作
> feature: taskflow/api/v4/node_action 接口支持进行强制失败操作

- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
> sprintfix:集群筛选变量测试问题修复

- dev_log/dev/v_xugzhou_202009211409.yaml
- frontend/desktop/src/components/common/RenderForm/HostAllocation/HostFilter.vue
- frontend/desktop/src/components/common/RenderForm/HostAllocation/index.vue
- 优化项
- 主机变量给cc_search_host接口添加表头字段
> improve： 主机变量给cc_search_host接口添加表头字段（V3.6.X_iterate)

- gcloud/core/context_processors.py
- 优化项
- 打包过程优化后端调整, 添加前端入口 url
> minor: 打包过程优化后端调整, 添加前端入口 url

- frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
> sprintfix: 筛选ip数据为空问题修复

- gcloud/core/resources.py
- gcloud/resources/urls.py
> improve: 后台添加基于用户权限的项目列表拉取接口

- pipeline_plugins/components/utils/job.py
- 新功能
- job获取文件内容公共函数
- 优化项
- xxx
- bug fix
- xxx
> feature:job获取文件内容公共函数

- pipeline_plugins/components/utils/job.py
- 新功能
- xxx
- 优化项
- 修改job获取远程服务器文件失败ip错误提示
- bug fix
- xxx
> minor:修改job获取远程服务器文件失败ip错误提示

- dev_log/dev/normal-wls_202009211542.yaml
- pipeline_plugins/components/utils/sites/open/utils.py
- pipeline_plugins/tests/utils/sites/open/test_utils.py
- 优化项
- JOB 回调默认链接使用 PAAS_INNER_HOST 拼接
> improvement: JOB 回调默认链接使用 PAAS_INNER_HOST 拼接

- gcloud/iam_auth/resource_api/task.py
- minor
- TaskResourceProvider page limit增加为1000
> minor: TaskResourceProvider page limit增加为1000

- pipeline_plugins/components/query/sites/open/cc.py
> feature: 增加查询对象全部属性的接口

- pipeline_plugins/components/query/sites/open/cc.py
> feature: 增加查询对象全部属性的接口(3.5.x)

- frontend/desktop/src/pages/task/TaskList/index.vue
- 优化项
- 任务列表页公共流程创建的任务再创建权限由接口返回
> minor: 任务列表页公共流程创建的任务再创建权限由接口返回

- frontend/desktop/src/pages/task/TaskList/index.vue
> minor: 修改公共流程创建任务已有权限数据

- frontend/desktop/src/store/modules/template.js
- bug fix
- 全局变量修改KEY后输出变量列表未更新问题修复
> bugfix:全局变量修改KEY后输出变量列表未更新问题修复

- frontend/desktop/src/components/common/modal/SelectProjectModal.vue
- frontend/desktop/src/components/layout/Navigator.vue
- frontend/desktop/src/components/layout/ProjectSelector.vue
- frontend/desktop/src/components/layout/permissionApply.vue
- frontend/desktop/src/pages/admin/statistics/index.vue
- frontend/desktop/src/pages/audit/AuditList.vue
- frontend/desktop/src/pages/functor/FunctionList.vue
- frontend/desktop/src/pages/home/AddCollectionDialog.vue
- frontend/desktop/src/pages/home/SelectCreateTaskDialog.vue
- frontend/desktop/src/pages/project/index.vue
- frontend/desktop/src/store/modules/project.js
> improvement:全量项目列表接口替换为用户有权限列表接口

- gcloud/iam_auth/resource_api/project.py
- iam/contrib/django/dispatcher/dispatchers.py
- iam/contrib/django/dispatcher/exceptions.py
- 优化项
- search_instance接口添加keyword长度校验和缓存机制
> minor: search_instance接口添加keyword长度校验和缓存机制

- docs/apidoc/en/get_task_list.md
- docs/apidoc/en/modify_constants_for_task.md
- docs/apidoc/zh_hans/get_task_list.md
- docs/apidoc/zh_hans/modify_constants_for_task.md
- minor
- 补充 任务列表查询 和 任务变量修改 api接口文档
> minor: 补充 任务列表查询 和 任务变量修改 api接口文档

- iam/contrib/django/dispatcher/dispatchers.py
- minor：
- 补充考虑provider中没有实现search_instance函数的情况
> minor: 补充考虑provider中没有实现search_instance函数的情况

- dev_log/dev/normal-wls_20200930.yaml
- gcloud/iam_auth/resource_api/project.py
- iam/contrib/django/dispatcher/dispatchers.py
- iam/contrib/django/dispatcher/exceptions.py
- 新功能
- 权限中心项目新增search_instance接口
> 权限中心项目新增search_instance接口(36x)

- dev_log/dev/Atropos1999_202010121041.yaml
- pipeline_plugins/components/query/sites/open/cc.py
minor: 修改 cc_search_object_attribute_all 函数
> minor: 修改 cc_search_object_attribute_all 函数

- dev_log/dev/normal-wls_202010111633.yaml
- docs/apidoc/en/start_task.md
- docs/apidoc/zh_hans/start_task.md
- gcloud/apigw/views/start_task.py
- gcloud/tests/apigw/views/test_start_task.py
- 优化项
- start_task api 返回内容新增task_url
> improve: start_task api 返回内容新增task_url

- gcloud/contrib/admin/migration_api/app_maker.py
- bug fix
- 修复轻应用迁移时生成的前缀链接错误的问题
> bugfix: 修复轻应用迁移时生成的前缀链接错误的问题

- packages/blueking/component/apis/job.py
- pipeline_plugins/components/collections/sites/open/job/local_content_upload/v1_0.py
- pipeline_plugins/tests/components/collections/sites/open/job_test/local_content_upload/test_v1_0.py
- 新功能
- xxx
- 优化项
- xxx
- bug fix
- 添加esb client api method
> V3.6.15 release begin
