requirements.txt

- bug fix
-  修复redis最新版本不兼容redis-py-cluster的问题，redis版本号升级到2.10.6
close #20

bugfix: #20 修复redis最新版本不兼容redis-py-cluster的问题，redis版本号升级到2.10.6

---

pipeline/blueflow/src/pages/template/TemplateEdit/NodeConfig.vue

- 新功能
- 无
- 优化项
- 流程模版编辑时，所引用的子流程节点有更新时，点击更新需要保留用户当前编辑输入参数表单的值
- bug fix
- 无
close #76

improvement: 子流程更新时保留当前输入参数值 #76

---

pipeline/blueflow/builds/webpack.base.js

- 新功能
- 无
- 优化项
- 无
- bug fix
- 修复 webpack 配置图片引用路径错误，导致图片加载失败的问题
close #83

bugfix: 修复图片引用路径的问题 #83

---

pipeline/blueflow/src/components/common/RenderForm/FormItem.vue
pipeline/blueflow/src/components/common/RenderForm/formMixins.js
pipeline/blueflow/src/pages/template/TemplateEdit/NodeConfig.vue

- 新功能
- 无
- 优化项
- 任务节点在编辑输入参数时，当参数勾选为全局变量后，在标准插件配置项定义的事件回调里，支持调用 changeHook 方法来去掉对应表单的勾选状态
- bug fix
- 无
close #81

improvement: 标准插件Tag表单支持changeHook方法 #81

---

pipeline/blueflow/package.json

- 新功能
- 无
- 优化项
- 无
- bug fix
- 更新 webpack 版本到4.29.0及以上版本后，代码构建失败问题修复。
close #103

bugfix:锁定webpack版本，解决部分版本webpack无法动态导入vue组件的问题 #103

---

app.yml
docs/release.md
pipeline/engine/utils.py
readme.md
readme_en.md

- bug fix
- 修复在 get_task_status API 返回的 elapsed_time 为 Float 的问题
close #150

Bugfix node elapse time type error

---

pipeline_plugins/cmdb_ip_picker/utils.py
pipeline_plugins/tests/cmdb_ip_picker/test_utils.py
pipeline_plugins/tests/utils.py

- bug fix
- 修复新版 IP 选择器同时拥有筛选条件和过滤条件时返回 IP 为空的问题
close #229

bugfix: 修复新版 IP 选择器同时拥有筛选条件和过滤条件时返回 IP 为空的问题 #229

---

frontend/desktop/src/components/common/RenderForm/IpSelector/SelectCondition.vue
frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/VariableEditDialog.vue

- 优化项
- 排除条件中提示是“增加一条筛选条件”改为“增加一条排除条件”
- 添加静态 ip 的确定、取消按钮位置放到表格头部
- 表单校验时，静态 ip 为空，跳转到静态 ip 列表
close #298

improvement:  ip选择器错误提示和排除条件为空时文案优化

---

frontend/desktop/src/components/common/RenderForm/FormItem.vue
frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue

- 优化项
- 修复表格tag数据为空的样式问题
-导入模版流程名称表头左对齐
- bug fix
- 无
link #326

improve:修复导入模版流程名称表头没对齐和表格tag数据为空的样式问题

---

frontend/desktop/src/pages/admin/statistics/Instance/index.vue
frontend/desktop/src/pages/periodic/PeriodicList/index.vue
frontend/desktop/src/scss/datastatistics/datastatistics.scss

- 优化项
- 部分选择器的选择项只有两条，没必要增加搜索效果，所以去除部分选择器的搜索框
- 优化运营数据里的时间维度选择器顺序，把选择每天或每月的选择器放置在最后
- bug fix
- 无
link #414

improvement:去除部分选择器的搜索框和优化时间维度选择器顺序

---

frontend/mobile/build/config.js

- bug fix
- 前端打包路径加上 static 和 '/' 符号
- mobile 改为 weixin

sprintfix: 前端打包路径加上static、公共路径'/'符号问题修复

---

frontend/mobile/src/api/index.js

- bug fix
- 移动端全局变量为global对象 window.xxx改成global.xxx

bugfix: 移动端全局变量为global对象 #466

---

frontend/desktop/src/pages/admin/manage/SourceSync/index.vue

improvement: 远程插件同步列表同步时间为空是显示默认标识

---

config/default.py

- bug fix
- 修复settings中中间件顺序问题导致获取移动端获取用户失败

sprintfix: 修复settings中中间件顺序问题导致获取移动端获取用户失败

---

frontend/desktop/src/pages/appmaker/AppCard.vue

- 优化项
- 轻应用“更多”浮框颜色还原
- 修复鼠标移入轻应用右侧时详情覆盖了边框
- bug fix
- 无
link #446

minor:轻应用浮框颜色还原及修复鼠标移入右侧覆盖边框

---

frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue

- bug fix
- 修复周期任务和任务记录里的新建任务弹窗bug。
即在打开弹窗选择流程后退出窗口，再次进入后之前选择的流程仍然是被选中状态。
link #457

bugfix:修复周期任务和任务记录里的新建任务弹窗

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables.vue

- bug fix
- 新建任务中的新建变量后面的tooltips在鼠标移入时，展示的提示信息箭头偏移
link #547

bugfix:修复tooltips未对齐

---

pipeline/contrib/periodic_task/djcelery/tzcrontab.py

- bug fix
- 修复周期任务会受到 CELERY_ENABLE_UTC 配置影响导致其他时区下调度不正确的问题
close #646

bugfix: 修复周期任务会受到 CELERY_ENABLE_UTC 配置影响导致其他时区下调度不正确的问题

---

pipeline_plugins/components/collections/sites/open/job.py

- bug fix
- 修复 JOB 快速执行脚本完成时获取全局变量失败的问题

bugfix: 修复 JOB 快速执行脚本完成时获取全局变量失败的问题

---

frontend/desktop/src/pages/template/TemplateEdit/index.vue

- bug fix
- 修复切换缓存图标消失问题
- 原因：从缓存里更新数据后绑定在 dom 上的数据没被更新

sprintFIx: 修复切换缓存图标消失问题

---

frontend/desktop/src/pages/task/ParameterInfo.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue
frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue

- 优化项
- 关闭子流程节点后重新打开，流程模板选择框希望能定位到当前选中的流程
- 导出流程/公共流程未选中时错误提示样式优化
- bug fix
- 修改子流程跳转样式修复
- 修复未引用全局变量，在新建流程时被视为必填

bugfix: 修复未引用全局变量被视为必填，子流程跳转样式修复；优化未选中时错误提示样式优，定位到当前选中的流程

---

frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue
frontend/desktop/src/pages/config/index.vue
frontend/desktop/src/pages/periodic/PeriodicList/ModifyPeriodicDialog.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

- 优化项
- 周期表达式tab没有纵向居中对齐
- 任务执行右侧操作icon尺寸偏小
- 强制生效 tips 宽度减少，icon 左移
- 编辑周期任务tilte和表单项的样式统一

improve: 周期tab垂直居中，任务执行icon位置调整，强制生效tips调整，周期任务title调整

---

pipeline/core/data/expression.py

- bug fix
- 修复mako语法中包含#解析时出现memory error的问题，包含#字符的mako语法不再解析 
close #713

bugfix: 修复mako语法中包含#解析时出现memory error的问题，包含#字符的mako语法不再解析 #713

---

pipeline/component_framework/test.py

- bug fix
- mock掉单元测试中的logger
close#895

bugfix: 解决单元测试中Service对象没有logger属性的错误

---

gcloud/apigw/views.py

- bug fix
- 修复获取公共流程模板实例 API 没有添加相应装饰器的问题
close #923

bugfix: 修复获取公共流程模板实例 API 没有添加相应装饰器的问题

---

frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue

- bug fix
- tagdatatable单元格的校验功能恢复
close #927

bugfix: tagdatatable单元格校验功能恢复

---

pipeline/contrib/external_plugins/tests/utils/importer/test_s3.py
pipeline/contrib/external_plugins/utils/importer/s3.py

- 优化项
- S3远程插件读取文件超时时间设置为10s,重试次数改为2次 
close #966

improve: S3远程插件读取文件超时时间设置为10s,重试次数改为2次 #966

---

gcloud/apigw/decorators.py

- bug fix
- 修复从 JWT 获取 bk_username 报错 500 的问题 
link #1106

sprintfix: 修复从 JWT 获取 bk_username 报错 500 的问题 #1106

---

blueapps/core/exceptions/middleware.py
gcloud/core/views.py

- 优化项
- API和静态资源找不到直接返回404，而不是vue首页 
close #1164

improve: API和静态资源找不到直接返回404，而不是vue首页 #1164

---

pipeline_plugins/components/collections/sites/open/cc.py

- bug fix
- 修复转移主机模块插件调用 CC 接口时模块 ID 传递错误的问题
close #1201

bugfix: 修复转移主机模块插件调用 CC 接口时模块 ID 传递错误的问题

---

pipeline_plugins/components/collections/sites/open/cc.py

- bug fix
- 修复 CMDB-故障机替换插件主机不存在时错误信息未国际化问题 
close #1245

bugfix: 修复 CMDB-故障机替换插件主机不存在时错误信息未国际化问题 #1245

---

frontend/desktop/package.json

- bug fix
- magicbox版本升级select api变更导致页面下拉框无法使用修复

bugfix: magicbox版本升级select api变更导致页面下拉框无法使用修复

---

frontend/desktop/src/components/common/TemplateCanvas/index.vue
frontend/desktop/src/components/common/TemplateCanvas/options.js

- 优化项
- 画布只读模式不可拖拽连线
- 节点连线端点改为半圆

画布只读模式不可拖拽连线、节点连线端点改为半圆

---

pipeline_web/drawing.py

- bug fix
- 修复前端节点大小修改后自动编排未对齐的问题，去掉 stage_name 的强制校验

sprintfix: 修复前端节点大小修改后自动编排未对齐的问题，去掉 stage_name 的强制校验

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig.vue

- bug fix
- 节点配置面板点击tooltip内容时，会收起面板修复

bugfix: 节点配置面板点击tooltip内容时，会收起面板修复

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue

- bug fix
- 节点执行详情接口默认不传loop参数
- loop次数选择倒序排列

sprintfix: 节点执行详情接口默认不传loop参数，loop次数选择倒序排列

---

gcloud/apigw/views.py
gcloud/periodictask/models.py
gcloud/taskflow3/models.py
gcloud/tasktmpl3/constants.py

- bug fix
- 修复部分历史数据 template_source 为 business 导致的任务无法读取及周期任务模板名空白的问题

bugfix: 修复部分历史数据 template_source 为 business 导致的任务无法读取及周期任务模板名空白的问题（V3.4.X)

---

gcloud/apigw/views.py
gcloud/periodictask/models.py
gcloud/taskflow3/models.py
gcloud/tasktmpl3/constants.py

- 修复部分历史数据 template_source 为 business 导致的任务无法读取及周期任务模板名空白的问题

bugfix: 修复部分历史数据 template_source 为 business 导致的任务无法读取及周期任务模板名空白的问题（V3.5.X）

---

pipeline_plugins/components/collections/sites/open/cc.py

- bug fix
- 修复 CMDB-更新集群属性 插件集群容量参数未使用整数的问题

bugfix: 修复 CMDB-更新集群属性 插件集群容量参数未使用整数的问题

---

frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue

- bug fix
- 修复tagTree在查看模式下子节点未选中时会展示父节点的问题

bugfix: 修复tagTree在查看模式下子节点未选中时会展示父节点的问题(V3.5.X)

---

frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue

- bug fix
- 修复tagTree在查看模式下子节点未选中时会展示父节点的问题

bugfix: 修复tagTree在查看模式下子节点未选中时会展示父节点的问题(V3.4.X)

---

frontend/desktop/package.json
frontend/desktop/src/main.js
frontend/desktop/src/pages/home/AddCollectionDialog.vue

- 优化项
- magicbox 升级到 2.1.9-beta.5
- bug fix
- 添加收藏 searchInput 下拉不显示

bugfix: 添加收藏 searchInput 下拉不显示, magicbox 升级到 2.1.9-beta.5

---

frontend/desktop/src/pages/functor/FunctionList.vue

- bug fix
- 职能化高级搜索所属项目字段project__id 改成 task__project__id

bugfix: 职能化高级搜索所属项目字段修复

---

frontend/desktop/src/pages/functor/index.vue

- bug fix
- 职能化高级搜索project__id 改成 task__project__id

bugfix: 职能化高级搜索所属项目字段修复（V3.4.X）

---

config/default.py

- bug fix
- 修复 open_paas 版本低于 2.10.7 时申请权限跳转链接错误问题 
close #1934

bugfix: 修复 open_paas 版本低于 2.10.7 时申请权限跳转链接错误问题 (V3.5.X)

---

pipeline/core/data/expression.py
pipeline/tests/core/data/test_expression.py

- bug fix
- 修复变量引擎中 mako 语法错误时渲染参数异常的问题，优化后直接返回原字符串 
close #2009

bugfix: 修复变量引擎中 mako 语法错误时渲染参数异常的问题，优化后直接返回原字符串 #2009

---

pipeline_plugins/components/collections/sites/open/cc.py

- 新增cc插件方法
- cc_parse_textarea_path 将目标主机/模块/自定义层级的文本路径解析为列表形式，支持空格/空行容错解析
- cc_list_match_node_inst_id 路径匹配，对path_list中的所有路径与拓扑树进行路径匹配

feature: 新增cc插件方法

---

pipeline/engine/utils.py

- 优化项
- 计算插件耗时方法改为四舍五，而不是向下取整 
close #2073

imporve: 计算插件耗时方法改为四舍五，而不是向下取整 #2073

---

pipeline/engine/models/core.py

- bug fix
- 修复节点失败重试/修改定时节点的定时时间后，节点执行结束时间未清空的问题 
close #2129

bugfix: 修复节点失败重试/修改定时节点的定时时间后，节点执行结束时间未清空的问题 #2129

---

pipeline/apps.py

- 优化项
- 增加 python 解释器允许的最大递归数上限

optimization: 增加 python 解释器允许的最大递归数上限

---

dev_log/dev/fannluo_202007201735.yaml
frontend/desktop/src/pages/template/TemplateEdit/index.vue

- bug fix
- 编辑公共流程引用子流程时需要判断common_flow_view权限

bugfix:编辑公共流程引用子流程时需要判断common_flow_view权限

---

iam/utils.py

- bug fix
- 修复 gen_perms_apply_data 生成 parent instance 未处理 resource attributes 为 None 的问题

bugfix: 修复 gen_perms_apply_data 生成 parent instance 未处理 resource attributes 为 None 的问题

---

dev_log/dev/homholueng_202008201556.yaml
packages/bkoauth/decorators.py

- bug fix
- 修复 BKAPP_API_JWT_EXEMPT 环境变量存在时 API 从 HTTP 头部中获取不到 APP CODE 的问题

bugfix: 修复 BKAPP_API_JWT_EXEMPT 环境变量存在时 API 从 HTTP 头部中获取不到 APP CODE 的问题（V3.6.X）

---

dev_log/dev/homholueng_202008201556.yaml
packages/bkoauth/decorators.py

- bug fix
- 修复 BKAPP_API_JWT_EXEMPT 环境变量存在时 API 从 HTTP 头部中获取不到 APP CODE 的问题

bugfix: 修复 BKAPP_API_JWT_EXEMPT 环境变量存在时 API 从 HTTP 头部中获取不到 APP CODE 的问题（V3.5.X）

---

frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue

sprintfix:select tag 去掉重载的_get_value、_set_value方法(V3.5.X_release)

---

frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue

sprintfix:select tag 去掉重载的_get_value、_set_value方法(V3.6.X)

---

dev_log/dev/normal-wls_202011181544.yaml
pipeline_plugins/cmdb_ip_picker/query.py

- bug fix
-  cmdb_search_host处理agent参数时过滤ip为空的主机

bugfix: cmdb_search_host处理agent参数时过滤ip为空的主机

---

gcloud/apigw/schemas.py

- 优化项
- APIGW create_task 接口对任务名的长度校验改为 100

minor: APIGW create_task 接口对任务名的长度校验改为 100

---

pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_module_ip_selector.py
pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py

- bug fix
- minor:修复集群模块IP选择器不选择过滤set或module时，全选集群下ip,单元测试更新

minor:修复集群模块IP选择器不选择过滤set或module时，全选集群下ip,单元测试更新

---

frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue

improve: 插件表格分页每页最大数量配置为 10

---

pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py

bug fix：快速分发文件2.0插件不可用

---

support-files/supervisord.conf

bugfix: 修复 supervisor 中 bk_sops_celery 进程启动命令不正确的问题

bugfix: 修复 supervisor 中 bk_sops_celery 进程启动命令不正确的问题

---

packages/blueking/component/apis/cc.py

bugfix: 修复 transfer_host_to_recyclemodule API 不存在的问题

bugfix: 修复 transfer_host_to_recyclemodule API 不存在的问题

---

frontend/desktop/src/pages/template/common/CommonTemplateList.vue

- bug fix
- 公共流程删除报错后弹窗不能再次显示修复

bugfix: 公共流程删除报错后弹窗不能再次显示修复

---

pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
static/components/atoms/job/job_push_local_files/v2_0.js

- 优化项
- 作业平台(JOB)-分发本地文件 2.0 版本添加文件后不要清空目标路径

improvement : 【优化】作业平台(JOB)-分发本地文件 2.0 版本添加文件后不要清空目标路径

---

gcloud/project_constants/apis/drf/permissions.py

bugfix: 修复创建项目环境变量使用项目查看而不是项目编辑权限的问题

bugfix: 修复创建项目环境变量使用项目查看而不是项目编辑权限的问题

---

dev_log/dev/homholueng_202109231453.yaml
gcloud/taskflow3/domains/dispatchers/node.py

bugfix: 修复 operate_node API 不修改参数重试 engine v2 失败节点时节点数据会被清空的问题

bugfix: 修复 operate_node API 不修改参数重试 engine v2 失败节点时节点数据会被清空的问题

---

pipeline_plugins/components/collections/controller.py

定时节点支持任意长的定时时间

---

pipeline_plugins/components/static/components/atoms/nodeman/create_task/v2_0.js

节点管理新建任务插件认证方式为TJJ时auth_key为非必填

节点管理新建任务插件认证方式为TJJ时auth_key为非必填

---

pipeline_plugins/components/collections/sites/open/monitor/base.py
pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield/test_v1_1.py
pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield/test_v1_2.py
pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield_strategy/test_v1_1.py
pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield_strategy/test_v1_2.py
pipeline_plugins/tests/components/collections/sites/open/monitor_test/test_alarm_shield.py
pipeline_plugins/tests/components/collections/sites/open/monitor_test/test_alarm_shield_strategy.py

 修复监控插件失败无异常输出的问题

---

pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_module_ip_selector.py
pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py

优化集群ip选择器筛选逻辑

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

fix: meta变量复用不去更新变量配置和值

---

env.py
gcloud/core/tasks.py

* fix: 修复周期扫描发送周期任务消息通知 #7364
* fix: 修复周期扫描发送周期任务消息通知 #7364

fix: 修复周期扫描发送周期任务消息通知 #7364 (#7425)

---

frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue

fix: ip选择器接口调用逻辑优化 #7543

---

frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue

fix: ip选择器接口调用自测问题修复 #7543

---

gcloud/contrib/admin/views/command.py

API `/swagger/` error due to error description of the schema

fix: bug of swagger schema description

---

frontend/desktop/package.json
frontend/desktop/src/components/common/modal/ErrorCodeModal.vue
frontend/desktop/src/main.js
frontend/desktop/src/pages/task/PeriodicList/BootRecordDialog.vue
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/OutputParams.vue

fix: 使用v-html模板语法时添加安全预防 --bug=119961524

---

frontend/desktop/src/components/common/RenderForm/IpSelector/IpSelectorTable.vue
frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
frontend/desktop/src/store/index.js

feat: IP选择器静态ip支持后端分页 #7550

---

frontend/desktop/src/main.js
frontend/desktop/src/pages/task/PeriodicList/BootRecordDialog.vue
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/utils/tools.js

fix: 节点执行报错信息跳转链接未新开tab问题修复 --bug=119961524

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue

fix: 变量是否为常量改为必选 --bug=120999984

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue

fix: 第三方插件执行中调用 detail 接口报错问题修复 --story=120926155

---

frontend/desktop/src/pages/task/TaskList/index.vue
frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue

fix: 公共流程导入流程覆盖支持搜索

---

config/default.py
gcloud/apigw/management/commands/data/api-resources.yml

feat: 添加CSRF_TRUSTED_ORIGINS配置 #7625

feat: 添加CSRF_TRUSTED_ORIGINS配置 #7625

---

app_desc.yaml
gcloud/core/trace.py
gcloud/periodictask/signals/handlers.py

refactor:  修复定时任务trace不连通的问题 --story=126421543
