TencentBlueKing/bk-sops

config/prod.py
gcloud/iam_auth/resource_creator_action/task.py
gcloud/iam_auth/resource_creator_action/utils.py

minor: 修改 属性新建关联 传入属性值

---

frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
frontend/desktop/src/store/modules/template.js

improvement:任务节点样式优化

---

pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
pipeline_plugins/components/static/components/atoms/cc/host_custom_property_change/v1_0.js
static/components/atoms/cc/host_custom_property_change/v1_0.js

minor:前端表单增加验证，增加插件的详细描述

---

pipeline/core/data/expression.py
pipeline_plugins/variables/collections/datatable.py
pipeline_plugins/variables/collections/sites/open/cc.py
pipeline_plugins/variables/collections/sites/open/cmdb/var_set_module_selector.py

- bug fix
- 修复 返回值为对象类型的变量引用点操作 未生效问题

bugfix: 修复 返回值为对象类型的变量引用点操作 未生效问题

---

pipeline_plugins/components/utils/common.py
pipeline_plugins/tests/utils/test_utils.py

V3.6.x dev chunk table data

---

gcloud/core/resources.py

- 优化项
- 优化 DB 中存在内存中没有的插件时的处理逻辑

optimization: 优化 DB 中存在内存中没有的插件时的处理逻辑

---

gcloud/tests/utils/cmdb/test_business_host_topo.py
gcloud/tests/utils/cmdb/test_get_business_host.py
gcloud/utils/cmdb.py

improvement: CC 工具函数传参优化

---

pipeline_plugins/components/utils/common.py
pipeline_plugins/tests/utils/test_utils.py

- bug fix
- bugfix:单行扩展deepcopy colum

bugfix:单行扩展deepcopy colum

---

dev_log/3.6.19/homholueng_202010261139.yaml
gcloud/core/api.py
gcloud/core/urls.py

minor: 增加 healthz 接口

---

dev_log/dev/normal-wls_2020102262210.yaml
pipeline_plugins/components/collections/sites/open/cc/replace_fault_machine/legacy.py
pipeline_plugins/components/static/components/atoms/cc/cc_replace_fault_machine.js
static/components/atoms/cc/cc_replace_fault_machine.js

- bug fix
- 修复 故障机替换 插件 bk_host_innerip KeyError 问题，增加是否复制故障机属性选项

bugfix: 修复 故障机替换 插件 bk_host_innerip KeyError 问题，增加是否复制故障机属性选项

---

pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py

- 优化项
- minor:节点管理新建任务查询接口部分失败状态支持

minor:节点管理新建任务查询接口部分失败状态支持

---

.gitignore
gcloud/core/templates/core/base_vue.html
gcloud/taskflow3/models.py
gcloud/tests/taskflow3/models/test_taskflow_preview_pipeline_tree_exclude_task_nodes.py
pipeline_web/parser/format.py
pipeline_web/tests/parser/format/__init__.py
pipeline_web/tests/parser/format/test_classify_constants.py

optimization: 后台允许用户取消勾选带有输出参数的节点

---

dev_log/dev/normal-wls_202010232100.yaml
docs/develop/dev_plugins.md
pipeline/core/flow/activity/service_activity.py
pipeline/engine/core/handlers/service_activity.py
pipeline/tests/mock.py

- 新功能
- 新增 标准运维插件 execute_pre_process 数据预处理和校验函数钩子

feature: 新增 标准运维插件 execute_pre_process 数据预处理和校验函数钩子

---

dev_log/dev/normal-wls_202010091414.yaml
iam/contrib/drf/__init__.py
iam/contrib/drf/permission.py
iam/contrib/drf/resource.py

feature: iam sdk 新增基于drf的支持

---

docs/apidoc/sops.yaml
gcloud/apigw/views/claim_functionalization_task.py
gcloud/apigw/views/get_task_list.py
gcloud/iam_auth/view_interceptors/apigw/claim_functionalization_task.py

- minor:
- get_task_list 接口实现更新

minor：get_task_list 接口实现更新

---

pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_allocation.py
pipeline_plugins/variables/collections/sites/open/cc.py

minor: 集群资源筛选添加单元测试

---

gcloud/core/api.py
gcloud/core/urls.py

- minor: 
- 修改healthz接口路径/增加豁免登陆

minor: 修改healthz接口路径/增加豁免登陆

---

frontend/desktop/src/assets/html/template.html
frontend/desktop/src/components/layout/Navigator.vue

improvement: 文档中心跳转链接由后台动态返回(V3.6.14_for_community)

---

dev_log/dev/normal-wls_202011021754.yaml
gcloud/core/api.py
gcloud/core/footer/sites/open/footer.py
locale/en/LC_MESSAGES/django.po
locale/zh_hans/LC_MESSAGES/django.po

improve: 页面footer添加 蓝鲸智云桌面 选项

---

dev_log/dev/Atropos1999_202011031454.yaml
pipeline_plugins/components/query/sites/open/cc.py

minor: cc_search_object_attribute函数增加bk_biz_id参数，支持查询自定义属性

minor: cc_search_object_attribute函数增加bk_biz_id参数，支持查询自定义属性

---

gcloud/taskflow3/context.py
gcloud/taskflow3/models.py
gcloud/tasktmpl3/migrations/0017_tasktemplate_executor_proxy.py
gcloud/tasktmpl3/models.py
gcloud/tests/mock_settings.py
gcloud/tests/taskflow3/context/__init__.py
gcloud/tests/taskflow3/context/task_context/__init__.py
gcloud/tests/taskflow3/context/task_context/test_task_executor.py
gcloud/tests/taskflow3/models/taskflow/test_executor_proxy.py
gcloud/tests/taskflow3/models/taskflow/test_is_manual_intervention_required.py

feature: 后台支持配置单个流程的执行代理人

---

dev_log/dev/homholueng_202010301711.yaml
pipeline_web/drawing_new/position.py

bugfix: 修复自动排版时分支条件被覆盖的问题

---

dev_log/dev/Atropos1999_202011061148.yaml
pipeline_plugins/variables/collections/sites/open/cmdb/var_set_group_selector.py

minor:集群分组选择器添加变量 _pipeline_var_str_value

bugfix:集群分组选择器添加变量 _pipeline_var_str_value

---

pipeline/models.py

- 优化项
- 优化 pipeline set_{status} 系列接口

optimization: 优化 pipeline set_{status} 系列接口

---

pipeline/utils/mako_utils/visitors.py

- minor: 
修改mako template 安全检查提示

minor: 修改mako template 安全检查提示

---

dev_log/dev/fannluo_202011081511.yaml
docs/develop/tag_usage_dev.md
frontend/desktop/src/components/common/RenderForm/RenderForm.vue
frontend/desktop/src/components/common/RenderForm/formMixins.js
frontend/desktop/src/pages/template/TemplateEdit/index.vue

- 新功能
- renderform 组件内置获取任一表单值的方法

feature:renderform 组件内置获取任一表单值的方法

---

frontend/desktop/src/config/login.js

improvement:弹窗登录小窗关闭icon样式调整

---

Procfile
pipeline/celery/settings.py
pipeline/contrib/statistics/signals/handlers.py
pipeline/contrib/statistics/tasks.py
pipeline/contrib/statistics/utils.py
pipeline/models.py
pipeline/tests/mock_settings.py
pipeline/tests/models/test_instance.py
support-files/supervisord.conf

- 优化项
- 优化 pipeline_post_save_handler 的实现, 改为异步方式进行相关数据统计

optimization: 优化 pipeline_post_save_handler 的实现, 改为异步方式进行相关数据统计

---

pipeline_plugins/components/utils/common.py

- 新功能
- 同步尝试解密操作函数
- 优化项
- xxx
- bug fix
- xxx

同步尝试解密操作函数

---

pipeline/core/flow/activity/service_activity.py

minor：优化输出参数`执行结果`的说明，改为`执行结果的布尔值，True or False`

minor：优化输出参数`执行结果`的说明，改为`执行结果的布尔值，True or False`

---

pipeline/docs/user_guide_component_unit_test_v2.md

- 新功能
- 标准运维插件单元测试开发文档
- 优化项
- xxx
- bug fix
- xxx

docs: 新增标准运维插件单元测试开发文档

---

gcloud/tasktmpl3/resources.py

minor: 流程模板新增接口返回描述信息

---

gcloud/utils/cmdb.py
pipeline_plugins/cmdb_ip_picker/query.py

improve: 优化ip动态分组接口调用写法

---

pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
pipeline_plugins/tests/components/collections/sites/open/bk_test/approve/test_v1_0.py
static/components/atoms/bk/approve/v1_0.js

improve:插件 bk_审核  增加是否阻塞选项

---

dev_log/dev/normal-wls_202011162017.yaml
docs/apidoc/en/preview_common_task_tree.md
docs/apidoc/sops.yaml
docs/apidoc/zh_hans/preview_common_task_tree.md
gcloud/apigw/urls.py
gcloud/apigw/views/get_common_template_info.py
gcloud/apigw/views/preview_common_task_tree.py
gcloud/iam_auth/view_interceptors/apigw/__init__.py
gcloud/iam_auth/view_interceptors/apigw/common_flow_view.py
gcloud/tests/apigw/views/test_preview_common_task_tree.py
gcloud/tests/mock_settings.py

- 新功能
- API 新增 preview_common_task_tree 接口

feature: API 新增 preview_common_task_tree 接口

---

pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
static/components/atoms/job/job_execute_task.js

- 优化项
- improve:执行作业 IP存在性校验，默认值改为“是”

improve:执行作业 IP存在性校验，默认值改为“是”

---

pipeline_plugins/components/collections/sites/open/job/fast_push_file/legacy.py
pipeline_plugins/components/collections/sites/open/job/fast_push_file/v1_0.py
pipeline_plugins/components/static/components/atoms/job/fast_push_file/v1_0.js
pipeline_plugins/components/static/components/atoms/job/job_fast_push_file.js
static/components/atoms/job/fast_push_file/v1_0.js
static/components/atoms/job/job_fast_push_file.js

minor: job快速分发文件插件 添加超时设置

---

gcloud/core/resources.py
pipeline/component_framework/base.py
pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
pipeline_plugins/components/query/sites/open/job.py
pipeline_plugins/components/static/components/atoms/job/job_execute_task_output.js
static/components/atoms/job/job_execute_task_output.js

optimization: JOB-执行作业输出表单实现替换

---

gcloud/utils/cmdb.py

- 优化项
- 根据通知分组查询最终通知人，允许传入自定义分组

improve: 根据通知分组查询最终通知人，允许传入自定义分组

---

config/dev.py
config/prod.py
config/stag.py
pipeline/engine/core/handlers/endevent/executable_end_event.py
pipeline/engine/core/handlers/service_activity.py
pipeline/engine/core/schedule.py

- 优化项
- 将引擎中的日志同步一份到pipeline.logging中，可在节点日志中查看

improve: 将引擎中的日志同步一份到pipeline.logging中，可在节点日志中查看

---

dev_log/dev/normal-wls_202011141506.yaml
gcloud/iam_auth/conf.py
gcloud/iam_auth/resource_api/common_flow.py
gcloud/iam_auth/resource_api/flow.py
gcloud/iam_auth/resource_api/mini_app.py
gcloud/iam_auth/resource_api/periodic_task.py
gcloud/iam_auth/resource_api/project.py
gcloud/iam_auth/resource_api/task.py

- 优化项
- 各类资源实现 search_instance 接口

improve: 各类资源实现 search_instance 接口

---

frontend/mobile/src/store/modules/task.js
frontend/mobile/src/store/modules/template.js
frontend/mobile/src/views/task/canvas.vue
frontend/mobile/src/views/task/create.vue
frontend/mobile/src/views/task/reset.vue
frontend/mobile/src/views/task/timing.vue

bugfix:移动端接口参数适配

---

gcloud/tasktmpl3/api.py
pipeline/utils/graph.py
pipeline_web/drawing_new/rank/longest_path.py

optimization: 优化有向图环检测算法

---

config/default.py
dev_log/dev/homholueng_202011301559.yaml
env.py

- 新功能
- 支持通过 SOPS_MAKO_IMPORT_MODULES 环境变量配置任务 MAKO 语法渲染上下文中能够使用的模块

feature: 支持通过 SOPS_MAKO_IMPORT_MODULES 环境变量配置任务 MAKO 语法渲染上下文中能够使用的模块

---

pipeline/log/migrations/0006_auto_20201201_1638.py
pipeline/log/models.py

- 优化项
- 为 pipeline.log LogEntry 的 logged_at 字段添加索引

optimization: 为 pipeline.log LogEntry 的 logged_at 字段添加索引

---

gcloud/core/signals/__init__.py
gcloud/core/views.py
gcloud/iam_auth/signals/__init__.py
gcloud/iam_auth/signals/handlers.py
gcloud/iam_auth/tasks.py

- 优化项
- 任务新建关联接口调用位置调整,改为用户进入系统时进行关联

optimization: 任务新建关联接口调用位置调整,改为用户进入系统时进行关联

---

dev_log/dev/fannluo_202012041040.yaml
frontend/desktop/src/components/common/RenderForm/FormItem.vue
frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskList/index.vue
frontend/desktop/src/pages/template/TemplateList/index.vue

improvement: renderform组件样式优化

---

frontend/desktop/src/App.vue

improvement:标准插件前端缓存清空逻辑优化

---

api/collections/gse_kit.py

- bug fix
- 修复gst_kit.py中request拼写问题

fixbug:修复gst_kit.py中request拼写问题

---

api/collections/gse_kit.py
pipeline_plugins/components/query/sites/open/gsekit.py
pipeline_plugins/components/static/components/atoms/gse_kit/job_exec/v1_0.js
static/components/atoms/gse_kit/job_exec/v1_0.js

- 优化项
- 适配表单字段配置
- 配置模版拉取
@homholueng

V3.6.x dev gsekit plugins job exec

---

api/collections/gse_kit.py
pipeline_plugins/components/static/components/atoms/gse_kit/job_exec/v1_0.js
static/components/atoms/gse_kit/job_exec/v1_0.js

minor: enhance gse kit job exec form

---

api/collections/gse_kit.py
pipeline_plugins/components/static/components/atoms/gse_kit/job_exec/v1_0.js
static/components/atoms/gse_kit/job_exec/v1_0.js

- bug fix
- 调整 esb api 中 gsekit path 配置
@homholueng

minor: modify path for gsekit api in esb

---

api/collections/gse_kit.py
pipeline_plugins/tests/variables/collections/sites/open/gse_kit/test_var_gse_kit_ip_selector.py
pipeline_plugins/variables/collections/sites/open/gse_kit/var_gse_kit_ip_selector.py

minor:修改esb地址与api名称

---

frontend/mobile/index.html
frontend/mobile/src/main.js
frontend/mobile/src/store/modules/component.js
frontend/mobile/src/views/home/index.vue

- bug fix
- 业务列表页数据重复加载问题修复
- 标准插件配置文件加载form文件地址去掉host
- 插件远程加载支持

bugfix: 移动端问题处理

---

frontend/mobile/src/components/VantForm/VantCell.vue
frontend/mobile/src/store/modules/taskList.js

- bug fix
- 任务列表页接口需要传project__id参数

bugfix:移动端任务列表页接口需要传project__id参数

---

pipeline_plugins/components/collections/gse_kit/job_exec/v1_0.py
pipeline_plugins/components/static/components/atoms/gse_kit/job_exec/v1_0.js
static/components/atoms/gse_kit/job_exec/v1_0.js

- fix
- 使用 env code
@homholueng

minor: update gsekit job object choices and env code

---

scripts/new_dev_log.sh

minor: 开发日志文件生成脚本添加日志规范示例

---

dev_log/dev/fannluo_202012162102.yaml
frontend/desktop/src/components/common/RenderForm/tags/TagInt.vue

improvement:TagInt组件删除表单值时默认设置值为0

---

dev_log/dev/normal-wls_202012152055.yaml
docs/apidoc/en/get_plugin_detail.md
docs/apidoc/sops.yaml
docs/apidoc/zh_hans/get_plugin_detail.md
gcloud/apigw/urls.py
gcloud/apigw/views/get_plugin_detail.py
gcloud/core/models.py
gcloud/core/resources.py
gcloud/tests/apigw/views/test_get_plugin_detail.py
gcloud/tests/mock_settings.py

- 新功能
- 添加get_plugin_detail api接口，根据插件code获取业务下插件信息

feature: 添加get_plugin_detail api接口，根据插件code获取业务下插件信息

---

frontend/desktop/src/components/common/RenderForm/HostAllocation/HostFilter.vue
frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue
frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue

- bug fix
- 集群资源筛选变量tree节点禁用态不正确修复

bugfix:集群资源筛选变量tree节点禁用态不正确修复

---

api/collections/gse_kit.py

- bug fix
- remove expression_scope param 
@homholueng

remove useless expression_scope for  gsekit plugins job exec

---

api/collections/gse_kit.py
pipeline_plugins/components/collections/gse_kit/job_exec/v1_0.py

- bug fix
- 适配 job task id 查询接口

minor: query job status for gsekit

---

api/collections/gse_kit.py
pipeline_plugins/components/collections/gse_kit/job_exec/v1_0.py
pipeline_plugins/components/static/components/atoms/gse_kit/job_exec/v1_0.js
static/components/atoms/gse_kit/job_exec/v1_0.js

- 优化项
- 适配接口，当配置模版为空时匹配全部
@homholueng

minor: gsekit exec job with extra_data(config_template_ids)

---

frontend/mobile/src/store/modules/component.js
frontend/mobile/src/store/modules/task.js
frontend/mobile/src/store/modules/taskList.js
frontend/mobile/src/views/template/index.vue

- 优化项
- 模板列表页收藏数据按照当前业务筛选
-  api 请求路径以 / 结尾

minor:移动端修改

---

pipeline_plugins/components/collections/gse_kit/job_exec/v1_0.py

- bug fix
- 修改参数类型适配 scope expression中的字段

minor: gsekit exec job with scope_expression param

---

frontend/desktop/src/components/common/RenderForm/FormItem.vue

bugfix:job执行作业刷新按钮错位修复

---

pipeline_plugins/components/collections/gse_kit/job_exec/v1_0.py

- 优化项
- 应需求方要求使用任务状态中文异常说明
@homholueng

minor: use zh error message for failed gsekit job

---

frontend/mobile/src/views/template/index.vue

bugfix:移动端收藏的模板根据业务过滤修复

---

api/collections/gse_kit.py
pipeline_plugins/components/static/components/atoms/gse_kit/job_exec/v1_0.js
static/components/atoms/gse_kit/job_exec/v1_0.js

- bug fix
- 更新 gsekit process 相关 url

fix: update url (esb path) for gsekit process related

---

gcloud/contrib/collection/management/__init__.py
gcloud/contrib/collection/management/commands/__init__.py
gcloud/contrib/collection/management/commands/flush_expired_collections.py

- 新功能
- 添加 flush_expired_collections 命令，用于清理过期收藏数据

feature: 添加 flush_expired_collections 命令，用于清理过期收藏数据

---

dev_log/dev/JavHou_202012141203.yaml
pipeline_plugins/tests/variables/test_utils.py
pipeline_plugins/variables/utils.py

bugfix:list_biz_module接口添加module id限制

bugfix:list_biz_module接口添加module id限制

---

api/collections/gse_kit.py

- bug fix
- 刷新实例进程使用 esb api
@homholueng

minor: update gsekit flush process path in esb

---

dev_log/dev/fannluo_202012301010.yaml
frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue

- 优化项
- 删除执行方案所需申请权限调整为flow_edit

improvement:删除执行方案所需申请权限调整为flow_edit

---

frontend/desktop/src/components/layout/Navigator.vue

minor:顶部子导航zindex调整

---

pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py

- bug fix
- 按规则修改主机自定义属性执行失败的问题

fixbug:按规则修改主机自定义属性执行失败的问题

---

pipeline_plugins/components/collections/sites/open/cc/batch_update_host/v1_0.py
pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py

- bug fix
- 修复 open 版本插件 inputs_formats 问题

bugfix: 修复 open 版本插件 inputs_formats 问题

---

packages/blueking/component/apis/cc.py
pipeline_plugins/cmdb_ip_picker/query.py
pipeline_plugins/components/query/sites/open/cc.py
pipeline_plugins/variables/static/variables/cmdb/var_cmdb_resource_allocation.js
static/variables/cmdb/var_cmdb_resource_allocation.js

feature:资源筛选添加find_host_by_topo接口

Feature set allocation host count

---

api/collections/gse_kit.py
pipeline_plugins/variables/collections/sites/open/gse_kit/var_gse_kit_ip_selector.py

- bug fix
- 修复 gsekit IP 选择器的批量请求问题

V3.6.x fix gsekit IP selector

---

dev_log/dev/normal-wls_202012311523.yaml
docs/apidoc/en/get_plugin_detail.md
docs/apidoc/en/get_plugin_list.md
docs/apidoc/zh_hans/get_plugin_detail.md
docs/apidoc/zh_hans/get_plugin_list.md
gcloud/apigw/views/get_plugin_detail.py
gcloud/apigw/views/get_plugin_list.py
gcloud/tests/apigw/views/test_get_plugin_detail.py
gcloud/tests/apigw/views/test_get_plugin_list.py
gcloud/tests/mock.py
pipeline_plugins/components/collections/sites/open/cc/batch_update_host/v1_0.py
pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
pipeline_plugins/components/collections/sites/open/monitor/alarm_shield/v1_1.py
pipeline_plugins/components/collections/sites/open/monitor/alarm_shield_strategy/v1_1.py
pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py

- 优化项
- plugin相关API返回数据添加form字段

improve: plugin相关API返回数据添加form字段

---

pipeline_plugins/variables/collections/common.py
pipeline_plugins/variables/collections/sites/open/cc.py
pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
pipeline_plugins/variables/collections/sites/open/cmdb/var_set_group_selector.py
pipeline_plugins/variables/collections/sites/open/cmdb/var_set_module_selector.py

minor: 将值动态获取的变量类型改为 dynamic

---

gcloud/tasktmpl3/api.py
gcloud/tasktmpl3/urls.py
gcloud/tasktmpl3/utils.py
gcloud/tasktmpl3/validators.py
gcloud/tests/tasktmpl3/utils/__init__.py
gcloud/tests/tasktmpl3/utils/test_analysis_pipeline_constants_ref.py

- 新功能
- 添加 analysis_constants_ref 变量引用计算接口

feature: 添加 analysis_constants_ref 变量引用计算接口

---

requirements.txt

- 优化项
- 解决 requirements 中的依赖包版本冲突

minor: 解决 requirements 中的依赖包版本冲突

---

dev_log/dev/homholueng_202012141028.yaml
pipeline_plugins/components/static/components/atoms/bk/http/v1_0.js
static/components/atoms/bk/http/v1_0.js

- 优化项
- http 1.0 插件 url 允许引用变量, 超时时间最大值改为 30s

optimization: http 1.0 插件 url 允许引用变量, 超时时间最大值改为 30s

---

gcloud/core/resources.py

- 新功能
- component resource 接口增加 sort_key_group_en 字段

feature: component resource 接口增加 sort_key_group_en 字段

---

dev_log/dev/homholueng_202012241716.yaml
pipeline/engine/core/handlers/base.py
pipeline/engine/core/handlers/service_activity.py
pipeline/engine/core/runtime.py
pipeline/tests/engine/core/handlers/test_service_act_handler.py
pipeline/tests/engine/core/test_runtime.py
pipeline/tests/mock.py

- bug fix
- 修复高并发情况下 sleep 可能会覆写 schedule 产生的数据的问题

V3.6.x bugfix sleep rewrite open

---

gcloud/core/context_processors.py

minor: 支持配置首页渲染上下文内容

---

pipeline_web/parser/format.py
pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py

- bug fix
- 修复预渲染变量引用了隐藏的动态类型全局变量时引用失败的问题（dev bug，不需要 dev log）

bugfix: 修复预渲染变量引用了隐藏的动态类型全局变量时引用失败的问题

---

iam/dummy_iam.py

- minor
- _do_policy_query_with_cache同步dummy iam

minor: _do_policy_query_with_cache同步dummy iam

---

docs/develop/bksops-developer-tools.md
readme.md

feature: 标准运维开发者工具包使用文档更新

---

scripts/auto_reload_tools/__init__.py
scripts/auto_reload_tools/auth_collectstatic_patch.py
scripts/auto_reload_tools/auto_reload_worker.py
scripts/auto_reload_tools/common.py

Feature: 新增标准运维开发者工具

---

gcloud/contrib/appmaker/api.py

optimization:初始化轻应用描述

---

dev_log/dev/normal-wls_202012302115.yaml
pipeline_plugins/components/collections/controller.py

- 优化项
- 暂停节点支持api调用node_callback接口进行启动并传入数据

improvement: 暂停节点支持api调用node_callback接口进行启动并传入数据

---

gcloud/tasktmpl3/api.py
gcloud/tasktmpl3/utils.py
gcloud/tests/tasktmpl3/utils/test_analysis_pipeline_constants_ref.py

- 优化项
- analysis_constants_ref 接口返回字段优化

optimization: analysis_constants_ref 接口返回字段优化

---

dev_log/dev/normal-wls_202101121744.yaml
gcloud/apigw/utils.py
gcloud/apigw/views/get_plugin_detail.py
gcloud/apigw/views/get_plugin_list.py
gcloud/apigw/views/get_task_status.py
gcloud/apigw/views/get_tasks_status.py
gcloud/apigw/views/get_user_project_detail.py
gcloud/apigw/views/get_user_project_list.py
gcloud/tests/apigw/views/test_get_user_project_detail.py
iam/dummy_iam.py

improve: get 相关api接口添加缓存

---

dev_log/dev/spacesun_202101052021.yaml
packages/blueking/component/apis/jobv3.py
packages/blueking/component/collections.py
pipeline_plugins/components/collections/sites/open/job/base.py
pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_legacy.py
pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_legacy.py

- 优化项
- JOB 系列插件获取执行日志使用 V3 接口

improvement:JOB 系列插件获取执行日志使用 V3 接口

---

frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/BranchGateway.vue
frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

improve：网关节点tip改为图标样式更改

---

dev_log/dev/fannluo_202101141912.yaml
frontend/desktop/src/pages/template/TemplateEdit/index.vue

improvement:优化画布 loading 取消逻辑

---

frontend/desktop/builds/webpack.base.js

bugfix：monaco-editor插件worker文件加载路径调整

---

gcloud/taskflow3/mixins.py

- 优化项
- query_appmaker_by_group 增加 appmakerId 返回

minor: query_appmaker_by_group 增加 appmakerId 返回

---

frontend/mobile/src/views/home/index.vue

- bug fix
- 修复移动端用户无业务时重复请求业务列表接口的问题

bugfix:修复移动端用户无业务时重复请求业务列表接口的问题

---

gcloud/tasktmpl3/api.py
locale/en/LC_MESSAGES/django.po
locale/zh_hans/LC_MESSAGES/django.po
pipeline_plugins/components/collections/common.py
pipeline_plugins/components/collections/controller.py
pipeline_plugins/components/collections/http/v1_0.py

- bug fix
- 修复 HTTP-请求 描述中的错别字
- 修复定时节点输入整型类型变量时报错的问题
- 修复模板变量引用分析接口500的问题

V3.6.28 fix

---

gcloud/contrib/admin/views/taskflow.py
gcloud/tasktmpl3/resources.py

Bugfix: 修复sentry上报错问题

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue

improve: 基础信息标签选择色块添加圆角

---

frontend/desktop/src/store/modules/templateList.js

- 优化项
- 修复多模板导出失败时前端报错后后端返回不一致问题

improve: 修复多模板导出失败时前端报错后后端返回不一致问题

---

frontend/desktop/src/pages/template/TemplateEdit/index.vue

improve: 选择标准插件页插件列表排序

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

- 优化项
- 修复节点配置中勾选变量后查看全局变量列表样式偏移问题

improve: 修复节点配置中勾选变量后查看全局变量列表样式偏移问题

---

frontend/desktop/src/components/common/RenderForm/FormGroup.vue
frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

- bug fix
- 职能化认领预览弹窗右上角关闭绑定handler
- 子流程更新后value值丢失问题修复

bugfix:体验问题处理

---

frontend/desktop/src/components/common/TemplateCanvas/ToolPanel/index.vue

minor:  画布工具面板icon更改位置

---

gcloud/apigw/views/get_user_project_list.py
gcloud/tests/apigw/views/test_get_user_project_list.py

- bug fix
- 修复 get_user_project_list 500 的问题

bugfix: 修复 get_user_project_list 500 的问题

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

minor:节点配置面板快速编辑变量问题处理

---

frontend/desktop/src/components/common/advanceSearchForm/index.vue
frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
frontend/desktop/src/pages/appmaker/index.vue
frontend/desktop/src/pages/audit/AuditList.vue
frontend/desktop/src/pages/functor/FunctionList.vue
frontend/desktop/src/pages/task/PeriodicList/index.vue
frontend/desktop/src/pages/task/TaskList/index.vue
frontend/desktop/src/pages/template/TemplateList/index.vue
frontend/desktop/src/pages/template/common/CommonTemplateList.vue

- 优化项
- url中带筛选条件时列表高级搜索自动填充并展开

improvement:url中带筛选条件时列表高级搜索自动填充并展开

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue

improvement:公共流程编辑时去掉流程标签表单

---

pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py

- bug fix
- 修复企业微信发送消息 md 格式 @ 不生效

bugfix:修复企业微信发送消息 md 格式 @ 不生效

---

static/components/atoms/nodeman/plugin_operate/v1_0.js

minor: 节点管理插件操作前端文件

---

pipeline_plugins/components/static/components/atoms/monitor/alarm_shield_strategy/v1_1.js
static/components/atoms/monitor/alarm_shield_strategy/v1_1.js

bugfigx:按照策略屏蔽监控插件无法使用

---

iam/contrib/iam_migration/migrator.py

minor: SKIP_IAM情况下跳过iam相关migrate过程

---

pipeline_plugins/components/query/sites/open/nodeman.py
pipeline_plugins/components/static/components/atoms/nodeman/plugin_operate/v1_0.js

minor: 节点管理插件操作优化

---

pipeline_plugins/components/static/components/atoms/bk/http/v1_0.js
static/components/atoms/bk/http/v1_0.js

minor: http 请求插件默认超时时间改为 5s

---

frontend/desktop/src/pages/task/PeriodicList/BootRecordDialog.vue
frontend/desktop/src/store/modules/admin.js

improve: 管理员入口查看周期任务启动记录前端分页处理

---

frontend/desktop/src/pages/task/TaskList/index.vue

- 优化项
- 轻应用执行历史跳转到任务管理页面请求数据缺少参数问题修复

improve: 轻应用执行历史跳转到任务管理页面请求数据缺少参数问题修复

---

frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue

- 优化项
- IP选择器动态选择节点后，根节点不勾选问题修复

improve: IP选择器动态选择节点后，根节点不勾选问题修复

---

pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py

- bug fix
- 添加跨业务时需要作业平台白名单的描述

bugfix:添加跨业务时需要作业平台白名单的描述

---

pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py

- bug fix
- 修复快速分发文件2.0执行失败的bug

bugfix:修复快速分发文件2.0执行失败的bug

---

pipeline_web/parser/format.py
pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py

- 新功能
- 后台解析流程树时支持读取用户配置的变量预渲染选项

feature: 后台解析流程树时支持读取用户配置的变量预渲染选项

---

config/default.py
config/dev.py
config/prod.py
config/stag.py
gcloud/core/logging.py
gcloud/core/middlewares.py

- 新功能
- 日志中同一请求添加trace_id & 整合多个环境日志配置

feature: 日志中同一请求添加trace_id & 整合多个环境日志配置

---

pipeline_plugins/base/query/cmdb.py

- bugfix
-  修复cc_get_host_by_module_id传参中存在字符串报错问题

minor: 修复cc_get_host_by_module_id传参中存在字符串报错问题

---

frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue

improve: 添加IP选择器选中最外层情况处理

---

frontend/desktop/src/components/common/RenderForm/FormItem.vue
frontend/desktop/src/components/common/RenderForm/RenderForm.vue
frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
frontend/desktop/src/components/common/RenderForm/tags/TagSetAllocation.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

improve: 集群资源筛选逻辑优化

---

static/components/atoms/nodeman/plugin_operate/v1_0.js

- 新功能
- xxx
- 优化项
- 节点管理插件操作前端优化

minor: 节点管理插件操作前端优化

---

pipeline_plugins/components/collections/sites/open/job/base.py
pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py

bugfix:修复快速执行脚本2.0轮询时的错误

---

pipeline_plugins/components/collections/sites/open/job/base.py
pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_0.py
pipeline_plugins/tests/components/collections/sites/open/job_test/push_local_files/test_v2_0.py

minor: job文本上传输出描述优化

---

requirements.txt

- 优化项
- httplib2 0.9.1 -> 0.18.0
#3020 3020

minor: httplib2 0.9.1 -> 0.18.0

---

dev_log/dev/fannluo_202102231734.yaml
frontend/desktop/package.json
frontend/desktop/src/pages/admin/statistics/VerticalBarChart.vue
frontend/desktop/src/pages/admin/statistics/index.vue

- 优化项
- 图表插件由plotly.js替换为bkcharts

imporvement:图表插件由plotly.js替换为bkcharts

---

frontend/packages/jsflow/.gitignore
frontend/packages/jsflow/src/lib/defaultOptions.js
frontend/packages/jsflow/src/lib/dom.js
frontend/packages/jsflow/src/lib/uuid.js
frontend/packages/jsflow/webpack.config.js

minor:更新jsflow包文件

---

pipeline/engine/admin.py

optimization: engine admin 页面性能优化

---

pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_module_ip_selector.py
pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py

bugfix:集群模块IP选择器 服务模版all默认选择空闲机池的问题

bugfix:集群模块IP选择器 服务模版all默认选择空闲机池的问题

---

pipeline_plugins/components/static/components/atoms/job/job_push_local_files.js
static/components/atoms/job/job_push_local_files.js

- bug fix
- 修复本地上传文件后前端列表不更新问题

bugfix: 修复本地上传文件后前端列表不更新问题

---

frontend/desktop/package.json
frontend/desktop/src/components/common/RenderForm/tags/TagPassword.vue

bugfix: jsencrypt依赖包引入方式修改

---

gcloud/contrib/operate_record/apis/__init__.py
gcloud/contrib/operate_record/apis/drf/__init__.py
gcloud/contrib/operate_record/apis/drf/serilaziers/__init__.py
gcloud/contrib/operate_record/apis/drf/serilaziers/operate_record.py
gcloud/contrib/operate_record/apis/drf/viewsets/__init__.py
gcloud/contrib/operate_record/apis/drf/viewsets/operate_record.py
gcloud/resources/urls.py

minor: 新增获取操作记录流水信息接口

---

pipeline/engine/core/api.py

- bug fix
- 修复pipeline worker连不上rabbitmq时重试逻辑不生效的问题 
close #3002

bugfix: 修复pipeline worker连不上rabbitmq时重试逻辑不生效的问题 #3002

---

frontend/desktop/src/store/index.js

- bug fix
- 修复集群资源筛选变量获取模块数量接口参数不正确问题

bugfix: 修复集群资源筛选变量获取模块数量接口参数不正确问题

---

frontend/desktop/src/routers/index.js

feature:前端检测静态资源更新时自动刷新页面

---

frontend/desktop/src/pages/audit/AuditList.vue
frontend/desktop/src/pages/functor/FunctionList.vue
frontend/desktop/src/pages/project/index.vue
frontend/desktop/src/pages/task/PeriodicList/index.vue
frontend/desktop/src/pages/task/TaskList/index.vue
frontend/desktop/src/pages/template/TemplateList/index.vue
frontend/desktop/src/pages/template/common/CommonTemplateList.vue

- 新功能
- 列表页面支持用户配置视图，自定义需要展示的列

feature: 列表页面支持用户配置视图，自定义需要展示的列

---

frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
frontend/desktop/src/store/index.js

minor:集群资源筛选调用查询主机时增加search_host_lock参数

---

frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue

- bug fix
- 集群资源筛选变量主机数量不生效修复
- improvement
- 增加接口异常错误提示

bugfix:集群资源筛选变量主机数量不生效修复，增加接口异常提示

---

frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue

improve: 轻应用创建的任务名跟随轻应用名

---

frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue
frontend/desktop/src/main.js
frontend/desktop/src/pages/admin/manage/SourceEdit/CacheForm.vue
frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue
frontend/desktop/src/pages/appmaker/AppEditDialog.vue
frontend/desktop/src/pages/project/index.vue
frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
frontend/desktop/src/pages/task/TaskList/TaskCloneDialog.vue
frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateSnapshoot.vue

- 优化项
-  修复VeeValidate组件计算属性中的名称和自定义列里面的名称重复问题

improve: 修复VeeValidate组件计算属性中的名称和自定义列里面的名称重复问题

---

dev_log/dev/normal-wls_202103161628.yaml
pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_ip_selector.py
pipeline_plugins/variables/collections/sites/open/cc.py

improvement: ip选择器支持选择不同分隔符

---

gcloud/contrib/analysis/analyse_items/task_flow_instance.py
gcloud/taskflow3/mixins.py

optimization: 运营数据-任务统计页面性能优化

---

config/dev.py
pipeline/tests/engine/test_api.py
pipeline/tests/mock_settings.py
pipeline/tests/models/test_instance.py

minor: 处理单元测试问题

---

frontend/desktop/src/pages/admin/statistics/Atom.vue

improve: 运营数据支持插件多版本

---

frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue

improve: 集群资源筛选主机资源所述支持搜索

---

dev_log/3.6.29/v_xugzhou_202103111920.yaml
frontend/desktop/src/components/common/RenderForm/formMixins.js

- 新功能
-  提供根据 KEY 获取 renderform context 中变量值的方法

feature: 提供根据 KEY 获取 renderform context 中变量值的方法

---

dev_log/dev/normal-wls_202103161754.yaml
gcloud/apigw/utils.py
gcloud/apigw/views/get_task_detail.py
gcloud/apigw/views/get_task_status.py

- 优化项
- get_task_status和get_task_detail接口添加基于业务的60s缓存

improvement: get_task_status和get_task_detail接口添加基于业务的60s缓存

---

config/default.py
dev_log/dev/normal-wls_202103150131.yaml
pipeline/core/data/sandbox.py

improvement: 变量解析新增os.path下函数支持

---

pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
static/components/atoms/job/job_execute_task.js

minor: job执行作业支持ip跨业务

---

gcloud/taskflow3/mixins.py

- 优化项
- taskflow statistics where statement optimization

minor: taskflow statistics where statement optimization

---

gcloud/shortcuts/message/__init__.py
gcloud/shortcuts/message/common.py
gcloud/shortcuts/message/send_msg.py

minor: 流程执行失败、成功发送消息链接转为超链接

---

pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
static/components/atoms/job/job_push_local_files/v2_0.js

feature:上传文件支持多个文件

---

dev_log/dev/spacesun_202101191158.yaml
pipeline_plugins/components/collections/common.py
pipeline_plugins/components/collections/http/v1_0.py
pipeline_plugins/components/http.py

- 优化项
- HTTP-请求插件在请求前对 url 进行 strip

improve：HTTP-请求插件在请求前对 url 进行 strip

---

pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_0.py

optimization：批量更新主机所属业务模块异常信息优化

optimization：批量更新主机所属业务模块异常信息优化

---

pipeline_plugins/components/query/sites/open/job.py
static/components/atoms/job/fast_execute_script/v1_0.js

feature: 修改拉取公共脚本逻辑

---

dev_log/dev/normal-wls_202102031619.yaml
gcloud/iam_auth/view_interceptors/taskflow.py
gcloud/taskflow3/api.py
weixin/resources.py

- bug fix
- 修复 处理api/status接口&微信端流程权限问题

bugfix:修复 处理api/status接口&微信端流程权限问题

---

gcloud/commons/tastypie/resources.py
gcloud/label/viewsets.py

tastypie 外键支持icontains过滤

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue

bugfix: 修复节点执行日志接口报错问题

---

pipeline_plugins/tests/components/collections/sites/open/job_test/local_content_upload/test_v1_0.py

minor: hard code ip remove

---

sdk/bamboo-engine/LICENSE.txt

minor: add license

---

config/default.py
dev_log/dev/normal-wls_202104021555.yaml

improvement:将最大请求体限制改为25MB

---

pipeline_plugins/components/collections/sites/open/cc/batch_module_update/v1_0.py
pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_0.py
pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
pipeline_plugins/components/collections/sites/open/cc/create_set/v1_0.py
pipeline_plugins/components/collections/sites/open/cc/create_set/v2_0.py
pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py

minor: 插件单行自动扩展说明补充

---

config/default.py
env.py
pipeline_plugins/components/collections/sites/open/nodeman/plugin_operate/v1_0.py
pipeline_plugins/components/utils/sites/open/utils.py
pipeline_plugins/tests/components/collections/sites/open/nodeman_test/plugin_operate_test/test_nodeman_plugin_operate_v1_0.py

minor: nodeman 插件安装输出任务链接

---

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

- bug fix
- 任务执行完毕后未执行节点状态不存在报错问题修复

bugfix:  任务执行完毕后未执行节点状态不存在报错问题修复

---

pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_module_ip_selector.py
pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py

bugfix:解决未选择空闲机池，筛选集群中有空闲机池会选择空闲机模块的问题

bugfix:解决未选择空闲机池，筛选集群中有空闲机池会选择空闲机模块的问题

---

dev_log/dev/normal-wls_202104081115.yaml
pipeline_plugins/components/collections/sites/open/job/base.py

- 优化项
-  job插件每个步骤只取第一个ip日志进行记录

improvement: job插件每个步骤只取第一个ip日志进行记录

---

frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
frontend/desktop/src/components/common/RenderForm/SeparatorSelect.vue
frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue

improvmement: IP 选择器筛选条件支持自定义分隔符

---

pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_0.py

minor: 批量更新主机所属业务模块失败信息补充

---

gcloud/taskflow3/api.py

minor: add callback data log

---

gcloud/core/api.py
gcloud/openapi/schema.py
scripts/generate_frontend_files.sh

minor: 添加前端自动打包脚本 & check_variable_key接口兼容${xxx}情况

---

env.py

minor: BK_IAM_SKIP读取的环境变量添加BKAPP_IAM_SKIP

---

gcloud/contrib/analysis/analyse_items/task_flow_instance.py
gcloud/contrib/analysis/analyse_items/task_template.py

minor:插件版本运营查询优化

---

gcloud/contrib/operate_record/apis/drf/viewsets/operate_record.py
gcloud/contrib/operate_record/apps.py

minor: 流水记录优化

---

frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue

improvement:  新增执行方案名称输入框交互优化

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

improvement:  插件版本列表倒序排序

---

frontend/desktop/src/pages/template/TemplateEdit/index.vue

improve:  模板数据无修改时去编辑执行方案不显示弹框

---

frontend/desktop/src/pages/template/TemplateEdit/index.vue

improvement:  克隆模板可以引用被克隆的模板

---

frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue

- 优化项
- 新建项目时点击执行方案获取方案详情接口返回字段前端调整

improvmement:  新建项目时点击执行方案获取方案详情接口返回字段前端调整

---

frontend/desktop/src/main.js
frontend/desktop/src/pages/home/CommonlyUsed.vue
frontend/desktop/src/pages/home/MyCollection.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue
frontend/desktop/src/pages/template/TemplateList/index.vue

feature: 新增页面操作埋点

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue

- 优化项
- 执行详情侧栏中的"执行次数"在切换节点时未刷新问题修复

improvement:  执行详情侧栏中的"执行次数"在切换节点时未刷新问题修复

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
frontend/desktop/src/store/modules/atomForm.js

improvement:  全局变量类型添加说明

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

improvement:  预渲染配置逻辑问题修复

---

gcloud/apigw/views/get_functionalization_task_list.py
gcloud/apigw/views/get_task_status.py
gcloud/apigw/views/get_template_list.py
gcloud/apigw/views/plugin_proxy.py
gcloud/apigw/views/utils.py

optimization: apigw 错误日志增加异常堆栈

---

gcloud/contrib/operate_record/apis/drf/viewsets/operate_record.py

minor: 支持节点流水查看

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskExecute/OperationFlow.vue
frontend/desktop/src/store/modules/task.js

improvement:  节点操作流水逻辑优化

---

pipeline_web/parser/format.py
pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py

feature: 支持一层 lazy 变量引用渲染

---

gcloud/core/resources.py
pipeline/component_framework/base.py

feature:前端页面支持继承

---

gcloud/utils/handlers.py
pipeline_plugins/tests/components/collections/sites/open/cc_test/update_set_service_status/test_v1_1.py
pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_execute_task/test_legacy.py
pipeline_plugins/tests/components/collections/sites/open/job_test/cron_task/all_bizfast_execute_task/test_legacy.py
pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_legacy.py
pipeline_plugins/tests/components/collections/sites/open/job_test/local_content_upload/test_v1_0.py

- 优化项
- handle_api_error输出request_id，及单元测试修改

optimization： handle_api_error输出request_id，及单元测试修改

---

pipeline_plugins/components/collections/sites/open/nodeman/base.py
pipeline_plugins/tests/components/collections/sites/open/nodeman_test/create_task_test/test_nodeman_v2_create_task.py

optimization: 节点管理错误日志输出格式化

---

gcloud/tasktmpl3/resources.py

bugfix: 修复流程标签无法清空问题

---

dev_log/dev/homholueng_202105061446.yaml
pipeline_plugins/components/utils/sites/open/utils.py
pipeline_plugins/tests/components/utils/__init__.py
pipeline_plugins/tests/components/utils/test_cc_get_ips_info_by_str.py

- 优化项
- 优化 CMDB/JOB 系列插件及集群模块 IP 选择器变量从 CMDB 拉取 IP 时的速度

optimization: 优化 CMDB/JOB 系列插件及集群模块 IP 选择器变量从 CMDB 拉取 IP 时的速度

---

gcloud/core/views.py

minor: 解决未登录情况下非首页地址无法正常跳转登陆弹窗问题

---

gcloud/contrib/analysis/analyse_items/task_flow_instance.py
gcloud/contrib/analysis/analyse_items/task_template.py

bugfix: 运营数据报错修复

---

frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
frontend/desktop/src/pages/task/TaskParamEdit.vue

improve:  新建任务时修改资源集群的集群报错问题修复

---

frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue

improvement:  创建执行方案校验不通过时显示错误信息

---

dev_log/dev/homholueng_202105061556.yaml
docs/apidoc/en/create_task.md
docs/apidoc/zh_hans/create_task.md
gcloud/apigw/views/create_task.py
gcloud/taskflow3/models.py
gcloud/tests/apigw/views/test_create_task.py

- 新功能
- create_task API 支持简化变量类型

feature: create_task API 支持简化变量类型

---

frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue

minor: 创建任务下一步按钮禁用问题修复

---

config/default.py
gcloud/taskflow3/api.py
gcloud/taskflow3/dispatchers/node.py
gcloud/taskflow3/dispatchers/task.py
gcloud/taskflow3/models.py
gcloud/tests/mock_settings.py
gcloud/tests/taskflow3/dispatchers/__init__.py
gcloud/tests/taskflow3/dispatchers/node/__init__.py
gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/__init__.py
gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v1.py
gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_detail_v1.py
gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_detail_v2.py
gcloud/tests/taskflow3/models/taskflow/test_get_node_detail.py
requirements.txt

V3.6.x develop all node detail backend

---

frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
frontend/desktop/src/store/modules/task.js

improvement:  勾选执行方案后报错问题修复

---

dev_log/dev/homholueng_202104121605.yaml
gcloud/taskflow3/models.py

- bug fix
- 修复通过 create_task API 创建任务时下拉框等元变量无法展示的问题

bugfix: 修复通过 create_task API 创建任务时下拉框等元变量无法展示的问题

---

frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue

- bug fix
- 表格分页后第一条数据编辑取消或删除后显示不正确问题和文本框字体大小问题修复

bugfix: 表格分页后第一条数据编辑取消或删除后显示不正确问题和文本框字体大小问题修复

---

pipeline_plugins/components/collections/sites/open/nodeman/base.py
pipeline_plugins/components/collections/sites/open/nodeman/plugin_operate/v1_0.py
pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
pipeline_plugins/components/static/components/atoms/nodeman/create_task/v2_0.js
pipeline_plugins/tests/components/collections/sites/open/nodeman_test/create_task_test/test_nodeman_v2_create_task.py
pipeline_plugins/tests/components/collections/sites/open/nodeman_test/plugin_operate_test/test_nodeman_plugin_operate_v1_0.py
static/components/atoms/nodeman/create_task/v2_0.js

V3.6.37 experience op

---

frontend/desktop/src/components/layout/Navigation.vue
frontend/desktop/src/pages/admin/statistics/index.vue

bugfix: 运营数据刷新页面项目列表不可选修复

---

frontend/desktop/src/pages/admin/statistics/Atom.vue

- bug fix
- 标准插件统计插件多版本全选中问题修复

bugfix: 标准插件统计插件多版本全选中问题修复

---

gcloud/tests/apigw/views/utils.py

- 优化项
- 修复self单词拼写错误 
close #2823

minor: 修复self单词拼写错误 #2823

---

pipeline_plugins/components/query/sites/open/cc.py

- bug fix
- 修复cc_find_host_by_topo接口结果判断问题

minor: 修复cc_find_host_by_topo接口结果判断问题

---

frontend/desktop/src/pages/admin/statistics/Atom.vue

improvement:  标准运维插件传参错误问题修复

---

frontend/desktop/src/main.js
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

improvement: 任务执行页面控制节点支持查看节点详情

---

support-files/supervisord.conf

- 新功能
- xxx
- 优化项
- xxx
- bug fix
- xxx

minor: modified supervisord.conf error

---

pipeline_plugins/components/static/components/atoms/cc/cmdb_add_host_lock/v1_0.js
pipeline_plugins/components/static/components/atoms/cc/cmdb_delete_host_lock/v1_0.js
pipeline_plugins/components/static/components/atoms/cc/host_custom_property_change/v1_0.js
pipeline_plugins/components/static/components/atoms/cc/transfer_host_module/v1_0.js
pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
pipeline_plugins/components/static/components/atoms/job/job_fast_push_file.js
pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v1_0_0.js
pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_0.js
pipeline_plugins/components/static/components/atoms/nodeman/create_task/v2_0.js
pipeline_plugins/components/static/components/atoms/nodeman/plugin_operate/v1_0.js
static/components/atoms/cc/cmdb_add_host_lock/v1_0.js
static/components/atoms/cc/cmdb_delete_host_lock/v1_0.js
static/components/atoms/cc/host_custom_property_change/v1_0.js
static/components/atoms/cc/transfer_host_module/v1_0.js
static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
static/components/atoms/job/all_biz_fast_push_file/v1_0.js
static/components/atoms/job/fast_execute_script/v1_0.js
static/components/atoms/job/job_fast_execute_script.js
static/components/atoms/job/job_fast_push_file.js
static/components/atoms/job/job_push_local_files/v1_0_0.js
static/components/atoms/job/job_push_local_files/v2_0.js
static/components/atoms/job/local_content_upload/v1_0.js
static/components/atoms/nodeman/create_task/v2_0.js
static/components/atoms/nodeman/plugin_operate/v1_0.js

minor: 优化插件 IP 字段填写提示

---

dev_log/dev/v_xugzhou_202105201531.yaml
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskExecute/OperationFlow.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabOperationFlow.vue

- 优化项
- 流水操作节点name前端实现
- bug fix
- 流水操作记录操作时间显示不全

improvement: 流水操作记录操作时间显示不全优化&& 流水操作节点name前端实现

---

dev_log/3.6.39/v_xugzhou_202105201522.yaml
frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue

improvement: 周期任务crontab没有重置问题修复

---

gcloud/contrib/operate_record/apis/drf/serilaziers/operate_record.py
gcloud/contrib/operate_record/constants.py

minor: 去掉流水记录节点接口的name字段

---

frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue

improvement:  公共流程暂时禁用执行方案功能

---

frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue

improvement:  克隆流程保存时同时需要保存执行方案

---

config/default.py
gcloud/core/urls.py
requirements.txt

optimization: 添加 django-prometheus

---

gcloud/label/viewsets.py

- minor
- LabelViewSet使用allow_or_raise_auth_failed进行鉴权

minor: LabelViewSet使用allow_or_raise_auth_failed进行鉴权

---

pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
pipeline_plugins/components/collections/sites/open/job/local_content_upload/v1_0.py

- 优化项
- 丰富 JOB 插件 log_outputs 字段的描述

minor: 丰富 JOB 插件 log_outputs 字段的描述

---

pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py

minor: 企业微信发送消息插件增加使用说明

---

env.py
gcloud/contrib/appmaker/resources.py

- 新功能
- mini app list add desktop_url field

feature: mini app list add desktop_url field

---

api/utils/request.py
packages/blueking/component/base.py

- 优化项
- batch_request 请求中注入引擎当前节点上下文

optimization: batch_request 请求中注入引擎当前节点上下文

---

gcloud/commons/template/api.py
gcloud/commons/template/urls.py
gcloud/tasktmpl3/api.py
gcloud/tasktmpl3/unified_api_utils.py

feature: 公共流程新增batch_form接口

---

gcloud/common_template/apis/django/api.py
gcloud/common_template/apis/django/validators.py
gcloud/tasktmpl3/apis/django/api.py
gcloud/tasktmpl3/apis/django/validators.py
gcloud/tasktmpl3/models.py
gcloud/template_base/apis/django/api.py
gcloud/template_base/apis/django/validators.py

模板接口公共代码提取

---

requirements.txt

minor: iam upgrade to 1.1.13

---

gcloud/common_template/apis/django/api.py
gcloud/iam_auth/view_interceptors/common_template.py
gcloud/iam_auth/view_interceptors/template.py
gcloud/tasktmpl3/apis/django/api.py
gcloud/template_base/apis/django/api.py
gcloud/template_base/apis/django/validators.py

- bug fix
- 模板 API 统一后导出模板 500 问题修复

bugfix: 模板 API 统一后导出模板 500 问题修复

---

gcloud/common_template/models.py
gcloud/tasktmpl3/models.py
gcloud/template_base/domains/importer.py

- 优化项
- schema_convertor 联调问题修复

optimization: schema_convertor 联调问题修复

---

dev_log/dev/homholueng_202106101226.yaml
env.py
pipeline_plugins/components/collections/sites/open/job/base.py
pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_legacy.py

- 新功能
- 新增通过 BKAPP_JOB_LOG_VAR_SEARCH_CUSTOM_PATTERNS 环境变量添加 JOB 日志变量提取模式功能

feature: 新增通过环境变量添加 JOB 日志变量提取模式功能

---

dev_log/dev/fannluo_202104301453.yaml
frontend/desktop/src/components/common/RenderForm/formMixins.js

- 优化项
- renderform表单正则校验默认通过格式类型值

improvement: renderform表单正则校验默认通过格式类型值

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue

minor:公共流程编辑去掉执行代理人配置

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue

improvement:子流程加载时机优化

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

bugfix: 勾选变量无法显示默认值问题修复

---

gcloud/common_template/apis/django/api.py
gcloud/template_base/apis/django/api.py
gcloud/template_base/apis/drf/viewsets/template_scheme.py

- bug fix
- 修复batch_form接口version和template不对应问题

bugfix: 修复batch_form接口version和template不对应问题

---

gcloud/iam_auth/view_interceptors/taskflow.py
gcloud/taskflow3/api.py

minor: status接口去掉iam鉴权逻辑

---

gcloud/core/views.py

minor: page_not_found兼容各个环境

---

gcloud/common_template/apis/django/api.py
gcloud/iam_auth/view_interceptors/common_template.py
gcloud/iam_auth/view_interceptors/template.py
gcloud/tasktmpl3/apis/django/api.py
gcloud/tasktmpl3/urls.py
gcloud/template_base/apis/django/api.py
gcloud/template_base/apis/django/validators.py
gcloud/template_base/models.py
gcloud/tests/mock_settings.py
gcloud/tests/template_base/__init__.py
gcloud/tests/template_base/models/__init__.py
gcloud/tests/template_base/models/base_template_manager/__init__.py
gcloud/tests/template_base/models/base_template_manager/test_check_templates_subprocess_expired.py
pipeline_web/tests/wrapper/pipeline_template_web_wrapper/test_unfold_subprocess.py
pipeline_web/wrapper.py
requirements.txt

- 新功能
- 子流程支持配置 always_use_latest 字段

feature: 子流程支持配置 always_use_latest 字段

---

config/urls_custom.py
gcloud/iam_auth/utils.py
gcloud/iam_auth/view_interceptors/base_template.py
gcloud/template_base/apis/django/api.py
gcloud/template_base/apis/django/validators.py
gcloud/template_base/domains/converter_handler.py
gcloud/template_base/domains/schema_converter.py
gcloud/template_base/domains/template_manager.py
gcloud/template_base/urls.py
gcloud/utils/decorators.py

feature: 添加Yaml格式流程文件上传、导入导出接口

---

frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue

minor: 任务执行页面节点树样式优化

---

gcloud/core/urls.py
gcloud/core/views.py

- 优化项
- django prom metrics view add login exempt

minor: django prom metrics view add login exempt

---

frontend/desktop/src/App.vue

minor:分支合并导致eslint校验不通过处理

---

gcloud/iam_auth/drf_permission_helpers/permission.py
gcloud/template_base/apis/django/validators.py
gcloud/template_base/apis/drf/permission.py
gcloud/template_base/apis/drf/viewsets/template_scheme.py

V3.6.x develop debug

---

dev_log/dev/v_xugzhou_202106241200.yaml
frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue
frontend/desktop/src/store/modules/task.js

improvement: 公共流程接口联调

---

gcloud/contrib/operate_record/apis/drf/serilaziers/operate_record.py
gcloud/contrib/operate_record/apis/drf/viewsets/operate_record.py

bugfix: 公共流程获取操作记录失败修复

---

support-files/supervisord.conf

- bug fix
- 修复 bamboo-engine worker 进程命令不正确的问题

bugfix: 修复 bamboo-engine worker 进程命令不正确的问题

---

gcloud/taskflow3/dispatchers/node.py
gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v1.py
gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py

- bug fix
- 修复查看子流程中节点详情时 500 的问题

bugfix: 修复查看子流程中节点详情时 500 的问题

---

frontend/desktop/package.json
frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue

minor: yaml文件导入错误处理优化

---

gcloud/template_base/domains/schema_converter.py

- 新功能
- Yaml Schema Converter添加条件并行网关支持

feature: Yaml Schema Converter添加条件并行网关支持

---

frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue

- bug fix
- 修复表格tag导入文件数据列与表格列不匹配导致失败的问题

bugfix: 修复表格tag导入文件数据列与表格列不匹配导致失败的问题

---

pipeline_plugins/variables/static/variables/datatable.js
pipeline_plugins/variables/static/variables/select.js

minor: 元变量表单hookable改为true

---

pipeline_web/parser/format.py

bugfix: 修复预渲染变量条件判断问题

---

gcloud/taskflow3/dispatchers/task.py
requirements.txt

- bug fix
- 修复系统变量在新版本引擎子流程中无法渲染的问题

bugfix: 修复系统变量在新版本引擎子流程中无法渲染的问题

---

gcloud/apigw/views/get_tasks_status.py

- bug fix
- 修复 get_tasks_status 在处理 children 字段时未判断是否存在的问题

bugfix: 修复 get_tasks_status 在处理 children 字段时未判断是否存在的问题

---

gcloud/taskflow3/dispatchers/task.py

- 新功能
- 修复 TaskCommandDispatcher.start_v1 任务 ID 获取方式不正确的问题

bugfix: 修复 TaskCommandDispatcher.start_v1 任务 ID 获取方式不正确的问题

---

config/default.py
gcloud/apigw/views/get_task_status.py
gcloud/apigw/views/get_tasks_status.py
gcloud/label/viewsets.py
gcloud/project_constants/__init__.py
gcloud/project_constants/admin.py
gcloud/project_constants/apis/__init__.py
gcloud/project_constants/apis/drf/__init__.py
gcloud/project_constants/apis/drf/permissions.py
gcloud/project_constants/apis/drf/serializers.py
gcloud/project_constants/apis/drf/viewsets.py
gcloud/project_constants/apps.py
gcloud/project_constants/domains/__init__.py
gcloud/project_constants/domains/context.py
gcloud/project_constants/migrations/0001_initial.py
gcloud/project_constants/migrations/__init__.py
gcloud/project_constants/models.py
gcloud/project_constants/tests/__init__.py
gcloud/project_constants/tests/domains/__init__.py
gcloud/project_constants/tests/domains/test_context.py
gcloud/resources/urls.py
gcloud/taskflow3/api.py
gcloud/taskflow3/dispatchers/task.py
gcloud/taskflow3/models.py

project scope constants backend impl

project scope constants backend impl

---

pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js

minor:分发本地文件2.0文件信息分隔符修改和添加删除按钮

minor:分发本地文件文件信息分隔符修改和添加删除按钮

---

gcloud/tests/utils/throttle/test_check_task_operation_throttle.py
gcloud/utils/redis_lock.py
gcloud/utils/throttle.py

- 优化项
- 基于业务的任务操作限制加锁用redis锁替代线程锁

optimization: 基于业务的任务操作限制加锁用redis锁替代线程锁

---

config/default.py
engine_pickle_obj/__init__.py
engine_pickle_obj/context.py
gcloud/taskflow3/context.py
gcloud/taskflow3/dispatchers/task.py
requirements.txt

- bug fix
- 修复 engine v2 任务启动时不支持有环任务及周期任务未传入额外流程上下文的问题

bugfix: 修复 engine v2 任务启动时不支持有环任务及周期任务未传入额外流程上下文的问题

---

frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
frontend/desktop/src/pages/task/TaskCreateHeader.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue

- 优化项
- 新建任务是返回路径问题优化
- 新建执行方案返回时显示弹框优化

improvement: V3.6.X体验问题修复

---

frontend/desktop/src/pages/audit/AuditList.vue
frontend/desktop/src/pages/functor/FunctionList.vue
frontend/desktop/src/pages/project/index.vue
frontend/desktop/src/pages/task/PeriodicList/index.vue
frontend/desktop/src/pages/task/TaskList/index.vue
frontend/desktop/src/pages/template/TemplateList/index.vue
frontend/desktop/src/pages/template/common/CommonTemplateList.vue

improvement: 表格列储存的storage添加兼容处理

---

frontend/desktop/src/pages/template/TemplateEdit/index.vue

minor：总是使用最新版关闭后提示更新的通知不显示处理

---

pipeline_plugins/components/collections/sites/open/cc/create_set/v1_0.py
pipeline_plugins/components/collections/sites/open/cc/create_set/v2_0.py

- bug fix
- 修复创建集群插件设计容量字段为int校验不通过问题

bugfix: 修复创建集群插件设计容量字段为int校验不通过问题

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskList/index.vue

feature: 任务记录表格增加引擎版本列

---

pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
static/components/atoms/job/job_push_local_files/v2_0.js

 minor:分发本地文件2.0前端展示优化

---

gcloud/project_constants/apis/drf/permissions.py

bugfix: 修复 project_constants 接口 500 的问题

bugfix: 修复 project_constants 接口 500 的问题

---

frontend/desktop/src/pages/audit/AuditList.vue
frontend/desktop/src/pages/functor/FunctionList.vue
frontend/desktop/src/pages/project/index.vue
frontend/desktop/src/pages/task/PeriodicList/index.vue

- bug fix
- 表格列储存的兼容时数据类型异常问题修复

fixbug: 表格列储存的兼容时数据类型异常问题修复

---

pipeline_web/wrapper.py

bugfix: 修复导入模板和执行方案时执行方案内节点 ID 未替换的问题

bugfix: 修复导入模板和执行方案时执行方案内节点 ID 未替换的问题

---

pipeline_plugins/components/collections/sites/open/job/base.py

optimization: job get_job_instance_global_var_value 返回值为 None 兼容

optimization: job get_job_instance_global_var_value 返回值为 None 兼容

---

app.yml
config/default.py
docs/release.md
readme.md
readme_en.md
version_log/version_logs_md/V3.6.4201_2021-07-15.md

minor: release V3.6.4201

---

app.yml
config/default.py
docs/release.md
readme.md
readme_en.md
scripts/start_new_version.sh
version_log/version_logs_md/V3.6.4202_2021-07-15.md

minor: release V3.6.4202

---

pipeline_plugins/components/static/components/atoms/cc/batch_transfer_host_module/v1_0.js
static/components/atoms/cc/batch_transfer_host_module/v1_0.js

optimization: 批量更新主机所属业务模块表单优化

optimization: 批量更新主机所属业务模块表单优化

---

pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_0.py
pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
pipeline_plugins/tests/components/collections/sites/open/job_test/push_local_files/test_v2_0.py
static/components/atoms/job/job_push_local_files/v2_0.js

- 优化项
- JOB 分发本地文件 2.0 版本支持配置超时时间(V3.6.X)

minor:JOB 分发本地文件 2.0 版本支持配置超时时间(V3.6.X)

---

gcloud/taskflow3/utils.py
pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
pipeline_plugins/components/static/components/atoms/cc/batch_transfer_host_module/v1_0.js
pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
static/components/atoms/cc/batch_transfer_host_module/v1_0.js
static/components/atoms/job/all_biz_fast_execute_script/v1_0.js

bugfix: 修复 taskflow/api/status 接口拉取 v1 engine 任务时没有返回 error_ignored 字段的问题

V3.6.43 bugfix

---

files/managers/base.py
files/managers/nfs.py
files/managers/upload_module.py

feature: filemanager.push_files_to_ips 支持传入 timeout 参数

feature: filemanager.push_files_to_ips 支持传入 timeout 参数

---

pipeline_plugins/tests/components/collections/sites/open/job_test/push_local_files/test_v2_0.py

minor: unit test fix

---

pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py

- minor
- 快速分发文件插件添加了目标路径strip

minor:快速分发文件插件添加了目标路径strip

---

frontend/desktop/src/pages/template/TemplateList/index.vue

improvement:流程列表默认先倒序排序

---

frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue

improvement: 修改参数无数据时获取组件dom失败问题修复

---

gcloud/core/apis/drf/viewsets/utils.py

optimization: 对于 204 响应不做 response 标准化处理

optimization: 对于 204 响应不做 response 标准化处理

---

frontend/desktop/src/pages/task/ParameterInfo.vue
frontend/desktop/src/pages/task/TaskParamEdit.vue

bugfix: 修复隐藏状态的下拉框变量取值的问题

---

files/managers/base.py
files/managers/nfs.py
files/managers/upload_module.py
gcloud/core/apis/drf/viewsets/utils.py
pipeline_plugins/components/collections/sites/open/cc/create_set/v1_0.py
pipeline_plugins/components/collections/sites/open/cc/create_set/v2_0.py
pipeline_plugins/components/collections/sites/open/job/base.py
pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_0.py
pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
pipeline_plugins/tests/components/collections/sites/open/job_test/push_local_files/test_v2_0.py
pipeline_web/wrapper.py
static/components/atoms/job/job_push_local_files/v2_0.js

V3.6.X merge to V3.6.44

---

gcloud/project_constants/apis/drf/serializers.py

optimization: 后台增加对业务级别环境变量 key 的校验逻辑

optimization: 后台增加对业务级别环境变量 key 的校验逻辑

---

frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
frontend/desktop/src/pages/project/config.vue
frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableCitedList.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue
frontend/desktop/src/store/modules/template.js

monir:修改展示字段的缺失和环境变量删除的处理

---

docs/develop/tag_usage_dev.md
frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue

improvement: 上传组件增加自定义上传函数配置项

---

frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
frontend/desktop/src/components/common/TemplateCanvas/index.vue

bugfix: 修复画布执行状态ui样式问题

---

dev_log/dev/yovafeng_202107160955.yaml
pipeline_plugins/tests/variables/collections/test_text_value_select.py
pipeline_plugins/variables/collections/common.py
pipeline_web/parser/format.py

- feature
- 新增支持获取已选择text和value的文本值下拉框

feature:新增支持获取已选择text和value的文本值下拉框

---

frontend/mobile/src/store/modules/taskList.js

minor: 移动端任务列表去掉只加载移动端创建任务的筛选条件

---

frontend/desktop/src/assets/html/index.html

minor: 去掉index.html引入的remote_api文件

---

config/default.py
config/urls_custom.py
plugin_service/__init__.py
plugin_service/admin.py
plugin_service/api.py
plugin_service/apps.py
plugin_service/conf.py
plugin_service/decorators.py
plugin_service/env.py
plugin_service/plugin.py
plugin_service/plugin_client.py
plugin_service/serializers.py
plugin_service/tests/test_plugin.py
plugin_service/urls.py

feature: 新增对接远程插件服务

---

frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue

- bug fix
- upload组件绑定httpRequest方法异常修复

bugfix: upload组件绑定httpRequest方法异常修复

---

frontend/desktop/src/constants/index.js
frontend/desktop/src/pages/appmaker/AppEditDialog.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue
frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
frontend/desktop/src/pages/template/TemplateList/index.vue
frontend/desktop/src/pages/template/common/CommonTemplateList.vue

bugfix: 新建轻应用无法选择类别问题修复

---

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
frontend/desktop/src/pages/task/TaskExecute/index.vue

- bug fix
- 任务执行状态浏览器tab icon路径去掉多余/

bugfix: 任务执行状态浏览器tab icon路径去掉多余/

---

dev_log/3.6.40/fannluo_202107282026.yaml
frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue

improvement: 表格tag导出数据表头优化

---

config/default.py
pipeline_plugins/cmdb_ip_picker/utils.py
pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py

optimization: 日志配置优化,变量关键节点增加日志

optimization: 日志配置优化,变量关键节点增加日志

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

improvement: 全局变量为显示状态时默认值校验逻辑优化

---

frontend/desktop/src/pages/template/TemplateEdit/index.vue

bugfix: 不存在的插件会导致画布卡死问题修复

---

frontend/desktop/src/pages/template/TemplateEdit/index.vue

- bugfix
- 任务节点code修改后打开配置面板提示逻辑优化

bugfix: 任务节点code修改后打开配置面板提示逻辑优化

---

plugin_service/api.py
plugin_service/decorators.py
plugin_service/exceptions.py
plugin_service/plugin_client.py
plugin_service/serializers.py

- minor
- plugin_service PaaS 接口适配

minor: plugin_service PaaS 接口适配

---

pipeline_plugins/components/static/components/atoms/nodeman/plugin_operate/v1_0.js
static/components/atoms/nodeman/plugin_operate/v1_0.js

bugfix:修复节点管理安装插件表单插件名称
close #3863

bugfix:修复节点管理表单插件名称版本级联问题

---

app.yml
config/default.py
docs/release.md
readme.md
readme_en.md
support-files/supervisord.conf
version_log/version_logs_md/V3.6.4208_2021-08-24.md

minor: release V3.6.4208

---

pipeline_plugins/components/utils/sites/open/utils.py

bugfix: 修复 get_biz_ip_from_frontend 没有处理 ip 为空情况的问题

bugfix: 修复 get_biz_ip_from_frontend 没有处理 ip 为空情况的问题

---

pipeline_plugins/components/utils/sites/open/utils.py
pipeline_web/parser/format.py
pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py

Ip str none fix

---

frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue

- 优化项
-  ip选择器新样式界面问题修复
closed #3914

improvement: ip选择器新样式界面问题修复

---

frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
frontend/desktop/src/store/modules/task.js

feature: 子流程任务节点支持查看执行信息和失败重试

---

frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue

bugfix: 导入临时方案问题修复

---

frontend/desktop/src/store/modules/template.js
frontend/desktop/src/utils/tplSnapshoot.js

- bug fix
- 流程本地快照存储空间超出最大值时保存失败问题修复

bugfix：流程本地快照存储空间超出最大值时保存失败问题修复

---

gcloud/iam_auth/view_interceptors/taskflow.py
gcloud/taskflow3/apis/django/api.py
gcloud/taskflow3/domains/dispatchers/node.py
requirements.txt

feature: node_action API 支持 retry_subprocess
close  #3899

feature: node_action API 支持 retry_subprocess

---

frontend/desktop/src/components/common/RenderForm/IpSelector/ManualInput.vue
frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
frontend/desktop/src/components/common/TemplateCanvas/index.vue
frontend/desktop/src/pages/appmaker/AppEditDialog.vue
frontend/desktop/src/pages/audit/AuditList.vue
frontend/desktop/src/pages/home/MyDynamic.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

bugfix: 前端测试问题修复

---

dev_log/dev/waylon_202108311001.yaml
pipeline_plugins/components/utils/sites/open/utils.py
pipeline_plugins/tests/components/utils/test_cc_get_ips_info_by_str.py

- 优化项
- 从ip_str中匹配IP信息在纯IP格式和云区域ID:IP格式下支持host_innerip为多ip情况

improvement: 从ip_str中匹配IP信息在纯IP格式和云区域ID:IP格式下支持host_innerip为多ip情况

---

pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py

minor: 审核插件审核结果字段不再进行国际化

---

bksops_iam_migrations/migrations/0007_bk_sops_202109011700.py
dev_log/dev/waylon_202109011719.yaml
support-files/iam/07_add_common_actions.json

improvement: 注册所有常用操作到IAM

---

pipeline_plugins/components/collections/sites/open/bk/notify/v1_0.py
pipeline_plugins/components/static/components/atoms/bk/notify/v1_0.js
pipeline_plugins/tests/components/collections/sites/open/bk_test/notify/test_v1_0.py
static/components/atoms/bk/notify/v1_0.js

spring-fix:是否通知执行人

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabPipelineTreeEdit.vue
frontend/desktop/src/utils/validatePipeline.js

- bug fix
- 流程模板tree数据编辑合法性校验提示交互修改
close #3939

bugfix: 流程模板tree数据编辑合法性校验提示交互修改

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

- bug fix
- 修复输入参数复用自定义全局变量时勾选状态不生效问题
- 修复勾选的输出变量保存失败的问题

bugfix: 修复V3.5.51输入参数勾选状态及输出参数变量编辑问题

---

gcloud/taskflow3/domains/dispatchers/node.py
gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
requirements.txt

- minor
-  preview_node_inputs接口调用调整

minor: preview_node_inputs接口调用调整

---

dev_log/dev/waylon_202108242143.yaml
gcloud/core/apis/drf/viewsets/project_config.py
gcloud/core/apis/drf/viewsets/staff_group.py
gcloud/core/apis/drf/viewsets/utils.py

- bug fix
- 修复ProjectConfig和StaffGroup接口无权限中心校验问题

bugfix: 修复ProjectConfig和StaffGroup接口无权限中心校验问题

---

plugin_service/env.py
plugin_service/exceptions.py
plugin_service/plugin_client.py

minor: 插件服务兼容未启用情况

---

frontend/desktop/src/pages/audit/AuditList.vue
frontend/desktop/src/pages/home/MyDynamic.vue

bugfix: 首页-我的动态加载失败问题修复

---

app.yml
config/default.py
docs/release.md
readme.md
readme_en.md
requirements.txt
version_log/version_logs_md/V3.6.54_2021-09-06.md

minor: release 3.6.54

---

gcloud/taskflow3/apis/drf/viewsets/render_current_constants.py

bugfix: 修复 RenderCurrentConstantsView 鉴权 500 的问题

bugfix: 修复 RenderCurrentConstantsView 鉴权 500 的问题

---

dev_log/dev/waylon_202109061748.yaml
gcloud/apigw/views/get_task_status.py
gcloud/apigw/views/get_tasks_status.py
gcloud/iam_auth/view_interceptors/taskflow.py
gcloud/taskflow3/api.py
gcloud/taskflow3/apis/views/v4/state.py
gcloud/taskflow3/apis/views/v4/urls.py
gcloud/taskflow3/models.py
gcloud/taskflow3/resources.py
gcloud/tests/apigw/views/test_get_tasks_status.py
gcloud/tests/mock.py

minor: 添加state接口查看任务树状态

---

gcloud/taskflow3/apis/drf/viewsets/render_current_constants.py

bugfix: 修复 RenderCurrentConstantsView 500 的问题

bugfix: 修复 RenderCurrentConstantsView 500 的问题

---

gcloud/contrib/appmaker/resources.py
gcloud/iam_auth/utils.py
gcloud/taskflow3/resources.py
gcloud/tasktmpl3/resources.py

- bug fix
-  轻应用、任务、流程列表管理员用户项目权限检查豁免

bugfix: 轻应用、任务、流程列表管理员用户项目权限检查豁免

---

frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue

bugfix: 导入临时执行方案按钮去掉前端鉴权

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue

improvement: 第三方插件日志支持滚动加载

---

config/default.py

minor: add bk-monitor-report logger

minor: add bk-monitor-report logger

---

gcloud/common_template/apis/django/api.py
gcloud/tasktmpl3/apis/django/api.py
gcloud/template_base/apis/django/api.py
gcloud/template_base/apis/django/validators.py

feature: DAT格式导出流程模板接口支持 is_full 参数
#3904

feature: DAT格式导出流程模板接口支持 is_full 参数

---

gcloud/label/viewsets.py

minor: 流程标签创建操作添加权限校验

---

pipeline_web/parser/format.py

bugfix:V2引擎 创建含子流程任务失败

---

gcloud/taskflow3/domains/dispatchers/node.py
gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py

bugfix: 修复查看没有Data对象的节点时报错的问题

---

pipeline_plugins/components/static/components/atoms/job/fast_push_file/v1_0.js
pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_0.js
static/components/atoms/job/fast_push_file/v1_0.js
static/components/atoms/job/fast_push_file/v2_0.js

minor: 快速分发文件插件表格列宽度自适应

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue

- bug fix
- 修复输出参数表单和输出参数表单key相同时勾选判断的问题

bugfix: 修复输出参数表单和输出参数表单key相同时勾选判断的问题

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
frontend/desktop/src/pages/template/TemplateList/index.vue
frontend/desktop/src/pages/template/common/CommonTemplateList.vue

bugfix: 模板批量操作权限判断问题修复

---

frontend/desktop/src/config/setting.js
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskParamEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

imporvement: renderfrom渲染注入host

---

requirements.txt

minor: bump pipeline to 3.7.0

---

frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue

- 新功能
- crontab组件增加每个时间维度的清空按钮
close #4011

feature: crontab组件增加每个时间维度的清空按钮

---

frontend/desktop/src/pages/task/TaskParamEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue

- bug fix
- 修复任务创建参数填写页面相同类型的表单执行渲染出第一个的问题

bugfix: 修复任务创建参数填写页面相同类型的表单执行渲染出第一个的问题

---

app.yml
config/default.py
dev_log/3.7.8/homholueng_202109221947.yaml
docs/release.md
gcloud/apigw/views/get_task_node_detail.py
gcloud/tests/apigw/views/test_get_task_node_detail.py
readme.md
readme_en.md
version_log/version_logs_md/V3.7.8_2021-09-22.md

minor: release 3.7.8

---

frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue

- bug fix
- 第三方插件默认版本错误问题修复
- 第三方节点重试问题修复

bugfix: 第三方插件问题修复

---

app_desc.yaml
bin/post_compile
gcloud/core/api_adapter/app_maker/v3.py

minor: fix app maker api miss app_secret issue

minor: fix app maker api miss app_secret issue

---

gcloud/clocked_task/models.py
gcloud/clocked_task/serializer.py
gcloud/clocked_task/viewset.py
requirements.txt

minor: 任务计划功能优化

---

gcloud/clocked_task/models.py
gcloud/clocked_task/permissions.py
gcloud/clocked_task/viewset.py
gcloud/core/apis/drf/viewsets/staff_group.py
gcloud/core/apis/drf/viewsets/utils.py
gcloud/iam_auth/conf.py
gcloud/iam_auth/res_factory.py
gcloud/iam_auth/resource_api/__init__.py
gcloud/iam_auth/resource_api/clocked_task.py
gcloud/iam_auth/resource_creator_action/clocked_task.py
gcloud/iam_auth/resource_helpers/clocked_task.py
support-files/iam/08_add_clocked_task_actions.json
support-files/iam/09_update_action_group.json
support-files/iam/10_update_resource_creator_actions.json
support-files/iam/11_update_common_actions.json

feature: 计划任务权限中心接入

---

bksops_iam_migrations/migrations/0008_bk_sops_202109261155.py
bksops_iam_migrations/migrations/0009_bk_sops_202109261155.py
bksops_iam_migrations/migrations/0010_bk_sops_202109261155.py
bksops_iam_migrations/migrations/0011_bk_sops_202109261155.py

- minor:
- update bksops_iam_migrations

minor: update bksops_iam_migrations

---

gcloud/clocked_task/serializer.py
gcloud/clocked_task/viewset.py
gcloud/tasktmpl3/apis/tastypie/resources.py

minor: 计划任务联调问题修复

---

frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
frontend/desktop/src/pages/task/ClockedList/index.vue

fixbug: 计划任务体验问题修复

---

docs/apidoc/en/create_task.md
docs/apidoc/zh_hans/create_task.md
gcloud/apigw/schemas.py
gcloud/apigw/views/create_task.py
gcloud/apigw/views/utils.py
gcloud/tests/apigw/views/test_create_task.py

- feature
- create_task接口支持选择执行节点

feature:create_task接口支持选择执行节点

---

frontend/desktop/src/pages/functor/FunctionList.vue

improvement: 职能化中心新建任务项目选择过滤已归档业务

---

pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_legacy.py

feature: 【功能】快速执行脚本生成任务名支持自定义

---

frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue

- bug fix
- 修复任务节点重试面板第二次点开时表单不显示的问题

bugfix: 修复任务节点重试面板第二次点开时表单不显示的问题

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue

- bug fix
- 修复第三方插件plugin_code取值不正确问题

bugfix: 修复第三方插件plugin_code取值不正确问题

---

app.yml
config/default.py
dev_log/3.7.13/fanluo_202109272152.yaml
docs/release.md
readme.md
readme_en.md
version_log/version_logs_md/V3.7.13_2021-09-27.md

minor: release V3.7.13

---

dev_log/dev/yovafeng_202108251130.yaml
docs/apidoc/en/create_and_start_task.md
docs/apidoc/sops.yaml
docs/apidoc/zh_hans/create_and_start_task.md
gcloud/apigw/schemas.py
gcloud/apigw/urls.py
gcloud/apigw/views/create_and_start_task.py
gcloud/tests/apigw/views/test_create_and_start_task.py
gcloud/tests/mock_settings.py

- feature
- 新增create_and_start_task接口，支持创建并执行任务

feature:新增create_and_start_task接口，支持创建并执行任务

---

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

improvement: 职能化添加模板跳转按钮

---

dev_log/dev/waylon_202109281544.yaml
gcloud/periodictask/models.py
gcloud/tests/periodictask/models/test_periodic_task.py
gcloud/tests/utils/strings/__init__.py
gcloud/tests/utils/strings/test_django_celery_beat_cron_time_format_fit.py
gcloud/utils/strings.py

- 优化项
- 周期任务策略字段显示适配新版django_celery_beat返回格式

improvement:周期任务策略字段显示适配新版django_celery_beat返回格式

---

app.yml
config/default.py
dev_log/3.7.14/homholueng_202109281140.yaml
docs/release.md
readme.md
readme_en.md
requirements.txt
version_log/version_logs_md/V3.7.14_2021-09-28.md

- 新功能
- xxx
- 优化项
- xxx
- bug fix
- xxx

minor: release 3.7.14

---

gcloud/taskflow3/domains/dispatchers/node.py
gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py

bugfix: 子流程重试功能联调问题修复

---

gcloud/core/context_processors.py

- minor:
- 前端资源加载入口url配置修改为相对路径

前端资源加载入口url配置修改为相对路径

---

frontend/desktop/src/pages/project/index.vue

improvement: 项目配置权限问题修复

---

gcloud/analysis_statistics/migrations/0001_initial.py
gcloud/analysis_statistics/models.py

修复数据库创建不成功

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
frontend/desktop/src/pages/task/TaskParamEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

第三方插件api前端调用方式调整

---

frontend/desktop/src/pages/project/index.vue

- bug fix
- 修复没有项目编辑权限的用户能够进入项目配置页面的问题

修复没有项目编辑权限的用户能够进入项目配置页面的问题

---

pipeline_plugins/components/collections/sites/open/monitor/alarm_shield/v1_1.py
pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield/test_v1_1.py

修改添加监控屏蔽插件add_shield传参bk_inst_id为bk_module_id

修复添加监控屏蔽插件按节点屏蔽节点ID传递错误的问题

---

frontend/desktop/src/pages/home/AddCollectionDialog.vue

- bug fix
- 查看收藏的模板申请权限 项目提示undefined问题修复

查看收藏的模板申请权限 项目提示undefined问题修复

---

frontend/desktop/src/api/index.js

improvement: 全局错误信息提示优化

---

dev_log/dev/yovafeng_202109291121.yaml
gcloud/contrib/operate_record/core.py

- bug fix
- 修复API操作任务节点时未记录流水日志

修复API操作任务节点时未记录流水日志的问题

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

节点名称，步骤名称输入框增加去掉首尾空格

---

frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue

导出流程面板无法保存问题修复

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
frontend/desktop/src/pages/task/TaskParamEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

第三方插件前端url路径拼接调整

---

frontend/desktop/src/pages/task/TaskExecute/GlobalVariable.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
frontend/desktop/src/store/modules/task.js

任务详情页面支持查看所有全局变量的值

---

frontend/desktop/src/components/common/TemplateCanvas/index.vue
frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue
frontend/desktop/src/store/modules/template.js

表达式分支标签支持调整

---

gcloud/taskflow3/models.py

运营数据任务统计模块查询优化

---

frontend/desktop/src/pages/admin/statistics/Percentage.vue

任务统计模块字段显示错误

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

修复变量的KEY字段不合法时点击保存会一直补全格式的问题

---

pipeline_plugins/components/collections/controller.py

修改定时插件的秒数正则,支持无限长时间定时

---

pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py

节点管理新建任务插件添加版本号

---

frontend/desktop/src/pages/home/MyCollection.vue

首页申请创建任务权限时错误问题修复

---

docs/apidoc/en/get_tasks_status.md
docs/apidoc/zh_hans/get_tasks_status.md
gcloud/apigw/views/get_tasks_status.py

网关接口get_tasks_status添加limit限制50大小

网关接口get_tasks_status添加limit限制50大小

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

勾选变量后全局变量窗口卡死问题修复

---

api/collections/nodeman.py
pipeline_plugins/components/static/components/atoms/nodeman/create_task/v2_0.js

job_install参数添加tcoa_ticket,优化前端表单交互

修复节点管理新建任务插件TJJ认证不可用的问题

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue

子流程搜索不支持特殊符号问题修复

---

gcloud/taskflow3/models.py
gcloud/tests/taskflow3/models/taskflow/test_function_task_claimant.py

职能化任务失败支持通知认领人

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

* feature: 变量编辑页面增加格式化语句的快捷插入操作面板
* bugfix: 快捷插入操作面板体验问题修复
* optimization: 模板生成器 operator 文案优化

optimization: 快捷插入操作面板体验问题修复 (#4836)

---

plugin_service/plugin_client.py

修改请求paas接口请求失败的异常捕获范围

---

docs/apidoc/en/start_task.md
docs/apidoc/zh_hans/start_task.md
gcloud/apigw/views/start_task.py
gcloud/tests/apigw/views/test_start_task.py

网关接口start_task增加data返回

---

pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
pipeline_plugins/components/collections/sites/open/job/base.py
pipeline_plugins/components/collections/sites/open/job/execute_task/v1_1.py
pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_1.py
pipeline_plugins/components/static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan.js
pipeline_plugins/components/static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan_output.js
pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
pipeline_plugins/components/static/components/atoms/job/execute_task/v1_1.js
pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_execute_job_plan/test_v1_0.py
pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_1.py

job执脚本/作业后ip按照步骤tag进行分组

---

pipeline_web/preview.py
pipeline_web/tests/prview/test_preview.py

preview_task_tree_with_schemes增加outputs放回

preview_task_tree_with_schemes增加outputs返回

---

gcloud/contrib/operate_record/core.py
gcloud/taskflow3/apis/django/api.py

(cherry picked from commit f3725900deb5643ca801f041f19d53eab285e119)

修复页面操作节点没有流水记录的问题

---

frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue

feature: 任务列表页“新建任务”窗口全量拉取流程数据优化 Tencent#4764

feature: 任务列表页“新建任务”窗口全量拉取流程数据优化 Tencent#4764 

---

gcloud/taskflow3/apis/drf/viewsets/preview_task_tree.py

添加template_source为project时，project_id的参数校验

添加template_source为project时，project_id的参数校验

---

gcloud/core/apis/drf/permission.py
gcloud/core/apis/drf/viewsets/project.py

(cherry picked from commit 950b99d2a438d238959fbf105b79742b855a5638)
(cherry picked from commit e3fda4757aed4c3bb5653e02b73e0f0d8f33871f)

minor: project权限调整

---

pipeline_web/preview.py
pipeline_web/tests/prview/test_preview.py

outputs过滤掉执行方案未选中节点中的设置输出的component_inputs变量

outputs过滤掉执行方案未选中节点中的设置输出的component_inputs变量

---

pipeline_web/preview.py
pipeline_web/preview_base.py
pipeline_web/tests/prview/test_preview.py
pipeline_web/tests/prview/test_preview_base.py
pipeline_web/tests/wrapper/pipeline_template_web_wrapper/test_unfold_subprocess.py
pipeline_web/wrapper.py

子流程选择执行方案兼容节点不可选的情况

---

pipeline_web/preview.py
pipeline_web/tests/prview/test_preview.py

subprocess show custom variable

修复子流程自定义全局变量设置输出，在父流程中被未引用隐藏的问题

---

gcloud/taskflow3/apis/drf/viewsets/preview_task_tree.py
gcloud/tasktmpl3/apis/django/api.py
gcloud/tasktmpl3/apis/drf/permissions.py
gcloud/tasktmpl3/apis/drf/serilaziers/batch_form_with_schemes.py
gcloud/tasktmpl3/apis/drf/serilaziers/form_with_schemes.py
gcloud/tasktmpl3/apis/drf/viewsets/batch_form_with_schemes.py
gcloud/tasktmpl3/apis/drf/viewsets/form_with_schemes.py
gcloud/tasktmpl3/urls.py
pipeline_web/preview.py
pipeline_web/tests/prview/test_preview.py

批量更新子流程支持选择执行方案

---

pipeline_plugins/components/collections/sites/open/job/execute_task/v1_1.py

bugfix: job执行作业插件v1.1版本输出表单没有展示log_outputs字段

bugfix: job执行作业插件v1.1版本输出表单没有展示log_outputs字段

---

frontend/desktop/src/pages/template/TemplateList/projectTplList.vue

bugfix: 修复流程默认排序icon展示问题

---

pipeline_plugins/components/collections/sites/open/nodeman/base.py
pipeline_plugins/components/collections/sites/open/nodeman/create_task/v4_0.py
pipeline_plugins/components/static/components/atoms/nodeman/create_task/v4_0.js
pipeline_plugins/tests/components/collections/sites/open/nodeman_test/create_task_test/test_nodeman_v4_create_task.py

- 安装/重装操作新增表单项是否安装最新版本插件 
- 卸载AGENT操作参数和重装AGENT保持一致
- 移除操作下线

新增节点管理新建任务插件4.0版本

---

gcloud/template_base/domains/schema_converter.py
gcloud/tests/template_base/schema_converter/test_complicated_yaml_data.yaml

修复若干 Yaml 导入导出问题

---

gcloud/core/views.py
packages/blueking/component/apis/bk_login.py
requirements.txt

* feature: 支持用户应用屏蔽功能
* minor: 移除 csrftoken 更新逻辑

支持用户应用屏蔽功能 (#6917)

---

gcloud/core/project.py
gcloud/taskflow3/apis/django/api.py
gcloud/taskflow3/signals/handlers.py
gcloud/tests/core/test_project.py

#6669  #6721 功能代码同步

---

frontend/desktop/src/components/common/TemplateCanvas/ToolPanel/index.vue
frontend/desktop/src/components/common/TemplateCanvas/index.vue
frontend/desktop/src/mixins/task.js
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
frontend/desktop/src/scss/task.scss

 更换icon&&任务详情中画布连线取消hover效果

---

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

节点审批逻辑调整优化

---

frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

子流程节点更新时，表单项采用【手动创建】方式创建的变量配置更新异常问题修复

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

插件配置项免渲染默认值逻辑判断异常修复

---

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

fix: 非独立子流程节点操作完以后重新加载节点详情

---

frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue

feat: 未选择任何节点时，添加一个错误message #6750

---

frontend/desktop/src/pages/task/TaskList/index.vue

fix: 任务记录过滤180天判断逻辑异常修复 #7293

---

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
frontend/desktop/src/pages/task/TaskList/index.vue

fix: 节点树算法添加退出递归方案 

---

frontend/desktop/src/pages/project/config.vue
frontend/desktop/src/store/modules/template.js

fix: 执行代理人限制仅能设置为本人 #7289

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

fix: 子任务网关失败支持跳过

---

frontend/desktop/src/utils/errorNotify.js
gcloud/template_base/domains/template_manager.py

optimization: 前台报错提示优化
optimization: 后台报错内容优化 
修复流程&任务删除报错问题

同步V3.28.0优化前后台内容报错提示到V3.26

---

frontend/desktop/src/utils/errorNotify.js

fix: 接口400状态码报错信息不展现问题修复 --bug=119762901

---

frontend/desktop/src/pages/task/TaskList/index.vue

refactor: 任务列表状态查询去掉失败、暂停，修改执行中参数 --ignore

---

frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
frontend/desktop/src/pages/task/TaskCreate/index.vue

fix: 创建任务-默认节点勾选逻辑同步 --bug=119078037

---

.pre-commit-config.yaml
gcloud/taskflow3/models.py

fix: 任务在执行前校验任务是否被删除 #7307

---

.github/workflows/unittest.yml
bin/post_compile
bin/pre_release
config/default.py
gcloud/contrib/notice/__init__.py
gcloud/contrib/notice/apps.py
gcloud/contrib/notice/management/__init__.py
gcloud/contrib/notice/management/commands/__init__.py
gcloud/contrib/notice/management/commands/register_bksops_notice.py
gcloud/core/context_processors.py
requirements.txt
urls.py

* feat: 通知中心代码迁移 #7309
* feat: bk_notice_sdk 添加到installed_apps #7309
* fix: 修复单元测试 #ignore
* fix: code review #ignore
* feat: 升级通知中心sdk的版本 #ignore

feat: 通知中心代码迁移 #7309 (#7310)

---

frontend/desktop/package.json
frontend/desktop/src/App.vue
frontend/desktop/src/assets/html/index-dev.html
frontend/desktop/src/assets/html/index.html
frontend/desktop/src/pages/admin/manage/index.vue
frontend/desktop/src/pages/admin/statistics/index.vue
frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
frontend/desktop/src/pages/task/TaskCreate/index.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue

feat: 通知中心代码迁移 #7309

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

fix: 修复失败节点下跳过icon点击报错的问题 --bug=120214755

---

frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue

fix: 导入流程-分页后导致之前选择的数据被清空问题修复 --bug=116340266

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue

fix: 第三方插件执行详情输出展示问题修复 --bug=116432067

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/index.vue
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/index.vue

fix: 代码合并功能不生效问题修复&&详情页加载loading优化 --ignore

---

frontend/desktop/src/store/modules/task.js

fix: 修复强制失败节点请求参数格式不正确问题

---

frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

fix: 轻应用再次执行路由跳转错误问题修复 --ignore

---

frontend/desktop/package.json
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/JsonschemaForm.vue
frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/JsonschemaInputParams.vue

chore: 更新bkui-form版本 #ignore

---

frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue

bugfix: 第三方插件输入框失焦后未去拉取列表问题修复 #ignore

---

frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue

fix: 轻应用页面查看任务url路径错误问题修复 #ignore

---

frontend/desktop/src/components/layout/NavigatorHeadRight.vue

fix: 修改登出链接 #ignore

---

frontend/desktop/src/components/layout/Navigation.vue
frontend/desktop/src/store/index.js

fix: 项目title、footer未国际化问题修复 #ignore

---

frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue

fix: 输入框文本框粘贴后保存数据为空问题修复 --ignore

---

frontend/desktop/src/pages/task/PeriodicList/index.vue
frontend/desktop/src/pages/task/TaskList/index.vue
frontend/desktop/src/store/modules/taskList.js

pref: 任务列表分页优化 #ignore

---

frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/index.vue

fix: 独立子流程loading未关闭问题修复 #ignore

---

frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue

fix: 文本框组件\n为渲染问题修复

---

frontend/desktop/src/config/i18n/en.js
frontend/desktop/src/pages/appmaker/AppEditDialog.vue

fix: 新建轻应用获取流程没有重置offset问题修复 #7556

---

frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue

fix: 手机网页打开sops，侧栏打开后页面无法拖动问题修复  #7563

---

.pre-commit-config.yaml
env_v3.py

refactor: 优化环境变量获取方式,降低本地开发配置成本
style: black固定版本号，最新的不兼容py3.6

refactor: 优化环境变量获取方式,降低本地开发配置成本

---

frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue

fix: 文本框组件展示内容为underfind问题修复 --bug=129170523

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
frontend/desktop/src/store/modules/template.js

feat: 前端支持bkchat通知方式 --bug=120383214

---

frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue

feat: 周期任务通知方式数据显示不对问题修复 --bug=120383214

---

frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue

fix: 代码编辑框检测变量方法不准确问题修复 --bug=120963616

---

frontend/desktop/src/App.vue
frontend/desktop/src/constants/routes.js
frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
frontend/desktop/src/pages/task/TaskCreateHeader.vue
frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
frontend/desktop/src/routers/index.js
frontend/desktop/src/utils/checkDataType.js

fix: 流程市场嵌入画布支持 #7626

---

frontend/desktop/src/pages/template/TemplatePreview/index.vue

fix: 流程市场嵌入画布支持-遗漏文件提交 #7626

---

frontend/desktop/src/pages/template/TemplateList/SharedTemplate/markdownEditor/editor.vue

fix: 共享到商店-上传图片跨域问题修复 --story=121000017

---

frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue

fix: 任务执行页被嵌入后，点击返回抛出事件 --story=121000017

---

frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue

fix: 任务执行页被嵌入后，点击返回抛出事件逻辑提前 --story=121000017

---

frontend/desktop/src/pages/template/TemplateList/SharedTemplate/SharedTplSlider.vue
frontend/desktop/src/pages/template/TemplateList/SharedTemplate/markdownEditor/editor.vue

fix: 共享到商店侧栏保存传参错误问题修复 --story=121000017

---

frontend/desktop/src/pages/template/TemplateList/SharedTemplate/markdownEditor/editor.vue

fix: 编辑器图片上传不成功问题修复 --story=121000017

---

gcloud/core/context_processors.py

* feat: 添加返回数据间隔时间 --story=120737215
* fix: 修复相应上下文问题 --story=120737215

feat: 添加返回数据间隔时间 --story=120737215

---

frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue

fix: 公共流程创建周期任务-权限校验优化 --story=121334648

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue

fix: GSEKit ip选择器变量切ip选择器后无法正常操作问题修复 --story=121335817

---

frontend/desktop/src/config/i18n/cn.js
frontend/desktop/src/config/i18n/en.js
frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
frontend/desktop/src/pages/template/TemplateList/SharedTemplate/SharedTplSlider.vue
frontend/desktop/src/store/modules/periodic.js

fix: 共享到商店侧栏风险等级字段错误问题修复 --story=121000017

---

frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
frontend/desktop/src/pages/template/TemplateList/SharedTemplate/SharedCategorySelect.vue
frontend/desktop/src/pages/template/TemplateList/SharedTemplate/SharedTplSlider.vue

fix: 共享到商店侧栏场景分类下拉框交互优化 --story=121000017

---

frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue

fix: 公共流程创建周期任务采用allow接口鉴权  --story=136521403

---

frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue

fix: 周期任务权限判断js报错问题修复  --story=136521403

---

frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
frontend/desktop/src/pages/template/TemplateList/SharedTemplate/SharedTplSlider.vue

fix: 体验问题修复  --story=136521403

---

frontend/desktop/src/pages/template/TemplateList/SharedTemplate/SharedTplSlider.vue

fix: 切换共享类型时重置场景配置 --story=136520635

---

frontend/desktop/src/App.vue

fix: 被嵌入时如果访问模板预览页则不调项目详情接口 #ignore

---

frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue

fix: 创建任务选择执行方案时候，有概率默认执行方案不生效问题修复 #ignore

---

frontend/desktop/src/pages/market/PeriodicTaskCreate/index.vue

fix: 创建周期任务页创建成功抛出任务id #ignore

---

frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue

fix: 输入框变量额外多一个空格问题修复 --story=121740037

---

frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
frontend/desktop/src/pages/task/TaskCreate/index.vue
frontend/desktop/src/pages/template/TemplateEdit/index.vue

fix: 执行方案代码优化 --story=121748933

---

.coveragerc
.github/workflows/unittest.yml
codecov.yml
readme.md

refactor: sops 单测覆盖率 --story=122181498

---

frontend/desktop/src/components/common/RenderForm/FormGroup.vue
frontend/desktop/src/components/common/RenderForm/FormItem.vue

feat: 表单label展示从scheme.attrs.name取值 --ignore

---

pipeline_plugins/components/collections/sites/open/job/fast_push_file/v3_0.py
pipeline_plugins/components/static/components/atoms/job/fast_push_file/v3_0.js

feat: 快速分发文件支持文件源 #7731

---

gcloud/core/api.py
pipeline_plugins/components/static/components/atoms/bk/notify/v1_0.js

fix: 修复bkchat名称和图标问题 --story=122065757

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue

feat: bkchat通知方式优化 --bug=120383214

---

frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue

fix: 周期任务、定时任务通知方式未回填值问题修复 --ignore

---

gcloud/apigw/views/get_template_list.py
gcloud/tests/apigw/views/test_get_template_list.py

feat: get_template_list接口返回添加模板labels信息 #7737

---

files/bartenders/utils.py
files/managers/job_repo.py
gcloud/core/api.py
packages/bkapi/bk_cmsi/__init__.py
packages/bkapi/bk_cmsi/shortcuts.py
packages/bkapi/bk_nodeman/client.py
packages/bkapi/jobv3_cloud/client.py
pipeline_plugins/components/collections/sites/open/job/base.py
pipeline_plugins/components/collections/sites/open/job/push_local_files/base_service.py
pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_1.py
pipeline_plugins/components/collections/sites/open/nodeman/base.py
pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py
pipeline_plugins/components/collections/sites/open/nodeman/create_task/v3_0.py
pipeline_plugins/components/collections/sites/open/nodeman/create_task/v4_0.py
pipeline_plugins/components/query/sites/open/gsekit.py
pipeline_plugins/components/query/sites/open/itsm.py
pipeline_plugins/components/query/sites/open/job.py
pipeline_plugins/components/query/sites/open/monitor.py
pipeline_plugins/components/query/sites/open/nodeman.py

fix: job插件多租户改造测试和问题修复 --story=121994365

---

frontend/desktop/src/components/common/RenderForm/FormGroup.vue
frontend/desktop/src/components/common/RenderForm/FormItem.vue

fix: 变量表单label展示错误问题修复 --ignore

---

gcloud/apigw/views/get_template_list.py
gcloud/tests/apigw/views/test_get_template_list.py

fix: 添加参数实现控制是否返回模板信息 #7737

---

pipeline_plugins/components/query/sites/open/cc.py

fix: 标准运维多租户改造变量和CMDB插件 --story=122659384

---

.github/workflows/commitlint.yml
.github/workflows/eslint.yml
.github/workflows/flake8_and_black.yml
.github/workflows/unittest.yml
app.yml
app_desc.yaml
config/default.py

fix: 多租户部署体验测试--story=123610576

---

frontend/desktop/src/pages/template/TemplateList/TemplateUpdateDialog.vue
frontend/desktop/src/pages/template/TemplateList/projectTplList.vue

fix: 流程列表-批量更新时label字段数据异常 --bug=123692968

---

frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue

fix: 周期任务-更新流程后已选执行方案不生效验问题修复 --bug=123722062

---

.github/workflows/commitlint.yml
.github/workflows/eslint.yml
.github/workflows/flake8_and_black.yml
.github/workflows/unittest.yml
gcloud/shortcuts/message/send_msg.py

fix: 修复bkchat校验错误 --story=122528762

---

app.yml
app_desc.yaml
config/default.py
gcloud/apigw/views/create_periodic_task.py
gcloud/apigw/views/create_task.py
gcloud/apigw/views/fast_create_task.py
gcloud/apigw/views/get_common_template_info.py
gcloud/apigw/views/get_common_template_list.py
gcloud/apigw/views/get_functionalization_task_list.py
gcloud/apigw/views/get_user_project_detail.py
gcloud/apigw/views/preview_common_task_tree.py
gcloud/apigw/views/preview_task_tree.py
gcloud/apigw/views/register_project.py
gcloud/contrib/appmaker/models.py
gcloud/core/api_adapter/app_maker/v3.py
gcloud/core/utils/sites/open/utils.py
pipeline_plugins/cmdb_ip_picker/query.py
pipeline_plugins/cmdb_ip_picker/utils.py
pipeline_plugins/variables/collections/sites/open/ip_filter_base.py

fix: 多租户部署体验测试 --story=123610576

---

frontend/desktop/src/components/common/Individualization/MemberSelect.vue

fix: 多租户人员选择器样式调整 --ignore

---

gcloud/core/api.py
pipeline_plugins/components/static/components/atoms/bk/notify/v1_0.js

fix: 通知渠道渲染逻辑问题修复 --story=122528762

---

gcloud/core/apis/drf/viewsets/appmaker.py

fix: --bug=142368699 【标准运维多租户】通过拼接url方式可以进入另外的租户空间

---

frontend/desktop/src/pages/audit/AuditList.vue
frontend/desktop/src/pages/commonManage/CommonTplList.vue
frontend/desktop/src/pages/functor/FunctionList.vue
frontend/desktop/src/pages/task/ClockedList/index.vue
frontend/desktop/src/pages/task/PeriodicList/index.vue
frontend/desktop/src/pages/task/TaskList/index.vue
frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
frontend/desktop/src/pages/template/TemplateList/projectTplList.vue

fix: 渲染表格多租户人员列判断逻辑异常问题修复 --ignore

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

fix: 字段错误问题修复 --ignore

---

gcloud/template_base/domains/schema_converter.py

fix: 修复导出yaml变量转换下拉框会变成非法数据源问题 #7784

fix: 修复导出yaml变量转换下拉框会变成非法数据源问题 #7784

---

config/default.py

feat: settings中加入iam的网关地址 --story=121994291

---

app.yml
app_desc.yaml
config/default.py

feat: 修改版本号为3.34.1-rc.17 --story=121994291

---

config/default.py
gcloud/clocked_task/permissions.py
gcloud/core/apis/drf/resource_helpers.py
gcloud/core/middlewares.py
gcloud/core/utils/sites/open/tenant_tools.py
gcloud/iam_auth/resource_api/__init__.py
gcloud/iam_auth/resource_creator_action/utils.py
gcloud/utils/handlers.py

feat: 多租户适配权限中心 --story=121994291

---

frontend/desktop/src/components/layout/Navigation.vue

fix: 多租户模式下导航过滤掉【插件开发】 --ignore

---

frontend/desktop/src/components/layout/NavigatorHeadRight.vue

fix: 多租户模式切换语言调用接口调整 --ignore

---

pipeline_plugins/variables/collections/bk_manage_user_selector.py

fix: 人员选择器变量的值使用bk_username格式

---

gcloud/core/apis/drf/viewsets/taskflow.py
gcloud/iam_auth/res_factory.py

fix: 获取任务详情时根据租户id过滤 --bug=142771700

---

gcloud/contrib/itsm_workflow/management/commands/migrate_itsm_workflow.py
packages/bkapi/bk_itsm4/client.py
pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
pipeline_plugins/components/query/sites/open/itsm.py
pipeline_plugins/components/query/sites/open/monitor.py

fix: 监控告警屏蔽(按策略)插件适配 --bug=142314631

---

gcloud/core/apis/drf/serilaziers/common_template.py

fix: 补充返回信息 #7824

---

frontend/desktop/src/components/common/modal/SelectProjectModal.vue
frontend/desktop/src/pages/commonManage/CommonTplList.vue
frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
frontend/desktop/src/pages/template/TemplateList/SharedTemplate/index.vue
frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
frontend/desktop/src/store/modules/template.js

feat:公共流程可见范围控制 --igonre

---

app.yml
app_desc.yaml
config/default.py
config/mock/__init__.py
config/mock/mock_json.py
gcloud/template_base/domains/converter_handler.py
gcloud/tests/template_base/schema_converter/test_yaml_schema_converter.py

refactor: mako模板支持安全的json模块调用 --story=125616815

---

gcloud/iam_auth/resource_creator_action/utils.py

fix: 修改权限中心方法参数

---

gcloud/apigw/views/create_periodic_task.py
gcloud/apigw/views/get_periodic_task_info.py
gcloud/apigw/views/get_periodic_task_list.py
gcloud/apigw/views/get_template_info.py
gcloud/apigw/views/get_template_list.py
gcloud/apigw/views/utils.py
gcloud/tests/apigw/views/test_create_periodic_task.py
gcloud/tests/apigw/views/test_get_periodic_task_info.py
gcloud/tests/apigw/views/test_get_periodic_task_list.py
requirements.txt

fix: 修复遗漏数据返回未被参数控制 --story=124898883

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

This reverts commit f41492187ec8e4f9a75f920e9e000ba050183650.

Revert "fix: 第三方插件父流程有多余输出 --story=125204339 (#7881)"

---

frontend/desktop/src/components/layout/NavigatorHeadRight.vue

fix: 修改用户语言接口请求方法 --ignore

---

gcloud/template_base/apis/drf/permission.py

fix: 修复删除流程报错问题

---

frontend/desktop/src/store/modules/project.js

fix: 修改项目变量接口添加路径 --ignore

---

gcloud/core/apis/drf/serilaziers/common_template.py
gcloud/core/apis/drf/viewsets/common_template.py

fix: 公共流程新增列表页修改接口 #7824

---

pipeline_plugins/tests/components/collections/http_test/test_v1_0.py

fix: 修复http插件测试问题 --story=125852796

---

gcloud/core/apis/drf/viewsets/common_template.py

fix: 修改可见范围控制逻辑 #7824

---

gcloud/core/apis/drf/serilaziers/task_template.py
gcloud/core/apis/drf/viewsets/task_template.py

feat: 模板列表页面增加标签修改接口 --story=125724568

---

gcloud/core/apis/drf/serilaziers/common_template.py
gcloud/tests/core/apis/drf/views_set/test_common_template_view.py

fix: 公共流程补充测试用例并修复错误 #7824

---

gcloud/core/apis/drf/serilaziers/common_template.py
gcloud/core/apis/drf/viewsets/common_template.py
gcloud/template_base/models.py

fix: 修复修改子流程使用范围越界问题 #7824

---

gcloud/common_template/models.py
gcloud/template_base/apis/django/api.py

fix: 修复公共流程导入文件租户id缺失问题。

---

frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue

fix: 节点勾选时复用已有变量被值引用时依然删除问题修复 --story=124846751

---

gcloud/common_template/models.py
gcloud/core/apis/drf/serilaziers/common_template.py
gcloud/template_base/models.py

fix: 修改公共流程报错提示信息 #7824

---

gcloud/core/apis/drf/serilaziers/common_template.py

fix: 修复逻辑判断问题 #7824

---

gcloud/core/apis/drf/serilaziers/common_template.py
gcloud/core/apis/drf/viewsets/common_template.py

fix: 修复更新逻辑并同步更新时间和更新人 #7824

---

gcloud/utils/middleware.py

feat: 新增日志模块及认证日志记录

---

gcloud/utils/middleware.py

feat: 新增从请求头获取租户ID并传入get_user方法

---

gcloud/apigw/decorators.py

feat: 网关获取检索字段支持参数为空 --story=126076158

---

gcloud/clocked_task/serializer.py
gcloud/core/apis/drf/serilaziers/periodic_task.py
gcloud/core/apis/drf/viewsets/periodic_task.py
gcloud/utils/pipeline.py
pipeline_web/parser/validator.py

feat: 流程和任务模板增加对常量的校验 --story=124852371

---

gcloud/utils/middleware.py

fix: 删除debug 日志

---

gcloud/core/trace.py
gcloud/taskflow3/apis/django/api.py
gcloud/taskflow3/domains/dispatchers/node.py
gcloud/taskflow3/domains/dispatchers/task.py

refactor: 增加支持继承属性的trace装饰器和上下文管理器  --story=126421543

---

frontend/desktop/builds/webpack.dev.config.js

refactor: 删除postcss依赖 --ignore

---

gcloud/core/apis/drf/viewsets/task_template.py

fix: 修复更新功能取值错误 --story=126514126

---

gcloud/core/trace.py

refactor:  修复部分drf请求获取trace属性报错的问题 --story=126421543

---

gcloud/utils/webhook.py

feat: 补充webhook配置参数校验 --story=126514126

---

frontend/desktop/src/components/common/TemplateCanvas/index.vue
frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/index.vue
frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
frontend/desktop/src/store/modules/task.js

feat: 新增审批插件与之前审批插件隔离开，调用不同接口 #ignore

---

gcloud/iam_auth/view_interceptors/template.py
gcloud/tasktmpl3/apis/django/api.py
gcloud/tasktmpl3/urls.py
gcloud/template_base/apis/django/validators.py

feat: 新增方法获取流程树 --story=146567037

---

frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/HttpCallback.vue

fix: 补充头信息校验 --story=124942044

---

gcloud/apigw/views/get_user_project_detail.py

fix: 修复用户组信息过滤问题 --story=147892934

---

frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue

fix: 变量输入联想渲染问题修复 --story=127178067

---

gcloud/apigw/views/get_task_detail.py
gcloud/core/apis/drf/viewsets/taskflow.py
gcloud/utils/local.py
gcloud/utils/webhook.py

feat: 增加回调事件中文名称 --story=147958653

---

gcloud/core/apis/drf/viewsets/task_template.py

fix: 修改调试请求错误提示 --story=126514126

---

gcloud/utils/webhook.py

fix: 修改配置错误提示信息 --story=126514126

---

app.yml
app_desc.yaml
config/default.py

feat: 更新版本号 --story=147958653

---

pipeline_plugins/components/collections/sites/open/monitor/alarm_shield/v2_0.py
pipeline_plugins/components/collections/sites/open/monitor/alarm_shield_strategy/v2_0.py
pipeline_plugins/components/static/components/atoms/monitor/alarm_shield/v2_0.js
pipeline_plugins/components/static/components/atoms/monitor/alarm_shield_strategy/v2_0.js

feat: 告警屏蔽插件支持自定义屏蔽原因 --story=126416676

---

frontend/desktop/src/pages/task/TaskExecute/WebhookCallback.vue

fix: 转译以及tooltips --story=127502680
